### ISSUE TITLE
useSearch hook with strict false type error

### ISSUE THREAD

**Issue by TommysG** [TanStack/router#1007]
### Describe the bug

I have a route with some searchParams using validateSearch with zod.

When using useSearch with strict=false in an abstract component, TypeScript throws the following error: "Property 'mode' does not exist on type 'RootSearchSchema'."

### Your Example Website or App

https://stackblitz.com/edit/github-g4hol2?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Define a route with searchParams validated by Zod.
2. Create a component.
3. Use useSearch with strict=false in the component.
4. Observe the TypeScript error.

### Expected behavior

There should be no TypeScript error when using useSearch with strict=false and maybe show me a union of all possible route search params .

### Platform

- OS: macOS
- Browser: Chrome
- Version: [e.g. 91.1]
- TanStack Router: 1.4.6

**Comment by TommysG** [comment]
@schiller-manuel I don't have autocomplete in `search` because the result type is the union e.g: 
```ts
{} | {} | {
page?: number | undefined; pagesize?: number | undefined;
}
```

So it says that `page` does not exist on this type. Is this the expected? Should i declare the type of `search` when using `useSearch({strict:false})` ?

**Comment by schiller-manuel** [comment]
You wrote it yourself above: " show me a union of all possible route search params ."
That's what you get from router if you set strict=false.

You can do something like:

```tsx
const search = useSearch({strict: false});
if ('page' in search) {
   console.log(search.page);
}
```
