### ISSUE TITLE
Router context broken with SSR on client side

### ISSUE THREAD

**Issue by rekotiira** [TanStack/router#1009]
### Describe the bug

When using SSR the router context is `undefined` after page load finishes. On the server render it is working properly, but after the app is dehydrated on client side, and re-rendered, `route.useRouteContext()` inside a React component returns `undefined` instead of the context. Changing a route while the app is mounted fixes the issue.

I modified the Basic SSR example to reproduce this bug. When entering the page, the rendered context is `undefined`, but when navigating to "Posts" page and then back to "Home", it renders the context successfully.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-rn5jgg?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the repro site.
2. See that Context is not printed at all in Home page.
3. Go to Posts page.
4. Go back to Home page.
5. Now the Context is rendered correctly.

### Expected behavior

As a user, I expect the context to render correctly on client side on initial render. In the repro site it should render `{ head: "" }` on initial render.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 120.0.6099.129

**Comment by tannerlinsley** [comment]
I'm aware of this issue and it may not be able to fixed until v2, since it would require very breaking changes. We've slated it internally for v2 and will track internally.

**Comment by rekotiira** [comment]
> I'm aware of this issue and it may not be able to fixed until v2, since it would require very breaking changes. We've slated it internally for v2 and will track internally.

Any workarounds aside from not using the context at all?

**Comment by tannerlinsley** [comment]
The best workaround would be to not rely on the router context in your components, only in beforeLoad/loader. Those are guaranteed to have the correct context. The real issue is that router context isn't currently serialized and shipped to the browser during SSR, and if we did serialize and ship it, it would destroy any non-JSON compatible values.
