### ISSUE TITLE
Loader called every time for nested root route even without changing path

### ISSUE THREAD

**Issue by blitzbohne** [TanStack/router#1018]
### Describe the bug

Not sure if this is a bug but since the change to loaderDeps and shouldReload, how are we supposed to prevent reloading a nested root route every time we navigate?

We have for example a structure of Root route -> Nested root route -> Inner route.

The path is for example /$objectId/something where as our nested root route hosts all sub routes of $objectId/**

Our intention was that the nested root only loads once as long as the objectId parameter is the same (this was possible with the shouldReload function before now no longer?). As of now, the nested root route reloads and re-mounts every time if we navigate to any subroute which makes no sense.

How can this be "fixed" with the current tanstack router?

### Your Example Website or App

https://stackblitz.com/github/tanstack/router/tree/beta/examples/react/quickstart?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

Please see description its more of an abstract problem

### Expected behavior

Having a way to prevent reloading nested root routes when the params do not change

### Platform

- macOS
- Chrome
- Tanstack Router: latest

**Comment by tannerlinsley** [comment]
A simple `shouldReload: false` should do the trick.
