### ISSUE TITLE
Meta route options is gone?

### ISSUE THREAD

**Issue by ziggy6792** [TanStack/router#1025]
### Describe the bug

Firstly, thanks a lot for an awesome tool!
Have wanted this in react for ages!

In the alpha release `^0.0.1-alpha.0` we have a meta property on route options.
I see in v1 that this is gone.
But then the docs do still mention [Dynamic meta tag management](https://tanstack.com/router/v1/docs/guide/router-context) and I am wondering
- Is meta tagging still available but moved?
- Just removed?
- Replaced with something else?

Below I show an example of how I was using meta options.
<img width="1001" alt="Screenshot 2024-01-19 at 12 05 07 PM" src="https://github.com/TanStack/router/assets/60313838/afee8ea6-b26d-411f-9d2d-c4ded90c8a11">

Then type safety using this
<img width="384" alt="Screenshot 2024-01-19 at 12 06 30 PM" src="https://github.com/TanStack/router/assets/60313838/b2e936a7-b6f7-4029-8991-e5ca9bbfacb8">

This was working well, but maybe theres is a different/better way to do this now?

Thanks :)

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

- Install latest version of `@tanstack/react-router` `^1.6.0`
- Meta options is gone from `RouteOptions`

### Expected behavior

Meta options still available on `RouteOptions`

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

N/A

**Comment by MrAdam** [comment]
I was also using this to generate the menu structure in my app, from the route tree.
I haven't been able to find a way to get it working with RouteContext, as it seems like this isn't usable outside the `<Outlet/>`.

**Comment by tannerlinsley** [comment]
cc @schiller-manuel

**Comment by tannerlinsley** [comment]
You can now use the newly added `staticData` route option: https://tanstack.com/router/latest/docs/framework/react/guide/static-route-data

**Comment by mikededo** [comment]
Hey @tannerlinsley, would it be possible to [enforce static data](https://tanstack.com/router/latest/docs/framework/react/guide/static-route-data#enforcing-static-data) at a Route level?

For example, if I define a `/_layout`, that all `/_layout/<children>` must include that static data; while if there's another `/_other-layout`, such static data is not enforced.

**Comment by tannerlinsley** [comment]
Possible, but it’ll take some work.

**Comment by mikededo** [comment]
Do you mean that it will take work to be added to the library?

**Comment by tannerlinsley** [comment]
Correct!

**Comment by ziggy6792** [comment]
Hey @tannerlinsley thanks a lot for the response.
Replaced `meta` with `staticData` everything seems to work fine :)

**Comment by tannerlinsley** [comment]
And better yet, it’s available right in the match!

**Comment by Pateriack** [comment]
@tannerlinsley I can open a new issue if you'd like, but is it intentional that the types don't support doing this with lazy routes? If I ignore the type errors, it works just fine.

**Comment by schiller-manuel** [comment]
You need to create both routes, a lazy one and non-lazy one.
Put `staticData` into the non-lazy one. see also https://tanstack.com/router/latest/docs/framework/react/guide/code-splitting#how-does-tanstack-router-split-code
