### ISSUE TITLE
Custom search param serialization does not work like the example in the documentation

### ISSUE THREAD

**Issue by tbassetto** [TanStack/router#1026]
### Describe the bug

I would like to migrate on of our app to @tanstack/router without breaking URLs. Our homepage has no search params by default, but you can search products by one or more categories which will be added to the search params as duplicate keys. Example: example.net/?categories=1&categories=2 (which implies `categories: [1, 2]`). Also, if `categories` is undefined I don't want to see `?categories=` in the URL, I want it gone.

This is not the default serialization done by @tanstack/router so I followed the documentation on https://tanstack.com/router/v1/docs/guide/custom-search-param-serialization and used `query-string` as you can configure the `arrayFormat` this library uses. The default `arrayFormat` being the behavior I am looking for :).

Unfortunately, when I call:
```ts
navigate({
  to: Route.to, // equivalent to '/'
  search: {
    users: [
      ...(search.users || []),
      user.id,
    ], // I add user.id to the current search params `users` which is an array
  },
});
```
I am redirect to `/user=1` instead of `/?user=1`.

### Your Example Website or App

https://stackblitz.com/~/github.com/tbassetto/tanstack-local-news

### Steps to Reproduce the Bug or Issue

1. Open the preview in a new URL as the browser inside StackBlitz never displays the search params.
2. Click on `Leanne Graham #1`
3. Click on `Ervin Howell #2`
3. Notice that the content on the right is from those 2 authors.The URL end with `/?users=%5B1%2C2%5D`.
4. Uncomment line 4, 12, 13 in `src/app.tsx`. And restart the preview from the root without any search params.
5. Click on `Leanne Graham #1`.
6. You are now looking at a 404, the URL is `/users=1` instead of `/users?=1`.

### Expected behavior

Not a 404, I am expecting to see `/?users=1&users=2` if I click on the 2 first authors.

### Platform

- OS: macOS
- Browser: Edge
- Version: 120.0.2210.133 (Official build) (x86_64)

**Comment by schiller-manuel** [comment]
you need to prefix your query string with `?` just like the default implementation does: https://github.com/TanStack/router/blob/main/packages/react-router/src/searchParams.ts#L74

**Comment by schiller-manuel** [comment]
can this issue be closed?

**Comment by tbassetto** [comment]
It feels to me that the documentation should be changed to fix this issue. I can create a PR soon-ish (I have the flu at the moment 😫).On 23 Jan 2024, at 19:51, Manuel Schiller ***@***.***> wrote:﻿
can this issue be closed?

**Comment by tannerlinsley** [comment]
Happy to accept a PR to update this if it's not clear.

**Comment by mrlubos** [comment]
@tbassetto did you ever update the documentation?

**Comment by tbassetto** [comment]
> @tbassetto did you ever update the documentation?

No because when I was ready to update the doc had been reworked and I could not find a relevant page to add information about search param serialization. And I am not using TanStack router at the moment so I have not looked at the docs in a long time.
