### ISSUE TITLE
RouteContext type is not working on matches and beforeLoad return

### ISSUE THREAD

**Issue by knightburton** [TanStack/router#1031]
### Describe the bug

First of all, awesome project! I was soooo excited when you have released v1.

Back to the issue...

The `RouterContext` is defined and passed to the `rootRouteWithContext` to create the `rootRoute`.
I would like to access one of the context prop (`title`) inside the matches of router state in my breadcrumbs component.
The code works and all the breadcrumbs are there and usable but my IDE (VSCode) just says the prop (`title`) is not exist on the `RouteContext` even tho the project is running and building just fine.

In addition the `beforeLoad` does not use the same context type when I try to pass a context proeprty from it.

Is my code missing something or do I missing something important here?

Exact error:
```
Property 'title' does not exist on type 'RouteContext | { title: string; } | { title: string; } | { title: string; }'.
  Property 'title' does not exist on type 'RouteContext'.ts(2339)
```

Exact code piece:
```ts
const breadcrumbs = router.state.matches
  .filter((match) => !!match.routeContext?.title)
  .map((match) => ({
    label: match.routeContext.title,
    path: match.pathname,
  }));
```

For further details and example please check the given stackblitz project.

### Your Example Website or App

https://stackblitz.com/edit/github-llc8um?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Init a project with root router context
2. Add custom properties to the context
3. Add a component that accesses to the router state matches
4. Use the `routeContext` on a `match` to access to the context custom property
5. Just look confused when the IDE just failing but the code works 

### Expected behavior

As a user I expect to see the typing on the `routeContext` properly as I have described in the initial router context both in the `beforeLoad` return statement and on the matches each `match.routeContext`.

### Platform

- OS: macOS (M1 Pro)
- Browser: Chrome
- Router Version: v1.6.1
- TS Version: v5.3.2
- VSCode Version: v1.85.2

**Comment by schiller-manuel** [comment]
You need to access `context` instead of `routeContext` if you want to get the merged context:

```tsx
 const breadcrumbs = router.state.matches
    .filter((match) => !!match.context.title)
    .map((match) => ({
      label: match.context.title,
      path: match.pathname,
    }));
```
https://stackblitz.com/edit/github-llc8um-uy5n5o?file=src%2Fmain.tsx

**Comment by knightburton** [comment]
Well, that works indeed, in a simple case.
However I do not provide title for each and every route that I have. Some of my routes just acts like an additional layer or common layout and I do not want to inlcude them into the breadcrumbs.

Like:
`/_private/users/$userId/permissions`
Where
- the `_private` just an authentication route with `beforeLoad` check
- the `/users` is an additional layout/wrapper route
- the`/users/` is the index route of my users list table

In the abe case I've seen the accumulated context always filled up so in this case I've got the same routes/titles multiple times in the breadcrumbs, like the users title is in the breadcrumbs twice.

**Comment by schiller-manuel** [comment]
Can you please provide a minimal example on stackblitz/codesandbox where `context` does not fulfill your needs, but `routeContext` does?

**Comment by knightburton** [comment]
@schiller-manuel sure mate

https://stackblitz.com/edit/github-pkahw1?file=src%2Froutes%2Fusers%2F%24userId%2Fpermissions%2Findex.tsx

In this example I've created the same file based routing that I am using in my project for users for example. You can walk down to the last page, the `User Permissions` to see the breadcrumbs.
Also, I've added the breadcrumbs with `context` and `routeContext` as well to be easier to compare.

My expected behaviour is the `routeContext` one, which is working obviously, I am just furious about that the IDE refuse to show me my custom context types on it. Those should be the same type of context, right?

OR, my routing logic just doesn't make sense in this format?

**Comment by shreddish** [comment]
> You need to access `context` instead of `routeContext` if you want to get the merged context:
> 
> ```tsx
>  const breadcrumbs = router.state.matches
>     .filter((match) => !!match.context.title)
>     .map((match) => ({
>       label: match.context.title,
>       path: match.pathname,
>     }));
> ```
> 
> https://stackblitz.com/edit/github-llc8um-uy5n5o?file=src%2Fmain.tsx

FYI - The example docs for RouteContext use the `match.routeContext` property which had me scratching my head until i found this thread. Unless I'm missing something, the docs should be updated if we are supposed to be using the `context` property instead. Additionally, it would be nice to show how you are supposed to be setting the title or `getTitle` function in the example for each route. Using @knightburton example I saw that we should just be returning an object in beforeLoad - However that is not apparent in the docs for beforeLoad

https://tanstack.com/router/v1/docs/guide/router-context

**Comment by knightburton** [comment]
@shreddish I assumed that the context can be changed by returning something in the `beforeLoad` based on this example last secion:
[https://tanstack.com/router/v1/docs/guide/router-context#modifying-the-router-context](https://tanstack.com/router/v1/docs/guide/router-context#modifying-the-router-context)

and the kitchen sink example `src/routes/_auth.tsx` file line number 22:
[https://tanstack.com/router/v1/docs/examples/react/kitchen-sink-react-query-file-based](https://tanstack.com/router/v1/docs/examples/react/kitchen-sink-react-query-file-based)

**Comment by giacomorebonato** [comment]
It also would be nice to have a way to manipulate the `context` from the `loader` function, when for example the title of the page depends on the value of a db query

**Comment by knightburton** [comment]
I don't know if this is accepted or not, but I've found that the `RouteContext` sitting there as an empty interface so I've just expanded it alongside with the `Register`:

```ts
declare module '@tanstack/react-router' {
  interface Register {
    router: typeof router;
  }

  interface RouteContext {
    title?: string;
  }
}

```

**Comment by knightburton** [comment]
I close this issue since the above augmentation solved my issue and the docs kinda covers the context usage for me.

**Comment by smashah** [comment]
Why do the docs show how to use a `getTitle` but not how to set it? If this issue is closed then docs should at least be updated.

**Comment by gmr458** [comment]
I am using this:

```jsx
const router = useRouter();

const breadcrumbs = router.state.matches
    .filter((match) => match.meta?.[0]?.title)
    .map((match) => ({
        label: match.meta?.[0]?.title,
        href: match.pathname,
    }));
```
