### ISSUE TITLE
File based routing causes full-page refresh and not hot reload

### ISSUE THREAD

**Issue by TommysG** [TanStack/router#1052]
### Describe the bug

When i'm using the file-based routing with `@tanstack/router-vite-plugin` everytime i'm doing a simple change in the route component the whole page refreshes. That doesn't happen when using code-based routing. Is this expected?

### Your Example Website or App

https://stackblitz.com/edit/github-g4hol2?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to route.component
2. Just change the text or styling

### Expected behavior

I expected to just hot reload the content that changed, without full page refresh. For example when changing a div's styling should immediate show the change in my screen.

### Platform

- OS: macOS
- Browser:  Chrome
- Version: [e.g. 91.1]
- @tanstack/react-router : 1.8.3
- @tanstack/router-vite-plugin: 1.8.2

**Comment by TommysG** [comment]
No still the issue persists

**Comment by tannerlinsley** [comment]
This is fixed in the latest version :) Cheers!
