### ISSUE TITLE
TanStackRouterDevtools outside of the RouterProvider

### ISSUE THREAD

**Issue by ceiger89** [TanStack/router#1065]
### Describe the bug

I came across some non-functional aspects of the documentation. One of them is the DevTool outside the provider.

It's not working: https://tanstack.com/router/v1/docs/devtools#manually-passing-the-router-instance

I'm providing an example based on the basic code.

I get in console
Warning: useRouter must be used inside a <RouterProvider> component! 

### Your Example Website or App

 https://codesandbox.io/p/devbox/tanstack-router-devtools-outside-6hdrys

### Steps to Reproduce the Bug or Issue

1. Copy code from documentation

### Expected behavior

It should work, both the devtools and routing.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by nklhtv** [comment]
@tannerlinsley bumped to 1.14.5 and its still not working: [demo](https://codesandbox.io/p/devbox/tanstack-router-devtools-outside-forked-s4hcym)

**Comment by happycollision** [comment]
FWIW, the dupe I opened shows it still broken in `1.17.5`
