### ISSUE TITLE
Relative navigation is broken

### ISSUE THREAD

**Issue by NickSoftDev** [TanStack/router#1066]
### Describe the bug

The documentation featuring the relative navigation is not in the examples or in other code using navigate with relative routing. According to the documentation:
[Everything is Relative](https://tanstack.com/router/v1/docs/guide/navigation#everything-is-relative)
Believe it or not, every navigation within an app is relative, even if you aren't using explicit relative path syntax (../../somewhere).

the statement above is clearly not working. Neither is any routes disaplyed exept for "../" in the typescript hints.

const Component1 = () => {
  const navigate = useNavigate({from:"/tests/examples/$exampleId"});
  navigate({to: "../../"});
}

or 

const Component2 = () => {
  const navigate = useNavigate({from:"/tests/foo/$fooId"});
  navigate({to: "../examples/$exampleId", params: {exampleId: "23"}});
}

Example: 1
![eaxmple 2](https://github.com/TanStack/router/assets/157487000/288fc401-4588-42be-bc19-e5a41f5275cb)

Example: 2
![example 1](https://github.com/TanStack/router/assets/157487000/60bdc0fe-e09b-4383-9bf7-acaa04a1bcff)

### Your Example Website or App

https://tanstack.com/router/v1/docs/examples/react/kitchen-sink-react-query-file-based

### Steps to Reproduce the Bug or Issue

Go to https://tanstack.com/router/v1/docs/examples/react/kitchen-sink-react-query-file-based
Navigate to the file dashboard.invoices.$invoiceId.tsx
try to replace with navigate and relative routing navigate({to: "../other/route"});

### Expected behavior

The relative paths should compile and give support for relatives routes in typescript highlights.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment]
this was fixed
