### ISSUE TITLE
lazyRouteComponent hangs forever and never resolves the promise

### ISSUE THREAD

**Issue by skalidindi** [TanStack/router#1071]
### Describe the bug

I want to use lazyRouteComponent to do lazy loading of all my routes and do code splitting.

However, it seems like lazyRouteComponent never resolves it promise and defaultPendingComponent is shown forever.

### Your Example Website or App

https://stackblitz.com/edit/github-7h7yen-ljrjob?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to example stackblitz.
2. Click on About Link or Not Found Link
3. Notice that the placeholder Loading component is shown but the actual Route Component never loads or resolves because lazyRouteComponent is used for both of these routes.
4. Note index component which does not use lazyRouteComponent loads fine and display the correct route components.

### Expected behavior

I expect components which use lazyRouteComponent to load properly and not be stuck on loading forever.

### Platform

- OS: macOS
- Browser: Arc/Chrome
- Version: 1.9.0

**Comment by SeanCassiere** [comment]
The lazy loading of the *About* component for the `/about` route needs to be defined as such:
```tsx
const aboutRoute = new Route({
  getParentRoute: () => rootRoute,
  path: 'about',
  component: lazyRouteComponent(() => import('./components/About')),
  // not | component: () => lazyRouteComponent(() => import('./components/About'))
});
```

**Comment by skalidindi** [comment]
That works!. Sorry for the trouble, I should have looked closer. My mistake. Thank you for the quick turnaround though.
