### ISSUE TITLE
Throwing a redirect in `beforeLoad` from __root.tsx causes a suspense error

### ISSUE THREAD

**Issue by Xenfo** [TanStack/router#1109]
### Describe the bug

If I try to redirect a user in `beforeLoad` in my __root.tsx file then I get `A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.` upon visiting a URL that redirects me initially.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-uc7am2?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

1. Go to repro
2. Open `/custom/redirect` in your browser

### Expected behavior

It to not error.

### Platform

- OS: [e.g. macOS, Windows, Linux] Linux
- Browser: [e.g. Chrome, Safari, Firefox] Chrome & Firefox
- Version: [e.g. 91.1] FF 122.0, Chrome 121.0.6167.85

**Comment by schiller-manuel** [comment]
add `wrapInSuspense: true,`
see https://stackblitz.com/edit/tanstack-router-gw3aq5?file=src%2Froutes%2F__root.tsx

**Comment by Xenfo** [comment]
Now `/custom` isn't rendered, which is why I didn't originally add `wrapInSuspense`.

**Comment by Xenfo** [comment]
Hey @schiller-manuel, I know you're probably busy but can we get this issue opened again for the reason in my above comment?

**Comment by mgcrea** [comment]
Might be fixed by https://github.com/TanStack/router/commit/3cde4c01ffffb933d46b4c9c35d732ff89edcd7f if related to https://github.com/TanStack/router/issues/1295

**Comment by Xenfo** [comment]
Thank you, that seems to have fixed it!
