### ISSUE TITLE
Route paths with leading digits break file-based route generation

### ISSUE THREAD

**Issue by duniul** [TanStack/router#1110]
### Describe the bug

When using file-based routing with the Vite plugin, route paths with leading digits (like `/500/index.route.tsx`) result in invalid variable names.

**Example build output:**
```
♻️  Generating routes...
SyntaxError: An identifier or keyword cannot immediately follow a numeric literal. (6:22)
  4 |
  5 | import { Route as rootRoute } from './routes/__root'
> 6 | import { Route as 500IndexRouteImport } from './routes/500/index.route'
```

### Your Example Website or App

https://stackblitz.com/edit/github-19bjij?file=README.md

### Steps to Reproduce the Bug or Issue

1. Open the example
2. Wait for the installation and build to finish
3. Notice the error output in the console

### Expected behavior

The generated variable names are prefixed with a valid leading character, resulting in valid variable names.

### Platform

- OS: macOS

**Comment by GuillaumeLaroucheUQAT** [comment]
See also : [https://github.com/TanStack/router/discussions/1013#discussioncomment-8237205](https://github.com/TanStack/router/discussions/1013#discussioncomment-8237205)
