### ISSUE TITLE
Getting instantiation errors

### ISSUE THREAD

**Issue by erthewise** [TanStack/router#1121]
### Describe the bug

`const handleClick = (orderId: number) => {
    navigate({
      to: "/orders/orders_manager/$orderId",
      params: { orderId },
    });
  };`
  
 Im suddenly getting errors to all my navigate functions including the ones with search. Sometimes typescript reads it properly and my vscode is not returning error but there are times that ts is failing to get the proper type, and fails to compile
 
 Really weird and unsure how to reproduce it. It's just that my lead is the navigate function returning instantiation

### Your Example Website or App

.

### Steps to Reproduce the Bug or Issue

Not really sure how but my deploy/build logs are returning me different instantiation errors, most are all pointing to navigate function

### Expected behavior

I expect it to not have errors

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by tunganh-phamba** [comment]
Not sure if it's the same error but I also got `TS2589: Type instantiation is excessively deep and possibly infinite.` in every navigate function

**Comment by schiller-manuel** [comment]
please try to reproduce in a minimal example using the latest router version, otherwise there is no way to fix this.

**Comment by schiller-manuel** [comment]
closing this as no reproducer was provided.
happy to reopen once a reproducer is there.
