### ISSUE TITLE
The library is not compatible with "NodeNext" ts module resolution

### ISSUE THREAD

**Issue by vovkiv94** [TanStack/router#1128]
### Describe the bug

I have a package that uses "NodeNext" ts moduleResolution. 
When i try to add `'@tanstack/react-router'` imports like ` import { createRootRoute } from '@tanstack/react-router';` tsc is complaining that `error TS2305: Module '"@tanstack/react-router"' has no exported member 'createRootRoute'.` 

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

1. Create a new ts project and set ts module resolution to NodeNext
2. Install `@tanstack/react-router`
3. Import anything from the `@tanstack/react-router` library
4. Run `tsc`

### Expected behavior

The library should be compatible with `NodeNext` moduleResolution. 

### Platform

all

### Additional context

The issue is happening because the library ships `index.d.ts` file without  `.js` extensions in imports which is required by NodeNext. 
More details: https://github.com/microsoft/TypeScript/issues/50482

**Comment by schiller-manuel** [comment]
which version did you test this with? please provide a minimal example on e.g. codesandbox.

current versions of router have the correct exports:

![Screenshot 2024-02-01 at 20 43 12](https://github.com/TanStack/router/assets/6340397/a1762ea4-1e49-41ba-8832-bae701666330)

**Comment by vovkiv94** [comment]
Seems like I need to bump the version to `1.12.16+` where it was added. Thanks
