### ISSUE TITLE
File-based routing - digit started file names

### ISSUE THREAD

**Issue by eLeontev** [TanStack/router#1136]
### Describe the bug

file-based routing does not support digit started file names due to language syntax error during code generation of `routeTree.gen.ts`
Files with name `__404`, `404` or any **business** related `1st_anniversary` cannot be created due to this issue

**Reason:** Language specification limitation: (SyntaxError: An identifier or keyword cannot immediately follow a numeric literal.)
**MDN:** https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Identifier_after_number 

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

1. follow the instruction in quick start https://tanstack.com/router/v1/docs/framework/react/quick-start
2. add extra file starting with any digit (e.g. `__404.tsx` or `1st.custom.route.lazy.tsx`)
3. run dev/build to start code generation for `routeTree.gen.ts` file

### Expected behavior

new digit started routes work as expected

### Screenshots or Videos

![image](https://github.com/TanStack/router/assets/15786916/20915624-b4e7-42df-8b3a-e7d2c77a1873)

### Platform

- windows 10
- node: v20.10.0
- build: vite: 5.0.12 (template react-ts)
- integration with vite: @tanstack/router-vite-plugin: 1.15.4
- tans stack router: 1.15.7

### Additional context
**Optional:** it would be nice to align docs, since they contains 404 as a sample
https://tanstack.com/router/v1/docs/framework/react/guide/route-trees

**Suggested solution:** fix code gen script to start each variable name with predefined prefix e.g.  use `Route/Import` as prefix and not as a postfix or use regular flow like lodash/underscore based `_{variableName}`
![image](https://github.com/TanStack/router/assets/15786916/90c1959a-235b-4d7b-ae94-c1118fcf81c1)

**Comment by schiller-manuel** [comment]
This is already fixed in https://github.com/TanStack/router/releases/tag/v1.15.8, please upgrade.
