### ISSUE TITLE
Layout in folder doesn't work

### ISSUE THREAD

**Issue by WailRoth** [TanStack/router#1150]
### Describe the bug

Currently this works
/_layout/login.tsx -> /login
auth._layout.login.tsx -> /auth/login

Its just that this doesn't work
/auth/_layout/login.tsx -> /auth/layout/login

As you can see on the reproduction link, the _layout in the /auth/ folder is totally ignored by the router, ignoring my layout.

### Your Example Website or App

https://stackblitz.com/~/edit/github-odjbcq-wjavnw?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

Go on /auth/login, the layout isn't applied.

### Expected behavior

Apply the layout on /auth/_layout pages

### Platform

- OS: macOS
- Browser: [Edge]
- Version 114.0.1823.82 (Version officielle) (arm64)

**Comment by SeanCassiere** [comment]
For more context.

The problem is that the router-cli (vite-plugin) incorrectly infers the routing structure of a *layout* route when it is nested in a parent route.

✅ When the layout route is defined at the root, it generates the route tree correctly. [Example](https://stackblitz.com/~/edit/github-odjbcq?file=src%2Froutes%2F_layout.tsx)
```
src/routes
  _layout.tsx
  _layout/auth.login.tsx // generates the route /auth/login
  _layout/auth.register.tsx // generates the route /auth/register
  ...
```

✅ It also works correctly when flat files are used.
```
src/routes
  auth._layout.tsx
  auth._layout.login.tsx // generates the route /auth/login
  auth._layout.register.tsx // generates the route /auth/register
  ...
```

❌ However, when the layout is nested inside a parent folder is when stuff starts to break. [Reproduction where stuff is broken](https://stackblitz.com/~/edit/github-odjbcq-wjavnw?file=src%2Froutes%2F__root.tsx)
```
src/routes
  auth/
    _layout.tsx
    _layout/login.tsx // generates the route /auth/layout/login
    _layout/register.tsx // generates the route /auth/layout/register
  ...
```

✅ Weirdly enough, it works correctly if you define a `route.tsx` and `index.tsx` file within the auth route. [Example](https://stackblitz.com/edit/github-odjbcq-hfq9yv?file=src%2Froutes%2Fauth%2Froute.tsx)
```
src/routes
  auth/
    route.tsx
    index.tsx
    _layout.tsx
    _layout/login.tsx // generates the route /auth/login
    _layout/register.tsx // generates the route /auth/register
  ...
```

**Comment by ferretwithaberet** [comment]
I have the same issue, this is my folder structure:
![image](https://github.com/TanStack/router/assets/46427158/7564cb6e-c536-41b4-9a54-e5b0f0dcd38d)
I would expect `_BankAccounts` to not be added to the URL while being used as a layout for everything under `_BankAccounts/`. What actually happens is that `/BankAccounts` gets added to the URL.

The generated code from `routeTree.gen.ts` looks like this:
```ts
const ErpCompanyIdSettingsBankAccountsBankAccountsRoute =
  ErpCompanyIdSettingsBankAccountsBankAccountsImport.update({
    path: '/settings/bank-accounts/BankAccounts',
    getParentRoute: () => ErpCompanyIdRoute,
  } as any).lazy(() =>
    import(
      './routes/erp/$companyId/settings/bank-accounts/_BankAccounts.lazy'
    ).then((d) => d.Route),
  )
```

**Comment by divmgl** [comment]
Having this issue too. Layout routes are not working.
<img width="238" alt="Screenshot 2024-03-05 at 9 19 15 AM" src="https://github.com/TanStack/router/assets/5452298/da85a9f1-7f96-4903-bc4d-586a373dd818">

Projects and settings are inaccessible unless I move them out of the route. Pretty serious bug.......

**Comment by brandonryan** [comment]
Dev-tools needs an update. Gets confused about nested index routes:

Router Dev Tools:
![image](https://github.com/TanStack/router/assets/2406384/d35612a4-0c8e-4a83-8425-6ec365121c90)
File Tree:
![image](https://github.com/TanStack/router/assets/2406384/71f27dc5-f291-4eab-810d-9769cdaf00ef)

Thank you for this btw! Was the only thing holding me back from using this library for our production project.

**Comment by brandonryan** [comment]
I think it might actually be a bug with the route id?
![image](https://github.com/TanStack/router/assets/2406384/0459a078-c5d5-439e-87c8-69fd418b838e)

**Comment by schiller-manuel** [comment]
can you please create a new issue?

**Comment by mwood23** [comment]
I think this is still broken? The tree gen isn't picking up on the _ in workspaceLayout

![CleanShot 2024-03-09 at 18 03 16@2x](https://github.com/TanStack/router/assets/13633613/4cef90c5-6d62-437c-9567-7d0f1ddb9fad)
![CleanShot 2024-03-09 at 18 02 59@2x](https://github.com/TanStack/router/assets/13633613/86e083fb-246f-4522-a55d-f1de04404b02)

**Comment by alican-visuo-ai** [comment]
Is this issue really fixed? 

Still only works for me using the following structure recommended here

src/routes
  auth/
    route.tsx
    index.tsx
    _layout.tsx
    _layout/login.tsx // generates the route /auth/login
    _layout/register.tsx // generates the route /auth/register

**Comment by alicantorun** [comment]
Is this issue really fixed? Still only works for me using the following structure recommended here, which feels hacky 

![Screenshot 2024-03-11 at 20 56 41](https://github.com/TanStack/router/assets/46727738/f16195b1-9e86-4ec4-9cff-703cbbf15a9c)

**Comment by schiller-manuel** [comment]
@alicantorun can you please provide a minimal example by forking one of the examples on stackblitz ?
please also explain which workaround you consider "hacky" and would like to avoid.
