### ISSUE TITLE
link.d.ts: The expected type comes from property 'to' which is declared here on type ...

### ISSUE THREAD

**Issue by tiavina-mika** [TanStack/router#1151]
### Describe the bug

I have a type error when using <Link /> component.

### Your Example Website or App

https://codesandbox.io/p/github/tiavina-mika/vite-template

### Steps to Reproduce the Bug or Issue

[here](https://codesandbox.io/p/github/tiavina-mika/vite-template/main?file=%2Fsrc%2Fpages%2FLayout.tsx%3A9%2C54&workspaceId=f537bfc3-1f3e-4ada-958c-16a331c72bc2)
The warning:
![image](https://github.com/TanStack/router/assets/42656064/cbc988ee-b3cd-486c-93be-07979b7e586d)

### Expected behavior

There should be no warning

### Screenshots or Videos

![image](https://github.com/TanStack/router/assets/42656064/0763ac9a-cec8-4e95-849d-9cfb56250888)

### Platform

- OS: Windows10
- Browser :Chrome
- Version: 1.15.16

**Comment by schiller-manuel** [comment]
You will only get typesafety if you build the route tree as explained in the docs: https://tanstack.com/router/v1/docs/framework/react/guide/code-based-routing#manually-building-the-route-tree
