### ISSUE TITLE
Uncaught TypeError: [component from createLazyFileRoute].update is not a function

### ISSUE THREAD

**Issue by christian-rengifo** [TanStack/router#1176]
### Describe the bug

When trying to use `createLazyFileRoute`, I am met with a console error that breaks the application.

Hopefully I don't have a terrible architecture of routes. Open to better recommendations if there are any.

Thanks in advance, I still enjoy the package and all the work that's gone into it!

### Your Example Website or App

https://codesandbox.io/p/devbox/nifty-taussig-7c453s

### Steps to Reproduce the Bug or Issue

Open up console and see error

### Expected behavior

I expect the app not to break while I code split the components that utilize `createLazyFileRoute`

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment]
`$demoId.tsx` must be renamed to `$demoId.lazy.tsx`

see https://codesandbox.io/p/devbox/nifty-taussig-7c453s

see documentation https://tanstack.com/router/v1/docs/framework/react/guide/code-splitting#using-the-lazytsx-suffix

**Comment by christian-rengifo** [comment]
@schiller-manuel thanks for edited example. for some reason even when I was trying with .lazy.tsx locally, it wouldn't work out.. turned out I was on an v1.4.6 of @tanstack/router-vite-plugin which caused it. upgrading to latest fixed for me!
