### ISSUE TITLE
Implementing global error handling

### ISSUE THREAD

**Issue by kimsagro1** [TanStack/router#1181]
### Describe the bug

I am trying to implement a global error page and am having difficulties.

I have a sample here where you can try uncommenting the throw statements to see various scenarios
https://stackblitz.com/edit/github-rodaot?file=src%2Fmain.tsx

### Attempt 1 - ErrorBoundary
I first tried adding an ErrorBoundary to the root of my component tree, but it seem's like tanstack router has it's own in-built Something went wrong error component so my error boundary was never triggered.

### Attempt 2 - defaultErrorComponent
I next tried adding a defaultErrorComponent however the issue with this is that if the error is raised in the index component then the defaultErrorComponent is wrapped in the root layout. If the error is raised in the root component then the defaultErrorComponent is not wrapped in root layout. I'm trying to achieve an error page that looks the same in all scenarios.

### Issue 1 

It doesn't appear possible to achieve an error component that looks the same regardless of where the error is thrown and handles all scenarios?

### Issue 2

I also noticed that the error being thrown in the about loader doesn't seem to trigger the error component.

### Your Example Website or App

https://stackblitz.com/edit/github-rodaot?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Uncomment `// throw 'error from index';` to see the message `defaultErrorComponent: Something went wrong` but wrapped in the root layout
2. Uncomment `// throw 'error from root';` to see the message `defaultErrorComponent: Something went wrong` but *not* wrapped in the root layout
3. Uncomment `//  throw 'error from about loader';` to see the the error component is not shown

### Expected behavior

As a user I expected a way to show a fallback error component (much like when you specify a `notFoundComponent` on the `root` route) that displays the same regardless of where the error is thrown. Or perhaps a way to opt out completely and use my own error boundary 

### Platform

NA

**Comment by jaens** [comment]
This is a workaround, for now:
```
createRouter({
    ...
    defaultErrorComponent: (({ error }) => {
        throw error;
    }) satisfies ErrorRouteComponent,
});
```

It should indeed be nice to be able to disable error handling, in case the router is used in an environment that expects to handle errors completely on its own, eg. Storybook with Chromatic.

**Comment by geoff-harper** [comment]
https://github.com/TanStack/router/issues/724

**Comment by schiller-manuel** [comment]
is this still relevant?

**Comment by SeanCassiere** [comment]
Closing this since this should no longer be an issue with the user being able to set an `errorComponent` only on the root route and let the error bubble up to there.

https://stackblitz.com/edit/github-mx6tcy?file=src%2Froutes%2Fabout.tsx
