### ISSUE TITLE
`ToOptions` etc. types unusable?

### ISSUE THREAD

**Issue by jaens** [TanStack/router#1194]
### Describe the bug

It's not possible to use the `ToOptions`, `UseLinkPropsOptions` etc. types to store a link in a variable. It seems to always result in a type error. This is in the "basic" example.

(passing the exact same object to eg. `useLinkProps()` works fine)

I'm not sure what the type of a link is supposed to be, as I can't find any other possibilities anywhere in the documentation? Links do need to be occasionally stored in variables...

(note that using `as const` to not have a type at all is not a solution, in this simple example it would be, but practically this type also needs to occur in parameters or props, which always need an explicit type.)

![image](https://github.com/TanStack/router/assets/639345/c3d3291d-135e-4ebe-aec5-daf6fa2b8c08)

### Your Example Website or App

[CodeSandbox example (based on "basic")](https://codesandbox.io/p/devbox/dawn-cache-gwg7wl?file=%2Fsrc%2Fposts.tsx%3A11%2C10&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cls0fge4t00072v6e92l4ux0u%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cls0fge4t00022v6esrl0rxq7%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cls0fge4t00042v6e0obxjcno%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cls0fge4t00062v6euas78ggu%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cls0fge4t00022v6esrl0rxq7%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls0fge4s00012v6e5uwbexgq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clsqblr7a00022v6d6nibyex6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fposts.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A11%252C%2522startColumn%2522%253A10%252C%2522endLineNumber%2522%253A11%252C%2522endColumn%2522%253A10%257D%255D%257D%255D%252C%2522id%2522%253A%2522cls0fge4t00022v6esrl0rxq7%2522%252C%2522activeTabId%2522%253A%2522clsqblr7a00022v6d6nibyex6%2522%257D%252C%2522cls0fge4t00062v6euas78ggu%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls0fge4t00052v6ef6xag3fm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3001%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cls0fge4t00062v6euas78ggu%2522%252C%2522activeTabId%2522%253A%2522cls0fge4t00052v6ef6xag3fm%2522%257D%252C%2522cls0fge4t00042v6e0obxjcno%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cls0fge4t00032v6e14v5llp6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522cls0fge4t00042v6e0obxjcno%2522%252C%2522activeTabId%2522%253A%2522cls0fge4t00032v6e14v5llp6%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

_(edited, initial link was broken due to CodeSandbox bug...)_

### Steps to Reproduce the Bug or Issue

Check the Codesandbox.

### Expected behavior

There's some type I can use to store links that I can then pass to eg. `useNavigate()` or `useLinkProps()`

### Platform

all

**Comment by schiller-manuel** [comment]
`ToOptions` are relying on TS inferring types in e.g. `useNavigate`, so you can't use them as stand-alone types.
If you really need this kind of flexibility (and want give up on a lot of type-safety e.g. for search/path params) you can store the `to` prop as a string and pass it in:

```tsx
let to = '/';
useLinkProps({to});
```

**Comment by jaens** [comment]
I'm sorry, but that's not really a solution? I don't think this should be closed?

Are you saying there's **no way** to store links separately in a type safe way? That seems like... bad.

A simple solution would be to have a `link()` function like in the CodeSandbox that just returns the link as is, but would infer types. It's the standard TypeScript pattern of using an identity-function for type inference.

I'm just not sure what the type of such a `link`-function would be, given the visible type declaration in the public API is basically unapproachable without documentation:

```
export type UseLinkPropsOptions<TRouteTree extends AnyRoute = RegisteredRouter['routeTree'], TFrom extends RoutePaths<TRouteTree> | string = string, TTo extends string = '', TMaskFrom extends RoutePaths<TRouteTree> | string = TFrom, TMaskTo extends string = ''> = .....
```

**Comment by schiller-manuel** [comment]
What is "a link" exactly that you want to store in a "type safe way"? just the `to` part?

**Comment by jaens** [comment]
Everything that's in `ToOptions`, including parameters. Anything that can be passed to both `useNavigate()` and `useLinkProps()`.

**Comment by jaens** [comment]
I would actually be happy with just a single function that can make a literal turn into _any_ of the `*Options` types, since that's where the main benefit of type safety lies.

Anything else can be achieved by casting between the `*Options` types and does not really sacrifice the main benefit of type safety, which is strongly typing the path and params.

**Comment by jaens** [comment]
@schiller-manuel I believe this is still a valid issue/problem? Design systems often use generic link representations.

Here's my current "implementation" that works:

```typescript
export function link<
    TRouteTree extends AnyRoute = RegisteredRouter["routeTree"],
    TFrom extends RoutePaths<TRouteTree> | string = string,
    TTo extends string = "",
    TMaskFrom extends RoutePaths<TRouteTree> | string = TFrom,
    TMaskTo extends string = "",
>(options: UseLinkPropsOptions<TRouteTree, TFrom, TTo, TMaskFrom, TMaskTo>) {
    return options as UseLinkPropsOptions;
}

const _testLink: UseLinkPropsOptions = link({ to: "/" });
```

I can contribute a solution if there is consensus on how to move forward.

**Comment by tatwater** [comment]
In my case, I have a reusable component that, once the user is done with it, needs to be able to route different places based on where it started. I pass a prop I call `closeTo` into this component, and in its submit function it calls `navigate({ to: props.closeTo })`. I want to make sure that as more people work on this project with me, they get type-safe suggestions and warnings to ensure they pass a path into my component's `closeTo` prop that's a valid route in the `routeTree`. Having a quick and easy single exposed type that's even as simple as a union of all paths in the route tree would be awesome! Though I totally understand folks who would love type-safe params etc as well.

**Comment by CamParry** [comment]
I had the same issue and after a bit of playing around I found this works:

```typescript
import { RouterProvider, createRouter, Link, ToOptions } from '@tanstack/react-router';

import { routeTree } from './routeTree.gen';

export const router = createRouter({
	defaultPreload: 'intent',
	routeTree
});

const MyLink = ({ link }: { link: ToOptions<typeof router> }) => {
   return <Link {...link}>Testing</Link>
}

```

**Comment by ziw** [comment]
> I had the same issue and after a bit of playing around I found this works:
> 
> ```ts
> import { RouterProvider, createRouter, Link, ToOptions } from '@tanstack/react-router';
> 
> import { routeTree } from './routeTree.gen';
> 
> export const router = createRouter({
> 	defaultPreload: 'intent',
> 	routeTree
> });
> 
> const MyLink = ({ link }: { link: ToOptions<typeof router> }) => {
>    return <Link {...link}>Testing</Link>
> }
> ```

`ToOptions<typeof router>` worked out perfectly for us. Thank you

**Comment by SeanCassiere** [comment]
Closing this for now, since we've moved over to pushing `createLink`.

**Comment by evadecker** [comment]
> Closing this for now, since we've moved over to pushing `createLink`.

Can you link to the docs for this? I can't find any info on `createLink`.

**Comment by jaens** [comment]
> > Closing this for now, since we've moved over to pushing `createLink`.
> 
> Can you link to the docs for this? I can't find any info on `createLink`.

https://tanstack.com/router/v1/docs/framework/react/guide/custom-link

Note that `createLink` does not solve half the use cases in this issue, as it creates a link React **component**, which precludes usecases such as passing the link to `.navigate()`, or passing the same link to two different kinds of subcomponents (eg. regular "anchor-style" link and "button-style" link) etc.

**Comment by schiller-manuel** [comment]
are you maybe looking for https://tanstack.com/router/v1/docs/framework/react/api/router/linkOptions ?

**Comment by jaens** [comment]
Yes, that works, the new `linkOptions()` function is equivalent to the `link()` I proposed above.
