### ISSUE TITLE
`createFileLoader` type inference is sensitive to key order 

### ISSUE THREAD

**Issue by steevsachs** [TanStack/router#1198]
### Describe the bug

When calling `createFileRoute` in a typescript application, type inference is sensitive to the the order of the object keys provided.  We noticed this specifically with `loaderDeps` and `loader`: 
- if `loader` appears before `loaderDeps` (which is the default sort of our lint rules, for example), types do not infer. 
- if `loader` appears after `loaderDeps`, types do infer.

Thank you!

### Your Example Website or App

https://codesandbox.io/p/sandbox/tanstack-router-issue-4k796k?file=%2Fsrc%2Froute.tsx%3A16%2C4

### Steps to Reproduce the Bug or Issue

```import { createFileRoute } from "@tanstack/react-router";

interface TestParams {
  test?: string;
}

export const RouteWithTypeError = createFileRoute("/test-route")({
  component: () => <div>Hello</div>,
  validateSearch: (search: TestParams) => ({
    test: search["test"] ? search["test"] : "not-provided",
  }),
  // if loader key appears before loaderDeps, types are not inferred
  loader: ({ context, deps }) => {
    return deps.test;
  },
  loaderDeps: ({ search }) => search,
});

export const RouteNoTypeError = createFileRoute("/test-route")({
  component: () => <div>Hello</div>,
  validateSearch: (search: TestParams) => ({
    test: search["test"] ? search["test"] : "not-provided",
  }),
  // If loaderDeps key appears before loader, types are inferred
  loaderDeps: ({ search }) => search,
  loader: ({ context, deps }) => {
    return deps.test;
  },
});```


### Expected behavior

Because this is an object interface, we would not expect key order to have any effect on the typings.

### Screenshots or Videos

Error: 
![image](https://github.com/TanStack/router/assets/1848220/cb6aa8b0-8b84-48e6-9fce-46576059ae7b)
Inferred:
![image](https://github.com/TanStack/router/assets/1848220/da2bbee0-94ea-4c7a-97c5-f27f53f6f2ad)


### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]


### Additional context

_No response_

**Comment by schiller-manuel** [comment]
I think there is not much we can do here... do you have any suggestions ?

**Comment by tannerlinsley** [comment]
Other than making deep changes to provide a stricter builder api, this is necessary. I don’t plan on changing this either. It’s quite possible in the future that this inference will improve as it already has in the past to not be an issue.

**Comment by steevsachs** [comment]
I appreciate the responses, thank you!  If we come up with any good ideas, we'll definitely let you know : )

In the meantime, happy for this to be closed or however you all want to handle it.
