### ISSUE TITLE
Auth Routing 

### ISSUE THREAD

**Issue by chertik77** [TanStack/router#1199]
### Describe the bug

https://github.com/TanStack/router/assets/129002577/8e5d2683-22f3-41a6-b82e-1acde2e4e71e

### Your Example Website or App

https://stackblitz.com/github/tanstack/router/tree/main/examples/react/authenticated-routes-context?embed=1&theme=dark

### Steps to Reproduce the Bug or Issue

I sent a video, i also had an app with your beatiful router but because of that  - I came back to react router, i'm looking forward to see your help!

### Expected behavior

Not be able to come back after login using params

### Platform

- OS: macOS
- Browser: Arc
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment]
what's the problem? that the login state is not persisted?

**Comment by SeanCassiere** [comment]
@chertik77 the example you saw in the docs does not persist the user's authentication state. It is a demonstration of how, React context can be passed down into Tanstack Router and be read in the `beforeLoad` and `loader` callbacks to *protect* authentication-required pages.

Persisting the user's authentication state will be part of your application logic, through either an auth library or custom implementation.

**Comment by chertik77** [comment]
Oh, thanks. I didn't expect that, I thought it depended on the routing system so after login or signup, I could not come back, thank u for the explanation 👀👍

**Comment by SeanCassiere** [comment]
Sure thing!

Please close this issue.
