### ISSUE TITLE
After 30 seconds, hovering on link with search param sets the search param

### ISSUE THREAD

**Issue by pontusdacke** [TanStack/router#1201]
### Describe the bug

After loading a page, and waiting 30 seconds, hovering on a link with a search param will set the search param.
Its not set in the url unless you click, but the Route.useSearch() variable is set.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-mob5mz?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Go to stackblitz repro
2. After page is loaded, wait 30 seconds.
3. Hover "My link" with the mouse
4. A text appears that renders from the search parameter caught from `Route.useSearch()`.

Hovering before 30 does not cause issues.

### Expected behavior

The search param should not be set by hovering. 

### Platform

- OS: Windows 11 Version 23H2 (Build 22631.3007)
- Browser: Edge
- Version: 121.0.2277.128
- Chromium version: 121.0.6167.184

**Comment by pontusdacke** [comment]
The time is controlled by [staleAge](https://github.com/TanStack/router/blob/249e41e2af935a8f70f652720db8311592433ca7/packages/react-router/src/router.ts#L1392). 

```ts
// Lower to 1 second
const router = createRouter({
  routeTree,
  defaultPreload: 'intent',
  defaultPreloadStaleTime: 1_000,
});
```

As a work-around, setting `shouldReload: true` in the Route mitigates the issue.
```ts
export const Route = createFileRoute('/')({
  component: Home,
  validateSearch: (search: Record<string, unknown>): MyParams => {
    return {
      categoryIds: search.categoryIds as string[] | undefined,
    };
  },
  shouldReload: false,
});
```

or setting the `defaultPreload` to `false` or `undefined` in the route setup.
```ts
// Set up a Router instance
const router = createRouter({
  routeTree,
  defaultPreload: false,
});
```

**Comment by schiller-manuel** [comment]
should be fixed, please open a new issue if this is still relevant

**Comment by pontusdacke** [comment]
> should be fixed, please open a new issue if this is still relevant

I'm curious as to which change you expected to fix this issue?
1.22.9 still has the issue, and 1.23.0 contains no relevant changes. I'll open a new issue tomorrow.

**Comment by allan-vera** [comment]
I am experiencing this right now with v1.15.19. Have a few things I need to address before i can upgrade to the latest, but the `shouldReload: false` workaround appears to be working for me. Thank you for mentioning it.
