### ISSUE TITLE
Wrong component rendering in Basic Code Based Example

### ISSUE THREAD

**Issue by petertellgren** [TanStack/router#1205]
### Describe the bug

After rendering the Not Found component in Posts the next post selection does not render the post but Not Found remains shown.

### Your Example Website or App

https://tanstack.com/router/latest/docs/framework/react/examples/basic

### Steps to Reproduce the Bug or Issue

I think this bug is  on https://tanstack.com/router/latest/docs/framework/react/examples/basic

1. Go to Posts
2. click a post in the list
3. Click the last one ( Not found)
4. Click a post in the list:
5. **Not found still visible**

### Expected behavior

As a user I epxect the post selected to be show.

### Screenshots or Videos

![Screenshot 2024-02-21 at 11 12 43](https://github.com/TanStack/router/assets/76662/d7fb622e-dbbf-4f9e-8c1c-9a4d0aa2f2bc)

### Platform

- OS: macOS
- Browser: Chrome
- Version:121.0.6167.184 (Official Build) (arm64)

**Comment by schiller-manuel** [comment]
bug still exists in v.1.17.4


https://github.com/TanStack/router/assets/6340397/b5d9a150-1ffb-4b94-8f37-73ef0197956e

**Comment by SeanCassiere** [comment]
This was fixed in the [1.22.5](https://github.com/TanStack/router/releases/tag/v1.22.5) release.
