### ISSUE TITLE
Created a custom link element, it requires params, but they are not needed

### ISSUE THREAD

**Issue by xreider** [TanStack/router#1208]
### Describe the bug

Created a custom link element, it requires params, but they are not needed

### Your Example Website or App

https://github.com/xreider/tanstack_router_bug

### Steps to Reproduce the Bug or Issue

1. Yarn install
2. Go to `src\routes\__root.tsx`
3. Element CustomLink <CustomLink to='/' className="[&.active]:font-bold">Home</CustomLink> requires params, but no need actually

Error:
Type '{ children: string; to: "/"; className: string; }' is not assignable to type 'IntrinsicAttributes & TypeButtonNavIconLabel'.
  Property 'params' is missing in type '{ children: string; to: "/"; className: string; }' but required in type 'MakePathParamOptions<true | ParamsReducer<{} | {} | ({} & { cardId: string; }), {} | {} | ({} & { cardId: string; })>>'.ts(2322)
link.d.ts(58, 5): 'params' is declared here.

### Expected behavior

No need to add params on Custom Link
For e.g. the Link component above with the same path has no any params, and no errors

### Screenshots or Videos

![2024-02-22_20-34-01](https://github.com/TanStack/router/assets/49386751/e245584b-d0ba-4481-b3ac-3b44a649cc23)
![2024-02-22_20-33-34](https://github.com/TanStack/router/assets/49386751/81c6992f-f5a8-4db6-a1a7-de8487e13e23)
![2024-02-22_20-33-49](https://github.com/TanStack/router/assets/49386751/1f1cdcf6-fb82-4317-946f-562d579bda1e)

### Platform

- OS: Windows 11
- Browser: Opera
- Version: 107.0.5045.21

**Comment by SeanCassiere** [comment]
This is no longer present in the latest version. We'll sort out a better system for typing custom `<Link>` components.

For now, you can refer this example in a personal repo of mine on using LinkProps with the [correct generics])(https://github.com/SeanCassiere/nv-rental-clone/blob/c7cce2a8d2871df9e4576361eccac047d641cb77/src/routes/-components/auth/header/app-navigation.tsx#L120-L135).
