### ISSUE TITLE
Docs suggest `{ context: TAllContext }` in `loaderDeps` but it is not

### ISSUE THREAD

**Issue by lukaskoeller** [TanStack/router#1216]
### Describe the bug

The docs for [`loaderDeps`](https://tanstack.com/router/latest/docs/framework/react/api/router/RouteOptionsType#loaderdeps) indicate that you can access the `context` (besides e.g. `search`) to create a dependency record. Though, when I do that using `"@tanstack/react-router": "^1.16.6",` it is not found.

I assume it is either missing in the code or the docs are not up to date. If latter is the case, I wonder why `context` was removed, since I use it in `loader` to inject fetch arguments.

![No context in loaderDeps, only search](https://github.com/TanStack/router/assets/10390627/d89cc412-604d-48d6-b287-38fe6e99995a)

### Your Example Website or App

https://stackblitz.com/edit/github-swqukk?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to `main.tsx`
2. Go to line 34
3. See the underlined `context` error
4. See the `undefined` value in the console

### Expected behavior

I expect `context` from the `loaderDeps` to be defined.

### Screenshots or Videos

![Screenshot 2024-02-23 at 10 41 45](https://github.com/TanStack/router/assets/10390627/1cce5271-306a-45f8-9c84-38c3f70f31ee)

### Platform

- OS: macOS Sonoma 14.3.1
- Browser: Chrome
- Version: 1.16.6

**Comment by SeanCassiere** [comment]
Closed this with #2091.

I've written up an explanation in PR on the availability of `context` and `location` in `loaderDeps`.
