### ISSUE TITLE
[File based router] Catch all route (*) dir/file cannot be created on Windows OS

### ISSUE THREAD

**Issue by recallwei** [TanStack/router#1223]
### Describe the bug

It seems that cannot create a file dir named `*` or a file named `*.tsx` on Windows OS. So we cannot clone the repo which contains these on Windows. It violates the naming rules of Windows.

Router structure below:

<img width="282" alt="image" src="https://github.com/TanStack/router/assets/62941121/f227d488-19fd-4844-86f8-49eb117ae269">

### Your Example Website or App

Maybe no need to reproduce.

### Steps to Reproduce the Bug or Issue

Maybe description is enough.

### Expected behavior

Catch all route should be working on Windows.

### Platform

- OS: Windows

**Comment by tannerlinsley** [comment]
Use the dollar sign instead: $.tsx
