### ISSUE TITLE
[DevTools]: Panel is no longer usable on its own

### ISSUE THREAD

**Issue by happycollision** [TanStack/router#1246]
### Describe the bug

Attempting to use the TanstackRouterDevToolsPanel causes an error:

```
useDevtoolsOnClose must be used within a TanStackRouterDevtools component
```

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-lhmhbz?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

If you want to skip steps one and two, follow the link above.

1. Go to the latest basic example on stackblitz: https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart?embed=1&theme=light
2. Edit the file to use the dev tools _panel_. (Types must be satisfied with `setIsOpen`)
3. Observe the failuire

### Expected behavior

I expect the dev tools panel to appear or at least not crash.

### Screenshots or Videos

![CleanShot 2024-03-01 at 16 30 54@2x](https://github.com/TanStack/router/assets/3663628/b3aa1e77-4b42-485e-b65d-411315d0196b)

### Platform

- OS: macOS 14.3.1
- Browser: Safari, Chrome
- Version: (latest as of March 1, 2024)

**Comment by schiller-manuel** [comment]
did this work before https://github.com/TanStack/router/pull/1222 was merged?

**Comment by happycollision** [comment]
I don't know. I just tried it for the first time today as a workaround for #1065

**Comment by schiller-manuel** [comment]
can you please supply a complete example by forking the stackblitz example and applying the necessary changes?
