### ISSUE TITLE
Link component doesn't update URL with search params.

### ISSUE THREAD

**Issue by 01Boris** [TanStack/router#1268]
### Describe the bug

Link component in memorized sub-components doesn't update URL search params, without parent rerender.

- In dashboard like layout, we have multiple components that are memorized using `React.memo` to prevent rerenders. In this memorized components are used router `Link` component. 
- When user clicks on the link, search params are changed to show modals, etc... using old search params like:
    - `<Link search={old => ({...old, modalState: "visible" })} replace>Show modal</Link>`
- When the search params are changed, the child component isn't rerendered, and the old search in `Link` component neither.
- So we end up with mish-mash URLs in different links component:
    - real page `/about?param1=menu-prev`
    - Link1 `/about?param1=menu-prev`, sets `{param1: 'menu-prev'}`
    - LInk2 `/about?param1=menu-next&param2=menu-2`,  sets `{param2: 'menu-2'}`
- When using `useNavigate` hook, this works as intended.

### Your Example Website or App

https://stackblitz.com/edit/github-okg5qa?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to about page
2. On about page click on link `About + Prev`
3. On about page click on link `About + Param2`

### Expected behavior

Both `Link` components are updated to reflect the real search params so:
    - Link1 `/about?param1=menu-prev`
    - LInk2 `/about?param1=menu-prev&param2=menu-2`

### Platform

- OS: macOS
- Browser:  Chrome, Safari, Firefox
- Version: @tanstack/react-router@^1.19.1

**Comment by thomas-ndlss** [comment]
Hello, 

It seems that I'm having the same issue with the latest version:
When I add a `validateSearch` in a `createFileRoute`  
```typescript
/* eslint-disable unicorn/prefer-top-level-await */
import { z } from 'zod';

import { createFileRoute } from '@tanstack/react-router';

const searchValidators = z
	.object({ toto: z.number().optional().default(10).catch(20) })
	.optional()
	.default({ toto: 30 })
	.catch({ toto: 40 });

export const Route = createFileRoute('/_dashboard/dashboard/data/')({
	validateSearch: (search: Record<string, unknown>): z.infer<typeof searchValidators> => {
		return searchValidators.parse(search);
	},
	loader: () => {
		console.log('Inside loader: /_dashboard/dashboard/data/');
	},
});
```
In 1.16.0, it updates the url with the correct search params.
![Capture d’écran 2024-03-11 à 18 02 52](https://github.com/TanStack/router/assets/126558745/dc224d1f-9c24-4373-bf12-b94b47f1295f)
is updated:
![Capture d’écran 2024-03-11 à 18 02 56](https://github.com/TanStack/router/assets/126558745/febf9ffa-48a8-4a1e-bc2b-6542eab0a2fe)

In 1.19.4, it doesn't change the url, but the state inside tanstack router is up to date.
![Capture d’écran 2024-03-11 à 18 04 31](https://github.com/TanStack/router/assets/126558745/15418306-8773-4107-8dc5-2dd97c50fd65)
is not updated:
![Capture d’écran 2024-03-11 à 18 04 44](https://github.com/TanStack/router/assets/126558745/70c83667-7e35-44c4-91f3-14aebcd95b57)
But Devtools:
![Capture d’écran 2024-03-11 à 18 04 58](https://github.com/TanStack/router/assets/126558745/a6332935-3a23-41ae-b18a-d3de5197ce91)

Someone has any info on this ? 

Thank you in advance.

**Comment by thomas-ndlss** [comment]
Just to add more info on my previous message, it seems that the problem came between 1.18.3 & 1.18.4

**Comment by schiller-manuel** [comment]
so with 1.18.3 it worked as you expected ?

**Comment by thomas-ndlss** [comment]
Yes, with 1.18.3, it works as I expect it to work (it auto updates the search params according to the zod schema).
And in 1.18.4, it does not update anything.

**Comment by 01Boris** [comment]
We updated from lower version 1.3+ so I can't speak the last working example, but as @thomas-ndlss, we are using `validateSearch` with `zod` validation.
