### ISSUE TITLE
Issue with React Context in root route

### ISSUE THREAD

**Issue by trongbinh15** [TanStack/router#1269]
### Describe the bug

I wrap the whole app with DialogContext (in root route). When I use `useSearch` with an explicit `from` link within dialog content it throws an error (can see in attached stackblitz). It does not happen with `strict: false`

Any solution for this will be appreciated. Thanks

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-ljrdxn?file=src%2Froutes%2Findex.lazy.tsx

### Steps to Reproduce the Bug or Issue

Click Open 

### Expected behavior

Show not show error

### Platform

- OS: macOS
- Browser: Chrome
- Version: 122.0.6261.94

**Comment by SeanCassiere** [comment]
You are calling `useSearch({ from: '/about' })` when you are on the `/` page.

**Comment by schiller-manuel** [comment]
if you don't know the `from` value at compile time, you have to use 

```tsx
const search = useSearch({ strict: false})
```
