### ISSUE TITLE
redirect no type safety

### ISSUE THREAD

**Issue by AndreiTS** [TanStack/router#1274]
### Describe the bug

I am trying to use `redirect` from '@tanstack/react-router', but the `to` param is the type `string` instead of the routes:

![image](https://github.com/TanStack/router/assets/13489837/ff4ace28-4bc5-4ae0-81bd-b84613b55417)

This was working with a few routes but now that I have migrated all routes it stopped working.

My routeTree.gen.ts is big:
![image](https://github.com/TanStack/router/assets/13489837/ac06f97c-2bfb-450b-8e75-fce49bb83e3c)

Maybe this is a typescript perfomance thing?

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

I don't know how to reproduce

### Expected behavior

![image](https://github.com/TanStack/router/assets/13489837/940aff49-8a3e-48ec-abba-8d41acef397d)
![image](https://github.com/TanStack/router/assets/13489837/4b4fb091-9a93-4235-ab7e-7b7459e1465c)

### Platform

- OS: [Windows]
- Version:
"@tanstack/react-router": "^1.19.1",
"@tanstack/router-devtools": "^1.19.1",
"@tanstack/router-vite-plugin": "^1.19.0",

**Comment by schiller-manuel** [comment]
cc @chorobin

**Comment by AndreiTS** [comment]
I copied this example `https://github.com/TanStack/router/tree/main/examples/react/basic-file-based` and created a lot of routes to test:

With 900 routes it's fine:
![Sem título](https://github.com/TanStack/router/assets/13489837/5653fb5b-f0bb-4dce-b66f-e157b7eadc3b)

With 1000 routes it breaks:
![image](https://github.com/TanStack/router/assets/13489837/c314131f-b635-4b0f-9c74-cb23921ec958)

I don't have this many routes.

**Comment by schiller-manuel** [comment]
do you have lots of search / path params?

**Comment by AndreiTS** [comment]
> do you have lots of search / path params?

a few

**Comment by AndreiTS** [comment]
In my test project it's about 1000 routes, this routes:

![image](https://github.com/TanStack/router/assets/13489837/854c76fb-9f0d-4422-aece-ba362b44e8a9)
and another 997 test routes.

Until this point it was working:
![Sem título](https://github.com/TanStack/router/assets/13489837/c5be87ec-9862-493f-8a84-55d7a5fab49d)

Then, I created another test route, restarted vite and vscode, and it stopped (this took about 3min to load):
![image](https://github.com/TanStack/router/assets/13489837/31a1d1d2-e0ed-4e94-8005-4ca843121970)

In this case it makes sense that I'm hitting the typescript limit.
But, on my original project I don't have 1000 routes.

For comparison:

Test project (11k lines):
![image](https://github.com/TanStack/router/assets/13489837/c2eef482-0b54-4ab1-99b7-f455731eaa1e)

Original project (1k lines):
![image](https://github.com/TanStack/router/assets/13489837/93d7f43a-ecb2-4a5e-9176-8ebd220dae2d)

I dont really know what is happening here

**Comment by AndreiTS** [comment]
I don't think it's about the number of routes. I tested with different routes and got this results:

Test 1:
/public/ - not working
![image](https://github.com/TanStack/router/assets/13489837/9100985b-319c-401e-9439-b29830e7a238)

/auth/ - ok
![image](https://github.com/TanStack/router/assets/13489837/56ba7574-8904-4537-a2e5-12500ec9a782)

Test 2: 
/public/ - not working again
![image](https://github.com/TanStack/router/assets/13489837/e8e06e1b-2715-43ad-8102-11d00ec6873a)

/auth/ - working again
![image](https://github.com/TanStack/router/assets/13489837/50997d87-f240-4044-9066-f51d49d379e3)

**Comment by AndreiTS** [comment]
Mistery solved.

Some files are missing `.lazy` in the name and are using `createLazyFileRoute`:

![image](https://github.com/TanStack/router/assets/13489837/14c58740-63a1-4932-832d-0d0ec483c5d3)

fixed by adding `.lazy`:

![image](https://github.com/TanStack/router/assets/13489837/14d2db7c-97c3-48d8-96fa-c497c7d6bed1)

🤡

**Comment by schiller-manuel** [comment]
glad you found your problem, even better that we don't have anything to fix in the library :)

**Comment by AndreiTS** [comment]
> > Mistery solved.
> > Some files are missing `.lazy` in the name and are using `createLazyFileRoute`:
> > ![image](https://private-user-images.githubusercontent.com/13489837/311016362-14c58740-63a1-4932-832d-0d0ec483c5d3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDM2MTEsIm5iZiI6MTcwOTg0MzMxMSwicGF0aCI6Ii8xMzQ4OTgzNy8zMTEwMTYzNjItMTRjNTg3NDAtNjNhMS00OTMyLTgzMmQtMGQwZWM0ODNjNWQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIwMjgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4NjU1NTMzZDFlMWMwY2YwYzhmNDU0Mzk4ZjdlMjkyMGQzY2YzNDkzMGViODA4ZjBlNGVjYWNjNGZmMWU5ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6T38wks5RqwgtLhx2Tt4BJBPpy0wfi-KOaVNig1O7zs)
> > fixed by adding `.lazy`:
> > ![image](https://private-user-images.githubusercontent.com/13489837/311016629-14d2db7c-97c3-48d8-96fa-c497c7d6bed1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NDM2MTEsIm5iZiI6MTcwOTg0MzMxMSwicGF0aCI6Ii8xMzQ4OTgzNy8zMTEwMTY2MjktMTRkMmRiN2MtOTdjMy00OGQ4LTk2ZmEtYzQ5N2M3ZDZiZWQxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDIwMjgzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4YzM5ZWFhNDY5NGEzNWYyYmRiZDU5YTk1MmY1OGEzNTlkY2ZkZmQyNzMyZDRkMjgxMDA5NDQzMmE3NDQyMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LoeSeBCk8Iyvr1iuYtc-UfP7G48StoSNVh6oR9O_69U)
> > 🤡
> 
> Nice. How does tsc perform with the number of routes you have?

It takes some seconds to load, but it's fine.
