### ISSUE TITLE
Can't update search using `Link` component without providing `to` prop

### ISSUE THREAD

**Issue by kculmback-eig** [TanStack/router#1278]
### Describe the bug

In the docs, there is an example give where you can use the `Link` component to update search without having to provide a `to` prop (https://tanstack.com/router/latest/docs/framework/react/guide/navigation#search-param-links). However, typescript throws an error when attempting to do this:
```
Property 'to' is missing in type '{ children: string; replace: true; search: (prev: {} | {} | {}) => { test: string; }; }' but required in type 'CheckPathError<Route<any, "/", "/", string, "__root__", RootSearchSchema, RootSearchSchema, RootSearchSchema, RootSearchSchema, ... 11 more ..., any>>'.(2741)
```

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-5wgg6e?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

Add a `Link` component with only the `search` prop while using typescript. 
(See `src/routes/index.tsx` in linked reproduction for an example)

### Expected behavior

There should not be a type error about missing the `to` prop.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment]
@tannerlinsley 

This is the relevant snippet from the docs:

https://tanstack.com/router/latest/docs/framework/react/guide/navigation#search-param-links

> 🧠 Did you notice that how we didn't even need to supply a to prop? By default, all navigations are relative to the current route, so if you don't supply a to prop, it will just update the current route's search params.

Did this ever work? If yes, how was it typesafe?

**Comment by tannerlinsley** [comment]
It relies on the from being specified. At one point the to defaulted to “.” Which would resolve to the same route as from.

**Comment by schiller-manuel** [comment]
no, that won't work either. You have to specify a real route as `from`.
