### ISSUE TITLE
Layout Index Routes Don't Have Proper Id

### ISSUE THREAD

**Issue by brandonryan** [TanStack/router#1279]
### Describe the bug

Follow up of #1150.

Something in this changes caused the route id's to get a bit strange. Also causing confusion in dev tools

File Tree:
![311319082-2ee794e2-c133-4664-91c5-3d96ea2abfb6](https://github.com/TanStack/router/assets/2406384/6c45639d-5f5d-496e-bc42-9aaaf974e33b)

Router Dev Tools:
![311318390-d35612a4-0c8e-4a83-8425-6ec365121c90](https://github.com/TanStack/router/assets/2406384/35df754a-40e8-418c-9207-1897fb8abd00)
![311319423-0459a078-c5d5-439e-87c8-69fd418b838e](https://github.com/TanStack/router/assets/2406384/69f7ccc9-c1be-4f97-bd97-dc0cb7135621)

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

Create project as referenced above

### Expected behavior

I'm not exactly sure what the route Id should be but im pretty sure the layout should come before the second /auth

### Platform

- OS: Windows
- Browser: Firefox
- Version: 1.19.2

**Comment by schiller-manuel** [comment]
cc @SeanCassiere

**Comment by SeanCassiere** [comment]
I've fixed this locally. Will do some more testing and open a PR if all works as expected.

**Comment by SeanCassiere** [comment]
@brandonryan this should be fixed now.
