### ISSUE TITLE
Docs: incorrect useMatch argument description

### ISSUE THREAD

**Issue by nilshartmann** [TanStack/router#1281]
### Describe the bug

In the docs on `useMatch` at https://tanstack.com/router/latest/docs/framework/react/api/router/useMatchHook#usematch-options it says:

> The useMatch hook accepts a single _optional_ argument, an options object.

But the `options` object according to the type definitions is _not_ optional. I used tanstack/react-router 1.19.2

<img width="1030" alt="grafik" src="https://github.com/TanStack/router/assets/435073/636c215c-9e6f-4a45-bcc5-09f3e60b6b91">

### Your Example Website or App

https://stackblitz.com/edit/github-14t2wa?file=src%2Fmain.tsx%3AL15

### Steps to Reproduce the Bug or Issue

Use `useMatch`  in a component and do not specifiy any arguments.

### Expected behavior

Either the hook should work without args or the docs should be fixed.

### Platform

- TanStack Router 1.19.2
- TypeScript 5.3.3

**Comment by schiller-manuel** [comment]
yeah docs need to be updated. can you open a PR?

**Comment by nilshartmann** [comment]
opened pr #1282. I also tried to clarify the usage of `opts.from` and `opts.strict` as I think, it's not allowed to set `from` when `strict: false` and on the other hand it`s not allowed to skip `from` when `strict: true`.

please let me know if I should change anything.

**Comment by nilshartmann** [comment]
btw: how can I recive the current Match in a component? I thought it was just `useMatch()` but but that doesn't work, if `opts` is required. 

Now I use

```typescript
  const matches = useMatches();
  const current = matches[matches.length - 1];
```

Is this correct?

**Comment by schiller-manuel** [comment]
don't you know the current route you are in?

**Comment by nilshartmann** [comment]
no, i don't know the current route. I'm in a "generic" layout component that needs access to the current route' context.
