### ISSUE TITLE
Lazy routes are not generated on 1.19.3 version of router-vite-plugin

### ISSUE THREAD

**Issue by jureperak** [TanStack/router#1284]
### Describe the bug

I am using example code from https://tanstack.com/router/v1/docs/framework/react/quick-start

On version (latest currently) 1.19.3 of `@tanstack/router-vite-plugin` the lazy files are not imported in `routeTree.gen.ts` while on version 1.19.2 everything works.
Version of `@tanstack/react-router` is 1.19.2 (latest currently)

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-tbn9ny

### Steps to Reproduce the Bug or Issue

1. npm i
2. npm run dev
3. open app
4. the screen goes blank

### Expected behavior

The lazy files should be imported as on the previous version

### Platform

- OS: Windows
- Browser: Edge
- Version: 122.0.2365.80

**Comment by swarnim1494** [comment]
The routes are generated but for some reason they are not imported. Try the same thing with normal route (non lazy) routes and you will see, in the `routeTree.gen.ts` there are new import statements and everything works. Just need to fix the import statements for lazy routes.

**Comment by A-Wodnicki** [comment]
I noticed that this part is missing in `routeTree.gen.ts` in version 1.19.3, which is present when using 1.19.2:
```ts
// Create Virtual Routes

const IndexLazyImport = createFileRoute('/')()
```

**Comment by schiller-manuel** [comment]
fixed in https://github.com/TanStack/router/releases/tag/v1.19.5
