### ISSUE TITLE
Issue with nested params after updating to the latest release when prefixed with `_`

### ISSUE THREAD

**Issue by mgcrea** [TanStack/router#1289]
### Describe the bug

I'm encountering an issue with a nested param that is incorrectly skipped in the latest release, the newly generated routeTree is incorrect (cf. regression diff below in the generated output):

```diff
diff --git a/src/config/routeTree.gen.ts b/src/config/routeTree.gen.ts
index 78f84d0..8410d2c 100644
--- a/src/config/routeTree.gen.ts
+++ b/src/config/routeTree.gen.ts
@@ -72,13 +72,13 @@ const PrivateProjectsProjectIdRoute = PrivateProjectsProjectIdImport.update({
 
 const PrivateProjectsProjectIdUploadRoute =
   PrivateProjectsProjectIdUploadImport.update({
-    path: '/projects/$projectId/upload',
+    path: '/projects/upload',
     getParentRoute: () => PrivateRoute,
   } as any)
 
 const PrivateProjectsProjectIdImagesImageIdRoute =
   PrivateProjectsProjectIdImagesImageIdImport.update({
-    path: '/projects/$projectId/images/$imageId',
+    path: '/projects/images/$imageId',
     getParentRoute: () => PrivateRoute,
   } as any)
```

My routes:

```sh
▶ tree                                                                                                                           master|✚7 
.
├── __root.tsx
├── _private
│   ├── index.tsx
│   ├── projects
│   │   ├── $projectId.tsx
│   │   ├── _$projectId
│   │   │   ├── images
│   │   │   │   └── $imageId.tsx
│   │   │   └── upload.tsx
│   │   └── index.tsx
│   ├── test.tsx
│   └── users
│       └── index.tsx
├── _private.tsx
├── _public
│   ├── login.tsx
│   └── logout.tsx
└── _public.tsx
```

### Your Example Website or App

see code above

### Steps to Reproduce the Bug or Issue

1. generate routes

### Expected behavior

Expected the nested param to be properly preserved and not skipped

### Platform

- OS: macOS
- Browser: Safari
- Version: ^1.19.4

**Comment by schiller-manuel** [comment]
did you test with 1.19.6?

**Comment by schiller-manuel** [comment]
yes that was the question. can you please provide a minimal complete example e.g. by forking one of the existing examples on Stackblitz?

**Comment by schiller-manuel** [comment]
This does not work: `_$projectId`

A layout route cannot have a path parameter.

**Comment by mgcrea** [comment]
> This does not work: `_$projectId`
> 
> A layout route cannot have a path parameter.
> 
> Why isn't the folder named `$projectId`?

It used to work fine, if I name it `$projectId` I get two matches and I only have `projects/$projectId` that is rendered.

In my case I just want a separate page with the base layout and this specific path.

**Comment by schiller-manuel** [comment]
what do you mean by "two matches "?

**Comment by mgcrea** [comment]
My base layout in my case/tree is the `_private.txt` that looks like:
```
    <PrivateLayout params={params} breadcrumbs={query.data}>
      <Outlet />
    </PrivateLayout>
```

So basically I want:

- `/projects/$projectId`: `<PrivateLayout><ProjectPage /></PrivateLayout>`
- `/projects/$projectId/upload`: `<PrivateLayout><ProjectUploadPage /></PrivateLayout>`

If I drop the underscore, I get the following matches from the debug UI:

<img width="575" alt="Screenshot 2024-03-11 at 20 26 27" src="https://github.com/TanStack/router/assets/108273/8f30ee4a-1f58-4078-a95b-2e2e2a2f6891">

Which lead to only the first one (`projects/$projectId`) rendering, since it does not have an outlet the second/nested one is skipped.

Thanks for your help!

**Comment by schiller-manuel** [comment]
can it be that you are just missing an index route?

**Comment by mgcrea** [comment]
> can it be that you are just missing an index route?
> 
> move `/projects/$projectId.tsx` to `/projects/$projectId/index.tsx`

Looks like it works 👍! Thank you for your time and help!
