### ISSUE TITLE
Can't use errorComponent in createLazyFileRoute

### ISSUE THREAD

**Issue by umar006** [TanStack/router#1311]
### Describe the bug

I tried to use `errorComponent` in `createLazyFileRoute` but the component didn't show up when an error happened from the `loader`. But when I put `errorComponent` in `createFileRoute` it's working like what I expected (the component shows up). 

I want to know why it's like that because in [https://tanstack.com/router/v1/docs/framework/react/guide/code-splitting](https://tanstack.com/router/v1/docs/framework/react/guide/code-splitting), `errorComponent` is supported by the `createLazyFileRoute`

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-gtkrcc?file=src%2Froutes%2Findex.lazy.tsx

### Steps to Reproduce the Bug or Issue

1. open the example app in stackblitz
2. uncomment `errorComponent` in `createLazyFileRoute`, the component not show up
3. uncomment `errorComponent` in `createFileRoute`, the component show up

### Expected behavior

I was expecting the 'errorComponent' to show up from the 'createLazyFileRoute'

### Platform

- OS: Linux
- Browser: Chrome
- Version: 122.0.6261.111

Thank you

**Comment by AndreiTS** [comment]
You need both files.

https://tanstack.com/router/v1/docs/framework/react/guide/code-splitting#using-the-lazytsx-suffix

**Comment by umar006** [comment]
it's working, thank you

but I want to know, why I can't use `errorComponent` in `createLazyFileRoute`? 
because in [https://tanstack.com/router/v1/docs/framework/react/guide/code-splitting](https://tanstack.com/router/v1/docs/framework/react/guide/code-splitting), `errorComponent` is supported by the `createLazyFileRoute`

**Comment by AndreiTS** [comment]
oh, thats true, idk why it was not working.

**Comment by TkDodo** [comment]
I think this is a bug. According to the types and docs, we should be able to define `errorComponent` and `pendingComponent` alongside `component` in the `.lazy.tsx` file, so that they are code-split as well...

**Comment by schiller-manuel** [comment]
but the problem is that the loader, which is not code split, causes an error. then the error component is not available.

**Comment by TkDodo** [comment]
If the loader errors, I would expect the errorComponent to be lazy-loaded and then rendered, just like the component is also lazy-loaded and rendered when the loader is successful.

**Comment by SeanCassiere** [comment]
Re-tested with the latest version of TSR (1.28.7) and this now works.

Sandbox for testing: https://stackblitz.com/edit/tanstack-router-so1rct?file=src%2Froutes%2Findex.tsx

**Comment by farsil** [comment]
Hello, I was unfortunately able to reproduce the issue again with more updated libraries:
```
"dependencies": {
  "@tanstack/react-router": "1.166.2",
  "@tanstack/router-plugin": "1.166.2",
  "react": "19.2.4",
  "react-dom": "19.2.4"
},
"devDependencies": {
  "@types/react": "19.2.10",
  "@types/react-dom": "19.2.3",
  "@vitejs/plugin-react-swc": "4.2.2",
  "vite": "7.3.1"
}
```

https://stackblitz.com/edit/tanstack-router-on4kqf5s

While I have defined a custom error component in the lazy route (the error component defined in the normal route is commented out), TSR shows the default error component instead.

**Comment by schiller-manuel** [comment]
@farsil please create a new GitHub issue
