### ISSUE TITLE
Vite Plugin Route file generation does not work while Vite is running on Windows machines

### ISSUE THREAD

**Issue by natejboucher** [TanStack/router#1312]
### Describe the bug

We just implemented router in our application and developers with Mac machines have the code generation feature working while Vite is running, it picks up new files and file changes, like the documentation says ([docs](https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing))
However developers with Windows machines do not have that feature. The code generation only seems to check the folder when starting or restarting the application. 

We use the default configuration for the plugin with the `src/routes` folder structure. Currently running `router-vite-plugin: V1.19.0`  and  `tanstack/react-router: V1.19.1`. We tested the most recent release and the bug was still present, but decided to roll back due to known typescript issues.

This also does not work on the kitchen sink examples provided, however it is worth noting that it doesn't work there for Mac users either. 

### Your Example Website or App

https://tanstack.com/router/latest/docs/framework/react/examples/kitchen-sink-react-query-file-based

### Steps to Reproduce the Bug or Issue

1. Have a Windows machine
2. Have Tanstack Router in your application with the `router-vite-plugin` added. 
3. While the app is running, add a file to the `routes` folder 
4. The code generation feature should not have picked up the change and the file should remain empty, along with no changes to the `routeTree`
5. Stop the application and then start it
6. The code generation should pickup the new file, generate the code and update the `routeTree`

### Expected behavior

The code generation feature should see the new file or file change while Vite is running and run the code generation feature.

### Platform

- OS: Windows
- Browser: Chrome
- Version: React Router: `1.19.1` Router Vite Plugin: `1.19.0`

**Comment by SeanCassiere** [comment]
I made some changes to the hook that our vite plugin was using to watch for changes. It went out with [release 1.24.1](https://github.com/TanStack/router/releases/tag/v1.24.1).

@natejboucher - could you confirm if this has made any impact to the experience on Windows?
@nilshartmann - could you also confirm this against your scenarios that you listed?

**Comment by nilshartmann** [comment]
@SeanCassiere thanks a ton, it's working now 🎉  

Happy routing! 🐣

**Comment by SeanCassiere** [comment]
@natejboucher when you have chance, could you confirm if this change made any impact to the Windows experience?

You can download the [Router Stackblitz Starter](https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart-file-based) and quickly test it with the latest version of TanStack Router with the Vite Plugin.

**Comment by SeanCassiere** [comment]
Closing for now.

@natejboucher if this fix that went out with the release from this [comment](https://github.com/TanStack/router/issues/1312#issuecomment-2026265096) didn't fix the problem on Windows, please let us know.

**Comment by visualjerk** [comment]
@usmanabdurrehman I experienced the same issue on MacOS. Upgrading `vite` and `@vitejs/plugin-react` to the latest version fixed the issue for me.

**Comment by usmanabdurrehman** [comment]
@visualjerk 😭 man. Thank you so much. I thought when making apps with vite it would automatically install the latest vite versions but it was way behind. Thanks for the help 👍
