### ISSUE TITLE
Dynamic route matching component error

### ISSUE THREAD

**Issue by recallwei** [TanStack/router#1320]
### Describe the bug

Before, my router file structrue is:
```
- dynamic
  - route.lazy.tsx
  - $id
    - route.lazy.tsx
```

But now, `/dynamic/$id` seems not working. It will match `/dynamic` route.
(Seems router navigation is correct, but match the lazy component of `/dynamic`. Maybe the problem is routerTree.gen file not generated correctly.)

I have to change my file structure to:
```
- dynamic
  - index
    - route.lazy.tsx
  - $id
    - route.lazy.tsx
```

Now I should match `/dynamic` route exactly.

### Your Example Website or App

https://github.com/recallwei/dynamic-router-gen-recur

### Steps to Reproduce the Bug or Issue

```
pnpm i
pnpm dev
```

### Expected behavior

Expected to render the correct component.

<img width="159" alt="image" src="https://github.com/TanStack/router/assets/62941121/9c16448d-fa58-4a87-8875-36725b041314">

Click `dynamic-error/test` button will render the component of `dynamic-error` route.

### Platform

- OS: macOS 14.4
- Browser: Chrome
- Version: 122.0

**Comment by schiller-manuel** [comment]
This is expected.
In order to render a child match, a parent route must contain an `<Outlet />`.

Add it to `src/routes/dynamic-error/route.lazy.tsx`:
```tsx
import { Outlet, createLazyFileRoute } from '@tanstack/react-router'

export const Route = createLazyFileRoute('/dynamic-error')({
  component: () => <div>Hello /dynamic-error!<Outlet /></div>
})
```

![Screenshot 2024-03-17 at 06 38 21](https://github.com/TanStack/router/assets/6340397/d975d0f2-0bf4-468d-9f17-3bd63d6ccf0d)
