### ISSUE TITLE
Router's internal `state.location` is not updated when making manual changes to the url

### ISSUE THREAD

**Issue by Jarzka** [TanStack/router#1325]
### Describe the bug

I create my router like this:

```
const router = createRouter({routeTree})
```

Once the router has been created and the application is opened at the "/" route, the internal state of the router looks correct (i.e. `router.state.location.href` is `"/"` and `router.state.location.pathname` is also `"/"`.

Our application contains entry screen view that is rendered before anything else. The entry screen is NOT part of the TanStack router tree and it's not inside the RouteProvider context. We did this so that the entry screen could be easily rendered no matter what path was used to open the application. Also, by doing this, we do not tie the entry screen into individual route's render logic. Once the entry screen has been completed, its children are rendered (i.e. the current route).

A simplification of our component tree:

```
<EntryScreen>
   <Router />
</EntryScreen>
```

The entry screen contains a form which can be used to make some initial settings before entering the application. When these settings are changed, the page url is also modified to match the settings. For example, changing the language might update the url to look like this: `/en`

Since the EntryScreen is not part of the RouteProvider context, we cannot update the url using the router itself, but we manually modify it using native browser functions, like:

```ts
  const url = `/${uiLanguage}/${restOfPath}${queryParams}`;
  history.replaceState({}, "", url);
```

This causes a problem: When we modify the url like this and enter the application, nothing gets rendered. I believe this happens because the internal state of the router (i.e.  `router.state.location.href` and `router.state.location.pathname` still contain the old url `"/"`.

In the previous version of the router (`0.0.1-beta.185`) this was not a problem: we were able to modify the url manually and the router was happy. When we upgraded the router to `1.19.4` this problem started to happen. To workaround this problem, we update the router's internal state manually like this:

```ts
  history.replaceState({}, "", url);
  router.state.location.href = url;
  router.state.location.pathname = url;
```

After this, everything works just like before and the actual route is rendered after the entry screen has been completed.

Now I do understand if the router was not meant to follow manual url modifications in the first place, but I'm a bit confused why this behavior has been changed. Is this a bug or is it meant to work like this?

Also, I do believe our workaround is not an optimal solution for this problem in the long run as I believe we probably should not alter the router's internal state manually. Is there a better way to tell the router if the url has been updated manually and it needs to be updated into its internal state?

**Comment by schiller-manuel** [comment]
why don't use call `router.navigate({...})` instead of trying to rely on some internal behavior?

**Comment by Jarzka** [comment]
> why don't call `router.navigate({...})` instead of trying to rely on some internal behavior?

We tried that and were confused as it did not do anything. The internal state of the router remained unchanged. We guessed that `router.navigate` cannot be called outside of the RouterProvider context. 🤔

**Comment by schiller-manuel** [comment]
this works, see https://stackblitz.com/edit/tanstack-router-rsmqia?file=src%2Fmain.tsx

**Comment by Jarzka** [comment]
Thanks for clarifying that it should work and indeed it works in your minimal example. I wonder what's wrong in our case. Let me try to understand the differences and I'll get back if I find out something.

**Comment by Jarzka** [comment]
I think I was able to re-create the problem. Take a look: https://stackblitz.com/edit/tanstack-router-lclelz?file=src%2Fmain.tsx

When you press "Complete entry screen", nothing shows up.

However, if you change this:
```
{isButtonPressed && <RouterProvider router={router} />}
```
to this:
```
{<RouterProvider router={router} />}
```

the posts show up after pressing the button. However, I need that `isButtonPressed` check for blocking the normal navigation flow until the button has been pressed. :)

**Comment by schiller-manuel** [comment]
seems like you first need to render the `<RouterProvider>`, then call `router.navigate`:

https://stackblitz.com/edit/tanstack-router-kpj4yv?file=src%2Fmain.tsx

**Comment by Jarzka** [comment]
This looks like a reasonable solution. I'll try to use this in our application. Thanks!

**Comment by Jarzka** [comment]
This solution seems to work fine. Also, it seems that calling `router.navigate(...)` after the route has been rendered is enough, without using `createBrowserHistory` and passing `history` to the `RouterProvider`.

**Comment by Jarzka** [comment]
Actually, I found even simpler solution! I can keep `RouterProvider` always mounted, but hide it visually with CSS until the entry screen has been completed. This way `router.navigate()` can be called immediately when pressing the "Complete entry screen" button. It also makes it even faster the load the actual page as it is already built in the background.
