### ISSUE TITLE
bad types in file link.d.ts

### ISSUE THREAD

**Issue by livwvil** [TanStack/router#1343]
### Describe the bug

There is wrong types in link.d.ts:

```ts
...
export declare function createLink<const TComp>(Comp: TComp): LinkComponent<TComp>;
...
```

My ts says: `ERROR(TypeScript)  Declaration or statement expected.`

![image](https://github.com/TanStack/router/assets/53614453/539f153b-5ddd-406b-a498-9492cf3d85ab)

### Your Example Website or App

nope

### Steps to Reproduce the Bug or Issue

1. Get "@tanstack/react-router": "^1.20.5" in your project
2. Try to run project

### Expected behavior

No errors displayed

### Platform

- OS: Windows
- Browser: Chrome
- Version: 122
- @tanstack/react-router: "^1.20.5"
- typescript: "^4.9.5"

### Additional context

I have no this errors on "@tanstack/react-router": "^1.19.1"

**Comment by schiller-manuel** [comment]
which typescript version are you using?

**Comment by livwvil** [comment]
Just updated: `"typescript": "^4.9.5"`

**Comment by TkDodo** [comment]
I think we should just state that the minimal required TS version is v5.0

**Comment by TkDodo** [comment]
docs are updated with:
- https://github.com/TanStack/router/pull/1367

**Comment by GutsSOLO** [comment]
> > I think we should just state that the minimal required TS version is v5.0
> 
> Do you think it is the only way?

another solution would be : export declare function createLink<TComp>(Comp: TComp): TComp;

**Comment by TkDodo** [comment]
We only want to support TS 5.0 and upwards for other reasons too

**Comment by GutsSOLO** [comment]
For those who may need there is a patch file if you're working under typescript < 5.x.x

`
diff --git a/node_modules/@tanstack/react-router/dist/esm/link.d.ts b/node_modules/@tanstack/react-router/dist/esm/link.d.ts
index b523933..b9113bd 100644
--- a/node_modules/@tanstack/react-router/dist/esm/link.d.ts
+++ b/node_modules/@tanstack/react-router/dist/esm/link.d.ts
@@ -91,6 +91,6 @@ type LinkComponent<TComp> = <TRouteTree extends AnyRoute = RegisteredRouter['rou
 }> | React.Component<{
     ref: infer TRef;
 }> ? TRef : TComp extends keyof JSX.IntrinsicElements ? React.ComponentRef<TComp> : never>) => React.ReactElement;
-export declare function createLink<const TComp>(Comp: TComp): LinkComponent<TComp>;
+export declare function createLink<TComp>(Comp: TComp): TComp;
 export declare const Link: LinkComponent<'a'>;
 export {};
[@tanstack+react-router+1.22.7.patch](https://github.com/TanStack/router/files/14759834/%40tanstack%2Breact-router%2B1.22.7.patch)

`
