### ISSUE TITLE
HMR crash (under very specific circumstances)

### ISSUE THREAD

**Issue by jakst** [TanStack/router#1353]
### Describe the bug

I've got a real interesting HMR bug. It only happens under very specific circumstances.

This is the error message
```
Invariant failed: No match found for route '/_layout/a/b' while rendering the '/_layout/_layout/a/b' route. Did you mean to pass '{ strict: false }' instead?
```

Of course there's only one _layout file in my file tree, not two, so tanstack is adding an extra layout.

### Your Example Website or App

 https://stackblitz.com/edit/github-szfxdx?file=README.md

### Steps to Reproduce the Bug or Issue

1. `pnpm install`
2. `pnpm dev`
3. open http://localhost:3999 (you'll be redirected to http://localhost:3999/a/b,
  which is the problematic route)
4. In your editor, open [bQuery.graphql.ts](./__generated__/bQuery.graphql.ts)
5. With the browser still open, press save inside the file.
6. HMR should trigger and render this error:

```
Invariant failed: No match found for route '/_layout/a/b' while rendering the '/_layout/_layout/a/b' route. Did you mean to pass '{ strict: false }' instead?
```

### Expected behavior

HMR shouldn't crash the page when editing files.

### Platform

Stackblitz

### Additional context

I can only get it to reproduce with Relay in the mix, but the double `_layout` in the error message still makes me believe it's tanstack causing the error.

The error only happens under the very specific circumstances I put together in the repro. If the main.tsx and router.tsx files are merged into one, the error disappears. Without lazy routes, the error disappears. Without the nested layout, the error disappears.

**Comment by tannerlinsley** [comment]
This is one funky bug

**Comment by jakst** [comment]
**Additional context**

1. This is printed to the console when it happens
```
[vite] hmr invalidate /app/app.tsx Could not Fast Refresh ("true" export is incompatible). Learn more at https://github.com/vitejs/vite-plugin-react-swc#consistent-components-exports
```

2. Before `v1.21.1` the error message was `Cannot read properties of undefined (reading 'routeId')`, but I suspect that's just a change in error reporting.

**Comment by SeanCassiere** [comment]
Just tested this using the latest version of TSR, and I don't see these error messages any more.

@jakst could you confirm?

**Comment by jakst** [comment]
@SeanCassiere the issue is still there in v1.26.7/v1.26.8. The error message changed a bit though. It's now `Invariant failed: Could not find an active match from "/_layout/a/b"`

I forgot to mention in the instructions that you have to actually make a change in the file to trigger the error, so that might be why you can't reproduce. Here's the upgraded version https://stackblitz.com/edit/github-szfxdx-jvydpf?file=__generated__%2FbQuery.graphql.ts

**Comment by SeanCassiere** [comment]
> I forgot to mention in the instructions that you have to actually make a change in the file to trigger the error, so that might be why you can't reproduce. Here's the upgraded version https://stackblitz.com/edit/github-szfxdx-jvydpf?file=__generated__%2FbQuery.graphql.ts

Yup you are right. Honestly its hard to determine where this problem lies.

Good news is that making the [project](https://stackblitz.com/edit/github-szfxdx-etwfc1?file=__generated__%2FbQuery.graphql.ts) use the new `experimental.enableCodeSplitting` flag seems to resolve it, so hopefully when that exits the experimental stage, we should be able to close this.

**Comment by jakst** [comment]
I wouldn't consider it closed because of automatic code splitting though. We use Relay which indirectly enforces manual conventions on our page file names, so we need to use manual code splitting.

Until this works in all available modes, I would like to keep this open.

**Comment by sethmbrown** [comment]
Any updates here? Running into the same issue in our project as well.

**Comment by ccapndave** [comment]
My app also crashes when fast-refreshing, although it manifests as a hook provider not existing:

```
@react-refresh:267 Error: You used a hook from "ActorProvider" but it's not inside a <ActorProvider> component.
    at Object.useContext2 [as useActorRef] (@xstate_react.js?v=64932f4e:183:13)
    at useSystemActor (useSystemActor.ts:5:36)
    at HomePage (HomePage.tsx:17:24)
    at renderWithHooks (chunk-F6HKJT7G.js?v=43636092:12171:26)
    at updateFunctionComponent (chunk-F6HKJT7G.js?v=43636092:14577:28)
    at beginWork (chunk-F6HKJT7G.js?v=43636092:15912:22)
    at beginWork$1 (chunk-F6HKJT7G.js?v=43636092:19749:22)
    at performUnitOfWork (chunk-F6HKJT7G.js?v=43636092:19194:20)
    at workLoopSync (chunk-F6HKJT7G.js?v=43636092:19133:13)
    at renderRootSync (chunk-F6HKJT7G.js?v=43636092:19112:15
```

Not sure if its the same issue, but it also happens when saving a file and causes a hot refresh.

**Comment by ccapndave** [comment]
So I managed to fix my problem and I'm not sure it is related to this issue after all but in case someone ends up here after searching HMR, here is what I found.  It seems that if a context provider is declared outside of the `RouterProvider`, it will be lost on HMR:

```
<MyProvider>
  <RouterProvider router={router} />
</MyProvider>
```

is *not* ok.  Instead I needed to move `MyProvider` inside the `__root`.

**Comment by bolyesz** [comment]
The issues still persists on the latest version, we have a /vehicles route under a _protected route, and when I save any file without changes I get this error: `Invariant failed: Could not find an active match from "/_protected/vehicles/"` and when I check the devtools I see a cached route match: "/_protected/_protected/vehicles/"

**Comment by GutsSOLO** [comment]
I also have the same issue as @bolyesz do we have any solution for this ?

**Comment by GutsSOLO** [comment]
@bolyesz if you use a setTimeout before your navigate({to: '/'}) it should fix the issue the time we find a solution

**Comment by bolyesz** [comment]
I removed all my `.lazy` routes and it seems that it fixed my issue, also I had problems with full page reloads on file save, which was also sorted out by these changes

**Comment by TTRiznykLeo** [comment]
Having similar issue, 
It occurs when i use useSearch and the route is under _protected 

const search = useSearch({ from: '/_protected/a/b/' })
`Error: Invariant failed: Could not find an active match from "/_protected/a/b/"`

But when i use
const search = useSearch({ from: '/a/b/' })

The issue disappears, but i getting type error: 
`Type '"/a/b/"' is not assignable to type '"__root__" | "/" | "/_protected/a/b" | ..... `

**Comment by guilhermeguidetti** [comment]
same as @TTRiznykLeo, but when using useLoaderData

my layout:
```ts
export const Route = createFileRoute("/(private)/_private")({
	component: () => (
		<div>
			<MainNavBar />
			<Outlet />
		</div>
	),
});
```


`const userData = useLoaderData({ from: "/_private/perfil/$userId/" });`

`Invariant failed: Could not find an active match from "/_private/perfil/$userId/"`

**Comment by guilhermeguidetti** [comment]
> same as @TTRiznykLeo, but when using useLoaderData
> 
> my layout:
> 
> ```ts
> export const Route = createFileRoute("/(private)/_private")({
> 	component: () => (
> 		<div>
> 			<MainNavBar />
> 			<Outlet />
> 		</div>
> 	),
> });
> ```
> 
> Profile page
> 
> ```ts
> export const Route = createFileRoute(
> 	"/(private)/_private/(profile)/perfil/$userId/"
> )({
> 	component: UserPage,
> 	loader: async ({ params }) => {
> 		const userId = params.userId;
> 		const userData = await fetchUser(userId);
> 		return userData;
> 	},
> 	beforeLoad: async () => {
> 		if (!(await isAuthenticated())) {
> 			throw redirect({
> 				to: "/entrar",
> 			});
> 		}
> 	},
> });
> 
> export default function UserPage() {
> 	const userData = useLoaderData({ from: "/_private/perfil/$userId/" });
> 
> 	return (
> 		<div>
> 			<h1>{userData?.name}</h1>
> 			<p>{userData?.avatar}</p>
> 			{/* Renderize outras informações do usuário */}
> 		</div>
> 	);
> }
> ```
> 
> `Invariant failed: Could not find an active match from "/_private/perfil/$userId/"`

I updated my tanstack-router package from 1.48.1 to 1.48.4 and its now fixed

**Comment by alex-delia** [comment]
Cannot reproduce with version v1.91.2

https://stackblitz.com/edit/github-szfxdx-d7gysjgs?file=README.md

The original code still says it cannot hot reload, but this can be fixed by simply exporting the App component in main.tsx

**Comment by jakst** [comment]
> Cannot reproduce with version v1.91.2
> 
> https://stackblitz.com/edit/github-szfxdx-d7gysjgs?file=README.md
> 
> The original code still says it cannot hot reload, but this can be fixed by simply exporting the App component in main.tsx

Yeah you're right, it seems fixed. Closing 🙂

**Comment by Rick-Phoenix** [comment]
Still getting this problem even after exporting the app in main.tsx

**Comment by mahmingtea** [comment]
> Still getting this problem even after exporting the app in main.tsx

have you tried export default?

**Comment by martiuh** [comment]
I've got a similar error while using XState, Astro and React I don't understand very well the cause.

```ts
// onboarding-form.ts
import { Step1 } from './step-1';

export const MachineContext = createActorContext(machine);

export function OnboardingForm() {
  return (
    <OnboardingMachineContext.Provider>
      <Onboarding />
    </OnboardingMachineContext.Provider>
  );
}
```

Then I thought it was related to circular dependencies since I was importing the `MachineContext` in my `Step1`, then I created the context in a separate file `onboarding-machine-context` and import it

```ts
// onboarding-form.ts
import { Step1 } from './step-1';
import { MachineContext } from './onboarding-machine-context'

export function OnboardingForm() {
  return (
    <OnboardingMachineContext.Provider>
      <Onboarding />
    </OnboardingMachineContext.Provider>
  );
}
```

And it fixed it. Hope this can help someone else.

**Comment by schiller-manuel** [comment]
@martiuh  can you please create a new issue including a complete reproducer project ?
