### ISSUE TITLE
TSR Config double quotes causing TSR to remove semicolons in routeTree.gen.ts file

### ISSUE THREAD

**Issue by rieger-jared** [TanStack/router#1375]
### Describe the bug

With this TSR config, I'm losing the default style in which all statements are terminated with semicolons. 

```js
{
  "routesDirectory": "./src/routes",
  "generatedRouteTree": "./src/routeTree.gen.ts",
  "routeFilePrefix": "~",
  "quoteStyle": "double"
}
```

However when it's single quotes this does not happen. Our code style is linted to have semicolons so this is causing an issue for our CIs. 

```json
{
   "dependencies": {
    "@sniptt/monads": "^0.5.10",
    "@tanstack/react-query": "^5.24.1",
    "@tanstack/react-router": "^1.16.6",
    "@types/luxon": "^3.4.2",
    "@types/react-day-picker": "^5.3.0",
    "axios": "^1.6.7",
    "filepond": "^4.30.6",
    "filepond-plugin-file-validate-type": "^1.2.9",
    "filepond-plugin-image-preview": "^4.6.12",
    "filepond-plugin-media-preview": "^1.0.11",
    "firebase": "^10.8.0",
    "lucide-react": "^0.341.0",
    "luxon": "^3.4.4",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-filepond": "^7.1.2",
    "react-google-recaptcha-v3": "^1.10.1",
    "react-grid-gallery": "^1.0.1-alpha.0",
    "react-responsive-carousel": "^3.2.23",
    "sonner": "^1.4.1",
    "zustand": "^4.5.1"
  },
  "devDependencies": {
    "@acme/eslint-config": "^0.2.0",
    "@acme/prettier-config": "^0.1.0",
    "@acme/tailwind-config": "^0.1.0",
    "@acme/tsconfig": "^0.1.0",
    "@acme/ui": "^0.1.0",
    "@flydotio/dockerfile": "^0.5.2",
    "@tanstack/router-devtools": "^1.16.6",
    "@tanstack/router-vite-plugin": "^1.16.5",
    "@types/luxon": "^3.4.2",
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "@typescript-eslint/eslint-plugin": "^7.0.2",
    "@typescript-eslint/parser": "^7.0.2",
    "@vitejs/plugin-react": "^4.2.1",
    "autoprefixer": "^10.0.1",
    "eslint": "^8.56.0",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-react-refresh": "^0.4.5",
    "postcss": "^8.4.35",
    "tailwindcss": "^3.4.1",
    "typescript": "^5.2.2",
    "vite": "^5.1.4"
  }
  ```

### Your Example Website or App

https://stackblitz.com/github/tanstack/router/tree/beta/examples/react/quickstart?file=package.json,README.md

### Steps to Reproduce the Bug or Issue

1. using the dependencies and the tsr config listed above checkout a new project and add some routes. You should see that while the routes are quoted with double quotes there are no semicolons at the end of statements.

### Expected behavior

I expect that when I change the double quotes tsr config that I preserve the existing semicolons in the routes file.

### Platform

- OS: [e.g. macOS]

**Comment by SeanCassiere** [comment]
Just to get the jist of it, you need to be able to add semi-colons to the generated `routeTree.gen.ts`.

**Comment by SeanCassiere** [comment]
@rieger-jared you can now add semicolons to your generated route-tree using `semicolons: true` flag in your `tsr.config.json`.

**Comment by SeanCassiere** [comment]
> I'm I missing something? I'm using the router version `"@tanstack/react-router": "^1.23.1"`

The vite plugin needs to also be upgraded.

`yarn add @tanstack/react-router@latest @tanstack/router-vite-plugin@latest`
