### ISSUE TITLE
navigate (of useNavigate) should make 'to' property optional

### ISSUE THREAD

**Issue by tmax22** [TanStack/router#1380]
### Describe the bug

the following:
```
  navigate({
              search: {
                stage: nextStage,
              },
            });
```
makes a typescript error
```
Property to is missing in type <blabla>
```
![image](https://github.com/TanStack/router/assets/147702803/2f777c5e-371f-4fa6-b21a-ffaf47bc545b)

while here we are just changing the search param.('to' remains the same)  
This also works with no problem in runtime, the only issue is the typescript issue.

adding 'to' relaxes the typescript error
```
            navigate({
              to: "/clearances/$clearanceName",
              search: {
                stage: nextStage,
              },
            });
```
please make 'to' optional in the typescript declarations.

### Your Example Website or App

localhost:3000

### Steps to Reproduce the Bug or Issue

.

### Expected behavior

.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
.

**Comment by SeanCassiere** [comment]
A lot of this can vary on your typescript version, how you are validating your URL search params, how you've definite your routes, etc.

Please provide a minimal reproduction so we diagnose and solve the issue you are facing.

You can create a minimal reproducible example using one of our quickstart Stackblitz examples:
* [File-based](https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart-file-based)
* [Code-based](https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart)

**Comment by tmax22** [comment]
hey, after @tanstack/react-router updating to ^1.22.9 the issue has relaxed. this issue can be closed, sorry 🙃
