### ISSUE TITLE
preload="intent" triggers navigations in route's beforeLoad handler

### ISSUE THREAD

**Issue by its-jman** [TanStack/router#1382]
### Describe the bug

Links to a route will trigger any navigation inside the beforeLoad handler, when preloading that route. This can be reliably resolved by disabling preloading. 

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-zhwi16

### Steps to Reproduce the Bug or Issue

Hover "about" link. It will navigate to "/third" without you clicking on the link 

*(about is a route with a beforeLoad which navigates to "/third". )*

### Expected behavior

preloading does not trigger navigation from the preloaded page

### Screenshots or Videos

https://github.com/TanStack/router/assets/11013297/a652ed21-3935-439b-bfa8-286f71788990

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

Similar sounding previous issues, probably unrelated:
https://github.com/TanStack/router/issues/1201
https://github.com/TanStack/router/issues/1220

**Comment by louneskmt** [comment]
I personally use the `preload` boolean from `beforeLoad` parameters to conditionally navigate. 

In your example:
```ts
export const Route = createFileRoute('/about')({
  component: AboutComponent,
  beforeLoad({ navigate, preload }) {
    if(!preload) {
      navigate({ to: '/third' });
    }
  },
});
```

Not sure what the correct behaviour should be.

**Comment by its-jman** [comment]
Interesting, I hadn't seen that before. But I'd definitely envision that `navigate` behaves as a `preload` function if the `preload` flag is true, or is just a no-op if you don't want to follow navigations. Any arbitrary page shouldn't have to worry about those kinda things.

**Comment by louneskmt** [comment]
Now that you say it, it looks like a throwing a redirect in `beforeLoad` doesn't trigger a navigation when preloading. Should we have the same behavior for `navigate`?

**Comment by SeanCassiere** [comment]
This looks to be one of those anti-patterns that got carried over in the rapid development from beta.

@its-jman @louneskmt going forward please use the redirect function.

```tsx
import { createFileRoute, redirect } from '@tanstack/react-router';

export const Route = createFileRoute('...')({
  beforeLoad: () => {
    throw redirect({ to: '/somewhere' })
  }
})
```

**Comment by louneskmt** [comment]
Thank you @SeanCassiere!

**Comment by ali-shabani** [comment]
The `preload` is always set to false, and every time I hover over a link, the `beforeLoad` gets triggered—pretty annoying.
I'm using:
```
"@tanstack/react-router": "^1.114.23"
```

**Comment by schiller-manuel** [comment]
@ali-shabani please create a new GitHub issue including a complete minimal example
