### ISSUE TITLE
Typescript errors from using "navigate"

### ISSUE THREAD

**Issue by roastdev** [TanStack/router#1387]
### Describe the bug

Navigate from useNavigate of Tanstack Router is throwing a typescript error in later versions when about a month or so ago this setup did not produce a typescript error/warning

### Your Example Website or App

https://stackblitz.com/github/tanstack/router/tree/beta/examples/react/quickstart?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

`const navigate = useNavigate();`
```                                
navigate({
    to: '/register',
    replace: false,
});
```

gives the following typescript error: 
Argument type {replace: boolean, to: string} is not assignable to parameter type NavigateOptions<RegisteredRouter["routeTree"], string, string, string, ""> 
                                

### Expected behavior

No error should be given, only the later versions of Tanstack Router are giving this error for a fairly simple setup

### Platform

- OS: Windows
- Browser: Chrome
- Version: "@tanstack/react-router": "^1.23.1"

**Comment by schiller-manuel** [comment]
please provide a minimal complete example by forking and modifying one of the examples on stackblitz

**Comment by tushar-coin** [comment]
hi @schiller-manuel I dug little and found out some issues in the command stated above and had made some amends and that works well in stackblitz can u please assign me the issue

**Comment by SeanCassiere** [comment]
@tushar-coin, as requested I've assigned the issue to you.

Could you give us a bit of context about what you found out?

**Comment by tushar-coin** [comment]
hey @SeanCassiere on some digging i found out there were certain syntax changes in the useNavigate hook I am not 100% sure about the history of the syntax of this hook .
But i found that if we write the query differently using this syntax it does not give any error as mentioned by @roastdev 

`const navigate = useNavigate();
navigate('/register', {
  replace: false,
});`

**Comment by SeanCassiere** [comment]
> hey @SeanCassiere on some digging i found out there were certain syntax changes in the useNavigate hook I am not 100% sure about the history of the syntax of this hook . But i found that if we write the query differently using this syntax it does not give any error as mentioned by @roastdev
> 
> `const navigate = useNavigate(); navigate('/register', { replace: false });`
> 
> I verified the same on stackblitz

Are you sure you've got `@tanstack/react-router` on the latest version (not beta or something, right now latest is 1.26.1)?

Because looking at the [implementation](https://github.com/TanStack/router/blob/d2c12172e6b38e2ecdd234d734de66379991271f/packages/react-router/src/useNavigate.tsx#L29) of the result of the `useNavigate` function, it cannot accept a second input parameter at all.
