### ISSUE TITLE
SearchParams ending in "=" strips the equals sign

### ISSUE THREAD

**Issue by ViewableGravy** [TanStack/router#1404]
### Describe the bug

When using either validateSearch or useSearch() to access the search params, for search params that end in an equals sign, this is being stripped.

For example, below are some examples of what I get

URL: `http://localhost:3000?token=somerandomtoken=`
useSearch(): `{ token=somerandomtoken }`

URL: `http://localhost:3000?token=somerandomtoken=&test=somethingelse`
useSearch(): `{ token: "somerandomtoken", test: "somethingelse" }`

I've checked these same examples against URLSearchParams and this does include the equals sign.

My understanding is that the aim, at least for flat search params, is to behave identical to URLSearchParams to ensure that encoding works with other libraries, therefore this is likely a bug.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-s5pt7g?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the index route
2. Type in the following search param `?token=test=`
3. Check the console and note that the "=" is missing

### Expected behavior

I would expect the returned value in validateSearch and useSearch to be the following:
```ts
{
  token: "test="
}
```

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SeanCassiere** [comment]
For other maintainers, the search param values in the repro hasn't been correctly URI encoded. What we are seeing here is a case of a URL search param not being encoded correctly, and as such the parsing behaviour changes.

That being said, it's understandable why someone may find this to be a bug or even just troublesome, especially when the browser's URLSearchParam API handles this case.

<img width="421" alt="image" src="https://github.com/TanStack/router/assets/33615041/183be9fc-09c9-4bb7-8937-65192042943a">

However, if correctly encoded it does indeed function correctly and not strip out the last '=' character (you can test it out in this example Stackblitz set up [here](https://stackblitz.com/edit/tanstack-router-ebhbxc?file=src%2Froutes%2Findex.tsx)).

<img width="725" alt="image" src="https://github.com/TanStack/router/assets/33615041/d9f97e63-fa72-48c5-998d-461977959289">

And we do have a [section](https://tanstack.com/router/latest/docs/framework/react/guide/search-params#why-not-just-use-urlsearchparams) on why we don't use the built-in URLSearchParams API.

The question is, do we want to alter the default behaviour in this regards.

**Comment by SeanCassiere** [comment]
> The question is, do we want to alter the default behaviour in this regards.

Disregard this comment.

**Comment by ViewableGravy** [comment]
Thanks for looking into this. Yes, This is my fault for not encoding my token so I likely would've run into other problems (such as any `&` in my token had they existed) regardless, so fixing that will be my first point of action. 

From my perspective, I think, after any searchParams first `=`, the next delimiter should be an `&` and it should alternate this pattern until the end of the string. At least that is my intuition of how that would parse it, however, given the extended functionality of this library when it comes to search params, This may be too naive an approach.
