### ISSUE TITLE
Invalid loader type of `void` when loader function has `promise.then(data => data.x)`

### ISSUE THREAD

**Issue by toteto** [TanStack/router#1409]
### Describe the bug

When the loader method has promise chaining like `loader: async () => myDataLoader().then((d) => d.msg),`, the inferred type includes `void`, as in my simple example `string | void`.

When the loader has this restructured to first set the result into a field and then return the field, it is OK.

### Your Example Website or App

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQJQgV2wBoV0tcIIY9C04BfOAMyghDgCIABGDAOwDOvZAGsA9GWQwAtK1pQOAbgBQy5BEHxWVGtjgBeUpmx4dBbAAoE9AJQrlGAQE8+yZvlcxgGuCCcARLAwAGQgMABM0KAsbAC44AAVWEGABNAAeJBABAHN4oShgPhyGAD5EZTg4dBh8KD5E5NS0ADp0AQgAGwA3NCtfXPiOAAs0Ts6IDgY7ZXpVdU04Is6iiloDI3JdPoRKuBy0GASMdD5qczR4mINy7XPaIj2wLGGhsSZKDkeqiYio+McLjc1305T8gV4oT+0RsLRgoz4Fgs4RsNzg4Ra2RyNketnsCyEcAARlAMKJDtsNqhjGtLLsqgcjic0GdtldUaDqpR7sQni83kSTl89r9IlAAc5XHAQeV6VUUBpCeEghsMAB3DDAeDgoJQsUxOEIpEotEYrEzPZVGp1BrK3gqKr0XEWgnwAD6y1WEIwG09fFprXwaT1UW9MRUrrgbpJZJEh29Gxj5J5geDYTFYZmQA

### Steps to Reproduce the Bug or Issue

1. Create route
2. Add loader
3. Add loader method with `promise.then(....`

### Expected behavior

The type is inferred correctly

### Platform

`@tanstack/react-router: 1.26.3`

**Comment by TkDodo** [comment]
Not sure why but the issue goes away when removing async from this function (that doesn't have await in it anyway):
https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAbzgYygUwIYzQJQgV2wBoV0tcIIY9C04BfOAMyghDgCIABGDAOwDOvZAGsA9GWQwAtK1pQOAbgBQy5BEHxWVGtjgBeUpmx4dBbAAoE9AJQrlGAQE8+yZvlcxgGuCCcARLAwAGQgMABM0KAsbAC44AAVWEGABNAAeJBABAHN4oShgPhyGAD5EZTg4dBh8KD5E5NS0ADp0AQgAGwA3NCtfXPiOAAs0Ts6IDgY7ZXpVdU04Is6iiloDI3JdPoRKuBy0GASMdD5qczR4mINy7XPaIj2wLGGhsSZKDkeqiYioq5sN18ASCoT+0RsLRgoz4Fgs4UB+nK4Ra2RyNketnsCyEcAARlAMKJDtsNqhjGtLLsqgcjic0GdtgCgXdtt84M9oW88ScvntfpEoPFHC43NckRUqlUcfBwkENhgAO4YYDwPyBXhgwUxKEwuEIoEotEzPZVGp1Bpy3gqKr0TEmmVwAD6y1WGowG1dfEprXwaS1UXdMWUYjEUrgAD0APxqDS4p0EokiQ7ujaJ4n3bAtP1oANQIMzIA

I generally wouldn't mix async/await with promise chaining - choose one and stick with it :)

**Comment by toteto** [comment]
That solves it for now, but probably more devs will face this inconsistency. `await Promise.resolve('foo')` should be the same type as `await Promise.resolve().then(() => 'foo)`, both should be `Promise<string>`.

Additional hint, was using previously version `1.17.4` and this behaviour was OK. The regression was done between this and 1.26.3
