### ISSUE TITLE
useSearch returns old value temporarily if loader is defined

### ISSUE THREAD

**Issue by johnathanludwig** [TanStack/router#1411]
### Describe the bug

When a loader is defined, setting a search parameter will render with the new value, revert back to the old value, then render with the new value again. This occurs in specific situation where there is no `loaderDeps` set, or the `loaderDeps` does not include the changed search parameter (because the loader does not need it).

The issue only occurs once and then will behave as expected on subsequent search changes until the browser is refreshed again.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-kvlqe9?file=src/main.tsx,index.html

### Steps to Reproduce the Bug or Issue

1. Navigate to About
2. Open the devtools console
3. Refresh the page
4. click "set test" button
5. Observe logged search params. 

### Expected behavior

Only the new value should be logged, or at least it should only render the old value before a render with the new value has occurred.

### Screenshots or Videos

![CleanShot 2024-04-01 at 16 53 58](https://github.com/TanStack/router/assets/1262078/3660d610-9884-4c7c-9408-11300bf5e4c2)

### Platform

- OS: macOS
- Browser: Arc
- Version: confirmed on 1.0.7 and 1.26.3

### Additional context

In a situation where you have an effect that watches the changed search param unexpected behavior will occur due to the value reverting back after the initial change.

In our case our loaders currently just trigger prefetches for react-query, so a temporary workaround is setting `staleTime: Infinity` as we do not depend on the loader rerunning.

Another workaround is to define `loaderDeps` to include all search params, but this doesn't seem ideal for the correct caching behavior.

**Comment by SeanCassiere** [comment]
Retested with `1.28.9` and this looks to have been fixed.

Sandbox: https://stackblitz.com/edit/tanstack-router-rcnp7h?file=src%2Fmain.tsx
