### ISSUE TITLE
bug(router-vite-plugin): `experimental.enableCodeSplitting` nextCreate is not a function

### ISSUE THREAD

**Issue by SeanCassiere** [TanStack/router#1420]
### Describe the bug

Using the `experimental.enableCodeSplitting` flag, when you use a named inline function (instead of an arrow function), an error is thrown in both development and production.

This is the error that is thrown.

```
nextCreate is not a function
```

This error is not triggered when you use a traditional inline arrow function.

### Reproduction

https://stackblitz.com/edit/github-is6hai?file=src%2Froutes%2Fabout.tsx

### Reproduction steps

1. Go to the 'About' page.
2. See the error being printed to the console.

### Expected behavior

Not sure what should be the 'expected behaviour', but figured I should point this out before take the feature out of experimental status.

IMO: This is not urgent, with a simple enough workaround of converting the inline-named functions to inline-arrow functions.

### Platform

- OS: macOS
- Browser: Chrome/Arc
- TanStack React Router Version: 1.26.7
- TanStack Router Vite Plugin Version: 1.26.6

**Comment by schiller-manuel** [comment]
Currently 

this

```tsx
  const value = React.useMemo(function somethingHere() {
    return 'memoed-value';
  }, []);
```

compiles to
```tsx
const value = React.useMemo([]);
```

The issue lies in `eliminateUnreferencedIdentifiers`.
If this is commented out in `compilers.ts`,  the function is not removed and the error does not occur.

**Comment by tannerlinsley** [comment]
I released a new version, did that help at all? I was noticing an issue with array destructuring as well.

**Comment by schiller-manuel** [comment]
> I released a new version, did that help at all? I was noticing an issue with array destructuring as well.

no same problem exists in v1.26.8

https://stackblitz.com/edit/github-is6hai-wa51rg?file=package.json

**Comment by SeanCassiere** [comment]
Did a bit of debugging and figured it out.

If this [line](https://github.com/TanStack/router/blob/c25543fcf25dba23c497f2b62b66af48455541f7/packages/router-vite-plugin/src/eliminateUnreferencedIdentifiers.ts#L268) in the `getIdentifier` function is modified to include this, then this gets resolved.

```tsx
if (path.node.type === 'ArrowFunctionExpression' || path.node.type === 'FunctionExpression') {
    return null
  }
```

*Alternatively*, in the `isIdentifierReferenced` function, you could add a check before this [line](https://github.com/TanStack/router/blob/c25543fcf25dba23c497f2b62b66af48455541f7/packages/router-vite-plugin/src/eliminateUnreferencedIdentifiers.ts#L282) to check if a *FunctionExpression* is a child of a *CallExpression*.

```tsx
function isIdentifierReferenced(
  ident: NodePath<BabelTypes.Identifier>,
): boolean {
  const binding = ident.scope.getBinding(ident.node.name)

  if (
    binding?.path.node.type === 'FunctionExpression' &&
    binding.path.parentPath?.node.type === 'CallExpression'
  ) {
    return true
  }
 // ...
}
```

@tannerlinsley I'm hesitant to add a PR for this since testing pretty much breaks as some files rely on some absolute pathing for the tests to pass.

This was the test I used to validate that this worked.

```tsx
// tests/test-files/functionAsParameter.tsx
import * as React from 'react'

const value = React.useMemo(function performAction() {
  return 'true'
}, [])

console.log(value)

const value2 = React.useMemo(() => {
  return 'true'
}, [])

console.log(value2)
```
