### ISSUE TITLE
Uncaught TypeError: Cannot read properties of null (reading '__store')

### ISSUE THREAD

**Issue by tienhoangkhmt** [TanStack/router#1433]
### Describe the bug

import { Box, Button, Menu, MenuButton, MenuItem, MenuList } from '@chakra-ui/react'
import {
  NavGroup,
  NavItem,
  PersonaAvatar,
  Sidebar,
  SidebarSection,
} from '@saas-ui/react'
import { Link } from '@tanstack/react-router'

export const AppSidebar = () => {

  return (
    <Box>
        <Menu>
          <MenuButton
            as={Button}
            leftIcon={
              <PersonaAvatar name={"user?.name ?? user?.email"} size="xs" />
            }
          >
            {"user?.name ?? user?.email"}
          </MenuButton>
              
        </Menu>
        <Link name='"Sfs' to={"/logout"} />
        <NavGroup>
          <NavItem href="/">Home</NavItem>
        </NavGroup>
    </Box>
  )
}

### Your Example Website or App

a

### Steps to Reproduce the Bug or Issue

bug

### Expected behavior

s

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment]
please provide a minimal complete example e.g. by forking one of the existing examples (see for example https://tanstack.com/router/v1/docs/framework/react/examples/basic-file-based)

**Comment by tienhoangkhmt** [comment]
https://github.com/tienhoangkhmt/sass-demo
Please help me see the code on this repo

**Comment by schiller-manuel** [comment]
please strip it down to make it minimal.
also please provide instructions how to trigger the error.

**Comment by tienhoangkhmt** [comment]
When I call the Link component at the beginning, it gives me an error

**Comment by schiller-manuel** [comment]
I had a quick look, you seem to be using  `<Link>` outside of a `<RouterProvider>`. Please follow the documentation https://tanstack.com/router/latest/docs/framework/react/quick-start

**Comment by tienhoangkhmt** [comment]
thank you
