### ISSUE TITLE
notFound(), route loader, and initial application loading.

### ISSUE THREAD

**Issue by kisonay** [TanStack/router#1437]
### Describe the bug

Following the [documentation](https://tanstack.com/router/latest/docs/framework/react/guide/not-found-errors#configuring-a-routes-notfoundcomponent) I was able to setup a dynamic route, load some data, and if something doesn't exist, display not found.

This works as expected when navigating throughout the app (using the router). but once I refresh on a known-broken item, the default not found component does not render but the error component does.

### Your Example Website or App

https://stackblitz.com/edit/github-3cnvav?file=src%2Froutes%2F__root.tsx,src%2Froutes%2F%24type.%24id.tsx

### Steps to Reproduce the Bug or Issue

Navigate to each tab on render. you will see that unknown shows as not found.

now, in the address bar (above the render,) append `/unknown/id`the application will reload and show the error component.

### Expected behavior

I would expect not found to show once the application loads

### Platform

- latest macOS
- Brave/Chrome
- tanstack router v. 1.26.11

### Additional context

If an activity/id exists and a user bookmarks/saves the url, if they go back and it no longer exists, i would expect them to see the appropriate not found message, not an error.

**Comment by GuillaumeLaroucheUQAT** [comment]
I have the issue but only if I set the value 0 to `defaultPendingMs` when configuring the router instance.

**Comment by tannerlinsley** [comment]
Try again with the version I just released today?

**Comment by schiller-manuel** [comment]
please try again with https://github.com/TanStack/router/releases/tag/v1.28.2

this is the release Tanner referred to but was not released until now

**Comment by tannerlinsley** [comment]
Try 1.28.2

**Comment by SeanCassiere** [comment]
Re-tested with `1.28.7` and can confirm the original issue has been resolved.

Sandbox: https://stackblitz.com/edit/github-3cnvav-e5bwfj?file=src%2Froutes%2F%24type.%24id.tsx
