### ISSUE TITLE
"route.tsx" is not working as expected on the root route.

### ISSUE THREAD

**Issue by s97712** [TanStack/router#1450]
### Describe the bug

```
/
/route.tsx
/todo.tsx
/todo.add.tsx
```

According to the route tree above, the URL /todo/add should render as `<route><todo><add/></todo></route>`, but it actually render as `<todo><add/></todo>`.

### Your Example Website or App

https://stackblitz.com/edit/github-b9cgvh?file=src%2Froutes%2Ftodo.tsx

### Steps to Reproduce the Bug or Issue

 navigate to `/todo/add`

### Expected behavior

the URL /todo/add should render as `<route><todo><add/></todo></route>`

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SeanCassiere** [comment]
Configuration for the root route should be done in `__root.tsx` file as mentioned in the docs and the shown in the examples.

[https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing#file-naming-conventions](https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing#file-naming-conventions)

Also, as mentioned in the docs, the `route.tsx` filename is a token used by the router-plugin to have add shared configuration for a path.

If you need "route" to be part of the pathname in the URL bar then it should be placed in a folder.

```
src/routes
  index.tsx <= /
  route/
    index.tsx <= /route/
```

Example: https://stackblitz.com/edit/github-gmqaya?file=src%2Froutes%2Ftest%2Froute.tsx

And if you still need to have the configuration offered by a `route.tsx` file, but for the entire app, and you don't want it to be done in the `__root.tsx` file, then you'll need to use a shared [pathless/layout route](https://tanstack.com/router/latest/docs/framework/react/guide/routing-concepts#pathless--layout-routes) to do so.

**Comment by s97712** [comment]
Thank you for your patient response. Perhaps my needs are somewhat unique, and the methods you've provided aren't quite suitable for me.
