### ISSUE TITLE
Can't move to lazy parent route from ErrorComponent

### ISSUE THREAD

**Issue by Semigradsky** [TanStack/router#1455]
### Describe the bug

Can't move to lazy parent route from ErrorComponent. See steps to reproduce

### Your Example Website or App

https://stackblitz.com/edit/github-xwen9w-y2yx3p?file=src%2Froutes%2Ffoo%2Fbar.tsx,src%2Froutes%2Ffoo%2Findex.lazy.tsx

`/foo/index.lazy.tsx`
```tsx
export const Route = createLazyFileRoute('/foo/')({
  component: () => <div>Hello /_others/foo!</div>,
});
```

`foo/bar.tsx`
```tsx
export const Route = createFileRoute('/foo/bar')({
  beforeLoad: () => {
    throw new Error();
  },
  component: () => <div>Hello /_others/foo/bar!</div>,
});
```

### Steps to Reproduce the Bug or Issue

1. Click on `foobar`. The error thrown in `beforeLoad`. The `DefaultErrorRouteComponent` is showing
2. Click on `foo`. Nothing happend

### Expected behavior

Need to move to `foo` route

### Screenshots or Videos

![image](https://github.com/TanStack/router/assets/1198848/eb27baae-6995-4da3-97f8-534c0453dfcd)

### Platform

- OS: Windows
- Browser: Chrome
- Version: 123.0.6312.106

**Comment by Semigradsky** [comment]
Currently I see only one workaround - change `/foo` route to non-lazy. But it's not suitable for me.

**Comment by Semigradsky** [comment]
@tannerlinsley Hello! I have tried [1.28.5](https://www.npmjs.com/package/@tanstack/react-router/v/1.28.5) and in this version error route component doesn't showing when throw error in `beforeLoad`. I just see empty page. You can try with example on this ticket, just change the version.

Previous version (1.28.4) works the same as described in the ticket.

**Comment by SeanCassiere** [comment]
Closing because as mentioned, this has been fixed.
