### ISSUE TITLE
TypeError: _a.assets.filter is not a function (Tanstack Router with Vinxi) 

### ISSUE THREAD

**Issue by Kumneger0** [TanStack/router#1458]
### Describe the bug

I'm encountering a `TypeError: _a.assets.filter is not a function` error while trying to use Tanstack Router with Vinxi. I've followed the example provided here: https://github.com/TanStack/router/tree/main/examples/react/vinxi-basic-ssr-streaming

However, I'm still facing the issue even after running the example in Codespaces.

### Your Example Website or App

https://github.dev/TanStack/router

### Steps to Reproduce the Bug or Issue

1. Navigate to the `examples/react/vinxi-basic-ssr-streaming` directory.
2. Install dependencies 
3. Run the development server.
4. Open your browser at given url

### Expected behavior

When I run the development server, I expect the application to render the home page when I navigate to the given URL in my browser. However, the browser remains blank

### Screenshots or Videos

[Screencast from 04-11-2024 02:27:53 PM.webm](https://github.com/TanStack/router/assets/93655689/efa9bb94-9882-4036-8f73-640902effb1e)

### Platform

- OS:  Linux
- Browser: brave

### Additional context

@tanstack/react-router version: 1.26.19
vinxi  version: 0.1.2
Node.js version : 20.12.1

**Comment by SeanCassiere** [comment]
All the SSR Basic and SSR + Vinxi examples are completely outdated.

These examples need to be brought in line with the learnings and changes Tanner made with the TanStack.com migration to TSR.

**Comment by Kumneger0** [comment]
Thank you for pointing this out.

> @Kumneger0 For the time being, you can use the [_TanStack/tanstack.com_](https://github.com/TanStack/tanstack.com) repository as a good baseline for implementing SSR with TanStack Router.
