### ISSUE TITLE
I'm reaching out to report a performance issue.

### ISSUE THREAD

**Issue by AndrejNemec** [TanStack/router#1462]
I'm reaching out to report a performance issue.

The problem involves performance in two scenarios:

1. When updating the search parameters using `useNavigation`, the entire page, including all layout components and child components, is re-rendered.
2. When there is a layout component with multiple child pages, navigating between these child pages triggers a re-render of the entire page, including all layout components.

In the classic `react-router` package, this problem does not exist, there it works as expected, parts are rerendered as expected.

Example Link: https://stackblitz.com/edit/vitejs-vite-ifxs98

_Originally posted by @AndrejNemec in https://github.com/TanStack/router/discussions/1460_

**Comment by divmgl** [comment]
Do we have an update on this? Also having this issue.

**Comment by createdbymahmood** [comment]
Same issue here.

**Comment by createdbymahmood** [comment]
`React.memo` can fix this issue for now.

**Comment by AO19** [comment]
@tannerlinsley do you know how this issue could be fixed?

**Comment by tannerlinsley** [comment]
The latest version may have fixed it. We improved performance quite a bit with some more fine grained selectors

**Comment by decipher-cs** [comment]
> The latest version may have fixed it. We improved performance quite a bit with some more fine grained selectors

It didnt'.  I'm on `v1.45.6` and I'm running into the same problem.

Here's code on how to reproduce it. The `onChange` firest `updateQuery` which re-render the entire app.
 https://github.com/TanStack/router/discussions/1993#discussion-6952871

**Comment by gbbrambila** [comment]
Not sure if it's totally related, but I had some performance issues when dealing with URL hash updates when using the Default Browser History as mentioned here: https://github.com/TanStack/router/issues/1999

**Comment by last-Programmer** [comment]
We are also having this issue. we migrated to tanstack from react router and found this problem very annoying. this kind of issue is not happening with react routers. we are thinking of rolling back to react router because of this issue.

**Comment by tunganh-phamba** [comment]
> We are also having this issue. we migrated to tanstack from react router and found this problem very annoying. this kind of issue is not happening with react routers. we are thinking of rolling back to react router because of this issue.

@last-Programmer That's no way to communicate. Please show some respect for people who put time and effort into open source. There is already a workaround using React.memo, and you should use it until it's fixed, or go back to whatever you want to use.

**Comment by trompx** [comment]
Not sure this is exactly related but on the React Example: [Basic](https://tanstack.com/router/latest/docs/framework/react/examples/basic) & [Basic File Based](https://tanstack.com/router/latest/docs/framework/react/examples/basic-file-based) (haven't tested others), on every url change, the RootComponent re-render twice. Was struggling with this and after putting memo and useCallback everywhere without success, I'm glad to find out it could be the issue.
Versions tested: 1.45.7 & 1.45.11

**Comment by trompx** [comment]
I just upgraded to 1.45.14. While there was a double rerender in my root component when using `const router = useRouter()` there is now none at all, so it breaks my app.

Is it expected that we get no rerender at all now on new url navigation and should use another hook for a single rerender?

**Comment by schiller-manuel** [comment]
@trompx can you please share a complete minimal example?

**Comment by trompx** [comment]
@schiller-manuel
1. Go to https://tanstack.com/router/latest/docs/framework/react/examples/basic
2. Import useRouter and add the following at the beginning of the function RootComponent() {:
```js
  const router = useRouter();
  console.log("ROOT", router)
```
3. Check console: only renders "ROOT" on the first page

**Comment by schiller-manuel** [comment]
`useRouter` is not reactive, we need to document this better.
use `useRouterState` instead: https://stackblitz.com/edit/tanstack-router-m1avwu?file=src%2Fmain.tsx&preset=node

**Comment by TkDodo** [comment]
`useRouter` is like `useQueryClient`. Somehow, there most people understand that it's not reactive. Maybe it should be `useRouterInstance` or something?

**Comment by trompx** [comment]
I just upgraded tanstack router to version 1.58.9 from 1.45.14 and tried using `useRouterState` instead. Now at each page load, I get a bunch of rerenders, 8 with the `status: 'pending'` and 2 with `status: 'idle'`. It also rerenders when hovering links.

Is there a way to have a single rerender on route navigation?

Sometimes rerenders are not problematic but I'm trying to do some custom page navigation/animation stuff with framer AnimatePresence and it breaks it.

**Comment by schiller-manuel** [comment]
@trompx please create a new issue with a complete minimal example by forking one of the examples on stackblitz
