### ISSUE TITLE
throws error while navigating back using 

### ISSUE THREAD

**Issue by piyushlalwani45** [TanStack/router#1470]
### Describe the bug

-> Cannot read properties of undefined (reading 'length')
using useRouter().history.back()  to navigate back to previous router throws error while using hash routing
 

### Your Example Website or App

https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

![Screenshot from 2024-04-15 22-22-16](https://github.com/TanStack/router/assets/165755029/cea1b850-619a-4037-aba8-b0e6bc867c91)

Cannot read properties of undefined (reading 'length')

### Expected behavior

router should navigate back to previous route, instead it throws error

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SeanCassiere** [comment]
Can you please make sure you are using the latest version?

I've tested this scenario using hash routing and it looks to be working: https://stackblitz.com/edit/github-rk8n6u?file=src%2Fmain.tsx
See the *About* page.

Also, when providing a reproduction, please make sure you've forked the Stackblitz example into your own account so whatever changes you've made get save.
