### ISSUE TITLE
Breaking changes on before load in 1.28.2

### ISSUE THREAD

**Issue by noah-wardlow** [TanStack/router#1472]
### Describe the bug

I just updated and am getting the following errors (also a problem in the default stackblitz):

`@tanstack_react-router.js?v=4e41ed87:915 Error: A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.`

If I wrap the whole app in Suspense, that error goes away, but I get:
```
@tanstack_react-rout….js?v=4e41ed87:2720 Uncaught (in promise) 
{to: '/dashboard', isRedirect: true, statusCode: 301, headers: {…}, routerCode: 'BEFORE_LOAD', …}
headers
: 
{}
isRedirect
: 
true
routeId
: 
"/"
routerCode
: 
"BEFORE_LOAD"
statusCode
: 
301
to
: 
"/dashboard"
```

### Your Example Website or App

https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart-file-based?file=src%2FrouteTree.gen.ts

### Steps to Reproduce the Bug or Issue

Create a route with beforeLoad,
try to go to it

seems to be broken in the default router quickstart as well

### Expected behavior

The routes to load 

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

macOs
Chrome
1.28.2

**Comment by enheit** [comment]
I have the same issue

**Comment by bulicmatko** [comment]
Had the same issue. Wrapping the `<RouterProvider router={router} />` to `<Suspense>` fixed it for me.

```ts
createRoot(root).render(
  <StrictMode>
    <RouterProvider router={router} />
  </StrictMode>,
);
```

PS: Not sure this is the optimal way to fix it but without `<Suspense />` my app throws an error. If the author intended `<Suspense />` to be used, this is a breaking change.

PSS: Thanks to everyone who contributed to this project. Love your work!

**Comment by noah-wardlow** [comment]
> I have the same issue with a file-based router
> 
> P.S. I rolled back to `@tanstack/react-router@1.28.1` and it works okay!

Same, rollback fixed for me

**Comment by ExpDev07** [comment]
Experiencing the same issue here. I believe this is a bug as throwing redirect is the recommended way to redirect if for example authentication failed, as described in https://tanstack.com/router/v1/docs/framework/react/guide/authenticated-routes#the-routebeforeload-option

**Comment by tannerlinsley** [comment]
Fixed in the next release! Sorry!

**Comment by ortonomy** [comment]
https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart-file-based?embed=1&theme=dark&preset=node still has an error. Not sure if related to this error @tannerlinsley
