### ISSUE TITLE
Links with `from` not inheriting params

### ISSUE THREAD

**Issue by SeanCassiere** [TanStack/router#1474]
### Describe the bug

With the `from` property defined on a `<Link>` a user shouldn't have to pass in the param again, rather inherit what is already present.

Currently, without it being passed in, it is being set to undefined.

### Your Example Website or App

https://stackblitz.com/edit/github-8fa8cc

### Steps to Reproduce the Bug or Issue

Go to the posts page, and try the Links on that page.

### Expected behavior

As a user, when I am on the `/posts/$postId` route, I should be able to define `/posts/$postId` as my `from`, and `/posts/$postId/summary` as my `to` on a `<Link>` and have the params be inherited.

### Platform

- TSR Version: 1.28.4

**Comment by itsjoeoui** [comment]
+1 on this, still present in 1.28.5 as well

Video: https://discord.com/channels/719702312431386674/1007702008448426065/1229969892594155561

**Comment by itsjoeoui** [comment]
For anyone having the same problem, reverting back to `1.26.21` seems to be pretty stable

**Comment by divmgl** [comment]
Can we have an option to omit `from` completely please? @schiller-manuel @tannerlinsley links tend to be static in nature in that they're only ever used in a single place, so we know its context. The library also worked fine without the `from` prop in previous versions. This is very cumbersome and a point of contention on my team.

**Comment by schiller-manuel** [comment]
@divmgl which version did not require from?
also, how would you expect to get typesafety for the params if you do not specify from? partial params would not work then.
