### ISSUE TITLE
can't render elements when testing using memoryHistory

### ISSUE THREAD

**Issue by fernandortec** [TanStack/router#1475]
### Describe the bug

I'm trying to write unit tests for my app, using **bun:test, Tanstack Router, happydom, and Testing library**

When trying to test a Link, I need to add a Router provider, to wrap my component.
After some searching, I found this code to create an in-memory router.

```
function createTestRouter(component: () => JSX.Element) {
	const rootRoute = createRootRoute({
		component: () => <Outlet />,
	});

	const componentRoute = createRoute({
		getParentRoute: () => rootRoute,
		path: "/",
		component,
	});

	const router = createRouter({
		routeTree: rootRoute.addChildren([componentRoute]),
		history: createMemoryHistory({ initialEntries: ["/"] }),
	});

	return router;
}
```

When I try to render my component NavLink (which uses Link) it doesn't throw any errors but it renders only the body and a div inside it, For example:

```
  const router = createTestRouter(() => <NavLink to="/">about</NavLink>);
  const link = render(<NavLink to="/">about</NavLink>, {
	  wrapper: () => <RouterProvider router={router} />,
  });
  link.debug();
```

Output (on debug console.log):

![image](https://github.com/TanStack/router/assets/62437672/3801955d-c3fd-434a-9ffb-abd5b9029639).
------

Here's my full code:

```
import { NavLink } from "@/components/nav-link";
import {
	Outlet,
	RouterProvider,
	createMemoryHistory,
	createRootRoute,
	createRoute,
	createRouter,
} from "@tanstack/react-router";
import { render } from "@testing-library/react";
import { describe, it } from "bun:test";

describe("Nav Link", () => {
	it("should highlight when the nav link when is the current page link", async () => {
		function createTestRouter(component: () => JSX.Element) {
			const rootRoute = createRootRoute({
				component: () => <Outlet />,
			});

			const componentRoute = createRoute({
				getParentRoute: () => rootRoute,
				path: "/",
				component,
			});

			const router = createRouter({
				routeTree: rootRoute.addChildren([componentRoute]),
				history: createMemoryHistory({ initialEntries: ["/"] }),
			});

			return router;
		}

		const router = createTestRouter(() => <NavLink to="/">about</NavLink>);
		const link = render(<NavLink to="/">about</NavLink>, {
			wrapper: () => <RouterProvider router={router} />,
		});
		link.debug();

	});
});

```

### Your Example Website or App

https://github.com/fernandortec/pizza-shop-web

### Steps to Reproduce the Bug or Issue

You can check my repo to reproduce the bug:

https://github.com/fernandortec/pizza-shop-web

Run `bun install`, then `bun test`

### Expected behavior

Should render the expected component, not a random div inside the body

### Platform

- OS: macos
- Browser: happydom
- Version: 1.26.20

**Comment by fernandortec** [comment]
Update:

I tried to add a Wrap to the router provider, but it still didn't work, at least now the errors is different, not sure which path to go from here.

```
const router = createTestRouter(() => <NavLink to="/">about</NavLink>);
const link = render(<NavLink to="/">about</NavLink>, {
  wrapper: ({ children }) => (
    <RouterProvider
	router={router}
	InnerWrap={({ children: routeChild }) => (
		<div>
			{children}
			{routeChild}
		</div>
	)}
    />
),
});
link.debug();
```

![error](https://github.com/TanStack/router/assets/62437672/a8e6130d-8356-46c1-a9db-3e630de86c2d)

**Comment by tannerlinsley** [comment]
We use an in-memory router in the test for the library. Have you looked at our implementation and compared yet?

**Comment by SeanCassiere** [comment]
Specifically, try this: https://github.com/TanStack/router/blob/eb8aee2f8d07f11e1d970bdb8f1f0cc779bded31/packages/react-router/tests/index.test.tsx#L573C1-L591C24

Then maybe trying passing in the Router instance into the renderer.

**Comment by fernandortec** [comment]
> Specifically, try this: https://github.com/TanStack/router/blob/eb8aee2f8d07f11e1d970bdb8f1f0cc779bded31/packages/react-router/tests/index.test.tsx#L573C1-L591C24
> 
> Then maybe trying passing in the Router instance into the renderer.

I just tried changing my test to match the example you gave me, but the output its still the same, it is not rendering the component. Here's my full test code

```
	it("should highlight when the nav link when is the current page link", async () => {
		const rootRoute = createRootRoute();

		const indexRoute = createRoute({
			path: "/",
			getParentRoute: () => rootRoute,
			beforeLoad: () => {
				throw redirect({
					to: "/about",
				});
			},
		});

		const aboutRoute = createRoute({
			path: "/about",
			getParentRoute: () => rootRoute,
			component: () => {
				return "About";
			},
		});

		const router = createRouter({
			history: createMemoryHistory({
				initialEntries: ["/"],
			}),
			routeTree: rootRoute.addChildren([indexRoute, aboutRoute]),
		});

		// Mock server mode
		router.isServer = true;

		await router.load();

		const link = render(<NavLink to="/about">about</NavLink>, {
			wrapper: () => <RouterProvider router={router} />,
		});
		
		link.debug();
	});
```

And here's the debug output

![image](https://github.com/TanStack/router/assets/62437672/7025a046-cb41-44ad-b977-51c0225c948a)

**Comment by SeanCassiere** [comment]
There shouldn't be a wrapper since the `<RouterProvider>` is the only entry and as such you'd only be rendering it.

So, your `<NavLink>` would probably have to be rendered inside the `indexRoute` or the `aboutRoute`. Also, try adding a sleep for 10ms after the render and let us know what happens.

**Comment by SeanCassiere** [comment]
I've added a PR to your original repo with the test runner working correctly, with the *debug* output looking like this.
<img width="1074" alt="image" src="https://github.com/TanStack/router/assets/33615041/6161b90f-4273-473c-a2fe-0e1a82d015dd">

See, the PR here: https://github.com/fernandortec/pizza-shop-web/pull/1

This setup more closely resembles what you were doing, except with the rendering done correctly. You can ofcourse, abstract away this setup process into its own function.

@tannerlinsley one thing to note is that, although the Router's internal state is matched correctly when a redirect is thrown from the `beforeLoad` callback in the index route, it doesn't actually reflect that for the components that are being rendered within the test environment.

Can't tell if this is due to the memory router, a test env issue, or an actual issue within the router itself.

And honestly, this kind of testing of the redirect behaviour, belongs in the Router codebase and not the user's. So, its something we can look at fixing if it starts impacting our test workflows.

**Comment by tannerlinsley** [comment]
Redirects behave differently in server vs client, try setting router.isServer = false

**Comment by SeanCassiere** [comment]
> Redirects behave differently in server vs client, try setting router.isServer = false

That doesn't work, it doesn't back to rendering an empty div.

<img width="778" alt="image" src="https://github.com/TanStack/router/assets/33615041/9580506d-ee6c-4f4a-a2fc-93b5734ba62c">

<img width="365" alt="image" src="https://github.com/TanStack/router/assets/33615041/1ec9ac16-44b3-4da4-93ea-30f1550363f3">

**Comment by tannerlinsley** [comment]
I’ll investigate

**Comment by fernandortec** [comment]
Thank you very much @tannerlinsley  and @SeanCassiere , I was having really a tough time trying to run those tests.
Have a great day!
