### ISSUE TITLE
Redirect from beforeLoad: uncaught error

### ISSUE THREAD

**Issue by bazo** [TanStack/router#1480]
### Describe the bug

when checking if user is authenticated and throwing a redirect from before load an unhandled error is thrown instead of redirect happenning

### Your Example Website or App

https://stackblitz.com/edit/github-qtxl7r?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

run the app
open console
try to go to /posts

this error is thrown
router.ts:1607 
 Uncaught (in promise) 
{to: '/login', search: {…}, isRedirect: true, statusCode: 301, headers: {…}, …}

### Expected behavior

i am redirected to login page

### Platform

- OS: mac
- Browser: edge
- Version: 122.0.2365.80 (Official build) (arm64)

**Comment by tannerlinsley** [comment]
Should be fixed in latest!

**Comment by gregflynn** [comment]
Still seeing this in `1.28.7`

**Comment by gregflynn** [comment]
as seen in other issues, downgrading to `1.28.1` is a solid workaround

**Comment by AndrejNemec** [comment]
+1

Another scenario involves manually entering a URL that belongs to an authenticated layout directly into the address bar. If I navigate to that page manually, not using a Link or navigate function, the same error occurs.

**Comment by bazo** [comment]
yeah still happens, even on 1.28.9

**Comment by 6jonathanaloi6** [comment]
Still happens in 1.28.9

**Comment by nick-cheatwood7** [comment]
> as seen in other issues, downgrading to `1.28.1` is a solid workaround

Can confirm, downgrading from `1.28.7` to `1.28.1` fixes the issue temporarily.

**Comment by planktonrobo** [comment]
Seeing this is broken in latest as well

**Comment by sher** [comment]
Can confirm this is a degradation from `1.28.2` and still exists in `1.29.2`.

Working: https://stackblitz.com/edit/vitejs-vite-qsrurg?file=src%2Frouter.tsx
Failing https://stackblitz.com/edit/vitejs-vite-m1s4ek?file=src%2Frouter.tsx

**Comment by junglast** [comment]
As mentioned above, this occurs when I initially hard-load the route that includes `redirect` in the browser address bar. It works well it navigates to that page on client side.

**Comment by artsiomshaitar** [comment]
Still happens in `1.29.2`

**Comment by angelsantosa** [comment]
Also happens using loader in route.

**Comment by andelkocvjetkovic** [comment]
Experiencing the same issue.

**Comment by felix-bohlin** [comment]
Same here, but it only happens in my prod build.
```json
"@tanstack/react-router": "^1.29.2",
"@tanstack/router-vite-plugin": "^1.30.0",
"vite": "^5.2.10",
```

**Comment by hugocostadev** [comment]
Still happening with the latest version.

Error: 
![image](https://github.com/TanStack/router/assets/20212776/e823d14e-4123-46af-af57-b3233a873a0a)


Code: 

```json
"@tanstack/react-router": "^1.30.1",
"@tanstack/router-devtools": "^1.30.1",
"@tanstack/router-vite-plugin": "^1.30.0",
```
```tsx
import { createFileRoute, redirect } from "@tanstack/react-router";

export const Route = createFileRoute("/")({
  beforeLoad: () => {
    throw redirect({ to: "/home" });
  },
});

```

**Comment by angelsantosa** [comment]
Hey, I just tested the new change, and while redirect does work, now it does not show Outlet content.
You can see the behavior here: https://stackblitz.com/edit/vitejs-vite-pcqzrt?file=src%2Fmain.tsx

**Comment by vafanassieff** [comment]
There is no more error in the console, but the redirect does not load the current page and leave me with an empty screen.

**Comment by hugocostadev** [comment]
> There is no more error in the console, but the redirect does not load the current page and leave me with an empty screen.

Same here

**Comment by miroslavmih** [comment]
Tested in 

`@tanstack/react-router": "^1.31.3`

and it seems that redirect doesn't work, i.e. 

`throw redirect({ to: '/' });`

will redirect to current page and not to: '/'

**Comment by mykhailoalekseiev** [comment]
Wrapping the  `<RouterProvider router={router} />` in Suspense component helped me to resolve this issue.

**Comment by dedene** [comment]
> Wrapping the `<RouterProvider router={router} />` in Suspense component helped me to resolve this issue.

This does not seem to help for our case. `throw redirect({ to: '/login', search: { redirect: location.href }});` is changing the url, but showing a blank screen, suggesting indeed the Outlet is not rendering?

**Comment by dedene** [comment]
Ah, version 1.31.20 seems to have a fix! 🙌 Probably https://github.com/TanStack/router/commit/51eb39b85ec437bb46c831ef388a9dc7ecb23c35 fixed it, it is working after updating. Thanks!!
