### ISSUE TITLE
React 19 canary causes hydration mismatch (vinxi-ssr-streaming)

### ISSUE THREAD

**Issue by lithdew** [TanStack/router#1483]
### Describe the bug

Installing React 19 canary causes a hydration mismatch. The client JS bundle on the latest React canary branch gets injected earlier in the SSR streamed chunks to the browser compared to React 18.2.0.

Reverting the following commit fixes the bug. It appears that having a <Suspense/> over the entire document causes this issue: https://github.com/TanStack/router/commit/713f92de7ff9eb21182cb510692a621e5df8b3c0

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-6fqjgm?file=package.json

### Steps to Reproduce the Bug or Issue

1. `npm install react@canary react-dom@canary --legacy-peer-deps` on the vinxi-ssr-streaming example.
2. Check logs.

```console
Uncaught Error: Hydration failed because the server rendered HTML didn't match the client. As a result this tree will be regenerated on the client. This can happen if a SSR-ed Client Component used:

- A server/client branch `if (typeof window !== 'undefined')`.
- Variable input such as `Date.now()` or `Math.random()` which changes each time it's called.
- Date formatting in a user's locale which doesn't match the server.
- External changing data without sending a snapshot of it along with the HTML.
- Invalid HTML tag nesting.

It can also happen if the client has a browser extension installed which messes with the HTML before React loaded.

https://react.dev/link/hydration-mismatch

  <StartClient router={{...}}>
    <RouterProvider router={{...}}>
+     <Suspense fallback={null}>
-     <html lang="en">

    at throwOnHydrationMismatch (react-dom_client.js?v=d2078787:10397:24)
    at tryToClaimNextHydratableSuspenseInstance (react-dom_client.js?v=d2078787:10460:13)
    at updateSuspenseComponent (react-dom_client.js?v=d2078787:16004:15)
    at beginWork (react-dom_client.js?v=d2078787:16810:22)
    at performUnitOfWork (react-dom_client.js?v=d2078787:22436:20)
    at workLoopSync (react-dom_client.js?v=d2078787:22262:13)
    at renderRootSync (react-dom_client.js?v=d2078787:22236:17)
    at performConcurrentWorkOnRoot (react-dom_client.js?v=d2078787:21718:83)
    at workLoop (react-dom_client.js?v=d2078787:188:42)
    at flushWork (react-dom_client.js?v=d2078787:167:22)
```

### Expected behavior

No hydration mismatch.

### Platform

- OS: [e.g. macOS, Windows, Linux] macOS
- Browser: [e.g. Chrome, Safari, Firefox] Chrome
- Version: [e.g. 91.1] 123.0.6312.106

**Comment by SeanCassiere** [comment]
This will have to be a bridge we cross when React 19 becomes stable (or at least is in the a more final version of 'release candidate').

Either way, it doesn't make sense for us to make changes based on these pre-release versions for now.
