### ISSUE TITLE
`beforeLoad` only being triggered on root route during first render

### ISSUE THREAD

**Issue by rmusaev99** [TanStack/router#1487]
### Describe the bug

I use vite ^4.5.3, @tanstack/router-vite-plugin ^1.28.2 and tanstack router ^1.28.6 with file routes. 
I put console logs into `beforeLoad` on root route and some sub routes. 
`beforeLoad` called properly when navigating from another route to my target sub route, but on initial page render, only root `beforeLoad` being called and my sub route `beforeLoad` is ignored

### Your Example Website or App

https://github.com/rmusaev99/tanstack-router-issue

### Steps to Reproduce the Bug or Issue

1. Pull repo and install deps
2. npm run dev
3. go to root http://localhost:5173/
4. You will see console log "beforeLoad from root"
5. Navigate to about page from top menu, you will see another "beforeLoad from root"
6. Navigate back to "Home" using top menu 
7. You will see two logs - "beforeLoad from root" and "beforeLoad from index"

"beforeLoad from index" expected to be at step "3."

### Expected behavior

Probably beforeLoad should be called on every load

### Platform

- OS: Linux
- Browser: Chrome
- Version: ^1.28.6

**Comment by SeanCassiere** [comment]
I re-tested this and there were some errors in the types of functions being used in the index route.

Sandbox: https://stackblitz.com/edit/github-xtyisc?file=src%2Froutes%2Findex.tsx

So, these are the order of events that should happen (and do):

1. Initial load, runs `beforeLoad` in root, and the `beforeLoad in "index".
2. Navigate to "about", `beforeLoad` in root runs.
3. Navigate back to "index", `beforeLoad` in root and in "index" runs.

This behaviour I've documented above is expected.

<img width="751" alt="image" src="https://github.com/TanStack/router/assets/33615041/61694c86-da90-49bd-8c47-6269b2db0387">
