### ISSUE TITLE
tanstack.com/router is failing to render

### ISSUE THREAD

**Issue by apiel51** [TanStack/router#1504]
### Describe the bug

Here's what I'm seeing in the console:
![image](https://github.com/TanStack/router/assets/17676991/e9e78962-e6d8-46cd-861e-013094c0f99f)

### Your Example Website or App

https://tanstack.com/router/latest

### Steps to Reproduce the Bug or Issue

1. Load https://tanstack.com/router/latest

### Expected behavior

As a user, I expected this site to load but it did not.

### Platform

- OS: macOS
- Browser: Chrome

**Comment by apiel51** [comment]
This appears to be fixed — maybe a blip?

**Comment by tannerlinsley** [comment]
Probably a browser extension modifying the dom before hydration

**Comment by yadielar** [comment]
Still experiencing this today. It doesn't seem related to an extension since it happens in Incognito mode in Chrome, and when opening the website in other browsers.

**Comment by mmorton** [comment]
The Dark Reader extension was the thing causing it to fail for me.
