### ISSUE TITLE
Can't override defaultViewTransition

### ISSUE THREAD

**Issue by ceski23** [TanStack/router#1526]
### Describe the bug

After configuring router with `defaultViewTransition: true`, using `navigate` or `Link` with `viewTransition: false` doesn't disable transition

### Your Example Website or App

https://stackblitz.com/edit/github-g4ctdl?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Click About link, route change is transitioned correctly
2. Click Home link, route change is transitioned but shouldn't

### Expected behavior

Using `Link` or `navigate` with `viewTransition: false` should override `defaultViewTransition` and disable transition when changing route

### Platform

- OS: Windows 11 (WSL)
- Browser: Microsoft Edge
- Version: 123

**Comment by SeanCassiere** [comment]
This has been fixed and published in the [1.31.6](https://github.com/TanStack/router/releases/tag/v1.31.6) release.
