### ISSUE TITLE
the `context` in the `onEnter` is callback on the Route definition returns `undefined` on first-load during runtime

### ISSUE THREAD

**Issue by Zebeqo** [TanStack/router#1529]
### Describe the bug

When first loading, `onEnter` runs before `loader` and `context` in `onEnter` is always undefined.

### Your Example Website or App

https://stackblitz.com/edit/github-h2bsvy

### Steps to Reproduce the Bug or Issue

1. The application loaded and the console output `context from onEnter undefined` and  `context from loader {test: 'abc'}`
2. Go to the `/about` page and back to `/`, the console output `context from loader {test: 'abc'}` and  `context from onEnter {test: 'abc'}`

### Expected behavior

The application loaded and the console output `context from loader {test: 'abc'}` and  `context from onEnter {test: 'abc'}`

### Platform

- OS: macOS
- Browser: Chrome
- Version: 124.0

**Comment by SeanCassiere** [comment]
Retested on `1.56.5` and can confirm that this has been fixed.
