### ISSUE TITLE
Cannot open router website in "https://tanstack.com/router/latest"

### ISSUE THREAD

**Issue by Dev7Eng4** [TanStack/router#1532]
### Describe the bug

I go in your website (https://tanstack.com/router/latest) and got a white page with some errors in console tab
<img width="953" alt="11111" src="https://github.com/TanStack/router/assets/87588010/f14c0872-1cd9-4534-8895-9595b1e100ba">

### Your Example Website or App

https://tanstack.com/router/latest

### Steps to Reproduce the Bug or Issue

1. Typing tanstack router in google
2. Click the link to go in website
3. Got a white page

### Expected behavior

Can open your website

### Platform

- OS: window
- Browser: Chrome
- Version: latest

**Comment by tannerlinsley** [comment]
To help us make the site more resilient to hydration errors, can you let us know what extensions you have enabled?

**Comment by Dev7Eng4** [comment]
I found out the site is broken because this extension: Chrome Remote Desktop(https://remotedesktop.google.com/access/)

**Comment by Dev7Eng4** [comment]
I tried disabling each extension and it seems like this error is caused by the eJOY AI dictionary extension
<img width="308" alt="image" src="https://github.com/TanStack/router/assets/87588010/a0ee4e99-620a-4615-b4a0-46b703874537">

**Comment by SeanCassiere** [comment]
@Dev7Eng4 could you try testing this again?

**Comment by andrewbellucci** [comment]
I get a flash of the website and then similar errors as the above. I don't have any extensions installed.

<img width="1444" alt="Screenshot 2024-05-01 at 11 50 03 PM" src="https://github.com/TanStack/router/assets/62807636/55bbbd3b-1e4f-4b91-be7c-d4460e5f1e33">

I did notice however that if I navigate to a route deeper into the tree, I'm able to navigate back to the home page and it shows just fine. IE:
https://tanstack.com/router/latest/docs/framework/react/guide/path-params

**Comment by Dev7Eng4** [comment]
Currently, it only happens when I click the link from google search like image 
![image](https://github.com/TanStack/router/assets/87588010/27f7c848-d967-41af-9cdc-fdf21076a1df)

**Comment by maksymskuibida** [comment]
I am facing the same with form. I beleive it is the same. I added screenshot of my plugins. I have it always when I reload the page page on https://tanstack.com/form/latest. Now for me it only happens on https://tanstack.com/form/latest. Other is ok, I have an issue only with form
<img width="1512" alt="image" src="https://github.com/TanStack/router/assets/57814533/287aa11c-d2ae-4368-b1ce-8be04054caa7">

**Comment by heberuriegas** [comment]
To me the fix was add to the whitelist in the dark reader extension

**Comment by maksymskuibida** [comment]
I made screen with all my extensions. None of my extensions should block something. Earlier this issue was with all websites, now only with forms. Before for all and now only for forms, If I navigating there from the main (https://tanstack.com/) website everything works and if I reload the page I see this error

**Comment by SeanCassiere** [comment]
Could y'all try again.

Tanner's switched to new hydration strategy.

**Comment by Dev7Eng4** [comment]
With me, it's ok now

**Comment by andrewbellucci** [comment]
It's loading fine for me now, thank you @tannerlinsley and @SeanCassiere

**Comment by maksymskuibida** [comment]
for me too, thanks you @tannerlinsley and @SeanCassiere
