### ISSUE TITLE
Redirect not work with direct url

### ISSUE THREAD

**Issue by tkimvu** [TanStack/router#1537]
### Describe the bug

In latest authenticated-routes example. When click to dashboard link from index, that work. But if write direct url like http://localhost:3001/dashboard => url redirect to http://localhost:3001/login?redirect=%2Fdashboard BUT auth layout loaded with isAuthenticated: false

### Your Example Website or App

https://github.com/tanstack/router/tree/main/examples/react/authenticated-routes

### Steps to Reproduce the Bug or Issue

Clone and open

### Expected behavior

I want throw redirect to login

### Screenshots or Videos

![Screenshot from 2024-04-30 18-19-44](https://github.com/TanStack/router/assets/138427238/96a16007-3914-4860-ac68-b1dc721b13f1)

### Platform

- OS: [Linux]
- Browser: [Chrome, Firefox]

**Comment by SeanCassiere** [comment]
For better context;

The `redirect` thrown in the `beforeLoad` callback in the [_auth.tsx](https://github.com/TanStack/router/blob/75074432059d8a85629a11d0732c7f7b7c4fef1e/examples/react/authenticated-routes/src/routes/_auth.tsx#L15) layout route, isn't correctly being resolving the redirect when you directly visit the URL (for example to `/dashboard`).

**Comment by SeanCassiere** [comment]
Tanner has fixed this and it's available in [1.31.5](https://github.com/TanStack/router/releases/tag/v1.31.5) release.
