### ISSUE TITLE
`parentMatchPromise` is `undefined` in the loader of a child route

### ISSUE THREAD

**Issue by visualjerk** [TanStack/router#1540]
### Describe the bug

Inside the loader of a child route `parentMatchPromise` is always `undefined`.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-rekhkq?file=src%2Froutes%2Fparent.child.tsx

### Steps to Reproduce the Bug or Issue

1. Click on "Child"
2. Error `expect parentMatchPromise to be defined` is thrown

### Expected behavior

As a developer, I expect `parentMatchPromise` to be defined in the loader of a child route, so I can await the loader of the parent route and act based on its result.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 1.29.2

### Additional context

This feature is not documented yet and I found it in [this discussion](https://github.com/TanStack/router/discussions/653).

**Comment by SeanCassiere** [comment]
Your example app is not loadable in Stackblitz.

It'd be best if you either update what you think is the appropriate reproducible Stackblitz link from the list of examples in the discussion thread you found or create an actual minimal reproducible example showcasing the issue. Add the link to the  new/updated Stackblitz reproducer to this thread.

You can create a minimal example using the [Router file-based stackblitz starter](https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart-file-based).

Here are some guidelines you can follow when creating a minimal reproducible example: https://stackoverflow.com/help/mcve
