### ISSUE TITLE
Vite Plugin not re-generating routes with a non-standard Vite root configured

### ISSUE THREAD

**Issue by a-maas** [TanStack/router#1550]
### Describe the bug

I've provided minimal example project that demonstrates a potential bug with the TanStack Router Vite Plugin not detecting and generating when using a non-standard vite `root` configuration. In this example, the vite `root` config is set to `app` in the `vite.config.ts` file. With this configuration, TanStack Router does not detect `tsr.config.json` in the project root, but will detect it if the file is moved to the `app` directory. Once moved to the `app` directory, the TanStack Router Vite plugin will successfully generate the routes on `vite dev` boot, but will not detect and re-generate based on adding and removing files in the `app/routes` directory.

### Your Example Website or App

https://github.com/a-maas/ts-router-ex

### Steps to Reproduce the Bug or Issue

1. Clone [this repository](https://github.com/a-maas/ts-router-ex)
2. Run `npm install`
3. Run `npm run dev`
4. Observe that the routes are generated on boot.
5. Add a `test.tsx` file to the `app/routes` directory.
6. Observe that the routes are not re-generated.

### Expected behavior

As a user, I expect the TanStack Router Vite plugin to re-generate routes when I add and remove files from the configured routes directory, even when Vite is configured with a non-standard `root`.

### Platform

- OS: macOS 14.4
- Browser: N/A
- Editor: VSCode

**Comment by schiller-manuel** [comment]
this PR seems to be related: https://github.com/TanStack/router/pull/1259

do you want to provide a PR to fix this issue?

**Comment by a-maas** [comment]
Thanks for the link, I didn't find that when searching for this issue before submitting. Yes, that PR and [related issue](https://github.com/TanStack/router/issues/1240) look like a very similar issue to what I described above, though, the issue still persists. 

I will take some time and try to work out a fix PR. Any guidance would be appreciated since I'm still pretty new to Vite and TSR.

**Comment by a-maas** [comment]
@schiller-manuel it seems like there are two options to fix this. The problem stems [from initially setting](https://github.com/TanStack/router/blob/f5767cb974dccfa3dcf314f1bf31c80cdba9aadd/packages/router-vite-plugin/src/index.ts#L47) `ROOT` to `process.cwd()`, but[ later redefining](https://github.com/TanStack/router/blob/f5767cb974dccfa3dcf314f1bf31c80cdba9aadd/packages/router-vite-plugin/src/index.ts#L91) `ROOT` as vite's configured root. This leads to a mismatch if you have vite's root set to anything other than the `process.cwd()`. 

Option 1: To be consistent, use `process.cwd()` everywhere, which would mean only changing [this line](https://github.com/TanStack/router/blob/f5767cb974dccfa3dcf314f1bf31c80cdba9aadd/packages/router-vite-plugin/src/index.ts#L91) to `process.cwd()` instead of `config.root`. I'm not sure if this would cause confusion or future issues for people using `vite.root`.

Option 2: Use `vite.root`, if set, everywhere, with a `process.cwd()` fallback. This would have a few consequences:
  - `tsr.config.json` would need to be placed at `vite.root`, not project root, if they were different. In my case, it would need to be placed in `./app` instead of project root.
  - File paths defined in `tsr.config.json`, like `routesDirectory` would need to be based on the `vite.root`, instead of project root, if they are different.

**Comment by a-maas** [comment]
Seems like in the [prior PR](https://github.com/TanStack/router/pull/1259), you were weighing both of these options, and ended up going with Option 1, but Option 2 may be more desirable.

**Comment by schiller-manuel** [comment]
would option 2 be a breaking change?
