### ISSUE TITLE
`navigate` functions without `to` but with `search` causes a route error inside a layout route.

### ISSUE THREAD

**Issue by ruiaraujo012** [TanStack/router#1560]
### Describe the bug

After version `1.31.7` the error started occurring. Related to #1548. @SeanCassiere

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-1udi7f?file=src%2Froutes%2F_test%2Ftabs-example.%24someId.tsx

### Steps to Reproduce the Bug or Issue

Go to "Tabs example" route, change the tab and the error is caused. If you put the URL manually, let's say `...?tab=tab2` it renders well, but as soon as you change the tab the app crash

### Expected behavior

Both tabs work well without crashing the app.

### Platform

- OS: [macOS]
- Browser: [Arc]
- Version: [1.31.7]

**Comment by SeanCassiere** [comment]
It has to do with this [line](https://github.com/TanStack/router/blob/fae0fe55f5d30391f414f0c9cfdd388f40adaaa0/packages/react-router/src/router.ts#L942).

For the `fromPath` it currently resolves to using the `routeId` of of the current route, which contains the *layout identifier* as a part of it.

It'll be matter of either sanitizing whats returned by the `routeId` or seeing if there's another property on the match that can be used here.

**Comment by SeanCassiere** [comment]
This has been fixed and released in [1.31.19](https://github.com/TanStack/router/releases/tag/v1.31.19).

**Comment by ruiaraujo012** [comment]
Thanks, I appreciated it.

**Comment by tatwater** [comment]
I'm on 1.31.28 and I'm still experiencing this same bug!

**Comment by SeanCassiere** [comment]
> I'm on 1.31.28 and I'm still experiencing this same bug! Routes that have an `id` instead of a `path` are getting their id inserted into the URL when navigating with search params, which errors.

This has been fixed as of the [1.31.29](https://github.com/TanStack/router/releases/tag/v1.31.29) release.
