### ISSUE TITLE
Router.status is always "pending" when you wrap the `RouterProvider` in `StrictMode`.

### ISSUE THREAD

**Issue by ThijsTyZ** [TanStack/router#1566]
### Describe the bug

If the `RouterProvider` is wrapped in `<React.StrictMode>`, the status of the Router is alway "pending".

Due to this issue, you can never get the correct resolvedLocation, because this will always return the first location you visited.

### Your Example Website or App

https://github.com/TanStack/router/blob/main/examples/react/basic-file-based/

### Steps to Reproduce the Bug or Issue

Change line 23 of `examples/react/basic-file-based/src/main.tsx` to:

```
root.render(<React.StrictMode><RouterProvider router={router} /></React.StrictMode>)
```

And run the app normally. Noticed in the TanStackRouterDevtools that the status of the Router is always "pending" and the resolvedLocation is never changed when navigating in the app.

### Expected behavior

As a user I would expect that the status if the router is "idle" after navigation and resolvedLocation returns the current location

### Platform

- OS: macOS
- Browser:Chrome
- Version: 124.0.6367.119

**Comment by SeanCassiere** [comment]
This has been completed as of the [1.31.26](https://github.com/TanStack/router/releases/tag/v1.31.26) release.

**Comment by tl-frameplay** [comment]
This bug re-occurred for me for version 1.36.2 onwards. My workaround was to remove strictmode.

Possibly re-introduced by https://github.com/TanStack/router/pull/1734

**Comment by SeanCassiere** [comment]
> This bug re-occurred for me for version 1.36.2 onwards. My workaround was to remove strictmode.
> 
> Possibly re-introduced by #1734

Moved this to #1912
