### ISSUE TITLE
Error when startin. (I have seen it's also on the docs examples)

### ISSUE THREAD

**Issue by OliverMengich** [TanStack/router#1567]
### Describe the bug

A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.

### Your Example Website or App

https://tanstack.com/router/v1/docs/framework/react/examples/basic-react-query-file-based

### Steps to Reproduce the Bug or Issue

1. Go to the docs examples and the select the file-based with react query example

### Expected behavior

The app isn't running. I have attached screenshot

### Screenshots or Videos

![tanstackrouter_bug](https://github.com/TanStack/router/assets/55626791/a872b776-c2da-481e-9c1d-d9ceb52b67a3)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by tonywei92** [comment]
#1554

**Comment by OliverMengich** [comment]
I have downgraded to v1.31.10 but now the Spinner doesn't work.

**Comment by OliverMengich** [comment]
> it's same issue with #1554

I have downgraded to v1.31.10 but now the Spinner doesn't work.

**Comment by OliverMengich** [comment]
> > > it's same issue with #1554
> > 
> > 
> > I have downgraded to v1.31.10 but now the Spinner doesn't work.
> 
> Have you tried 1.31.8?
![tanstackrouter_bug_spinner](https://github.com/TanStack/router/assets/55626791/d305ddbf-8123-467c-ac99-5bf6fbb3d6fa)


Yes, I am still getting the error, find my attached code screenshot

**Comment by tonywei92** [comment]
> > > > it's same issue with #1554
> > > 
> > > 
> > > I have downgraded to v1.31.10 but now the Spinner doesn't work.
> > 
> > 
> > Have you tried 1.31.8?
> > ![tanstackrouter_bug_spinner](https://private-user-images.githubusercontent.com/55626791/328813056-d305ddbf-8123-467c-ac99-5bf6fbb3d6fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNjA4MDUsIm5iZiI6MTcxNTE2MDUwNSwicGF0aCI6Ii81NTYyNjc5MS8zMjg4MTMwNTYtZDMwNWRkYmYtODEyMy00NjdjLWFjOTktNWJmNmZiYjNkNmZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA4VDA5MjgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA4ZTk3MzZmNTcxYjdiZDhmYWUzMjJjYzNmMDNmNDM4MTk0YzNlMzYyMjFiYzZmNmY4YjQxMTU0NmMxYzE4YWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zRc7h69MeGfVM2YVCpBMtWJIXua6UjABLTcv71V5Tls)
> 
> Yes, I am still getting the error, find my attached code screenshot

Alright, my also suddenly have the same error

**Comment by OliverMengich** [comment]
How can we fix it? I tried version "1.26.20" and it worked before, upon update I get the errors.

**Comment by tonywei92** [comment]
> How can we fix it? I tried version "1.26.20" and it worked before, upon update I get the errors.

maybe @tannerlinsley can help?

**Comment by kavika-1** [comment]
> How can we fix it? I tried version "1.26.20" and it worked before, upon update I get the errors.

Ran into the same, pinned 1.26.20, and the error remained.  We have a `npm run reset` script that removes node_modules and all tmp build directories, and then runs npm install again.  after that step, it started working again.  Maybe that helps short term?

**Comment by SeanCassiere** [comment]
This has been completed as of the [1.31.25](https://github.com/TanStack/router/releases/tag/v1.31.25) release.

**Comment by OliverMengich** [comment]
I see it's now working but still the spinner from the loading state isn't working
```js
const isLoading = useRouterState({ select: (s) => s.status === 'pending' })
```

**Comment by OliverMengich** [comment]
> This has been completed as of the [1.31.25](https://github.com/TanStack/router/releases/tag/v1.31.25) release.

I see it's now working but still the spinner from the loading state isn't working
```js
function RouterSpinner() {
    const isLoading = useRouterState({ select: (s) => s.status === 'pending' })
    return <Spinner show={isLoading} />
  }
```

**Comment by SeanCassiere** [comment]
@OliverMengich this is related to separate issue #1566.

**Comment by OliverMengich** [comment]
Ok, noted.
