### ISSUE TITLE
using React.StrictMode breaks the useMatchRoute hook

### ISSUE THREAD

**Issue by DNR500** [TanStack/router#1569]
### Describe the bug

The useMatchRoute hook no longer seems to be working as of version 1.31.17

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-in-browser-njf6lw-wyq9aw-ke3ssm?file=package.json

### Steps to Reproduce the Bug or Issue

In browser example is here - https://stackblitz.com/edit/tanstack-router-in-browser-njf6lw-wyq9aw-ke3ssm?file=package.json

1. Click on Component About
2. A back button should appear but doesn't display

Note: this appears to be broken for both for the in browser router and the in memory router - example of broken in memory version is here https://stackblitz.com/edit/tanstack-router-in-memory-njf6lw-thk9ow?file=package.json

### Expected behavior

This worked in versions older than 1.31.17

example of 1.31.8 here - https://stackblitz.com/edit/tanstack-router-in-browser-njf6lw-wyq9aw?file=package.json

1. Click on Component About
2. A back button is shown
3. Click on the Component home
4. The back button is hidden

### Platform

OS: macOS 13.3.1 (22E261)
Browser: Chrome Version 123.0.6312.59 (Official Build) (arm64)
Version: @tanstack/react-router: ^1.31.17

**Comment by SeanCassiere** [comment]
This is related to `React.StrictMode` bug as mentioned in #1566.

Testing using the examples above with [1.31.25](https://github.com/TanStack/router/releases/tag/v1.31.25) confirms this by commenting out the StrictMode tags.

**Comment by SeanCassiere** [comment]
This has been completed as of the [1.31.26](https://github.com/TanStack/router/releases/tag/v1.31.26) release.

Tested with both the browserHistory and memoryHistory.
