### ISSUE TITLE
1.31.23 produces `Something went wrong error`

### ISSUE THREAD

**Issue by DNR500** [TanStack/router#1570]
### Describe the bug

Trying to run an app using version 1.31.23 produces an error

`Something went wrong!`
`A component suspended while responding to synchronous input. This will cause the UI to be replaced with a loading indicator. To fix, updates that suspend should be wrapped with startTransition.`

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-in-memory-njf6lw-ujf4ue?file=package.json

### Steps to Reproduce the Bug or Issue

1. run the app
2. error is displayed

### Expected behavior

Runs without this error

### Screenshots or Videos

![Screenshot 2024-05-08 at 11 27 42](https://github.com/TanStack/router/assets/7836726/bb330934-bbb3-414d-bad2-8d381c55a304)

### Platform

OS: macOS 13.3.1 (22E261)
Browser: Chrome Version 123.0.6312.59 (Official Build) (arm64)
Version: @tanstack/react-router: ^1.31.23

**Comment by tonywei92** [comment]
Duplicates of #1567

**Comment by SeanCassiere** [comment]
This has been completed as of the [1.31.25](https://github.com/TanStack/router/releases/tag/v1.31.25) release.
