### ISSUE TITLE
version 1.31.23 has a bug

### ISSUE THREAD

**Issue by davidgvf** [TanStack/router#1571]
### Describe the bug

When you install the latest version it throws match errors
![image](https://github.com/TanStack/router/assets/62423420/e10cd8ad-187a-4cf3-a54d-b95d1e508fe0)
![image](https://github.com/TanStack/router/assets/62423420/98bc31c5-e5e1-4ae7-b127-2748745d6be4)

### Your Example Website or App

local

### Steps to Reproduce the Bug or Issue

1. Update to latest version
2. Run your project

### Expected behavior

Don't make mistakes

### Platform

- OS: [Windows]
- Browser: [Chrome, Safari, Firefox]

**Comment by tonywei92** [comment]
Duplicates of #1567, #1554 and #1570

**Comment by tannerlinsley** [comment]
Should be fixed in latest release. Let me know otherwise!
