### ISSUE TITLE
blank screen triggered on direct visit by beforeLoad calls in StrictMode with trailingSlash set to 'never' or 'always'

### ISSUE THREAD

**Issue by SeanCassiere** [TanStack/router#1591]
### Describe the bug

This bug was found when retesting #1553.

___

The crux of the bug is that, in the right conditions, when visiting a route directly (via the URL bar) the user will only see a white/blank screen with the `beforeLoad` not being properly awaited.

This bug only occurs when directly visiting a URL. It doesn't occur if you navigate to the page once the application is already loaded in.

___

It requires the 3 following conditions to be met.
1. `React.StrictMode` must be ON.
2. `Router.trailingSlash` must be set to `always` or `never`.
3. An async `beforeLoad` function is set with some wait period (i.e. `sleep(500)`).

When these 3 conditions have been met and a user then directly visits a route, its `beforeLoad` function resolves, but the user is only shown a white/blank screen.

When `React.StrictMode` is turned OFF, everything works correctly. But of course, this is not a solution.

### Reproduction

https://stackblitz.com/edit/github-h31abz-yta2mu?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

When `trailingSlash` is set to `never`.
1. Visit `/posts/` and see the URL then get rewritten to `/posts`.
2. Observe, the loader which instantly resolves, but the beforeLoad call finishes after.
3. Observe, a white/blank screen is then shown.

<br>

When `trailingSlash` is set to `always`.
1. Visit `/posts` and see the URL then get rewritten to `/posts/`.
2. However, a loader which instantly resolves, finishes before the beforeLoad call.
3. Observe, a white/blank screen is then shown.

### Expected behavior

All three trailingSlash behaviours in their loading patterns should be the same, when `React.StrictMode` is ON versus when it is turned off.

Currently, `React.StrictMode` OFF yields the expected behaviours, as opposed to when ON, the `beforeLoad` call is not correctly awaited and a white/blank screen is shown.

### Platform

- OS: macOS
- Browser: Chrome, Arc
- TSR Version: 1.32.5

**Comment by patrikzita** [comment]
Hi, I'm little bit confused about one behavior in Tanstack Router. I want to assure if my problem is related to this fixed bug or not. 

If I define beforeLoad like this.
```
beforeLoad: async () => {
  const result = await db.select().from(usersTable);
}
```

Everything looks fine in development mode 

However, if I slightly modify the function by removing the const result assignment:
```
beforeLoad: async () => {
  await db.select().from(usersTable);
}
```
and this option also not working. 
` beforeLoad: async () => db.select().from(usersTable),`

The Clerk sign-in component stops rendering, and the TanStack Router dev tools disappear.
