### ISSUE TITLE
Type error of the prop “to” Link component

### ISSUE THREAD

**Issue by sawa-ko** [TanStack/router#1605]
### Describe the bug

I am currently trying to use the Link component to visit the home page and I have 2 problems, which are typescript typing problems:

1. if I set only the path as “/” I get the following typescript error:

![image](https://github.com/TanStack/router/assets/56084970/ced4f138-59b9-4a64-9fb8-ccca4110a55d)

2. if I put the prop to value as typescript says it should go now I get the following type error:

![image](https://github.com/TanStack/router/assets/56084970/15a98995-8b30-40f7-b499-2d695a69a4d3)

I don't understand how I should put the path in the to prop for the Link component, as I always get a type error anyway.

### Your Example Website or App

I cannot reproduce it in the example test environment.

### Steps to Reproduce the Bug or Issue

1. Create a project using vite
2. Install tanstack router
3. Put the required files inside src
4. Try to use Link componente with the prop "to"

### Expected behavior

Correct typing for this component prop.

### Platform

- OS: Windows
- Browser: Edge
- Version: 124.0.2478.105

**Comment by schiller-manuel** [comment]
it looks like you don't have any real route, just the  `__root.tsx`.
add an `index.tsx` route next to it and you should be able to create a `<Link to="/">`

**Comment by SeanCassiere** [comment]
If you want this looked into further, please open a new issue with a valid reproduction of the bug you are facing.
