### ISSUE TITLE
useRouter() doesn't match all active routes

### ISSUE THREAD

**Issue by oschade** [TanStack/router#1606]
### Describe the bug

When navigating to the "user admin" page via the navigation bar, both "settings/users/admin" and "settings/users" links are highlighted. However, useRouter() only includes the match for "settings/users/admin" and not for "settings/users".

### Your Example Website or App

https://github.com/oschade/tanstack-router-bug

### Steps to Reproduce the Bug or Issue

    1. Clone the project from https://github.com/oschade/tanstack-router-bug
    2. Run the project.
    3. Navigate to the "user admin" page using the navigation bar link.

### Expected behavior

**Expected behavior:**
Both "settings/users/admin" and "settings/users" routes should be included in useRouter() matches.

**Actual behavior:**
Only "settings/users/admin" is included in useRouter() matches; "settings/users" is missing.

### Platform

- OS: Windows
- Browser: Chrome
- Version: current

### Additional context

This inconsistency affects accurate implementation of features like breadcrumbs. Any insights or resolutions would be appreciated.Bug in tanstack-router: useRouter() doesn't match all active routes

**Comment by schiller-manuel** [comment]
You need to create a `route.tsx` inside of `settings/users` or a `users.tsx` inside of `settings`. then you will get 
![Screenshot 2024-05-16 at 23 20 22](https://github.com/TanStack/router/assets/6340397/27e406b8-2c44-43dd-b333-581847da0f15)

**Comment by SeanCassiere** [comment]
The reason the solution above works is that the router matches all the routes that you've chosen to define. If it is not there, then it won't show up as a match.

You can read more about TSR's Route Matching here: https://tanstack.com/router/latest/docs/framework/react/guide/route-matching

Some thing I do with my projects with create routes at everypoint in the URL segments so I have explicit control over what I want to happen and what gets matched.

```
src/routes
index.tsx
settings.tsx <- maybe a shared layout?
settings.index.tsx <- maybe redirect to something since I don't want index to be accessible?
settings.user.tsx <- maybe a shared layout?
settings.user.index.tsx <- do a redirect here
settings.user.$userId.tsx <- display a page for the path param userId
```

**Comment by oschade** [comment]
Thank you very much for your quick response! However, I don't understand this. Why isn't `settings/users/index.tsx` sufficient? Shouldn't it be the route for `settings/users` that you mentioned I'm missing?

**Comment by SeanCassiere** [comment]
> Why isn't settings/users/index.tsx sufficient?

When you are at `/settings/users/$userId` you are not matching the `/settings/users/index` route anymore.

<br>

> Shouldn't it be the route for settings/users that you mentioned I'm missing?

See my response above, where I detailed the routes you'd need to create. In the nested directory, the `src/routes/settings.users.tsx` would be `src/routes/settings/users.tsx` or `src/routes/settings/users/route.tsx`.

<br>

Also, as mentioned in my response, the [Route Matching documentation](https://tanstack.com/router/latest/docs/framework/react/guide/route-matching) on this shows you how routes are matched based on the URL entered. There's also documentation on the [file-naming conventions](https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing#file-naming-conventions) used for file-based routing.

**Comment by oschade** [comment]
Ah, thank you very much. I'm starting to get my head around this now.
