### ISSUE TITLE
Update npmjs README

### ISSUE THREAD

**Issue by mrlubos** [TanStack/router#1614]
### Describe the bug

README in npmjs currently says "The request failed while talking to the backend."

### Your Example Website or App

https://www.npmjs.com/package/@tanstack/router-vite-plugin

### Steps to Reproduce the Bug or Issue

View https://www.npmjs.com/package/@tanstack/router-vite-plugin

### Expected behavior

A more helpful README is displayed

### Platform

N/A

**Comment by SeanCassiere** [comment]
Choosing not to trigger a release.

Rather when we next publish to npm, each package published will have its README updated at that moment.
