### ISSUE TITLE
Can't git clone repo on Windows due to `?split.tsx` files

### ISSUE THREAD

**Issue by ChristopherHaws** [TanStack/router#1634]
### Describe the bug

Windows file system does not allow for question mark characters in file paths so I am unable to clone the repo using Windows directly. I am able to clone the repo using WSL, but not every VSCode extension works in "remote sessions" which is how VSCode connects to WSL.

### Your Example Website or App

https://github.com/TanStack/router.git

### Steps to Reproduce the Bug or Issue

1. Open terminal on Windows (non-WSL)
2. Run `git clone https://github.com/TanStack/router.git`

### Expected behavior

The repository should be checked out locally.

### Screenshots or Videos

```sh
# chaws @ pc-chaws in D:\github\tanstack
$ git clone https://github.com/TanStack/router.git
Cloning into 'router'...
remote: Enumerating objects: 51157, done.
remote: Counting objects: 100% (6539/6539), done.
remote: Compressing objects: 100% (992/992), done.
remote: Total 51157 (delta 5597), reused 6221 (delta 5401), pack-reused 44618
Receiving objects: 100% (51157/51157), 13.11 MiB | 12.96 MiB/s, done.
Resolving deltas: 100% (40629/40629), done.
error: invalid path 'packages/router-vite-plugin/tests/snapshots/createServerFn?split.tsx'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

### Platform

- OS: Windows
- Browser: N/A
- Version: N/A

### Additional context

Here is a list of illegal path characters on Windows:

```
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```

**Comment by SeanCassiere** [comment]
This is because of the test snapshots in `packages/router-vite-plugin`.

Changing this would at least require changes to the vite-plugin over [here](https://github.com/TanStack/router/blob/05941e5ef2b7d2776e885cf473fdcc3970548b22/packages/router-vite-plugin/src/compilers.ts#L88) and [here](https://github.com/TanStack/router/blob/05941e5ef2b7d2776e885cf473fdcc3970548b22/packages/router-vite-plugin/src/compilers.ts#L496).

**Comment by SeanCassiere** [comment]
You should be able to clone the repo now.

**Comment by ChristopherHaws** [comment]
Thanks!
