### ISSUE TITLE
DOCS: Impossible to find something about defaultPendingComponent in docs

### ISSUE THREAD

**Issue by maksymskuibida** [TanStack/router#1636]
### Describe the bug

I remember, that I saw something about this, but I was not able to find it in docs, so, I asked and discussion and then I found this in API Reference. I am not able to find at least something about default pending component by any of "pending", "default pending", "defaultPending". I found some pages about pending components, but there is nothing about defaultPendingComponent

### Your Example Website or App

https://tanstack.com/router/latest/docs/framework/react/overview

### Steps to Reproduce the Bug or Issue

1. Go to search
2. Search "defaultPendingComponent" — nothing found
3. Search "pending". There is some pages about pending, bot there is nothing about defaultPendingComponent there

### Expected behavior

I expect that 
1) It is possible to find something in API reference by "defaultPendingComponent, "defaultPending", "default pending"
2) Something about default pending component here: https://tanstack.com/router/latest/docs/framework/react/guide/data-loading#showing-a-pending-component

### Screenshots or Videos

<img width="1512" alt="image" src="https://github.com/TanStack/router/assets/57814533/b7431a43-29d1-4d54-a27e-15139a057e53">
<img width="1512" alt="image" src="https://github.com/TanStack/router/assets/57814533/db76ce9e-bca8-4504-9dc8-916582b2fe94">

### Platform

-

**Comment by SeanCassiere** [comment]
Put this in the website maintainer's channel since this has to do with Orama search and the actual Router docs themselves.

**Comment by maksymskuibida** [comment]
What channel do you mean?

**Comment by SeanCassiere** [comment]
@maksymskuibida its a private Discord channel for maintainers of the Tanstack Website.

**Comment by maksymskuibida** [comment]
OK, I'll look for it
