### ISSUE TITLE
Context missing on route preload

### ISSUE THREAD

**Issue by jakst** [TanStack/router#1637]
### Describe the bug

When preloading a route inside a layout, the context defined in `beforeLoad` on that layout is not there on the first render of the layout when accessing it through `Route.useRouteContext()`.

### Your Example Website or App

https://stackblitz.com/edit/github-spzf56?file=src%2Froutes%2F_layout.tsx

### Steps to Reproduce the Bug or Issue

1. Open Stackblitz
2. Hover the `About` link to trigger a preload
3. Observe app crashing

### Expected behavior

I expect the static context defined on `beforeLoad` to always be available in the component using `Route.useRouteContext()`

### Platform

- OS: MacOS
- Browser: Arc (Chromium)
- Version: 125

**Comment by geoff-harper** [comment]
I was still seeing this on 1.33.6. I don't know if this makes sense but I had a structure that was similar to

```tsx
<StrictMode>
    <Suspense>
        <RouterProvider />
    </Suspense>
</StrictMode>
```

I think the suspense was a left over from before times and removing it appears to have solved it. I didn't try this on earlier versions but at least on 1.33.6 it's good

**Comment by geoff-harper** [comment]
I lied I think there's still an issue here. I forked the stackblitz from @jakst original post to demonstrate https://stackblitz.com/edit/github-spzf56-r7plo2?file=src%2Froutes%2Fother.tsx.

It seems like the context is still undefined if you refresh the page while on a route that doesn't have a layout parent
