### ISSUE TITLE
`Route.fullPath` is typed incorrectly when using path params

### ISSUE THREAD

**Issue by Tiedye** [TanStack/router#1665]
### Describe the bug

The type of `Route.fullPath` is more or less the path that is passed to the create<xd>Route function, but during runtime it is the current path of the page when `Route,fullPath` references a path with a paramater, which included the sub path, this makes it useless as a `from` parameter when used in a layout route. 

### Your Example Website or App

https://stackblitz.com/edit/github-jhyjxh?file=src%2Froutes%2F%24subsection.tsx

### Steps to Reproduce the Bug or Issue

Click on sub, click on the links and see every navigation is relative to the current url instead of the expected Route.fullPath

### Expected behavior

Not that, the same as for static routes, should behave like this:
https://stackblitz.com/edit/github-jhyjxh-4xvfsf?file=src%2Froutes%2Fsubsection.tsx

### Platform

- OS: Windows
- Browser: Firefox
- Version: 128a

**Comment by schiller-manuel** [comment]
The issue at hand is not that `Route.fullPath` is incorrectly typed, instead the following happens:

At runtime, router does **not** respect `from`, instead it always uses the current location when building relative links.

We had discussed this before, we even had a PR merged for this (see https://github.com/TanStack/router/pull/1595) but reverted since we were not confident about possible side effects.

cc @TkDodo

**Comment by Tiedye** [comment]
Wow, I wouldn't've guessed that

**Comment by Tiedye** [comment]
How is the behaviour of the demo I posted explained?  If I remove the path param it works fine

**Comment by schiller-manuel** [comment]
which path params? can you please post a separate working example?

**Comment by chorobin** [comment]
> I think the issue is simply that if you are on `/$subsection/section-a` and you make a link to `./section-b`, you will wind up on `/$subsection/section-a/section-b`, no matter if you provide `from` or not. TypeScript will allow it because `from` is defined and points to `$subsection`, so we have a discrepancy between type-level and runtime behaviour.
> 
> This should be the same no matter if `$subsection` is used or something static. If that's not the case, please show a separate reproduction.
> 
> So I see a couple of ways forward:
> 
> 1. make runtime behave like type-level and take `from` into account when building navigations. This is similar to what I've tried before but we reverted the merge.
> 2. don't allow relative routes with `./` or `../` if a `from` is supplied, as it's simply confusing. If I provide "from", I expect the link to navigate "from" that start. Since it always takes the current route at runtime (which we can't know at compile time), this would force us to use absolute routes when a from is supplied, like:
> 
> ```
> from="/$subsection"
> to="/$subsection/section-b"
> ```
> 
> that will work on whichever page we are on, and it will still guarantee that you don't have to provide a param for `$subsection` on type level, because it will be narrowed by what we pass to "from".
> 
> Tbh, 2) is what I'm doing right now because I think navigations with `./` or `../` don't really work the way I'd expect them to. When I'm just reading a `<Link>` component in isolation, and it says:
> 
> ```
> from="/$subsection"
> to="./section-b"
> ```
> 
> I'd expect the result to be "/$subsection/section-b", no matter on which page I'm currently on. But I also understand that isn't easy to achieve at runtime (I tried 😂), so maybe enforcing option 2) is a good compromise? @chorobin FYI

Let's try to fix the runtime. It can't be harder than the iterations we went through for the types for relative pathing

**Comment by Tiedye** [comment]
> which path params? can you please post a separate working example?

Here is the version that works, https://stackblitz.com/edit/github-jhyjxh-4xvfsf?file=src%2Froutes%2Fsubsection.section-a.tsx only difference is `$` removed

**Comment by TkDodo** [comment]
@Tiedye thank you. really interesting that this works and probably a good starting point to figure out the runtime differences
