### ISSUE TITLE
`beforeLoad` does not run when resetting from `errorComponent`

### ISSUE THREAD

**Issue by Zebeqo** [TanStack/router#1674]
### Describe the bug

`beforeLoad` does not run when resetting from `errorComponent`

### Your Example Website or App

https://stackblitz.com/edit/github-v42bzy?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. See the error component
2. Press the reset button within the errorComponent
3. `beforeLoad` does not run, resulting in the errorComponent not being displayed again.

### Expected behavior

`beforeLoad` should also run when resetting from `errorComponent`

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [125.0]

**Comment by schiller-manuel** [comment]
I cannot reproduce this anymore in v.1.51.1
https://stackblitz.com/edit/github-v42bzy-ihx2fw?file=package.json,src%2Froutes%2Findex.tsx

however, https://github.com/TanStack/router/issues/2006 is now appearing and will be tracked there
