### ISSUE TITLE
`matchRoute` from `useMatchRoute` doesn't resolve TS type  with pathless (layout) routes 

### ISSUE THREAD

**Issue by toteto** [TanStack/router#1680]
### Describe the bug

When trying to use the `matchRoute` function out of `useMatchRoute` hook with a path that is contained within a pathless route, the resulting match result is typed to `false`. Running this, returns the correct value, `false` when there is no match and the `RouteMatch` with params when there is.

### Your Example Website or App

https://stackblitz.com/edit/github-jqhxtt?file=src%2Froutes%2F_layout.comments.%24id.tsx

### Steps to Reproduce the Bug or Issue

1. Create route nested under a pathless route
2. Try to use `matchRoute`
3. The resulting type of the match is `false`

### Expected behavior

The match has the correct match type with correct route parameters

### Screenshots or Videos

<img width="507" alt="image" src="https://github.com/TanStack/router/assets/1628876/ef415e52-d18f-4439-9167-4a89b31878cd">

<img width="486" alt="image" src="https://github.com/TanStack/router/assets/1628876/af39a4ec-aee3-4acc-9139-e06f66cd565b">

### Platform

/

### Additional context

Side question: is there any recommended way to use the `useParams` or other method/hook inside shared components? For example, I have page component that I share between a `PostCreate` and `PostEdit`. The `PostCreate` is at route `posts/add` while the `PostEdit` is at `posts/$id/edit`. 

I know about using `strict: false` but I am not interested into having such solution.

**Comment by MoulyT** [comment]
I have the exact same issue

**Comment by vladrasenko** [comment]
I have the same issue on `1.139.12`

<img width="421" height="137" alt="Image" src="https://github.com/user-attachments/assets/5414c7a4-70bc-4f15-9855-46fea114f5c2" />

<img width="438" height="139" alt="Image" src="https://github.com/user-attachments/assets/61caf469-feef-4c25-88b8-dde44c291796" />

**Comment by schiller-manuel** [comment]
@vladrasenko please create a new issue including a complete reproducer
