### ISSUE TITLE
`search` seems to be inferring the output type of the `validateSearch` instead of `z.input`

### ISSUE THREAD

**Issue by khy-vireakpanha** [TanStack/router#1701]
### Describe the bug

I want to validate my search params while also making it optional when navigating from other routes but I'll provide the default value if there isn't one so I'm expecting the value to always be available in my route component. However, `useNavigate` and `Link` component seems to infer the type from `validateSearch` incorrectly.

```typescript
const searchSchema = z.object({
  foo: z.string().default(''),
})

// Expected
type Input = z.input<typeof searchSchema> // { foo?: string | undefined }

// Currently Required in `useNavigate` and `Link`
type Output = z.infer<typeof searchSchema> // { foo: string }
```

### Your Example Website or App

https://stackblitz.com/edit/github-guzfgr?file=src%2Froutes%2Findex.tsx&view=editor

### Steps to Reproduce the Bug or Issue

Go to `/src/routes/index.tsx` or `/src/routes/__root.tsx` and you will see the Typescript Error.

### Expected behavior

`search` field should NOT be required or is required with no value needed `{}`.

### Platform

- OS: Linux
- Browser: Chrome
- Version: 1.34.9

**Comment by schiller-manuel** [comment]
yes, the search params are inferred from the return type of `validateSearch`. 
If you want to use a different type as the input type of search params, you need to make this explicit through `SearchSchemaInput`

see the documentation: https://tanstack.com/router/latest/docs/framework/react/api/router/RouteOptionsType#validatesearch-method

there is also an example that shows this: https://github.com/TanStack/router/blob/main/examples/react/basic-default-search-params/src/main.tsx#L149
