### ISSUE TITLE
Link.from prop in layout crashes (started in v1.35.1)

### ISSUE THREAD

**Issue by jakst** [TanStack/router#1715]
### Describe the bug

When upgrading to v1.35.1 I stumbled upon this issue. v1.35.2 still has the issue, but v1.35.0 is fine.

When using a Link with a from prop in a layout, where the from is equal to the layout's path, and if the layout has an index route, the app crashes with `Invariant failed: Could not find match for from: /$var`.

**Example**
```
routes
  $var.tsx
  $var.index.tsx
  $var.about.tsx
```

routes/$var.tsx has the following

```tsx
<Link from="/$var" to="/$var">Home</Link>
<Link from="/$var" to="/$var/$about">About</Link>
```

Then the app will crash when visiting the about page.

### Your Example Website or App

https://stackblitz.com/edit/github-ugiq7e?file=src%2Froutes%2F%24var.tsx

### Steps to Reproduce the Bug or Issue

1. Open stackblitz example
2. Click the `> Go to /$var/about` link
3. Observe the crash

### Expected behavior

I expect layout components to be able to use their own path in the `from` prop.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SeanCassiere** [comment]
Fixed with the revert in [1.35.3](https://github.com/TanStack/router/releases/tag/v1.35.3).
