### ISSUE TITLE
Infinite navigation on redirects

### ISSUE THREAD

**Issue by polRk** [TanStack/router#1728]
### Describe the bug

If i throw the `redirect` error inside beforeLoad for component or inside parent layouts for the same location.href - i got an infinite redirects.

### Your Example Website or App

It doesn't metter

### Steps to Reproduce the Bug or Issue

I'am on `/wizard/choice` route

My file structure

```
- _auth.tsx
- _auth.wizard.choice.tsx
```

```tsx
export const Route = createFileRoute('/_auth')({
	beforeLoad: async ({ context, location }) => {
		const auth = getAuth(context.app)
		await auth.authStateReady()

		if (!auth.currentUser) {
			throw redirect({ to: '/wizard/choice', replace: true })
		}
	},
	component: AppLayout,
})
```

### Expected behavior

Ignore redirect on the same pathname or location.href

### Platform

- macOS
- Chrome
- "@tanstack/react-router": "^1.35.1"

**Comment by schiller-manuel** [comment]
can you please provide a minimal complete example by forking one of the existing examples on Stackblitz?

**Comment by sanchitrk** [comment]
I had the same issue, in my case I noticed I was not handling the auth in redirected route leading to infinite redirects.

**Comment by schiller-manuel** [comment]
closing this as no further information was provided
