### ISSUE TITLE
Typing: validateSearch with z.object() and .optional().default() makes field required in navigation

### ISSUE THREAD

**Issue by maksymskuibida** [TanStack/router#1739]
### Describe the bug

If I do validateSearch, like 
```
z.object({
	page: z.number().min(1).catch(1).default(1),
	pageSize: z.number().positive().min(1).optional().default(DefaultLimit),
	tab: CategoryTabEnum.optional().catch("edit").default("edit"),
	categoryId: z.number().positive().min(1).optional().catch(1),
	search: z.string().optional().catch("").default(""),
})
```

It makes page, pageSize, tab and search required. I don't exact version it is introduced in, but I have just updated from 1.34.9 to 1.36.3 version of @tanstack/react-router 

### Your Example Website or App

everywhere

### Steps to Reproduce the Bug or Issue

Make 
validateSearch: z.object({
	page: z.number().min(1).catch(1).default(1),
	pageSize: z.number().positive().min(1).optional().default(DefaultLimit),
	tab: CategoryTabEnum.optional().catch("edit").default("edit"),
	categoryId: z.number().positive().min(1).optional().catch(1),
	search: z.string().optional().catch("").default(""),
})

and then call Link or navigate without specifying page, pageSize, tab or search

### Expected behavior

I excepted if I set parameter as .optional() in zod it will be optional in fields even if it has .default(). Probably z.input<> should be used instead of z.infer<> in typescript

### Platform

- Version: 1.36.3

**Comment by schiller-manuel** [comment]
this is already discussed here: https://github.com/TanStack/router/issues/1701
