### ISSUE TITLE
beforeLoad Redirect on initial page load not working with Preact

### ISSUE THREAD

**Issue by ajmchambers** [TanStack/router#1741]
### Describe the bug

I have 3 routes:
- index
- dashboard
- other

the 'index' and 'other' routes both have a beforeLoad that redirects to 'dashboard'

Visiting '/' or '/other' will correctly update the browser url to '/dashboard' but the dashboard page will not actually appear.

Visiting '/dashboard' directly does load normally.

Navigating from '/dashboard' to either '/' or '/other' using the Link component seems to redirect back as expected.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-mjt1as?file=src%2Froutes%2F__root.tsx,src%2Froutes%2Fdashboard.tsx,src%2Froutes%2Findex.tsx,src%2Froutes%2Fother.tsx

### Steps to Reproduce the Bug or Issue

Here is a react version for comparison:
https://stackblitz.com/edit/vitejs-vite-t7hzuu?file=src%2Froutes%2F__root.tsx,src%2Froutes%2Fdashboard.tsx,src%2Froutes%2Findex.tsx,src%2Froutes%2Fother.tsx

### Expected behavior

Ideally the redirect would behave the same in preact as in the react version

### Screenshots or Videos

https://github.com/TanStack/router/assets/5426717/3f29e392-0b8a-4fe0-8e69-378e6a262ac6

### Platform

- OS: Windows 11
- Browser: Edge
- Version: 125.0.2535.92

**Comment by SeanCassiere** [comment]
Our README is out of date.

Currently, TanStack Router is pretty much "react-only".

**Comment by SeanCassiere** [comment]
README has been updated to be **react-only**.

**Comment by isaachinman** [comment]
@tannerlinsley Can you confirm if the "preact is not supported" stance still holds?

I've got a client-side only app running via `createHashHistory` and it's truly a shame to not be able to use Preact.

**Comment by schiller-manuel** [comment]
we are currently not supporting preact as in actively testing and fixing bugs for it.
if you however want to contribute that, you are welcome!
