### ISSUE TITLE
Typescript TS2322 error on router property in RouterProvider

### ISSUE THREAD

**Issue by jlin5** [TanStack/router#1745]
### Describe the bug

Starting from version [1.31.1](https://github.com/TanStack/router/releases/tag/v1.31.0), I get a Typescript error on RouterProvider's router property if another RouterProvider is declared in a different file that has a different route structure. The second RouterProvider is only intended to be used in unit tests and not in the actual application.

```
The types of __store.state are incompatible between these types.
```

<img width="937" alt="Screenshot 2024-06-11 at 2 40 09 PM" src="https://github.com/TanStack/router/assets/23406333/85e43d7e-52a9-4c4b-a7ad-52fd52d1e3df">

### Your Example Website or App

https://stackblitz.com/edit/github-9rubhf?file=src%2FtestWrapper.tsx

### Steps to Reproduce the Bug or Issue

View the error in the sample application:
https://stackblitz.com/edit/github-9rubhf?file=src%2FtestWrapper.tsx

### Expected behavior

There shouldn't be a Typescript type error.

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [14.5]

### Additional context

I noticed that if I remove this the error goes away:
```
// Register the router instance for type safety
declare module '@tanstack/react-router' {
	interface Register {
		router: typeof router;
	}
}
```

**Comment by SeanCassiere** [comment]
Do you have the router devtools installed as well? Please try upgrading it to match your version of the router package.

If not, please try nuking your `node_modules` and reinstalling, it should do the trick.

**Comment by jlin5** [comment]
@SeanCassiere 

I do not have router devtools installed. I tried removing `node_modules` and reinstalling, but the error still happens.

**Comment by SeanCassiere** [comment]
I just re-read your original post.

Are you trying to declare the router twice? If so, that'd definitely error-out, because typescript declaration merging can only really happen on a single router instance.

This shouldn't be a problem, since an app should only ever have one `createRouter` call and one `<Router provider>`.

Trying to conditionally render two different routers (/route-trees) could have unintended side-effects anyways with how the event listeners get set up.

**Comment by jlin5** [comment]
I have a second router to be used for unit testing so I can test pages without having to pass in the whole routeTree. What do you recommend I should do to set up a test router in unit tests?

**Comment by SeanCassiere** [comment]
@jlin5 When you are doing unit testing, it's probably best if you don't try to re-declare the router using declaration merging.

You may want to take a look at how we do unit testing with `createRouter` and the `<RouterProvider>` to get an idea for your setup.

https://github.com/TanStack/router/blob/main/packages/react-router/tests/routeContext.test.tsx

**Comment by jlin5** [comment]
@SeanCassiere I have the router declaration merging only once in the entire project and it's only at the application, not in the unit tests. I'm assuming Typescript applied the declaration merging to every Typescript file but the error wasn't happening prior to 1.31.1.

**Comment by jlin5** [comment]
Yes, casting the router as `any` will make the error go away.

**Comment by SeanCassiere** [comment]
> Yes, casting the router as `any` will make the error go away.

Then as long as you are using typescript^5, I'd then recommend doing the any casting so since it's competing with the module declaration merging done for the app.
