### ISSUE TITLE
useMatchRoute will match `routes/about.tsx` on `routes/$var`.

### ISSUE THREAD

**Issue by jakst** [TanStack/router#1760]
### Describe the bug

When visiting `routes/about.tsx`, `isOnVarRoute` is true here
```ts
const matchRoute = useMatchRoute();
const isOnVarRoute = Boolean(matchRoute({ to: '/$var' }));
```

### Your Example Website or App

https://stackblitz.com/edit/github-pimzz4?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

1. Click the `About` link
2. Look at the `isOn$varRoute` value in the header. It says true, even though we're visiting the non-dynamic route `/about`.

### Expected behavior

I expect `useMatchRoute` to not match static paths in dynamic segments.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment]
`matchRoute` does not take the into account the actual route configuration.
we have `useMatch({shouldThrow: false})` for this use case
https://tanstack.com/router/latest/docs/framework/react/api/router/useMatchHook#optsshouldthrow-option
