### ISSUE TITLE
loader doesn't run after redirects

### ISSUE THREAD

**Issue by bagindo** [TanStack/router#1777]
### Describe the bug

using the latest version, the loader with loaderDeps doesn't run initially.

the page needs to be reloaded for it to run.

Reproduction on version ^1.20.4 (✅ works fine)
[https://stackblitz.com/edit/github-p2w83v-xh9id6](https://stackblitz.com/edit/github-p2w83v-xh9id6)

Reproduction on the latest version (^1.38.1) (❌ doesn't run initially)
[https://stackblitz.com/edit/github-p2w83v-pz6euc](https://stackblitz.com/edit/github-p2w83v-pz6euc)

### Your Example Website or App

https://stackblitz.com/edit/github-p2w83v-pz6euc

### Steps to Reproduce the Bug or Issue

update to the latest version

### Expected behavior

run initially, without having to reload the page.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: 1.38.1

**Comment by bagindo** [comment]
Hi @SeanCassiere I tracked down in which version this has stopped working. It's v1.36.3 on #1713 PR, in which the loader is not called after redirection. What's the reason behind this? I have a one page app, and I just want to re-direct the page from the index route.

You can see the full implementation [here](https://github.com/bagindo/tauri-plugin-keygen/tree/9ff505a55b706254382346f49432d824c1b04d9b/examples/esp-trial-license/src/routes)

Is that the wrong way to do things? if it does, how should I implement it?

**Comment by schiller-manuel** [comment]
this will be fixed by #1907 

reproducer with pre-release package: https://stackblitz.com/edit/github-p2w83v-f2pkuk?file=package.json
