### ISSUE TITLE
Throwing `notFound()` in loader causes infinite "pending" state

### ISSUE THREAD

**Issue by mirague** [TanStack/router#1795]
### Describe the bug

If you `throw notFound()` in a loader after a short delay (e.g. when awaiting a request), the parent routes stay forever stuck in "pending" state.

This behaviour does not happen if the loader promise resolves very quick, e.g. within 100ms.

Simplest reproduction:
```tsx
export const Route = createFileRoute('/posts/$postId')({
  loader: async ({ params }) => {
    try {
      // Simulate a slow request. Resolving this within 100ms works fine, but if it takes longer
      // the route state will be forever stuck in pending.
      await new Promise((resolve, reject) => {
        setTimeout(() => {
          reject();
        }, 1000);
      });
    } catch (err) {
      // Never shows
      throw notFound();
    }
  },

  notFoundComponent: () => <div>Post not found</div>,
});
```

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-jc3pyp?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Go to `/posts/whatever` in Stackblitz (`posts.$postId.tsx`)

### Expected behavior

A "Not found message"

### Actual behavior

The matched root route is stuck in a pending state according to the dev tools, the final route correctly has "not found" state.

This causes the page to never load.

### Platform

- OS: macOS
- Browser: Arc (Chrome)
- Version: 1.47

**Comment by mirague** [comment]
@tannerlinsley This is currently very broken, where you're not able to `throw notFound()` in any async `loader` or `beforeLoad`.

Simplest repro (updated Stackblitz):
```tsx
export const Route = createFileRoute('/posts/$postId')({
  loader: async ({ params }) => {
    try {
      // Simulate a slow request. Resolving this within 100ms works fine, but if it takes longer
      // the route state will be forever stuck in pending.
      await new Promise((resolve, reject) => {
        setTimeout(() => {
          reject();
        }, 1000);
      });
    } catch (err) {
      // Never shows
      throw notFound();
    }
  },

  notFoundComponent: () => <div>Post not found</div>,
});
```

**Comment by mirague** [comment]
@schiller-manuel Would be amazing if you could confirm this use-case is also solved by #1907 😍

**Comment by schiller-manuel** [comment]
not solved (yet) unfortunately

**Comment by schiller-manuel** [comment]
reproducer with pre-release package: https://stackblitz.com/edit/tanstack-router-t7vccx?file=src%2Froutes%2Fposts.%24postId.tsx

**Comment by myeljoud** [comment]
I still have the same issue now

**Comment by schiller-manuel** [comment]
@myeljoud please create a new GitHub issue including a complete minimal example

**Comment by natedunn** [comment]
I am getting something similar but I can't seem to reproduce. I am very sad and tired. Just in my project. 😞
