### ISSUE TITLE
`params: (prev) => ({ ...prev, bar: "hello" })` causes a TS error when there are multiple params in `prev`

### ISSUE THREAD

**Issue by aconrad** [TanStack/router#1829]
### Describe the bug

When passing a function to `params` (per [the docs](https://tanstack.com/router/latest/docs/framework/react/guide/path-params#navigating-with-path-params)), the params contained within the `prev` argument are `string | undefined`, which doesn't look right to me.

```tsx
      onClick={() => {
        navigate({
          to: '/test/$foo/$bar',
          params: (prev) => ({ // <-- params has an error (see screenshot below)
            ...prev,
            bar: 'new-bar',
          }),
        });
      }}
```

<img width="1830" alt="Screenshot 2024-06-25 at 4 00 16 PM" src="https://github.com/TanStack/router/assets/247661/8a84ea5b-122c-4466-bde8-20aaf2a9cc14">

### Your Example Website or App

https://stackblitz.com/edit/github-xazqaz?file=src%2Froutes%2Ftest.%24foo.%24bar.tsx,src%2Froutes%2F__root.tsx,src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Open the [stackblitz](https://stackblitz.com/edit/github-xazqaz?file=src%2Froutes%2Ftest.%24foo.%24bar.tsx,src%2Froutes%2F__root.tsx,src%2Froutes%2Findex.tsx) project
2. Open `test.$foo.$bar.tsx`
3. Observe the TS error

### Expected behavior

I don't expect a TS error:

```
    Call signature return types '{ bar: string; foo?: string | undefined; }' and '{ foo: string; bar: string; }' are incompatible.
      The types of 'foo' are incompatible between these types.
        Type 'string | undefined' is not assignable to type 'string'.
          Type 'undefined' is not assignable to type 'string'.(2322)
```

Instead I expect the type `foo` to be `string`, not `string | undefined`.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 126.0.6478.115 (Official Build) (arm64)

**Comment by SeanCassiere** [comment]
You need to set the `from` field to get strict typing.

Like this:

```tsx
const Foo: React.FC = () => {
  const navigate = useNavigate({ from : '/test/$foo/$bar' });
  return (
    <button
```

**Comment by aconrad** [comment]
Gotcha, thanks.

How about `const navigate = Route.useNavigate()`, shouldn't that be equivalent to `useNavigate({ from: '/test/$foo/$bar' })` then?
