### ISSUE TITLE
Relative navigation always expects a `search` param?

### ISSUE THREAD

**Issue by mirague** [TanStack/router#1838]
### Describe the bug

When using navigation (e.g. `navigate` / `redirect`) with a `from` and relative `to`, it seems TypeScript always complains about the `search` param being required, even if none of the routes define a `validateSearch`.

This example works at runtime, but TypeScript complains:
```tsx
export const Route = createFileRoute('/posts/$postId')({
  beforeLoad: () => {
      // works, but TypeScript error about required "search" param
      throw redirect({
        from: Route.fullPath,
        to: '../',
      });
  }
});
```

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-ycpp7o?file=src%2Froutes%2Fposts.%24postId.tsx

### Steps to Reproduce the Bug or Issue

1. Open the `posts.$postId.tsx` file and go to the render function
2. Observe there's a TypeScript error, even though the actual code works

### Expected behavior

I expect that if the `to` route doesn't provide a `validateSearch`, it's not a required prop and TypeScript doesn't complain.

### Screenshots or Videos

![CleanShot 2024-06-27 at 11 06 30@2x](https://github.com/TanStack/router/assets/178117/5f88c1ab-b3a2-42a4-9cea-f8f09c0114c3)

### Platform

- OS: macOS / Arc

**Comment by sepirak-nick** [comment]
Getting the same issue, upgrading from 1.29 to 1.40.

**Comment by schiller-manuel** [comment]
The error you see is caused by the `trailingSlash` router property:

https://tanstack.com/router/latest/docs/framework/react/api/router/RouterOptionsType#trailingslash-property

It defaults to `never`, so in that case you should use

```tsx
        to: '..',
```

see https://stackblitz.com/edit/tanstack-router-xpxvgs?file=src%2Froutes%2Fposts.%24postId.tsx,src%2Fmain.tsx 

If you change`trailingSlash` to either `preserve` or `always`,  you can use `to: '../'`.

see https://stackblitz.com/edit/tanstack-router-wxombr?file=src%2Froutes%2Fposts.%24postId.tsx

**Comment by mirague** [comment]
@schiller-manuel Do you think the type should be more permissive, seeing as the slash will simply be stripped just like with normal navigation? If not, feel free to close this <3

**Comment by schiller-manuel** [comment]
Let's ask @chorobin about his opinion on this

**Comment by judgemavi** [comment]
Looks like in the latest version search param is required if route has validateSearch set. 

I have zod schema with all properties set to optional but link and navigate still require search to be provided

**Comment by chorobin** [comment]
> Let's ask @chorobin about his opinion on this

Yeah, we should at least not suggest '../' and suggest '..' instead

**Comment by chorobin** [comment]
> Looks like in the latest version search param is required if route has validateSearch set.
> 
> I have zod schema with all properties set to optional but link and navigate still require search to be provided

Do you have an example where this is not working?

Generally the type logic for required/search params works off the basis that, if `{}` is assignable to you search params then it is optional
