### ISSUE TITLE
No exported member 'TanStackRouterVite'

### ISSUE THREAD

**Issue by dsavevski** [TanStack/router#1848]
### Describe the bug

When I upgraded to the latest version of  "@tanstack/router-vite-plugin": "1.40.2", the following error appeared: `Module '"@tanstack/router-vite-plugin"' has no exported member 'TanStackRouterVite'.`
As soon as I downgrade to "@tanstack/router-vite-plugin": "1.39.1" the error disappears.

Reproducible both in vs code and webstorm.

### Your Example Website or App

https://tanstack.com/router/latest/docs/framework/react/examples/quickstart-file-based

### Steps to Reproduce the Bug or Issue

In the official [example](https://tanstack.com/router/latest/docs/framework/react/examples/quickstart-file-based) change the extension to ts in vite.config.js and try to import in vite.confing.ts `import { TanStackRouterVite } from '@tanstack/router-vite-plugin';` in version 1.40.x and observe the above mentioned error.

### Expected behavior

As a user I expect the TanStackRouterVite type to be found.

### Screenshots or Videos

<img width="787" alt="Screenshot 2024-06-28 at 09 32 06" src="https://github.com/TanStack/router/assets/18102293/50f45ea1-6b58-42a2-9590-b5faf8bb4686">

_No response_

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [26.0.6478.127]

**Comment by milesegan** [comment]
The example here: https://tanstack.com/router/latest/docs/framework/react/quick-start suggests this:

```typescript
import { TanStackRouterVite } from '@tanstack/router-plugin/vite'
```

Which also fails to find `TanStackRouterVite` but it does seem to work anyway. I can still use routes in my app.

**Comment by dsavevski** [comment]
@milesegan yes I forgot to mention that it works without a problem but it's not nice the editor to scream at you all the time 😄

**Comment by SeanCassiere** [comment]
Dropping this link here: https://discord.com/channels/719702312431386674/1255633461184696381

Your tsconfig needs to have `moduleResolution` set to `bundler`.

**Comment by tunganh-phamba** [comment]
> Dropping this link here: https://discord.com/channels/719702312431386674/1255633461184696381
> 
> Your tsconfig needs to have `moduleResolution` set to `bundler`.

I face the problem again after upgrade to  "@tanstack/router-vite-plugin": "~v1.45.3". Also changed  `moduleResolution` set to `bundler`. Again this does seem to work anyway.

**Comment by GuilhermeTrombini** [comment]
I was able to solve the type error by using `moduleResolution` set to `NodeNext`, consequentially I also needed to change `module` also to `NodeNext` in my `tsconfig.node.json` file

**Comment by janhendry** [comment]
To resolve the issue, you only need to modify the `tsconfig.node.json` file, not the main `tsconfig.json`. Here’s how you can adjust it:

In the `tsconfig.node.json`, you need to set `"moduleResolution": "Bundler"`. This configuration will allow TypeScript to correctly resolve the modules when working with the Vite configuration.

Here is the updated `tsconfig.node.json`:

```json
{
	"compilerOptions": {
		"composite": true,
		"module": "ESNext",
		"moduleResolution": "Bundler",
		"allowSyntheticDefaultImports": true
	},
	"include": ["vite.config.ts"]
}
```

And your `vite.config.ts` should look like this:

```typescript
import react from "@vitejs/plugin-react";
import { defineConfig } from "vite";
import { TanStackRouterVite } from "@tanstack/router-plugin/vite";

export default defineConfig({
	plugins: [react(), TanStackRouterVite()],
});
```

The key change is setting `"moduleResolution": "Bundler"` in `tsconfig.node.json`. This ensures that TypeScript will correctly resolve the `TanStackRouterVite` import, avoiding the issue without needing to alter your main `tsconfig.json`.

**Comment by SeanCassiere** [comment]
> ```ts
> // ...
> export default defineConfig({
> 	plugins: [react(), TanStackRouterVite()],
> });
> ```

I'd put the router-plugin before the react refresh plugin.

```ts
export default defineConfig({
  plugins: [TanStackRouterVite(), react()],
});
```

**Comment by alan345** [comment]
my error: 
![Image](https://github.com/user-attachments/assets/54bb1a21-b294-40bd-83bb-3876d7623ba3)


```
Cannot find module '@tanstack/router-plugin/vite' or its corresponding type declarations.
  There are types at '/Users/alan/Documents/apps/TER/node_modules/@tanstack/router-plugin/dist/esm/vite.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.
```

**Comment by SeanCassiere** [comment]
> my error: 
> ![Image](https://github.com/user-attachments/assets/54bb1a21-b294-40bd-83bb-3876d7623ba3)
> 
> 
> ```
> Cannot find module '@tanstack/router-plugin/vite' or its corresponding type declarations.
>   There are types at '/Users/alan/Documents/apps/TER/node_modules/@tanstack/router-plugin/dist/esm/vite.d.ts', but this result could not be resolved under your current 'moduleResolution' setting. Consider updating to 'node16', 'nodenext', or 'bundler'.
> ```

The error message tells you to sent the `moduleResolution` to "bundler" in your tsconfig.

**Comment by HaiderAli-Ravian** [comment]
**tsconfig.node.json:**
```
{
  "compilerOptions": {
    "moduleResolution": "bundler",
    "module": "ESNext",
    "allowSyntheticDefaultImports": true,
    "composite": true
  },
  "include": ["vite.config.ts"]
}
```


**vite.config.ts:**
```
TanStackRouterVite({
        target: "react",
        autoCodeSplitting: true,
        verboseFileRoutes: false,
      }),
```


**i am getting the following build error:**
```
exit status 1: running "bun run build":
$ vite build && tsc
vite v4.5.14 building for production...
✓ 0 modules transformed.
✓ built in 4ms
[tanstack:router-generator] Cannot read properties of undefined (reading 'config')
error during build:
TypeError: Cannot read properties of undefined (reading 'config')
    at Object.buildStart (/root/repo/node_modules/@tanstack/router-plugin/src/core/router-generator-plugin.ts:77:30)
    at file:///root/repo/node_modules/rollup/dist/es/shared/node-entry.js:25544:40
    at async Promise.all (index 2)
    at async PluginDriver.hookParallel (file:///root/repo/node_modules/rollup/dist/es/shared/node-entry.js:25472:9)
    at async file:///root/repo/node_modules/rollup/dist/es/shared/node-entry.js:26704:13
    at async catchUnfinishedHookActions (file:///root/repo/node_modules/rollup/dist/es/shared/node-entry.js:25910:16)
    at async rollupInternal (file:///root/repo/node_modules/rollup/dist/es/shared/node-entry.js:26701:5)
    at async build (file:///root/repo/node_modules/vite/dist/node/chunks/dep-827b23df.js:48135:18)
    at async CAC.<anonymous> (file:///root/repo/node_modules/vite/dist/node/cli.js:843:9)
error: script "build" exited with code 1
```

**Comment by RMHonor** [comment]
The generator requires at least Vite V6 to access the environment config

**Comment by HaiderAli-Ravian** [comment]
My Vite version is 

"vite": "^4.5.2"

what should i do fix this

**Comment by RMHonor** [comment]
Upgrade to vite@^6.

The peer deps are out of date, it allows v5, but v1.121 now needs v6

**Comment by HaiderAli-Ravian** [comment]
Thanks **RMHonor** it worked for me

**Comment by mikeytown19** [comment]
<img width="1207" alt="Image" src="https://github.com/user-attachments/assets/dbe95ff0-3220-464d-99d2-7b4e47e09670" />

I'm still getting the same issue, even after setting my module to `Bundler` or like the other comment `NodeNext`. 

Even running `npx create-tsrouter-app@latest my-app --template file-router` from the [docs](https://tanstack.com/router/latest/docs/framework/react/quick-start) I still get the same error. 

```   json
    "@tanstack/react-router": "^1.121.2",
    "@tanstack/react-router-devtools": "^1.121.2",
    "@tanstack/router-plugin": "^1.121.2",
```

**Comment by isaacwasserman** [comment]
I'm also experiencing this after using `bunx create-tsrouter-app@latest my-app --template file-router`. `node_modules/@tanstack/router-plugin` doesn't have a `dist`.

```json
"dependencies": {
    "@tanstack/react-router": "^1.121.2",
    "@tanstack/react-router-devtools": "^1.121.2",
    "@tanstack/router-plugin": "^1.121.2",
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  },
  "devDependencies": {
    "@testing-library/dom": "^10.4.0",
    "@testing-library/react": "^16.2.0",
    "@types/react": "^19.0.8",
    "@types/react-dom": "^19.0.3",
    "@vitejs/plugin-react": "^4.3.4",
    "jsdom": "^26.0.0",
    "typescript": "^5.7.2",
    "vite": "^6.1.0",
    "vitest": "^3.0.5",
    "web-vitals": "^4.2.4"
  },
```

**Comment by SeanCassiere** [comment]
> I'm also experiencing this after using `bunx create-tsrouter-app@latest my-app --template file-router`. `node_modules/@tanstack/router-plugin` doesn't have a `dist`.
> 
> ```json
> "dependencies": {
>     "@tanstack/react-router": "^1.121.2",
>     "@tanstack/react-router-devtools": "^1.121.2",
>     "@tanstack/router-plugin": "^1.121.2",
>     "react": "^19.0.0",
>     "react-dom": "^19.0.0"
>   },
>   "devDependencies": {
>     "@testing-library/dom": "^10.4.0",
>     "@testing-library/react": "^16.2.0",
>     "@types/react": "^19.0.8",
>     "@types/react-dom": "^19.0.3",
>     "@vitejs/plugin-react": "^4.3.4",
>     "jsdom": "^26.0.0",
>     "typescript": "^5.7.2",
>     "vite": "^6.1.0",
>     "vitest": "^3.0.5",
>     "web-vitals": "^4.2.4"
>   },
> ```

Unrelated issue, but this has been fixed.

**Comment by MariuzM** [comment]
> > I'm also experiencing this after using `bunx create-tsrouter-app@latest my-app --template file-router`. `node_modules/@tanstack/router-plugin` doesn't have a `dist`.
> > "dependencies": {
> >     "@tanstack/react-router": "^1.121.2",
> >     "@tanstack/react-router-devtools": "^1.121.2",
> >     "@tanstack/router-plugin": "^1.121.2",
> >     "react": "^19.0.0",
> >     "react-dom": "^19.0.0"
> >   },
> >   "devDependencies": {
> >     "@testing-library/dom": "^10.4.0",
> >     "@testing-library/react": "^16.2.0",
> >     "@types/react": "^19.0.8",
> >     "@types/react-dom": "^19.0.3",
> >     "@vitejs/plugin-react": "^4.3.4",
> >     "jsdom": "^26.0.0",
> >     "typescript": "^5.7.2",
> >     "vite": "^6.1.0",
> >     "vitest": "^3.0.5",
> >     "web-vitals": "^4.2.4"
> >   },
> 
> Unrelated issue, but this has been fixed.

still same issue today

**Comment by MariuzM** [comment]
<img width="672" height="323" alt="Image" src="https://github.com/user-attachments/assets/403efc1a-5739-45b1-806e-5a7e374d779c" />

**Comment by ben-grandin** [comment]
Note : you won't find the `"@tanstask/router-plugin/vite` if you have  :
- `"moduleResolution": "bundler",` 
- `"resolvePackageJsonExports": false,`

**resolvePackageJsonExports** kind of cancel the **moduleResolution**
