### ISSUE TITLE
start-basic fails to build on windows

### ISSUE THREAD

**Issue by SeanCassiere** [TanStack/router#1889]
### Describe the bug

Using the start-basic example, when you try to the build script it fails.

### Your Example Website or App

Use the start-basic example

### Steps to Reproduce the Bug or Issue

1. Clone the `start-basic` example onto a Windows computer.
2. Install deps.
3. Run the build script (`pnpm build`).

### Expected behavior

As a user, I expect the application to successfully build.

### Platform

@tanstack/start - 1.43.9
@tanstack/react-router - 1.43.6

**Comment by SeanCassiere** [comment]
This is the error message you get on Windows.

```
> tanstack-router-example-react-start-basic@ build D:\code\tanstack\router\examples\react\start-basic
> vinxi build

vinxi v0.3.11


⚙  Building your app...
removing D:/code/tanstack/router/examples/react/start-basic/.vinxi/build/client


📦 Compiling client router...
vinxi building router client in client mode

♻️  Generating routes...
✅ Processed routes in 543ms
vite v5.3.2 building for production...
virtual:#vinxi/handler/client (1:109): "default" is not exported by "app/client.tsx", imported by "virtual:#vinxi/handler/client".
✓ 131 modules transformed.
.vinxi/build/client/_build/server-functions-manifest.json    0.10 kB │ gzip:  0.10 kB
.vinxi/build/client/_build/.vite/manifest.json               0.38 kB │ gzip:  0.20 kB
.vinxi/build/client/_build/assets/app-JDGE9Y9X.css           6.96 kB │ gzip:  2.04 kB
.vinxi/build/client/_build/assets/client-JWaMu8ot.js       262.11 kB │ gzip: 81.66 kB
✓ built in 1.51s
✔ build done                                                                                                                                            12:20:54 pm


📦 Compiling ssr router...
vinxi building router ssr in http mode

♻️  Regenerating routes...
✅ Processed routes in 32ms
vite v5.3.2 building SSR bundle for production...
✓ 12 modules transformed.
x Build failed in 54ms

[12:20:54 pm]  ERROR  [tsr-routes-manifest] Could not load tsr:routes-manifest (imported by ../../../packages/start/dist/esm/router-manifest/index.js): Cannot read properties of undefined (reading 'map')

  at Object.load (/D:/code/tanstack/router/packages/start/dist/esm/config/index.js:284:46)
  at async PluginDriver.hookFirstAndGetPlugin (/D:/code/tanstack/router/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:19674:28)   
  at async /D:/code/tanstack/router/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:18845:33
  at async Queue.work (/D:/code/tanstack/router/node_modules/.pnpm/rollup@4.18.0/node_modules/rollup/dist/es/shared/node-entry.js:19884:32)



[12:20:54 pm]  ERROR  [tsr-routes-manifest] Could not load tsr:routes-manifest (imported by ../../../packages/start/dist/esm/router-manifest/index.js): Cannot read properties of undefined (reading 'map')

 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by SeanCassiere** [comment]
These are the client manifest outputs at `start-basic/.vinxi/build/client/_build/vite/manifest.json`.

<details><summary>Windows</summary>
<pre>
{
  "D:/code/tanstack/router/examples/react/start-basic/app/styles/app.css": {
    "file": "assets/app-JDGE9Y9X.css",
    "src": "D:/code/tanstack/router/examples/react/start-basic/app/styles/app.css"
  },
  "virtual:#vinxi/handler/client": {
    "file": "assets/client-JWaMu8ot.js",
    "name": "client",
    "src": "virtual:#vinxi/handler/client",
    "isEntry": true
  }
}
</pre>
</details>

**Comment by SeanCassiere** [comment]
I'm not sure if this an issue in Start's implementation or whether its upstream in Vinxi.

**Comment by NimmLor** [comment]
Having the exact same issue here! Also noticed the different manifest outputs.

**Comment by SamuelSackey** [comment]
Having the same issue. It builds fine on WSL but on Windows I get a `tsr:routes-manifest` error.

**Comment by SeanCassiere** [comment]
Closing this as https://github.com/TanStack/router/pull/2367 has resolved this.

This has been tested on a windows machine on the `start-basic` example. Dev was tested, build was tested, as well as running the build artefacts using `preset='node-server'`.
