### ISSUE TITLE
`useRouteContext` returns undefined when navigating with `<Navigate />`

### ISSUE THREAD

**Issue by nklhtv** [TanStack/router#1892]
### Describe the bug

Context is undefined when using `<Navigate />` to redirect.
The bug does not occur if you remove React.StrictMode
The bug does not occur if you remove the empty beforeLoad from postsRoute on line 46

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-fuvvzs

### Steps to Reproduce the Bug or Issue

1. run the app
2. wait 1 second for the setTimeout to trigger
3. check logs in console, context is undefined

### Expected behavior

context to be an object

### Platform

- OS: mac
- Browser: Chrome
- Version: any

### Additional context

Could be related or a duplicate of:
https://github.com/TanStack/router/issues/1886
https://github.com/TanStack/router/issues/1751
https://github.com/TanStack/router/issues/1740
but non of those mentions `<Navigate />`

**Comment by schiller-manuel** [comment]
this will be fixed by #1907
reproducer with pre-release package: https://stackblitz.com/edit/tanstack-router-jtyx8r?file=package.json
