### ISSUE TITLE
`defaultPendingComponent` always rendered once on load

### ISSUE THREAD

**Issue by nklhtv** [TanStack/router#1899]
### Describe the bug

defaultPendingComponent always rendered once on load, even if there are no loaders

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-ho2fk8?file=src%2Fmain.tsx&preset=node

### Steps to Reproduce the Bug or Issue

1. Run the app
2. Default pending component is rendered
3. Home route is rendered

### Expected behavior

1. Run the app
2. Home route is rendered

### Platform

- OS: mac
- Browser: Chrome
- Version: any

### Additional context
related to: https://github.com/TanStack/router/issues/1349 but this issue is for initial load only

_No response_

**Comment by ericchernuka** [comment]
I wonder if this is related to this bug, https://github.com/TanStack/router/issues/1646

**Comment by schiller-manuel** [comment]
this will be fixed by #1907

reproducer with pre-release package: https://stackblitz.com/edit/tanstack-router-mbxik2?file=src%2Fmain.tsx&preset=node
