### ISSUE TITLE
Active link based on undefined search param

### ISSUE THREAD

**Issue by tobyzerner** [TanStack/router#1920]
### Describe the bug

If you have a `Link` with `search={{ foo: undefined }}`, it will NOT be "active" when the query param `foo` is not present in the URL.

In my app, I have a navigation bar which controls a query param (`foo`). The first link unsets this query param, while subsequent links set it to different values. I want these links to have active status based just on this query param (disregarding other query params).

The default matching works great for the links which have a value for the query param. For the "home" link, I could use `activeOptions={{ exact: true }}` so that the link isn't active if the `foo` query param has a value. However, it also won't be active when other query params have a value.

Ideally I could set `search={{ foo: undefined }}` on the link. However, this does not actually match when the `foo` query parameter isn't present in the URL.

### Your Example Website or App

https://stackblitz.com/edit/github-7rehud-pn5er4?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

1. Click the `Foo = a` and `Foo = b` links. Observe that they become active.
2. Click the `Bar = a` link. Observe that it becomes active, and the `Foo = a|b` link remains active.
3. Click the `Exact` link, then the `Bar = a` link. Observe that `Bar = a` becomes active, but `Exact` is no longer active.
4. Click the `Foo = undefined` link. Observe that it does NOT become active.

### Expected behavior

The `Foo = undefined` link should be active when the `foo` query parameter is not present in the URL.

### Platform

- OS: macOS
- Browser: Safari, Chrome
- Version: all

**Comment by tobyzerner** [comment]
Yes it should be - but currently in the logic for whether a link is active or not they're not the same thing.

**Comment by SeanCassiere** [comment]
This should get fixed with #1969.

Here's the reproduction with the patch applied: https://stackblitz.com/edit/github-7rehud-jcedoy?file=src%2Froutes%2F__root.tsx
