### ISSUE TITLE
No typescipt error thrown if context is missing

### ISSUE THREAD

**Issue by nklhtv** [TanStack/router#1926]
### Describe the bug

No typescipt error thrown if context is missing from createRouter args.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-pte2gy

### Steps to Reproduce the Bug or Issue

Create a root route with a context with required prop
Create a router without specifying the context object
No typescript error is thrown

### Expected behavior

Typescript error should be thrown. The app should fail to compile a prod build.

### Platform

- OS: any
- Browser: any
- Version: any

**Comment by schiller-manuel** [comment]
you can provide the context either in `createRouter` or via `<RouterProvider>` (see e.g. https://tanstack.com/router/latest/docs/framework/react/guide/router-context#how-about-using-react-contexthooks ). there is no way to know which way you choose, so we cannot error here.

**Comment by nklhtv** [comment]
in the [Passing the initial Router Context](https://tanstack.com/router/latest/docs/framework/react/guide/router-context#passing-the-initial-router-context) section we have:
```If your context has any required properties, you will see a TypeScript error if you don't pass them in the initial router context.```

**Comment by nklhtv** [comment]
Also i can confirm it used to throw a typescript error in this exact case with version 1.34.7
https://stackblitz.com/edit/tanstack-router-tzp2th

**Comment by schiller-manuel** [comment]
interesting, which version did introduce this change?
