### ISSUE TITLE
Slow initial load

### ISSUE THREAD

**Issue by cheec** [TanStack/router#1929]
### Describe the bug

- At the time of writing, `latest` version is v1.44.0
- The initial load of a skeleton React app using the router is perceivably slow (~500ms from React profiler)
- [v1.28.1](https://github.com/TanStack/router/releases/tag/v1.28.1) is the latest good version (good as in not perceivably slow) which suggests that [v1.28.2](https://github.com/TanStack/router/releases/tag/v1.28.2) introduced a regression

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-vjwuwc?file=index.html,package.json,package-lock.json,src%2Fmain.tsx,vite.config.js

### Steps to Reproduce the Bug or Issue

- Bad: https://stackblitz.com/edit/tanstack-router-vjwuwc?file=index.html,package.json,package-lock.json,src%2Fmain.tsx,vite.config.js
- Good: https://stackblitz.com/edit/tanstack-router-u6raco?file=index.html,package.json,package-lock.json,src%2Fmain.tsx,vite.config.js

The only difference between Good and Bad is the router version.

1. Refresh the page on the StackBlitz browser
2. Notice that `This sentence is from React` loads instantly in the Good version, almost at the same time as `This sentence is from HTML`. 
3. Notice that `This sentence is from React` loads after a delay in the Bad version, ~500ms after `This sentence is from HTML`

### Expected behavior

As a user, I expected no perceivable delays on initial app load

### Platform

- macOS
- Chrome Version 126.0.6478.127 (Official Build) (arm64)

**Comment by ericchernuka** [comment]
Wonder if this is related to https://github.com/TanStack/router/issues/1899

**Comment by cheec** [comment]
Thanks @ericchernuka for the pointer! Sounds like a workaround would be to set `defaultPendingMinMs` to 0

**Comment by cheec** [comment]
+ #1646

**Comment by schiller-manuel** [comment]
this will be fixed by #1907 

reproducer with pre-release package: https://stackblitz.com/edit/tanstack-router-mp74sr?file=index.html,package.json,package-lock.json,src%2Fmain.tsx,vite.config.js

**Comment by levrik** [comment]
@schiller-manuel I'm still seeing this `500ms` delay on `1.45.11`

**Comment by schiller-manuel** [comment]
@levrik  can you please open a new issue by and provide a minimal complete example by forking one of the existing router examples on stackblitz?
e.g. https://tanstack.com/router/v1/docs/framework/react/examples/quickstart-file-based
