### ISSUE TITLE
Route Not found when using nested groups

### ISSUE THREAD

**Issue by SundayPowerEndre** [TanStack/router#1939]
### Describe the bug

Describe the bug
When i am using nested route groups i am not able to visit pages that are inside the second group. 

Say that i have a path that is "/(auth)/org/(graphql)/$orgId/revenue" I will not be able to visit "(auth)/org/(graphql)$orgId/revenue" but i can visit "(auth)/org/$orgId" since it is not inside two groups.

On version: "@tanstack/react-router": "^1.44.1"

### Your Example Website or App

https://stackblitz.com/edit/github-isj4z7?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

Attempt to visit /org/$orgId/revenue

### Expected behavior

I would expect to see the route. 

### Platform

Platform
OS: [MacOs]
Browser: [Arc]
Version: [Version 1.46.0 (50665)]

### Additional context

I had the issue #1725 but i never implemented the pattern in my app before now. So the error has been there from version 1.0 and i am assuming this is a bug due to the fix on the related issue

**Comment by schiller-manuel** [comment]
I updated all deps to the latest version and it works as expected: https://stackblitz.com/edit/github-isj4z7-kxrfjy

please note that the router vite plugin is now in a different package:

@tanstack/router-plugin

see https://tanstack.com/router/v1/docs/framework/react/quick-start#using-file-based-route-generation

**Comment by SundayPowerEndre** [comment]
I am going to work more on reproducing it, it is still happening in my main repo. And the structure of the routes seems to be exactly the same..

**Comment by SundayPowerEndre** [comment]
I found it: 

https://stackblitz.com/edit/github-isj4z7-63kzp3?file=src%2Froutes%2F__root.tsx

It was because i was using the nested groups where both of them contained some layout information. So now you'll see that the /(auth)/dashboard will contain the <div> element with "Auth".

While (auth)/org/$orgId/(org_context)/revenue will be not found. This happened after adding the (org_context).tsx with the <Outlet/>.

**Comment by SundayPowerEndre** [comment]
@schiller-manuel 

I found it: 

https://stackblitz.com/edit/github-isj4z7-63kzp3?file=src%2Froutes%2F__root.tsx

It was because i was using the nested groups where both of them contained some layout information. So now you'll see that the /(auth)/dashboard will contain the <div> element with "Auth".

While (auth)/org/$orgId/(org_context)/revenue will be not found. This happened after adding the (org_context).tsx with the <Outlet/>.

**Comment by schiller-manuel** [comment]
route groups do not support layouts. so you cannot have `(auth).tsx`

**Comment by SundayPowerEndre** [comment]
i mean, i might just have misread the documentation then, but in the application at work it has been working fine the whole time.

we have (auth).tsx and (auth) dir with JSX and Outlet. 

So i guess it is not supported but works in practice? 

Is there a reason for the seperation between layouts and groups? I generally prefer the (xxx) syntax over _xxx syntax, so that is why i used groups.

**Comment by SeanCassiere** [comment]
As @schiller-manuel mentioned, `(layout)` is not a supported convention for a layout route.

Route groups are distinctly different from a layout route, as route groups are only for organizing your _related_ routes within a single folder (not too dissimilar to what nextjs allows). In this regard, route groups should NOT have a route configuration attached to it. Layout routes, are TSR's solution for letting you have a shared layout across navigations without being present in the URL.

Tanner chose Remix's convention for layout routes (prefixed with a `_`) because he felt it better signified that the route in question wouldn't have an impact on the generated URL.

**Comment by SeanCassiere** [comment]
I'm pushing a change that'll disallow this behaviour to this kind of confusion doesn't happen in the future.

**Comment by SeanCassiere** [comment]
A fix has been released to not allow creating routes like `(group).tsx` with the [1.44.3](https://github.com/TanStack/router/releases/tag/v1.44.3) release.
