### ISSUE TITLE
Scroll Restoration component not working

### ISSUE THREAD

**Issue by darkv314** [TanStack/router#1944]
### Describe the bug

I'm trying to use the Scroll Restoration component in my React + Vite app and it's not working.
It appears that the "next" state is always saving null values for scroll x and y. 
<img width="168" alt="image" src="https://github.com/TanStack/router/assets/60781992/42b0ddc8-c3c6-4949-9466-7eaae1924bcc">

### Your Example Website or App

https://flades-test.vercel.app/

### Steps to Reproduce the Bug or Issue

1. Scroll the page
2. Click on a link in the nav bar or use a "Leer mas/Read more" button, both cases will redirect you to a new page
3. In the new page, click the left arrow from your browse to go back to the previous page
4. Observe that you're in the top of the page

### Expected behavior

As a user, I expected the scroll to be saved and to be preserved as I'm coming back to that page.

### Platform

- OS: [Windows]
- Browser: [Arc, Chrome, Edge]
- Version: [126.0.6478.127]

**Comment by SeanCassiere** [comment]
@darkv314 I am unable to reproduce this issue you are facing. Make sure you have rendered the `<ScrollResoration>`
 component in the Root component. Also, please make sure you are on the latest version of TanStack Router (`npm install @tanstack/react-router@latest`).

If you are still facing this issue, please provide a valid minimal reproduction of the issue you are facing. You can get started by forking the [Router stackblitz starter](https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart-file-based).

--- 

On the [implementation](https://github.com/TanStack/router/blob/0b5bff59425d03a81a5d5b673bb31285b0482d0f/packages/react-router/src/scroll-restoration.tsx#L99) side of things, we only commit or restore from the `tsr-scroll-restoration-v2` cache, on a navigation event which is tracked by subscribing to the Router's `onBeforeLoad` and `onResolved` events.

**Comment by darkv314** [comment]
I just tried to upgrade the version of tanstack router to the latest and scroll restauration is working just fine in developer mode, however when I get the app in production is not working correctly. 
I'm making my tests in this repo: https://github.com/darkv314/flades-test, the ScrollRestoration component is in the __root.tsx file in the src/routes folder. 
The production link is: https://flades-test.vercel.app/

**Comment by SeanCassiere** [comment]
@darkv314 A reproduction needs to be a minimal example showing off the issue. Without a minimal reproduction, it is difficult to trace the issue since it gets muddled up with any existing business logic and components.

Here is a minimal version, with it working as expected both in development mode and production: https://stackblitz.com/edit/github-kgxnup?file=src%2Froutes%2Findex.tsx

Please turn this starter into a reproduction that can be used.

**Comment by SeanCassiere** [comment]
After stripping away your reproduction, I think I've managed to pinpoint the issue.

**Comment by SeanCassiere** [comment]
This has been completed as of the [1.44.4](https://github.com/TanStack/router/releases/tag/v1.44.4) release.
