### ISSUE TITLE
Loader Function Doesn't Re-run on Context Change

### ISSUE THREAD

**Issue by anatolzak** [TanStack/router#1951]
### Describe the bug

The loader function doesn't re-run when context changes. Is this by design? 

### Your Example Website or App

https://stackblitz.com/edit/github-a82dce?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

Create React state outside of where `RouterProvider` is rendered and pass the state to the Router's context. Then use the state passed to the context in a route's loader function. The loader function will not re-run when the context changes.

### Expected behavior

The loader function should re-run when context changes. Or perhaps, we should get the context as a parameter in `loaderDeps`. Currently, you only receive `search` in the `loaderDeps` parameters.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SeanCassiere** [comment]
@schiller-manuel correct me if I'm wrong, but in this instance the you'd need to call `router.invalidate()` when the external state changes yes?

```diff
function App() {
  const [counter, setCounter] = useState(0);

  useEffect(() => {
    const interval = setInterval(() => {
      setCounter((prev) => prev + 1);
+     router.invalidate()
    }, 500);

    return () => clearInterval(interval)
  }, []);

  return (
    <div>
      <div>Counter Outside Router: {counter}</div>
      <RouterProvider router={router} context={{ counter }} />
    </div>
  );
}
```

**Comment by anatolzak** [comment]
@SeanCassiere thanks for your response. I didn't realize that the intended usage with external state is to invalidate the router when you update the external state. Thanks for your help!

**Comment by SeanCassiere** [comment]
Added a portion on a router context page on this: https://tanstack.com/router/latest/docs/framework/react/guide/router-context#invalidating-the-router-context

We've discussed this in the Discord discussions a few times I think, just that we forgot to actually add it to the docs I think 😅

**Comment by anatolzak** [comment]
@SeanCassiere So I played around with your suggestion of invalidating the router and I just wanted to say that I think having an option of adding certain state from context to `loaderDeps` would be a lot more helpful. When calling `router.invalidate()`, the loader of every route match is re-run which is unnecessary.

**Comment by SeanCassiere** [comment]
@anatolzak In its current state, that is intended. Since all currently active matched routes could depend on not only the entry context but also whatever is returned from `beforeLoad`.

We could look at getting context into `loaderDeps` after PR 1907 goes through, but even that might not completely get the behaviour you described.

ATM, I think we are OK with a bit of over-fetching vs getting into a state where some loaders haven't fired due to the intricacies of router context. Plus, we have an open issue for adding `context` to `loaderDeps`, https://github.com/TanStack/router/issues/1216.
