### ISSUE TITLE
Module '"@tanstack/router-vite-plugin"' has no exported member 'TanStackRouterVite'

### ISSUE THREAD

**Issue by 0xMALVEE** [TanStack/router#1958]
### Describe the bug

![image](https://github.com/user-attachments/assets/1d277515-a52e-47cf-9c9d-6f3cfd71d9f8)

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

![image](https://github.com/user-attachments/assets/0360539e-018a-4e72-903e-2b80c21fb972)

### Expected behavior

![image](https://github.com/user-attachments/assets/85c83bf4-922e-4992-9730-6c3112a3f630)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SeanCassiere** [comment]
This is typescript error. Setting the `moduleResolution` flag to "Bundler" should fix it.

Just play around with the `module` and `moduleResolution` flags.
