### ISSUE TITLE
NotFound route when refreshing or manual url to a route with special characters

### ISSUE THREAD

**Issue by Hampton-Matt** [TanStack/router#1959]
### Describe the bug

Using the file based routing with file names/routes that have special characters, in my case it is accented characters such as â or é etc., causes not found issues. (Running using vite and the file based plugin)

Manually routing to a page, i.e. typing in a url and hitting enter, or refreshing or opening in a new tab, throws notfound and consequentally will render the 404 or notfound component. 

I can easily fix it by renaming my files to use english characters only but thought I would flag it anyway.

### Your Example Website or App

https://stackblitz.com/edit/github-sxumx6?file=src%2Froutes%2Fex%C3%A2mple.tsx,src%2Froutes%2F__root.tsx

Link that actually throws not found instead of routing:
https://wmaibnrpmngithub-zclp--3001--70dbe416.local-corp.webcontainer.io/exâmple

### Steps to Reproduce the Bug or Issue

1. Create a new route / file with special characters like é
2. Let routetree.gen generate
3. Route to page using app to check it is working
4. Then refresh, open in new tab or manually retype url to reproduce issue (will throw a 404 instead of routing)

### Expected behavior

It should route to the page but instead 404s the exisiting route

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SeanCassiere** [comment]
I'm not sure if this is something that needs "fixing". As per [RFC 3986](https://www.rfc-editor.org/rfc/rfc3986), the URL only supports ASCII characters and everything else should be URL encoded.

**Comment by SeanCassiere** [comment]
Thinking on this a bit more, it isn't too much effort for the router to perform these checks under the hood.

I'll work on shipping this soon.

**Comment by SeanCassiere** [comment]
This has been completed as of the [1.45.2](https://github.com/TanStack/router/releases/tag/v1.45.2) release.

**Comment by themsv** [comment]
I am facing a similar issue, when I manually type the route in URL, I am getting a Not found error.
But I navigate using <Link to="/cart"> it works.

**Comment by SeanCassiere** [comment]
> I am facing a similar issue, when I manually type the route in URL, I am getting a Not found error. But I navigate using it works. But interestingly locally(development) this issue is not happening but happens on the deployed site.

@themsv Please create an issue with a reproduction.

**Comment by JulianMiguelAngle** [comment]
Hey mate, i'm facing same issue, is it bug or not?

**Comment by schiller-manuel** [comment]
@JulianMiguelAngle  please create a new issue including a minimal complete example

**Comment by PhilipGrefe** [comment]
I had the same issue when deploying to vercel and fixed this by adding a `vercel.json` at the root of my project with:
```json
{ "routes": [{ "src": "/[^.]+", "dest": "/", "status": 200 }] }
```

[Ref to a related stackoverflow](https://stackoverflow.com/questions/75963788/why-is-my-vercel-project-giving-me-an-error-404-on-refresh) question.

**Comment by syntaxlexx** [comment]
For monorepos with netlify
```toml
# netlify.toml

[build]
  publish = "apps/web/dist"  # Or your build output directory

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

```

**Comment by SyedZawwarAhmed** [comment]
> I had the same issue when deploying to vercel and fixed this by adding a `vercel.json` at the root of my project with:
> 
> { "routes": [{ "src": "/[^.]+", "dest": "/", "status": 200 }] }
> [Ref to a related stackoverflow](https://stackoverflow.com/questions/75963788/why-is-my-vercel-project-giving-me-an-error-404-on-refresh) question.

This does fix the issue.
