### ISSUE TITLE
notFound() errors thrown in components aren't caught, in spite of notFoundComponent and defaultNotFoundComponent

### ISSUE THREAD

**Issue by bohdancho** [TanStack/router#1977]
### Describe the bug

Throwing a `notFound()` error results in "Something went wrong!" page. Both `notFoundComponent` and `defaultNotFoundComponent` are ignored. Errors from `loader` or `beforeLoad` are being caught just as expected though.

### Your Example Website or App

https://stackblitz.com/edit/github-5yqpnd-rdpxks?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Open the reproduction
2. Click on the "Error" page in the navigation bar

### Expected behavior

I expected the error to be caught and a provided `notFoundComponent` to be shown, exactly as if the error was thrown in a `loader`.

### Screenshots or Videos

![image](https://github.com/user-attachments/assets/6ffe9189-50ef-49b1-a98e-0a34ef0327d2)

### Platform

- OS: Windows
- Browser: Chrome
- Version: 126.0.6478.183 (Official Build) (64-bit)

**Comment by schiller-manuel** [comment]
`notFound` can only be thrown in `beforeLoad` and`loader`. It's not supported to throw this in a component.

**Comment by SeanCassiere** [comment]
The `notFound` utility can only ever be thrown from the `beforeLoad` or `loader` callbacks.

You cannot throw a `notFound` in any of the components (i.e. `component`, `errorComponent`,`pendingComponent`, `notFoundComponent`).

**Comment by bohdancho** [comment]
> The `notFound` utility can only ever be thrown from the `beforeLoad` or `loader` callbacks.
> 
> You cannot throw a `notFound` in any of the components (i.e. `component`, `errorComponent`,`pendingComponent`, `notFoundComponent`).

I suppose this should be updated then?
![image](https://github.com/user-attachments/assets/53dbe76e-bf71-4046-8070-9454e2e766e7)

**Comment by SeanCassiere** [comment]
> I suppose this should be updated then?

Good catch, will update.

**Comment by miroslavvojtus** [comment]
I was pretty mislead with this documentation as well https://tanstack.com/router/latest/docs/framework/react/guide/not-found-errors#throwing-not-found-errors-in-components
