### ISSUE TITLE
Static route data is not enforced

### ISSUE THREAD

**Issue by VaclavSir** [TanStack/router#1978]
### Describe the bug

When using `createFileRoute`, the option `staticData` is always optional.

### Your Example Website or App

https://stackblitz.com/edit/github-vnv6ze?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Declare interface `StaticDataRouteOption` in `main.tsx`

### Expected behavior

The property `staticData` should be required when `StaticDataRouteOption` has any required properties.

### Platform

- OS: Windows
- Browser: Edge
- Version: 126.0.2592.102

**Comment by SeanCassiere** [comment]
This looks to only be on `createFileRoute` function.

Using the following route creation methods, the `staticData` type is correctly enforced.

- `new Route`
- `createRoute`
- `new FileRoute().createRoute`

**Comment by honzahruby** [comment]
I fixed that by adding an explicit output type for `createFileRoute`. Would you have a look @SeanCassiere? 🙏
