### ISSUE TITLE
When there's backticks in the loader response. Dev fails.

### ISSUE THREAD

**Issue by jadedevin13** [TanStack/router#1994]
### Describe the bug

This happens because the console.log that has the content "Injected From Server:" does not sanitize the output.

TBH. I'm not even sure if I should be the one to sanitize the inputs before returning it.

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

Replace _layout.ts in start basic example with the following codes.

```ts
import { Outlet, createFileRoute } from '@tanstack/react-router'

export const Route = createFileRoute('/_layout')({
  loader: async () => {
    return {
      staticData: {
        nice: 'sam`ple`data',
      },
    }
  },
  component: LayoutComponent,
})

function LayoutComponent() {
  const { staticData } = Route.useLoaderData()
  return (
    <div className="p-2">
      {staticData.nice}
      <div>I'm a layout</div>
      <div>
        <Outlet />
      </div>
    </div>
  )
}
```

<img width="1220" alt="image" src="https://github.com/user-attachments/assets/5c467386-e449-44a7-aaf1-6afe5454e356">

### Expected behavior

Should clean/sanitize the console.log output?

### Platform

    "@tanstack/react-router": "^1.45.6",
    "@tanstack/router-devtools": "^1.45.6",
    "@tanstack/router-plugin": "^1.45.3",
    "@tanstack/start": "^1.45.6",
    "@typescript-eslint/parser": "^7.16.0",
    "@vitejs/plugin-react": "^4.3.1",
    "isbot": "^5.1.12",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "redaxios": "^0.5.1",
    "tailwind-merge": "^2.4.0",
    "vinxi": "0.3.12"

**Comment by SeanCassiere** [comment]
Retested this in the start-basic example on Router and Start versions 1.52.5 and it worked as expected.



![Image](https://github.com/user-attachments/assets/8e420edf-5132-4404-8b24-7a8135329126)

![Image](https://github.com/user-attachments/assets/24577ebd-9bae-468f-87dc-27625187d8c3)
