### ISSUE TITLE
Error component is not displayed when an error is thrown by beforeLoad on the first access screen

### ISSUE THREAD

**Issue by FiNGAHOLiC** [TanStack/router#2006]
### Describe the bug

If an error is thrown by beforeLoad on the screen after the page is moved, the error component is displayed.
* Incidentally, there is also a problem that the error component remains displayed when returning with the back button of the browser, although this is not the main issue.

However, on the screen at the first access, the error component is not displayed even if an error is thrown by beforeLoad.

```tsx
import { createFileRoute } from '@tanstack/react-router';

export const Route = createFileRoute('/test/')({
  beforeLoad: async () => {
    await new Promise((resolve) => setTimeout(resolve, 1000));

    // If an error is thrown by beforeLoad on the screen after the page is moved, the error component is displayed.
    // However, on the screen at the first access, the error component is not displayed even if an error is thrown by beforeLoad.
    throw new Error('error');
  },
});

```

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-ptbzxn

### Steps to Reproduce the Bug or Issue

1. Open the StackBlitz reproduction and open preview in new tab
1. Click [test]
1. Error component is displayed on Test Page
1. Refresh Page on Test Page
1. Error component is not displayed on Test Page

### Expected behavior

The error component should be displayed if an error is thrown by beforeLoad, even on the first access.

### Platform

- OS: any
- Browser: any
- Version: latest

**Comment by tannerlinsley** [comment]
Do we have a failing test we could add for this?

**Comment by SeanCassiere** [comment]
Got tests for this in https://github.com/TanStack/router/pull/2040

**Comment by lo1tuma** [comment]
I think the same issue happens when an error is thrown in `shouldReload()`.

**Comment by FiNGAHOLiC** [comment]
any updates?

**Comment by schiller-manuel** [comment]
fixed this in https://github.com/TanStack/router/releases/tag/v1.74.6
