### ISSUE TITLE
Path parameter with value 0 is ignored

### ISSUE THREAD

**Issue by ThomasStock** [TanStack/router#2024]
### Describe the bug

`<Link
          to={'/employee/$id'}
          params={{
            id: 0,
          }}
        >
          Employee with id 0
        </Link>`

With route:

`export const Route = createFileRoute('/employee/$id')({
  component: AboutComponent,
});`

Since a recent update (1.38.1 -> 1.45.10), this link generates: `/employee` while it used to generate `/employee/0`

`<Link
          to={'/employee/$id'}
          params={{
            id: 5,
          }}
        >
          Employee with id 5
        </Link>`
Still correctly generates  `/employee/5`

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-jnrhtc?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

- Click on 'About with id 0'
- Notice it renders "Not found" because the link does not include the parameter

### Expected behavior

Path parameters should support the number 0 as we use index based routing in a List->Detail view for entities that don't have a uuid.

### Platform

- Browser: Chrome

### Additional context

Why I need this:
I use react-hook-form's fieldarray to let the user modifiy an array of 'things'. When the user clicks the 'add thing'
 button I add a 'thing' and navigate to /mypage/things/0 to let the user enter the thing's details.

**Comment by schiller-manuel** [comment]
params must be strings, indicated also by the typescript error in your example: 

```
Type 'number' is not assignable to type 'string'.(2322)
```

If you use `id: '0'`, it works as expected

**Comment by ThomasStock** [comment]
@schiller-manuel The problem remains when using the parse/stringify api which I forgot to add in my example.

See https://stackblitz.com/edit/tanstack-router-jnrhtc?file=src%2Froutes%2Fabout.%24id.tsx
