### ISSUE TITLE
Two very closely executed `navigate` within a useEffect cause overwrite of search params

### ISSUE THREAD

**Issue by lukaskoeller** [TanStack/router#2028]
### Describe the bug

There are two `useEffect` that run a `navigate` very close to each other. While the first one attaches `firstId`, the second attaches the `secondId` search param. The time the second `navigate` tries to spread the `old` params, `old` does not yet include the `firstId` from the first `navigate` right before (probably because the promise didn't resolve at that time).

The problem and result is that only `secondId` is attached as search param although I'd expect to see `firstId` and `secondId`.

Reference: https://discord.com/channels/719702312431386674/1263458457906839624/1265628984914214952

### Your Example Website or App

https://github.com/lukaskoeller/tanstack-react-router-useEffect-navigate-reproduction?tab=readme-ov-file#reproduction-1---second-navigate-does-not-have-updated-params-from-first-navigate-in-old-parameter-thus-overwrites-params-from-first-navigate

### Steps to Reproduce the Bug or Issue

1. Install dependencies via `pnpm i`
2. Start the dev server via `pnpm dev`
3. Open the console.
4. Navigate to `/news`
5. Only `?secondId=42` is attached. Also see how `old` is empty for the navigate:secondId.

### Expected behavior

As a user, I expect to see `firstId` and `secondId` as search params after both `navigate` runs, but I only see `secondId`.

### Screenshots or Videos

<img width="1918" alt="Screenshot 2024-07-24 at 13 05 39" src="https://github.com/user-attachments/assets/05d16462-ceef-4100-ad08-258a74f50e5d">

### Platform

- OS: macOS Sonoma 14.3.1
- Browser: Chrome
- Version: 126.0.6478.183 (Official Build) (arm64)

**Comment by schiller-manuel** [comment]
you call `navigate` in two separate `useEffect`s. You need to synchronize those calls so they happen serially.

**Comment by lukaskoeller** [comment]
> you call `navigate` in two separate `useEffect`s. You need to synchronize those calls so they happen serially.

Got it, thanks. Is this still an issue you're trying to tackle anytime soon or do you rather solely see that on the lib user's side? In the end, this kind of issue is not so easy to spot when it happens. And with a growing application there will be more `useEffect`s running close to each other and with it the likelihood that some navigation will be overwritten by another.

**Comment by schiller-manuel** [comment]
@lukaskoeller  this is fixed now in v1.51.7

**Comment by lukaskoeller** [comment]
@schiller-manuel Thank you very much! Thanks for contributing to OS, especially this awesome library. Much appreciated 🚀
