### ISSUE TITLE
Blank screen / loads indefinitely when using validateSearch and loader/beforeLoad on __root

### ISSUE THREAD

**Issue by zenoxs** [TanStack/router#2031]
### Describe the bug

A bug occurs when using the `validateSearch `method with a custom schema created with `zod `in the latest version of `tanstack/router`. Specifically, the bug manifests when the route is accessed without search parameters, causing the page to load indefinitely. However, if the URL includes the search parameters, the route works as expected. This issue arises only when `loader `or `beforeLoad `is used on the `__root.tsx`.

It seems things were working correctly on version `1.29.2`, but I couldn't find where the regression occurs.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-svgwoy?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

1. Setup a custom schema with zod and parse it on the `validateSearch`
```tsx
// routes/about.tsx
export const aboutSearchSchema = z.object({
  data: z.string().array().default([]),
});

export type AboutSearch = z.infer<typeof aboutSearchSchema>;
export type AboutSearchInput = z.input<typeof aboutSearchSchema>;

export const Route = createFileRoute('/about')({
  validateSearch: (search: AboutSearchInput & SearchSchemaInput): AboutSearch =>
    aboutSearchSchema.parse(search),
  component: AboutComponent,
});
```
2. Set up the root route with loader or beforeLoad:
```tsx
// routes/__root.tsx
export const Route = createRootRoute({
  component: RootComponent,
  // This cause the bug with validateSearch
  // loader: () => {
  beforeLoad: () => {
    console.log('beforeload called');
  },
});
```
3. Open the `/about` route in a new tab without any search parameters. The page goes blank and loads indefinitely.

4. Open the `/about?data=%5B%5D` route. The page loads as expected.

### Expected behavior

The route should load correctly regardless of whether search parameters are included in the URL.

**Actual Behavior:**

- Without search parameters (`/about`), the page goes blank and loads indefinitely.
- With search parameters (`/about?data=%5B%5D`), the page loads correctly.

### Platform

- OS: Windows / Linux
- Browser: Chrome / Firefox
- Version: 1.45.11

**Comment by schiller-manuel** [comment]
regression from 1.45.3
works in 1.45.2: https://stackblitz.com/edit/tanstack-router-sakdh8

**Comment by tannerlinsley** [comment]
Do we have any failing tests we could add for this?

**Comment by schiller-manuel** [comment]
@tannerlinsley added a test that reproduces this behavior here: https://github.com/TanStack/router/commit/8ffad3110c3458d88fd8c2577a2ccb523f914c7a

**Comment by ruiaraujo012** [comment]
I'm getting the same bug, in my case for every route, not only the __root that has a `loader` our `beforeLoad` and a `validateSearch`. Instead of `zod` I'm using `valibot`.
In my case, it happens by lazy load DevTools:
```ts
 import { lazy } from 'react';

 const TanStackRouterDevtools = import.meta.env.PROD
   ? () => null
   : lazy(() =>
       // Lazy load in development
       import('@tanstack/router-devtools').then((res) => ({
         default: res.TanStackRouterDevtools,
       })),
     );
```

If I import it like `import { TanStackRouterDevtools } from '@tanstack/router-devtools';` it works.

**Comment by Yz4230** [comment]
I encountered the same case, but I was able to solve it by setting `defaultPendingMinMs` to `0`!

It seems that setTimeout in `MatchInner` is related.
https://stackblitz.com/edit/tanstack-router-3m8kxc?file=src%2Frouter.tsx
https://github.com/TanStack/router/blob/bfba3ede236e58836f87eebe0ceac0c204643f8e/packages/react-router/src/Match.tsx#L208-L234

**Comment by schiller-manuel** [comment]
removing `TanStackRouterDevtools` from the reproducer does not change this incorrect behavior.

**Comment by ruiaraujo012** [comment]
> I encountered the same case, but I was able to solve it by setting `defaultPendingMinMs` to `0`! https://stackblitz.com/edit/tanstack-router-3m8kxc?file=src%2Frouter.tsx
> 
> It seems that setTimeout in `MatchInner` is related.
> 
> https://github.com/TanStack/router/blob/bfba3ede236e58836f87eebe0ceac0c204643f8e/packages/react-router/src/Match.tsx#L208-L234

I can confirm this, it resolved my issue.

**Comment by paaskus** [comment]
I also encountered this issue when setting a default value for a search param in `validateSearch`.

This causes a problem with infinite loading when a default value is set for the `dateFilter` search param.

```tsx
const Route = createFileRoute('/progress')({
	component: ProgressComponent,
	validateSearch: (search: Record<string, unknown>): ProgressSearch => {
		return {
			view: search.view as ProgressSearch['view'],
			orderId: search.orderId as ProgressSearch['orderId'],
			machineId: search.machineId as ProgressSearch['machineId'],
			dateFilter:
				(search.dateFilter as ProgressSearch['dateFilter']) ?? 'next_24h',
		}
	},
})
```

When removing the default search param, the issue doesn't occur:

```tsx
const Route = createFileRoute('/progress')({
	component: ProgressComponent,
	validateSearch: (search: Record<string, unknown>): ProgressSearch => {
		return {
			view: search.view as ProgressSearch['view'],
			orderId: search.orderId as ProgressSearch['orderId'],
			machineId: search.machineId as ProgressSearch['machineId'],
			dateFilter:
				(search.dateFilter as ProgressSearch['dateFilter']),
		}
	},
})
```

I can also confirm that setting `defaultPendingMinMs: 0` in the `createRouter` function solves the issue I'm experiencing.

```tsx
const router = createRouter({
	routeTree,
	defaultPreload: 'intent',
	defaultPendingMinMs: 0,
})
```

I'm on version `"@tanstack/react-router": "^1.46.0"`.
