### ISSUE TITLE
@tanstack/react-virtual window virtualizer dynamic measurement not working for items rendered on the server

### ISSUE THREAD

**Issue by idonov** [TanStack/router#2036]
### Describe the bug

After moving to tanstack router, the window virtualizer dynamic measurement stoped working for server rendered items.

I see no hydration errors, but for the items rendered on the server the measurement is not working if the item height changes on the client.
If you scroll away the items and scroll back, measurement will start working again for the same items on height change.

### Your Example Website or App

https://stackblitz.com/~/github.com/idonov/tanstack-router?file=examples/react/basic-ssr-file-based/src/routes/index.tsx

### Steps to Reproduce the Bug or Issue

1. Open & run the basic-ssr-file-based example from the forked repo
2. Refresh the page
3. Click the expand button on one of the items from the top that were rendered on the server
4. Notice the virtualizer does not update their height, but expanding any of the client rendered items from below works correctly
5. Scroll down until the server rendered items are not visible and then scroll back up.
6. Click expand/shrink again on the top items, notice the measurement now works.

### Expected behavior

I expect items rendered on the server to properly be measured on the client when they change height without them having to be re-rendered by scrolling away and back.

### Screenshots or Videos

<img width="1098" alt="image" src="https://github.com/user-attachments/assets/e56b9e76-daf7-4b0b-a0f4-d8ecbaebcca2">

### Platform

- OS: macOS
- Browser: Chrome
- Version: Sanoma

**Comment by SeanCassiere** [comment]
I'm not really about to view the reproduction since the Stackblitz link has cloned our entire mono-repo instead of the individual example.

You can start off from https://stackblitz.com/github/tanstack/router/tree/main/examples/react/basic-ssr-file-based?file=src/main.tsx
