### ISSUE TITLE
defaultPendingComponent takes precedence over __root pendingComponent in child-routes

### ISSUE THREAD

**Issue by lanice** [TanStack/router#2096]
### Describe the bug

When setting a `defaultPendingComponent` in the router properties, as well as a `pendingComponent` in the __root route, the `defaultPendingComponent` seems to take precedence when accessing any child routes.

I am not entirely sure if that's a bug or intended, but to me it feels like a `pendingComponent` set in the __root route should take precedence, as the __root route should encompass all child routes, right?

In the stackblitz I provided (forked from the basic file based example) I added a 5s timeout to the `fetchPost` function, so one can see the pending component.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-zu7pgy?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the "Posts" tab.
2. Click on any post.
3. On the right side, you see the text `defaultPendingComponent` for 5 seconds while the post is fetching.

### Expected behavior

I expected to see the text `_root pendingComponent` while the post is being fetched, because that is set as `pendingComponent` in the __root route, but I am seeing the default pending component instead.

### Platform

- OS: Linux
- Browser: Firefox & Chrome
- Version: 128.0.3 (Firefox) & 127.0.6533.72 (Chrome)

**Comment by schiller-manuel** [comment]
this is working as intended.
The `loader` is defined in the `/posts/$postId` route, and for this route a pending component is needed.
Since there is none defined, it will use the `defaultPendingComponent`.

**Comment by lanice** [comment]
Why wouldn't it use the `pendingComponent` of the `__root` route? It seems like the root `pendingComponent` has no use then?

**Comment by schiller-manuel** [comment]
`__root` route is not pending, since it does not have a loader. so why should it it use a pending component at all?

**Comment by lanice** [comment]
I thought the `__root` route is kind there to set things that wrap around all routes. Like defining `beforeLoad` on the `__root` route, that is called before **any** route loads, right?

**Comment by schiller-manuel** [comment]
yes, but still a route will only be in pending state if it loads something.
so move the loader to root and you will see the root pending component
