### ISSUE TITLE
Processing Accumulated Route Context does not get updated on navigation

### ISSUE THREAD

**Issue by maxgraw** [TanStack/router#2101]
### Describe the bug

When using the code snippet from the documentation [Processing Accumulated Route Context](https://tanstack.com/router/latest/docs/framework/react/guide/router-context#processing-accumulated-route-context), the correct context is displayed on loading but does not get refreshed when navigating between routes.

I did some testing, and it appears that the code snippet stopped working after the [v1.45.14](https://github.com/TanStack/router/releases/tag/v1.45.14) release.

### Your Example Website or App

https://stackblitz.com/edit/github-r165u1?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

1. Navigate to the "About" page.
2. Accumulated Route Context does not get updated

### Expected behavior

I expect, that the Accumulated Route Context gets updated when navigating inside the Application.

### Platform

- OS: Windows
- Browser: [Firefox, Chrome]
- Version: 129.0

### Additional context

https://stackblitz.com/edit/github-r165u1-241uhu?file=package.json a working example using  v1.45.13

**Comment by schiller-manuel** [comment]
`useRouter` is not reactive, use `useRouterState` instead. see also the docs https://tanstack.com/router/latest/docs/framework/react/api/router/useRouterHook#userouter-returns

https://stackblitz.com/edit/github-r165u1-juez4h?file=src%2Froutes%2F__root.tsx
