### ISSUE TITLE
defaultPendingMinMs doesn't work

### ISSUE THREAD

**Issue by quangphuchuynh95** [TanStack/router#2106]
### Describe the bug

Try my example here, I just forked it from your "Quickstart File Based" example and change `main.tsx` and `routes/__root.tsx`
https://stackblitz.com/edit/tanstack-router-fntpjs?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

- Add a `defaultPendingComponent: <span>Loading</span>` to `__root.tsx`
- Add a `defaultPendingMinMs: 10_000` to `createRouter()` options
- Add a `beforeLoad` to `__root.tsx` which return a promise and resolve after 300 ms
- Try to start & reload page

### What happened?

- "Loading" is flashed and hide immediately

### Expected behavior

-  Page should show "Loading" at least 10 secs

### Platform

- OS: [macOS: 14.5]
- Browser: [Chrome: 127.0.6533.90]
- Version: 1.46.8

**Comment by MYKEU** [comment]
I'm also seeing the same thing

**Comment by schiller-manuel** [comment]
this is a regression introduced in 1.46.3

working in 1.46.2: https://stackblitz.com/edit/tanstack-router-pv96gs?file=package.json
failing in 1.46.3: https://stackblitz.com/edit/tanstack-router-olqpmg?file=package.json
