### ISSUE TITLE
1.47.1 Release introduces hydration errors

### ISSUE THREAD

**Issue by idonov** [TanStack/router#2111]
### Describe the bug

When upgrading to the latest version, 1.47.1 at the time, hydration errors are introduced for ssr.

Latest working versions are 
"@tanstack/react-router": "1.46.8",
"@tanstack/router-devtools": "1.47.1",
"@tanstack/router-plugin": "1.47.0",
"@tanstack/start": "1.47.0",

### Your Example Website or App

https://tanstack.com/router/latest/docs/framework/react/examples/basic-ssr-file-based

### Steps to Reproduce the Bug or Issue

1. Open the basic-ssr-file-based example.
2. Refresh the app
3. Check console for hydration errors

### Expected behavior

No hydration errors

### Screenshots or Videos

<img width="789" alt="image" src="https://github.com/user-attachments/assets/96826ac2-ef70-4530-b9ba-5399ac538f6f">

### Platform

- OS: macOS
- Browser: Edge

**Comment by schiller-manuel** [comment]
@SeanCassiere  @mta-trackunit please have a look

**Comment by SeanCassiere** [comment]
Tanner is aware of this and looking into it.

@idonov for the time being please stick to [1.47.0](https://github.com/TanStack/router/releases/tag/v1.47.0).
