### ISSUE TITLE
docs: bugs in start examples

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [TanStack/router#2126]
### Describe the bug

- Posts rendering fails
- Navigation renders twice (**THIS only happens with the RSC example!**)

### Your Example Website or App

https://tanstack.com/router/latest/docs/framework/react/examples/start-basic-rsc

### Steps to Reproduce the Bug or Issue

1. Go to a start example and once it's started up, click "Posts".

### Expected behavior

- Posts rendering works
- Navigation renders once

### Screenshots or Videos

![start_rsc_posts](https://github.com/user-attachments/assets/af59ee3e-3119-4d59-99ce-84dd87724bea)

### Platform

- OS: Windows 10
- Browser: Chrome
- Version: 127.0.6533.120

**Comment by SeanCassiere** [comment]
This seems to be an issue with the embedded Stackblitz environment for the start examples. Both during active development and deployment this does work as expected.

What is broken however is the `Start Basic (RSC)` example, which doesn't work as TanStack Router hasn't gotten RSC working yet consistently.
The Start Basic Rsc example should be hidden till we happy for people to try it out.
