### ISSUE TITLE
`Route.onError` return type doesn't match `Redirect` return type

### ISSUE THREAD

**Issue by Rendez** [TanStack/router#2129]
### Describe the bug

I think there's a regression on `onError`, the documentation states: 

> "If this function returns a redirect object, the redirect will be applied immediately."
> https://tanstack.com/router/latest/docs/framework/react/api/router/RouteOptionsType#onerror-property

... But the typings say otherwise:

```ts
onError?: (err: any) => void;
```

### Your Example Website or App

https://tanstack.com/router/latest/docs/framework/react/api/router/RouteOptionsType#onerror-property

### Steps to Reproduce the Bug or Issue

1. create a Route.loader()
2. throw inside it
3. define Route.onError
4. return a redirect

### Expected behavior

Are we allowed to return a redirect()?

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SeanCassiere** [comment]
The docs need to be updated here.

The [implementation](https://github.com/TanStack/router/blob/265c6a505800ffa71fb43da91954c146309a82cd/packages/react-router/src/router.ts#L2194-L2202) requires that a `redirect` be thrown from the `onError` callback for it to be consumed by the handled by the router.
