### ISSUE TITLE
Using File- and Code-based route generation together, does not generate children entries in routeTree

### ISSUE THREAD

**Issue by smairo** [TanStack/router#2154]
### Describe the bug

Image a application that has loads of entities. Each entity has CRUD operations possible. If you were to use file based route generation, you'd end up with four times number of [add.route.tsx delete.route.tsx view.route.tsx update.route.tsx] for each entity.

For this reason, we were looking at combining the file based routes until the "root" of the entity has been reached, and then setup its crud routes ('view/$entityId', 'delete/$entityId') as code based routes. This is done with

```typescript
export const Route = createFileRoute('/$tenantName/some-entity/')({ ... })

const ViewRoute = createRoute({ ..., path: "view/$entityId, ..." })

Route.addChildren([ViewRoute])
```

Now we want to create TO link:
`to="view/12345"` which the linter says is not assignable (as the programatically added childRoute is not reflected at all in routeTree)

And also, we cant use:
`const { tenantName, entityId } = useParams({strict: false});` for the same reason.

Workaround is to export childRoute itself:
`const { tenantName, customerId } = ViewRoute.useParams();`

**Is there way to make addChildren from code based config, to show up in the routeTree?**

### Your Example Website or App

https://github.com/Granlund-Manager-Product-Development/gm-tanstack-children-params-repro

### Steps to Reproduce the Bug or Issue

npm install
npm run dev

or

bun install
bun run dev

### Expected behavior

I was expecting:
<Link to="view/123">View Customer</Link>
or
const { tenantName, customerId } = useParams({strict: false});

to work.

### Platform

- Linux
- Vivaldi (Chromium)

**Comment by SeanCassiere** [comment]
This doesn't work since TSR doesn't support using both file-based routing and code-based routing together.

This is because, the route-tree is built only-once ([see here in your code](https://github.com/Granlund-Manager-Product-Development/gm-tanstack-children-params-repro/blob/40bb026b2bbe1272df6b882540a5158dc4e204ba/src/routeTree.gen.ts#L39)), which is then used in the router.

You'll need to pick either to use file-based routing or code-based routing.

**Comment by smairo** [comment]
Okay, do you have any plans to support this type of behaviour in the future? Cosing as this was not a bug

**Comment by SeanCassiere** [comment]
@smairo no we don't have any plans for this as it'd mess with how we do our typescript declaration.

Making this change would be a major rewrite, as we use the return value of `.addChildren` for building the route-tree. Making this change would require rewriting the logic of the RouteClass and how the route-tree is built. It'd likely also, require a major rewrite of how the types are propagated.

**Comment by smairo** [comment]
Okay, thanks!

**Comment by davidvalen95** [comment]
Not to generate in `routeTree.gen.tsx` but We can combine the `file based` and `code style` router in 1 project

1. make routing with file based first to generate the `routeTree.gen.tsx`
2. now we can unify the coded style to the file based. at `router.tsx`  at the `createRouter` or any files that make use of the `createTanStackRouter`
like example below
``` typescript
import { routeTree } from "./routeTree.gen";

const adminIndexRoute = createRoute({
  path: "/",
  getParentRoute: () => routeTree,
  component: () => <div>index list</div>,
});
const adminListRoute = createRoute({
  path: "/admin/list",
  getParentRoute: () => routeTree,
  component: () => <div>admin list</div>,
});
const adminEditRoute = createRoute({
  path: "/admin/edit",
  getParentRoute: () => routeTree,
  component: () => <div>admin edit</div>,
});

export function createRouter() {
  const router = createTanStackRouter({
    routeTree: routeTree.addChildren([
      adminListRoute,
      adminEditRoute,
      adminIndexRoute,
    ]),
    defaultPreload: "intent",
    defaultErrorComponent: DefaultCatchBoundary,
    defaultNotFoundComponent: () => <NotFound />,
    scrollRestoration: true,
  });

declare module "@tanstack/react-router" {
  interface Register {
    router: ReturnType<typeof createRouter>;
  }
}
```
