### ISSUE TITLE
Duplicate identifier 'Register'

### ISSUE THREAD

**Issue by mmospanenko** [TanStack/router#2156]
### Describe the bug

In the docs you have:

```
declare module '@tanstack/react-router' {
  type Register = {
    router: typeof router;
  };
}
```

but you also have 

```
export interface Register {
}
```
in the client/node_modules/.pnpm/@tanstack+react-router@1.48.4_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/@tanstack/react-router/dist/esm/router.d.ts

so I have an error from TS:
<img width="530" alt="image" src="https://github.com/user-attachments/assets/25fdae0a-3b8c-471e-b45a-8b03ebb3d790">

### Your Example Website or App

website?

### Steps to Reproduce the Bug or Issue

1. create TS declaration in the file following https://tanstack.com/router/latest/docs/framework/react/guide/creating-a-router#router-type-safety
2. see an error

### Expected behavior

no any errors :)

### Platform

"typescript": "^5.5.4"

**Comment by schiller-manuel** [comment]
you need to declare this as an `interface`, not as a `type`, exactly as stated in the docs.
![Screenshot 2024-08-20 at 19 28 59](https://github.com/user-attachments/assets/db1d863a-6217-4663-bb97-33edd461b102)

otherwise declaration will fail
