### ISSUE TITLE
Devtools visible in production build

### ISSUE THREAD

**Issue by danielbayerlein** [TanStack/router#219]
**Describe the bug**

Currently, the devtools are also displayed in the production build. According to the [documentation](https://react-location.tanstack.com/tools/devtools#import-the-devtools), they should not be displayed.

**Version**

```json
"@tanstack/react-location": "^3.6.1",
"@tanstack/react-location-devtools": "^3.4.4",
```

**Expected behavior**

Devtools are displayed only in the development environment.

**Additional context**

Initially, the problem was fixed with commit 5f019c812808e084c6b48a6a8f30b61efdc2639c.

**Comment by reintroducing** [comment]
@tannerlinsley is it possible to get this resolved? react-query devtools don't show in production builds but react-location does.

**Comment by tannerlinsley** [comment]
Because of the way the new build system works we can’t build it the same way as React Query. For now, I would suggest creating a dynamic import of the React Location devtools that depends on your build systems environment variable

Tanner Linsley

**Comment by drenther** [comment]
Can we get the documentation updated accordingly?
