### ISSUE TITLE
Errors from createServerFn is being wrapped and tanstack/query is receiving that error.

### ISSUE THREAD

**Issue by jadedevin13** [TanStack/router#2238]
I wish to transform the errors coming from createServerFn. Those are actually zod validation errors that are server-side.

```ts
export const objectUpsertOptions: UseMutationOptions<
  void,
  void,
  z.infer<typeof upsertParamsSchema>
> = {
  mutationKey: ['objectUpsert'],
  mutationFn: objectUpsert,
  onSuccess: (data, variables, context) => {
    queryClient.invalidateQueries({ queryKey: ['objects'] })
  },
  onError: (error, variables, context) => {
    console.log(SuperJSON.stringify(error) as string)
    toast.error(SuperJSON.stringify(error) as string)
  },
}
```

Unfortunately, in the fetcher

https://github.com/TanStack/router/blob/a57398e1c4278c637100b6080e858d94b9538cf6/packages/start/src/client-runtime/fetcher.tsx#L134-L139

The response is being wrapped, is there a way to expose the JSON body and not have a string with a concatenated prefix of "Request failed with status 500"

![Image](https://github.com/user-attachments/assets/3dfe480c-5c86-4863-9010-affe1b149b6b)

**Comment by SeanCassiere** [comment]
@jadedevin13 With the [1.52.6](https://github.com/TanStack/router/releases/tag/v1.52.6) release you'll need to `JSON.parse` the `Error.message`, but it should be much easier now to read what's being returned.
