### ISSUE TITLE
Search parameters get overridden on page load

### ISSUE THREAD

**Issue by lithdew** [TanStack/router#2290]
### Which project does this relate to?

Start

### Describe the bug

```ts
export const Route = createFileRoute('/')({
  component: Home,
  validateSearch: z.object({
    step: z.enum(['a', 'b', 'c']).optional(),
  }),
  loaderDeps: ({ search: { step } }) => ({ step }),
  loader: async ({ deps: { step } }) => {
    if (step === undefined) {
      throw redirect({
        to: '/',
        search: ({ step: _, ...search }) => ({ ...search, step: 'a' }),
      })
    }
  },
})
```

When I navigate to `/`, it is expected that I get redirected to `/?step=a` - this works as expected.

However, when I navigate to `/?step=b`, I get redirected to `/`, and then subsequently get redirected to `/?step=a`.

No errors get thrown when I navigate to to `/?step=b`, which leads me to assume that the search parameters were properly validated by the Zod schema under `validateSearch`. 

It is expected that when I navigate to `/?step=b`, that I would stay on `/?step=b` without being redirected to `/` and subsequently `/?step=a`. 

This bug occurs irrespective of this redirect logic being placed in:

1. `beforeLoad`,
2. `loader`, or
3. in `component` with a `useEffect` over `Route.useSearch({ select: ({step}) => step })`

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-txrzyl?file=app%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Go to https://stackblitz.com/edit/tanstack-router-txrzyl?file=app%2Froutes%2Findex.tsx
2. Press `Open Preview in new tab` and press `Connect to project` - notice that you get automatically redirected from `/` to `/?step=a`.
3. Try navigate to `/?step=b`.

### Expected behavior

That I stay on `/?step=b` as it conforms to the Zod schema provided under `validateSearch`.

### Platform

- OS: [e.g. macOS, Windows, Linux] macOS
- Browser: [e.g. Chrome, Safari, Firefox] Chrome
- Version: [e.g. 91.1] Version 126.0.6478.183 (Official Build) (arm64)

**Comment by lithdew** [comment]
Just to clarify, I tested to see if this bug can be reproduced on Tanstack Router and it cannot be reproduced. This issue only occurs with Tanstack Start.

**Comment by schiller-manuel** [comment]
working example for router:

https://stackblitz.com/edit/tanstack-router-f9yax9?file=src%2Froutes%2Findex.tsx&preset=node
