### ISSUE TITLE
If I create a preview of a file using URL.createObjectURL it will match my root and reload the app.

### ISSUE THREAD

**Issue by jadedevin13** [TanStack/router#2291]
### Which project does this relate to?

Router

### Describe the bug

Weirdly tanstack matches the routes that are prefixed with blob:. I tried to create a preview for the user with URL.createObjectURL and it generated blob:http://localhost:3000/5824e840-d000-4cc5-b497-0e979e9a6412. It works and shows the video or the image but I can see my server refetching all react-queries as if the route exists. I have useQueries in my __root

### Your Example Website or App

NA

### Steps to Reproduce the Bug or Issue

NA

### Expected behavior

Exclude blob: and other url prefixes from matching the routes.

### Platform

macOS Chrome

**Comment by schiller-manuel** [comment]
Can you please provide a minimal complete example by forking one of the examples on stackblitz?

**Comment by jadedevin13** [comment]
I think this is an issue with vidstack. I can't reproduce it with just a plain video element. Closing this.
