### ISSUE TITLE
routeTree.gen not generated when setting up project

### ISSUE THREAD

**Issue by fiskpatte** [TanStack/router#2296]
### Which project does this relate to?

Router

### Describe the bug

I have set up a new project using Vite/React/Typescript/yarn.
After that I follow the installation and quickstart docs on tanstack.com
I installed router
`yarn add @tanstack/react-router`
Installed Vite plugin and router devtools
`yarn add -D @tanstack/router-plugin @tanstack/router-devtools`
Configured vite plugin by adding TanStackRouterVite() to the plugins array in vite.config.ts
I add the files
   ```
 src/routes/__root.tsx
    src/routes/index.lazy.tsx
    src/routes/about.lazy.tsx
    src/main.tsx
```

The following step is to update the main.tsx and here is instructions:
`Regardless if you are using the @tanstack/router-plugin package or manually running the tsr watch/tsr generate commands from your package scripts, the following file will be generated for you at src/routeTree.gen.ts.`
Hovewer, there is no routeTree.gen.ts generated for me. Am I missing some step?

### Your Example Website or App

notavailable

### Steps to Reproduce the Bug or Issue

1. Create a new project with Vite/React/Typescript using yarn.
2. Install tanstack/react-router `yarn add @tanstack/react-router`
3. Installed Vite plugin and router devtools `yarn add -D @tanstack/router-plugin @tanstack/router-devtools`
No `src/routeTree.gen.ts` is generated when I perform these steps

### Expected behavior

As a developer, I expect routeTree.gen.ts to be generated when I perform the steps above, according to the documentation.

### Platform

- OS: [macOS]

**Comment by ViniciusPilati2005** [comment]
Como você resolveu? Estou com este problema, reinstalei os pacotes da package.lock.json e da node_modules e nada ainda.

**Comment by KartikDatrika** [comment]
@ViniciusPilati2005 
unless we add createRootRoute it won't be generated, i got it from the warnings, now i feel it's true as there won't be tree without the seed or root !

**Comment by ViniciusPilati2005** [comment]
my __root.tsx folder looks like this

```
export const Route = createRootRoute({
  component: () => (
    <>
      <div className="p-2 flex gap-2">
        <Link to="/" className="[&.active]:font-bold">
          Home
        </Link>
        <Link to="/" className="[&.active]:font-bold">
          About
        </Link>
        <Link to="/password-changes" className="[&.active]:font-bold">
          password changes
        </Link>
      </div>
      <hr />

      

      <Toaster />

      <Outlet />
      <TanStackRouterDevtools />
    </>
  ),
})
```

even adding the root file with the necessary dependencies, it does not generate

**Comment by schiller-manuel** [comment]
@ViniciusPilati2005 please create a minimal complete example and open a new issue

**Comment by ivnmaksimovic** [comment]
> ## Steps to Reproduce the Bug or Issue
> 1. Create a new project with Vite/React/Typescript using yarn.
> 2. Install tanstack/react-router yarn add @tanstack/react-router
> 3. Installed Vite plugin and router devtools yarn add -D @tanstack/router-plugin @tanstack/router-devtools
> No src/routeTree.gen.ts is generated when I perform these steps

Step 4 is indeed not documented.
4. `npm run dev`

For me `src/routeTree.gen.ts` was not generated at that step as well, but with helpful message. I did not use default `src/routes` folder, but `src/app/routes`. That can be adjusted by setting `"routesDirectory": "./src/app/routes"` in `tsr.config.json`
