### ISSUE TITLE
config does not recognize custom directory path

### ISSUE THREAD

**Issue by andrewangelle** [TanStack/router#2297]
### Which project does this relate to?

Start

### Describe the bug

Config does not recognize custom directory path

```tsx
import { defineConfig } from '@tanstack/start/config'

export default defineConfig({
  tsr: {
    appDirectory: 'src',
  }
})
```

results in:

```sh
[h3] [unhandled] H3Error: Failed to load url /Users/andrewangelle/code/tanstack-router-app/app/ssr.tsx (resolved id: /Users/andrewangelle/code/tanstack-router-app/app/ssr.tsx) in virtual:$vinxi/handler/ssr. Does the file exist?
```

It's still looking for the files in the `app` directory.

### Your Example Website or App

https://github.com/andrewangelle/tsr-start-bug

### Steps to Reproduce the Bug or Issue

Clone repo repo:
```sh
$ git clone https://github.com/andrewangelle/tsr-start-bug.git
```

Install deps:
```sh
$ pnpm install
```

Run app:
```sh
$ pnpm dev
```

### Expected behavior

The dev server successfully runs

### Platform

- OS: macOS
- Browser: Chrome
- Version: Latest

**Comment by SeanCassiere** [comment]
You'll need to use all of these settings to get it to work with the `./src` directory.

```ts
// app.config.ts
import { defineConfig } from "@tanstack/start/config";

export default defineConfig({
	tsr: {
		appDirectory: "./src",
		generatedRouteTree: "./src/routeTree.ts",
		routesDirectory: "./src/routes",
	},
	routers: {
		client: {
			entry: "./src/client.tsx",
		},
		ssr: {
			entry: "./src/ssr.tsx",
		},
	},
});
```
