### ISSUE TITLE
Ranked Routes does not rank in Firefox in the same manner as other browsers  => Chrome, Safari, Edge

### ISSUE THREAD

**Issue by fetters5** [TanStack/router#231]
**Describe the bug**
Ranked Routes does not rank in the same manner as other browsers such as  Chrome, Safari, Edge.  It will not find a page in the route list where as the other browsers will

**To Reproduce**
1. Go to https://codesandbox.io/s/flamboyant-haze-6l1hin?file=/src/index.tsx
2. If you click on the Auth link in FF it will go to the catch all route if you click on the link in Chrome it goes to the auth route

**Expected behavior**
I would expect FF to sort the routes the same way that the other browsers do

**Screenshots**
Firefox 97.0.1
![image](https://user-images.githubusercontent.com/3276557/156211302-99b9a838-0391-460b-a7bd-58fce35b49a8.png)

Chrome
![image](https://user-images.githubusercontent.com/3276557/156211381-becccb9c-e5b6-416e-8d9b-ef1950df881a.png)

**Desktop (please complete the following information):**
 - OS:  Windows
 - Browser: Firefox
 - Version: 3.3 and 3.6.1

**Comment by obouchari** [comment]
Try removing the forward-slash from the "auth" path, change this from "/auth" to "auth":
```
<Router
      location={location}
      filterRoutes={rankRoutes}
      routes={[
        {
          path: "",
          element: <Wrapper />,
          children: [
            { path: "/", element: <Index /> },
            { path: "posts", element: <PostsIndex /> },
            { path: "*", element: <NotFound /> }
          ]
        },
        { path: "auth", element: <Auth /> }
      ]}
    >
```

**Comment by tannerlinsley** [comment]
We'll be sure to trim slashes in the ranker from here forward.
