### ISSUE TITLE
Error: `rootRouteNode` must not be undefined

### ISSUE THREAD

**Issue by iamyuu** [TanStack/router#2315]
### Which project does this relate to?

Router

### Describe the bug

Previously I was using `@tanstack/react-router@^1.52.5` it works well with options `routeFileIgnorePrefix: '_'`, but after upgrading to the latest version (v1.57.6), it won't generate the file, and showed an error `'rootRouteNode' must not be undefined`

### Your Example Website or App

https://stackblitz.com/edit/github-d4mdlv?file=vite.config.js:L10

### Steps to Reproduce the Bug or Issue

1. update the tsr plugin with options `routeFileIgnorePrefix: '_'`
2. run the CLI/dev server
3. see the error on the terminal

### Expected behavior

As a user, I expected to configure `routeFileIgnorePrefix` whatever I want

### Platform

- OS: macOS 14.6
- Browser: Brave Browser: 128.1.69.162
- Version: v1.57.6

### Additional context

If the value of `routeFileIgnorePrefix` is anything else except `_` and `__` it works

**Comment by lamualfa** [comment]
Same here:

![Image](https://github.com/user-attachments/assets/50a95d35-c27b-4f25-b4f4-f3c7070e8b05)

**Comment by czizzy** [comment]
```
  virtualRouteConfig: {
    "type": "root",
    "file": "__root.tsx"
  }
```
Add this to your tsr config

**Comment by SeanCassiere** [comment]
@lamualfa Yes, the `__root.tsx` file is required. If you were using the virtual file routes, you'd need to define the file as well. We can add a more descriptive error message here.

@iamyuu we'll need to restrict what can be added as a `routeFileIgnorePrefix` to disallow the use of a`"_"` since that would prevent you from using layout routes.

**Comment by czizzy** [comment]
@SeanCassiere I use `__` as `routeFileIgnorePrefix`, and I also encountered this issue with the latest version, `1.57.15`. Is `__` allowed?"

**Comment by Subilan** [comment]
I'm using code based routes and I got this error `Error: rootRouteNode must not be undefined. Make sure you've added your root route into the route-tree. Make sure that you add a "__root.tsx" file to your routes directory.` when building. I then created the `__root.tsx` and found the outcome was not what I expected and more like something under file based routes. I just ignored the error (it's an error!) and checked the built pages, finding it working without flaw.

So it seems the message is unnecessary here and somewhat misleading/confusing as an "error". I think this doesn't deserve an issue to be opened but I would like to share the behavior. Don't know if it's the right place, though.

**Comment by SeanCassiere** [comment]
> So it seems the message is unnecessary here and somewhat misleading/confusing as an "error". I think this doesn't deserve an issue to be opened but I would like to share the behavior. Don't know if it's the right place, though.

Just to be clear on this, regardless of your `routeFileIgnorePrefix` setting, we do expect you to define a root route in your route-tree.

As with all software, eventually code gets changed and/or rewritten - either for performance or feature implementations, and at that point any out-of-scope behaviours _could_ see changes or even be outright disallowed.

We really do recommend sticking to the rules for file-based routing or wiring up your own using [virtual file routes](https://tanstack.com/router/latest/docs/framework/react/routing/virtual-file-routes).
