### ISSUE TITLE
search types as unknown when using zod catch()

### ISSUE THREAD

**Issue by chribjel** [TanStack/router#2376]
### Which project does this relate to?

Router

### Describe the bug

When using the catch function for zod validation of search the types become unknown in navigate functions.

not when fetching the search.

```tsx
const searchSchema = object({
	path: string()
		.refine((arg) => arg.split(".").every((part) => Number.parseInt(part) >= 0))
		.catch("1")
		.default("1"),
	edit: boolean().catch(false).default(false),
});

export const Route = createFileRoute("/")({
	validateSearch: zodSearchValidator(searchSchema),
	component: Index,
});

function Index() {
	const { path, edit } = Route.useSearch();    // type is correct here
	const navigate = Route.useNavigate();

	return (
		<Main className="flex flex-col gap-2">
                                                       {/* edit is unknown here */}
			<Link to={Route.to} search={{ edit: true }}>Edit</Link>
                                                                           {/* edit is unknown here */}
			<Button onClick={() => navigate({ search: { edit: true } })}>Edit</Button>
		</Main>
	);
}
```

### Your Example Website or App

https://stackblitz.com/edit/github-bpozga?file=src%2Froutes%2Fabout.tsx,src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Use zodSearchValidator
2. Use .catch in the schema
3. unknown typing in navigation functions/components

### Expected behavior

I expect the types to be of the type that is available in the useSearch, matching the zod-schema

### Platform

- OS: All
- Browser: All
- Version: All

**Comment by chribjel** [comment]
found this in the zod validator package:
![Image](https://github.com/user-attachments/assets/b722cca3-e8f3-4ed7-9538-609e26576cf4)
https://github.com/TanStack/router/blob/5eff36110353404e7e1acfa244ef74e9ba04e186/packages/router-zod-adapter/src/index.ts#L64

it can be used like so instead of catching yourself
![Image](https://github.com/user-attachments/assets/afd219c6-64a3-44d9-92ad-c237defec836)

But i would still wish that catch would work out of the box

**Comment by schiller-manuel** [comment]
This is covered in our docs: https://tanstack.com/router/latest/docs/framework/react/guide/search-params#zod-adapter

A real solution can only be implemented by zod itself, please check this issue https://github.com/colinhacks/zod/issues/2852 and raise your concerns there.
