### ISSUE TITLE
how to set routes in code-base routing

### ISSUE THREAD

**Issue by tasmeer-naeem** [TanStack/router#2379]
### Which project does this relate to?

Router

### Describe the bug

Uncaught SyntaxError: The requested module '/node_modules/.vite/deps/@tanstack_react-router.js?v=0e4fce94' does not provide an export named 'createRootRoute' (at routes.ts:1:23)

import { createRoute, createRootRoute, createRouter  } from "@tanstack/react-router";      /// getting error in all 3 imports

how to set routes in  code-base routing 

### Your Example Website or App

https://codesandbox.io/p/sandbox/react-typescript-forked-f4q2hp?file=%2Fsrc%2FApp.tsx%3A18%2C1

### Steps to Reproduce the Bug or Issue

go to /categories route
see console error will be shown
on / home route error will be shown here as well

### Expected behavior

it should show pages on respective routes

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SeanCassiere** [comment]
- Your routes file is not in the `src` folder.
- Your route tree hasn't been setup correctlly
```ts
const routeTree = rootRoute.addChildren([home, categories]);
```

---

Please make sure that you check out the examples - [quickstart example](https://github.com/TanStack/router/blob/main/examples/react/quickstart/src/main.tsx)
