### ISSUE TITLE
[Start]: Issues with creating abstractions around `createServerFn`

### ISSUE THREAD

**Issue by juraj98** [TanStack/router#2393]
### Which project does this relate to?

Start

### Describe the bug

I ran into these issues while I was trying to create abstraction around `createServerFn` that validates payload using `zod`. There are two different issues based on how the abstraction is created. These are very simplified examples:

1. Abstraction "around" `createServerFn`:

In this example, `console.log` is executed  before `createServerFn`. The function passed into custom `createServerFnWithConsoleLog` must have explicit "use server" directive.

```typescript
const createServerFnWithConsoleLog: typeof createServerFn = (...args) => {
  console.log("Server function ran");

  return createServerFn(...args);
};

// This works
const helloWithUseServer = createServerFnWithConsoleLog("GET", async () => {
  "use server";
  return 'Hello with "use server"';
});

// This doesn't work
const helloWithoutUseServer = createServerFnWithConsoleLog("GET", async () => {
  return 'Hello without "use server"';
});
```

2. Abstraction "inside" `createServerFn`:

Arguably more common use-case, in this example, the abstraction `console.log`s payload passed to the server function. This doesn't work. When `hello` is called, it throws `ReferenceError: fn is not defined`. I believe `fn` is removed by compiler.

```typescript
function createServerFnWithConsoleLog<
  TMethod extends "GET" | "POST",
  TPayload = undefined,
  TResponse = unknown,
>(
  method: TMethod,
  fn: FetchFn<TPayload, TResponse>
): Fetcher<TPayload, TResponse> {
  return createServerFn(method, async (payload, context) => {
    console.log("Payload:", payload);

    return await fn(payload, context);
  });
}

const hello = createServerFnWithConsoleLog(
  "GET",
  async ({ name }: { name: string }) => {
    return `Hello ${name}!`;
  }
);
```

Creating this issue as a follow up on a discord conversation with @schiller-manuel.

### Your Example Website or App

https://stackblitz.com/~/github.com/juraj98/tss-abstraction

### Steps to Reproduce the Bug or Issue

Both cases are covered in stackblitz example on different routes. For "use server" issue navigate to `/abstraction-around`. For "ReferenceError" issue navigate to `/abstraction-inside`.

### Expected behavior

Not sure what is the correct solution for this, but there should probably be a way to create abstractions around `createServerFn`.

### Platform

- OS: macOS
- Browser: Chrome 128.0.6613.138
- Start version: 1.58.5
- Router version: 1.58.3

### Additional context

[Link to discord conversation with @schiller-manuel about this issue](https://discord.com/channels/719702312431386674/1287499743441977385)

**Comment by SeanCassiere** [comment]
The first issue mentioned is expected, as `start-vite` plugin checks call of `createServerFn` or a variant of it if it was renamed during import.
- https://github.com/TanStack/router/blob/main/packages/start-vite-plugin/src/compilers.ts#L69

Regarding the second issue, what are the results when using the wrappers with the `"use server"` directives added like this?

```diff
// 1.
function createServerFnWithConsoleLog<
  TMethod extends "GET" | "POST",
  TPayload = undefined,
  TResponse = unknown,
>(
  method: TMethod,
  fn: FetchFn<TPayload, TResponse>
): Fetcher<TPayload, TResponse> {
+ "use server"
  return createServerFn(method, async (payload, context) => {
    console.log("Payload:", payload);

    return await fn(payload, context);
  });
}
```

```diff
// 2.
function createServerFnWithConsoleLog<
  TMethod extends "GET" | "POST",
  TPayload = undefined,
  TResponse = unknown,
>(
  method: TMethod,
  fn: FetchFn<TPayload, TResponse>
): Fetcher<TPayload, TResponse> {
  return createServerFn(method, async (payload, context) => {
+  "use server"
    console.log("Payload:", payload);

    return await fn(payload, context);
  });
}
```

**Comment by juraj98** [comment]
> The first issue mentioned is expected, as `start-vite` plugin checks call of `createServerFn` or a variant of it if it was renamed during import.
> 
> * https://github.com/TanStack/router/blob/main/packages/start-vite-plugin/src/compilers.ts#L69
> 
> Regarding the second issue, what are the results when using the wrappers with the `"use server"` directives added like this?
> 
> // 1.
> function createServerFnWithConsoleLog<
>   TMethod extends "GET" | "POST",
>   TPayload = undefined,
>   TResponse = unknown,
> >(
>   method: TMethod,
>   fn: FetchFn<TPayload, TResponse>
> ): Fetcher<TPayload, TResponse> {
> + "use server"
>   return createServerFn(method, async (payload, context) => {
>     console.log("Payload:", payload);
> 
>     return await fn(payload, context);
>   });
> }
> // 2.
> function createServerFnWithConsoleLog<
>   TMethod extends "GET" | "POST",
>   TPayload = undefined,
>   TResponse = unknown,
> >(
>   method: TMethod,
>   fn: FetchFn<TPayload, TResponse>
> ): Fetcher<TPayload, TResponse> {
>   return createServerFn(method, async (payload, context) => {
> +  "use server"
>     console.log("Payload:", payload);
> 
>     return await fn(payload, context);
>   });
> }

Adding `"use server"` into `createServerFnWithConsoleLog` (the first example), changes the error to `Invariant failed: createServerFn must be called with a function that is marked with the 'use server' pragma.`. Adding additional `"use server"`s both inside `createServerFn` and into function that is passed to `createServerFnWithConsoleLog` has no effect. The error will still be `Invariant failed`

Adding `"use server"` into the function inside `createServerFn` (the second example) has no effect. Error is still `ReferenceError: fn is not defined `.

**Comment by SeanCassiere** [comment]
Closing this in favor of Tanner's response here: https://discord.com/channels/719702312431386674/1287499743441977385/1287923861211451486


> You can’t really create abstractions around use server or create server function
> They are extracted
> But you can create utilities for use around them or inside them
> Eg, createServerFn(withStuff(fn))
> Or withClientStuff(createServerFn(fn))
> Once you call create Server Fn or use use server, might as well rip that code right out of context. Its a serialization boundary just like a fetch request
