### ISSUE TITLE
[DEP0147] DeprecationWarning with @tanstack/router-plugin/rspack

### ISSUE THREAD

**Issue by brunosantanarj** [TanStack/router#2461]
### Which project does this relate to?

Router

### Describe the bug

When running `rsbuild build` with the plugin activated, the following alert is triggered in the console:

> (node:4004) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
> (Use `node --trace-deprecation ...` to show where the warning was created)

```ts
// rsbuild.config.ts
import tailwind from "tailwindcss";
import { defineConfig } from "@rsbuild/core";
import { pluginReact } from "@rsbuild/plugin-react";
import { TanStackRouterRspack } from "@tanstack/router-plugin/rspack";

export default defineConfig({
  plugins: [pluginReact()],
  tools: {
    postcss: (_, { addPlugins }) => {
      addPlugins(tailwind);
    },
    rspack: {
      plugins: [TanStackRouterRspack()],
    },
  },
  performance: {
    preconnect: ["https://fonts.googleapis.com", "https://fonts.gstatic.com"],
  },
});
```

Versions:
```
Node: v20.17.0
PNPM: 9.12.0
"@rsbuild/core": "^1.0.1",
"@tanstack/router-plugin": "^1.58.12",
"@tanstack/react-router": "^1.58.17",
```

I opened this issue here because without the plugin activated it doesn't trigger the error.

Thanks.

### Your Example Website or App

local

### Steps to Reproduce the Bug or Issue

1. Access https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing#configuration-with-rspackrsbuild
2. Follow documentation

### Expected behavior

No warnings in console

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/cffde66c-f90a-4d18-af60-af9f952a901c)

### Platform

- OS: MAC
- NODE
- Version: 20.17.0

**Comment by schiller-manuel** [comment]
this seems to come from unplugin:

https://github.com/unjs/unplugin/blob/73322a9f66359b984f6c326a604c0b15f2489614/src/rspack/utils.ts#L29

so I guess it would be best to create the issue there

**Comment by rminami** [comment]
You can silence this by setting your build script to
```
NODE_OPTIONS=--no-deprecation rsbuild build
```
