### ISSUE TITLE
Routes don't update internally when new routes passed to Router

### ISSUE THREAD

**Issue by jonathanbutler7** [TanStack/router#247]
### Describe the bug

This may be more of an optimization than a bug, but I wanted to log the issue here because it took me some time to figure out what was going on.

If the user tries to navigates directly to /payments (by typing into /payments into the address bar and pressing the return key), no route match is found, so the * page renders.

### Your Example Website or App

https://codesandbox.io/s/nice-benji-1i9jrw?file=/src/index.tsx

### Steps to Reproduce the Bug or Issue

Navigate directly to /payments by typing /payments into the address bar and pressing the return key. No route match is found, so the * page renders.

This is because, upon page load, the private routes are not available yet, since the user's auth status has not yet been set to true.

Once the user is authed, if the user clicks a link to a private route from within the app UI, the correct route matches.

### Expected behavior

When the routes that are passed to Router change, React Location doesn’t check to see if there’s a more direct match than a catch all for the current route. I would expect that if the routes that are given to it change, it should run a quick check to see if the current route is affected. If there’s a different match, it should change the route the user is on. If it’s the same, then nothing else needs to be done.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 99.0.4844.74

**Comment by Angelelz** [comment]
I encountered this issue and solved it in a somewhat unconventional way.

if you change your codepen lines from 21 to 32 to this:

```javascript
  const [isAuthed, setIsAuthed] = useState(false);
  // assume user is not authed, render public routes by default
  // const [activeRoutes, setActiveRoutes] = useState(publicRoutes);

  let activeRoutes =  publicRoutes;

  if (isAuthed) {
    activeRoutes = privateRoutes;
  }
  /**
   * the purpose of the delay is to mimic an api call
   * or localStorage check to see if a user is authed
   */
  setTimeout(() => {
    setIsAuthed(true);
    // setActiveRoutes(privateRoutes);
  }, 1000);
```

I just commented out your activeRoute state and let it be just a variable.
You end up with only one state. And you rely on it to update your routes.

Anyway, I think this a great package but it should expose a better way to handle protected routes!

**Comment by gloomweaver** [comment]
Should this be addressed? if so I would like to help.

**Comment by tannerlinsley** [comment]
With the latest move to TanStack Router, routes are now meant to be very static. We can play with adding dynamic routes if you'd like, but for now, it's not the happy path.
