### ISSUE TITLE
Payload passed incorrectly to server function when called from another server function

### ISSUE THREAD

**Issue by lucasthevenet** [TanStack/router#2481]
### Which project does this relate to?

Start

### Describe the bug

When calling a server function from another server function, the payload is passed incorrectly, wrapped in an object shaped like `{ method: "POST", payload: ... }`

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-t7wcgv?file=app%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Go to app/routes/index.tsx route
2. Press "test server function" button
3. Compare the results of the function being called directly and the function being called inside another server function

### Expected behavior

As a user, I expect the payload to be the same calling the function directly and calling the function from another function

### Platform

- OS: macOS
- Browser: Edge
- Version: 128.0.2739.79

**Comment by SeanCassiere** [comment]
This looks to be related to https://github.com/TanStack/router/issues/1866.

Keeping this on hold for the time being as the server function rewrite is underway. This rewrite has implications on how the endpoint's input is accepted and passed to another.

Once the rewrite has been released, this scenario shall be retested and either closed or have further changes made to ensure this works as expected.
