### ISSUE TITLE
Match Error with useSearch inside a route nested in a layout and pathless route group

### ISSUE THREAD

**Issue by Hazihell** [TanStack/router#2501]
### Which project does this relate to?

Router

### Describe the bug

Using a layout inside a pathless route group directory breaks useSearch. After calling the hook inside the route or the layout, with the correct from value, it gives the error: `Invariant failed: Could not find an active match from '/_layout/about'. `

I also noticed that the from property type is inferred as **__layout/about_**, which isn't good for consistency, as the from property in the Link component is inferred as **_/about_**.

### Your Example Website or App

https://stackblitz.com/edit/github-qwwxnn?file=src%2Froutes%2F(test)%2F_layout.about.tsx

### Steps to Reproduce the Bug or Issue

1. Go to https://stackblitz.com/edit/github-qwwxnn?file=src%2Froutes%2F(test)%2F_layout.about.tsx
2. Click on About Link.
3. See the error on the page.

### Expected behavior

The useSearch hook should infer the same from types as the Link component, and it should not throw an error.

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/48e76382-a900-4d30-83f3-635088a2b735)

### Platform

- OS: [Windows]
- Browser: [Chrome]
- Version: [^1.64.0]

**Comment by SeanCassiere** [comment]
Runtime `routeId` is incorrect.

![Image](https://github.com/user-attachments/assets/8ad19289-16a2-4968-82c7-c776cfa82a9e)

**Comment by MarkArchitect** [comment]
I have the same error  when using useLoaderData, useMatch.

**Comment by schiller-manuel** [comment]
route groups are now not removed from the route id anymore to be consistent between types and runtime.

**Comment by roger-serra-leanon** [comment]
@schiller-manuel , thanks a lot for the quick fix!

For consistency, can’t we have the same values inferred in the `from` prop of the `Link ` component? Using `'/(test)/_layout/about`' instead of just `'/about'` in `useSearch` feels odd.

![Image](https://github.com/user-attachments/assets/f0162183-6e52-45e5-86c4-6357cd86fff4)

**Comment by roger-serra-leanon** [comment]
> while both are named `from`, they referenced different concepts. `from` in `useSearch` is a route **id**
> 
> whereas `from` in `<LInk>` is a route **path**
> 
> btw, you can also use `Route.useSearch()` so you don't have to type this out.

I'm familiar with `Route.useSearch()`, but I usually need it outside the route file, and managing its exports/imports isn't ideal because they're default and have generic route names. I'm also trying to avoid circular dependencies, if that makes sense.

Thanks for taking time to answer this.
