### ISSUE TITLE
`componentStack` is not available to `errorComponent` or `defaultErrorComponent`

### ISSUE THREAD

**Issue by absassi** [TanStack/router#2512]
### Which project does this relate to?

Router

### Describe the bug

Even though `info?: { componentStack: string; }` appears in `ErrorComponentProps`, it is never passed to the error component.
The error info with the component stack is captured though, as it is logged to the console as warning and it is passed to `onCatch` and `defaultOnCatch`.

### Your Example Website or App

https://stackblitz.com/edit/github-ktjn1n-i4bu1m?file=src%2Fmain.tsx,src%2Froutes%2Fabout.tsx

### Steps to Reproduce the Bug or Issue

1. Create an error component that attempts to render the component stack:

```tsx
function CustomErrorComponent({ error, info }: ErrorComponentProps) {
  return (
    <div>
      <p>{error.message}</p>
      <div>
        <b>Stack:</b>
        <pre>{error.stack}</pre>
      </div>
      <div>
        <b>Component stack:</b>
        <pre>{info?.componentStack}</pre>
      </div>
    </div>
  );
}
```

2. Register it as `defaultErrorComponent`:

```tsx
const router = createRouter({ routeTree, defaultErrorComponent: CustomErrorComponent });
```

3. Throw an error in some route.
4. Navigate to that route and see that the component stack is undefined.

In the linked MCVE example, the about route is throwing an error. Opening the link and navigating to the About page will reproduce this.

### Expected behavior

The same `errorInfo` with the component stack that is passed to `onCatch` as its second parameter would also be passed to the error component in the `info` prop.

### Platform

- OS: WSL
- Browser: Edge
- Version: 1.64.0

**Comment by schiller-manuel** [comment]
Since setting state in `componentDidCatch` is deprecated, we cannot do much here, as `getDerivedStateFromError` does not expose `errorInfo`
https://react.dev/reference/react/Component#componentdidcatch-caveats

The best "solution" would probably be to remove `errorInfo` from `ErrorComponentProps`

**Comment by SeanCassiere** [comment]
Added this removal of errorInfo onto the v2 checklist. Closing this for now.
