### ISSUE TITLE
For directory route i have to escape $ sign for auto complete to work but app breaks

### ISSUE THREAD

**Issue by mrlectus** [TanStack/router#2532]
### Which project does this relate to?

Router

### Describe the bug

I found out that I have to escape the $ sign on Linux for the autocomplete to work if I am using Directory Routes. That is, if the file name starts with a $ sign. This is not mentioned anywhere in the documentation. If a route /posts/$postId, and I create a folder posts and under it create a file $postId this throws errors but creating a file \\$postId makes auto complete work but breaks the code

### Your Example Website or App

Nil

### Steps to Reproduce the Bug or Issue

On Linux try to create a filename starting with $

### Expected behavior

I expect it to work without escaping?

### Platform

- OS: [Linux]
- Browser: [Firefox]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment]
what exactly throws an error? please provide all necessary reproduction steps

**Comment by mrlectus** [comment]
> what exactly throws an error? please provide all necessary reproduction steps

I am closing this now, as restarting the editor fixed everything.
