### ISSUE TITLE
Error component's `reset()` does not retry the route

### ISSUE THREAD

**Issue by nstepien** [TanStack/router#2539]
### Which project does this relate to?

Router

### Describe the bug

If an error occurs when rendering a component, the router will render the error component, and calling `reset()` will re-render the component. This works great.

But if an error occurs in `beforeLoad`/`loader`/`validateSearch` or maybe other functions, then calling `reset()` will not try to run the route again, if that makes sense.

### Your Example Website or App

https://stackblitz.com/edit/github-c2wsaf?file=src%2Fmain.tsx,src%2Froutes%2Fabout.tsx

### Steps to Reproduce the Bug or Issue

1. Open About page until the error component is rendered (at random)
2. Click the `Retry` button

### Expected behavior

I'd expect `beforeLoad` in the example above to run again when clicking the `Retry` button.
Instead, the error is never cleared and the error component is re-rendered.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 129.0.6668.101

**Comment by schiller-manuel** [comment]
`reset` only clears the error, this is covered in the docs:

https://tanstack.com/router/latest/docs/framework/react/guide/data-loading#handling-errors-with-routeoptionserrorcomponent

> If the error was the result of a route load, you should instead call `router.invalidate()`, which will coordinate both a router reload and an error boundary reset:

**Comment by nstepien** [comment]
How can I distinguiosh where the error came from?
Should I always call `router.invalidate()` instead of `reset()`?
Should `reset()` be `undefined` if the error did not come from rendering a component?
Is it possible to only invalidate the route that errored instead of all the active routes?

**Comment by schiller-manuel** [comment]
have a look at the match's `error` ![Image](https://github.com/user-attachments/assets/c57c6b8a-ad89-40b8-a845-8653a4746cad)

>  Is it possible to only invalidate the route that errored instead of all the active routes?
I don't think we have an API for that, but might be nice enhancement to invalidate selected route subtrees

**Comment by nstepien** [comment]
`router.invalidate()` works great, thanks! 👍
I still wish the `reset` prop would be smart enough to know what there is to reset, but I can live with `router.invalidate()`.

**Comment by schiller-manuel** [comment]
I added selective invalidation in https://github.com/TanStack/router/releases/tag/v1.70.0

you can now pass a filter function to `invalidate`
