### ISSUE TITLE
Redirect errors are uncaught

### ISSUE THREAD

**Issue by hahnrobert** [TanStack/router#2554]
### Which project does this relate to?

Router

### Describe the bug

Throwing a redirect in `beforeLoad` won't actually redirect the client but send it to the `errorComponent`.

Expected Behavior:
The client will be sent to the requested page.

Actual Behavior:
The `errorComponent` will be rendered. 

Workaround:
This bug can be worked around by using `<Navigate to="/login" />` as `errorComponent` instead.

### Error Log
```
Uncaught Error: {"message":"Request failed with status 307","body":{"to":"/login","isRedirect":true,"statusCode":307}}
```

### Code
Server Function:
```typescript
// app/lib/auth.ts
export const authStateFn = createServerFn('GET', async (_, { request }) => {
    const { userId } = await getAuth(request)
    if (!userId) throw redirect({to: '/login'})
    return { userId }
})
```

Protected layout:
```tsx
// app/_app.tsx 
import { authStateFn } from '@/lib/auth'
import { SignedIn } from '@clerk/tanstack-start'
import { createFileRoute, Outlet } from '@tanstack/react-router'

export const Route = createFileRoute('/_app')({
  beforeLoad: async () => {
    const { userId } = await authStateFn()
    return { userId }
  },
  component: AppLayout,
})

function AppLayout() {
  return (
      <SignedIn>
        <Outlet />
      </SignedIn>
  )
}
```

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

See code example above.

### Expected behavior

The client will be sent to the requested page.

### Platform

- OS: macOS
- Browser: Chrome
- Version: unsure

**Comment by schiller-manuel** [comment]
fixed in https://github.com/TanStack/router/releases/tag/v1.69.3

**Comment by hahnrobert** [comment]
Awesome thanks @schiller-manuel for the blazing fast response!
