### ISSUE TITLE
getRouteApi types broken

### ISSUE THREAD

**Issue by RobertOstermann** [TanStack/router#2568]
### Which project does this relate to?

Router

### Describe the bug

The `getRouteApi` types recently changed to require folders such as `/(group)` to be included in the id. This seems to break the function.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-vfkfie?file=src%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the stackblitz
2. Click on the "Failing Route" link
3. Notice the error

### Expected behavior

This should work as it was before without errors

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment]
when I run this example locally in vscode, I cannot reproduce this.
![Image](https://github.com/user-attachments/assets/42a7d8e6-f215-4c48-a164-5c166232ee97)

**Comment by RobertOstermann** [comment]
Thats odd, are you seeing it recreate on the stackbliltz I linked? I am seeing this on a project I use TanStack Router with, seems like it was a fairly recent change, but I haven't dug into exactly when this chagned.

**Comment by schiller-manuel** [comment]
have you regenerated  the route tree?
as you can see from my screenshot, `/(guest)/temp/fail` is part of the autocomplete list and works as expected

**Comment by RobertOstermann** [comment]
@schiller-manuel I get this error - `Invariant failed: Could not find an active match from "/(guest)/temp/fail"` on the stackblitz, and the same error on my own project. I have regenerated the route tree. Are you able to view my stackblitz and are you able to see the error there?

**Comment by schiller-manuel** [comment]
oh I only checked the types since I thought that was the error you were having. will check again

**Comment by RobertOstermann** [comment]
Yeah thats my bad. I didn't realize that I forgot to put the specific error in the description.
