### ISSUE TITLE
negative value of number type key in search URL are transformed to string

### ISSUE THREAD

**Issue by jabidof** [TanStack/router#259]
### Describe the bug

See this TSearch type definition:
usersView?: {
	m?: number;
}

This URL will reach expected result:
`http://localhost:3000/abt_1593420797181?usersView=~(m~2)
`
`m=2` (number) as expected
`http://localhost:3000/abt_1593420797181?usersView=~(m~-7)`
`m="-7"` (string) not as expected or?

Thanks for any feedback.

### Your Example Website or App

none

### Steps to Reproduce the Bug or Issue

See bug descriptoin

### Expected behavior

Keep type definition in TSearch for URL search results.

### Platform

- any

**Comment by tannerlinsley** [comment]
JSURL is optional now in TanStack Router which would make this an upstream bug
