### ISSUE TITLE
Type mismatch in Vite plugins config

### ISSUE THREAD

**Issue by ondrejvelisek** [TanStack/router#2590]
### Which project does this relate to?

Start

### Describe the bug

Hi,

do we know about this? It is even visible on basic TanStart example:
https://tanstack.com/router/latest/docs/framework/react/examples/start-basic

Typescript expects function:
```
  vite: {
    plugins: () => [tsconfigPaths()],
  },
```

But it fails on runtime with "function is not iterable"

```
316 |                     //     ],
317 |                     //   },
318 |                     //   runtime: '@vinxi/react-server-dom/runtime',
319 |                     //   transpileDeps: ['react', 'react-dom', '@vinxi/react-server-dom'],
320 |                     // }),
321 |                     ...(getUserConfig(opts.vite).plugins || []),
                                                     ^
TypeError: Spread syntax requires ...iterable[Symbol.iterator] to be a function
```

This works on runtime:
```
  vite: {
    plugins: [tsconfigPaths()],
  },
```

But TS yells at me.
```
Type 'Plugin<any>[]' is not assignable to type '(...args: unknown[]) => PluginOption[]'.
  Type 'Plugin<any>[]' provides no match for the signature '(...args: unknown[]): PluginOption[]'.ts(2322)
⚠ Error (TS2322)  | 
```

### Your Example Website or App

https://tanstack.com/router/latest/docs/framework/react/examples/start-basic

### Steps to Reproduce the Bug or Issue

1. go to https://tanstack.com/router/latest/docs/framework/react/examples/start-basic
2. open app.config.ts file
3. see TS error

### Expected behavior

Not sure if function or simple array is correct. But TS and runtime should be in sync.

### Platform

- OS: macOS
- Browser: Chrome
- Version: "^1.73.1" (AFAIK it worked on 1.65.0)

### Additional context

Workarounds:

1. Use simple array and disable TS for the line

or

2. There are 3 places in TanStart lib code which can be updated. Like this:
`...(getUserConfig(opts.vite).plugins || []),` => `...(getUserConfig(opts.vite).plugins() || []),`
 (Not sure about other consequenes)

**Comment by schiller-manuel** [comment]
This change was announced here: https://github.com/TanStack/router/discussions/2403

the array format is correct. did you update all dependencies?

**Comment by ondrejvelisek** [comment]
Oh boy. No idea why, but I just opened the project today and it dissabpeared. Probably som old dep was holding for some reason.

I cant see the problem in the example either. :O which is even weirder. :D 

Anyway. Thanks for pointing me. Im closing this.

**Comment by sinasab** [comment]
Currently seeing this issue on the current start-basic example! https://tanstack.com/router/latest/docs/framework/react/examples/start-basic
![Image](https://github.com/user-attachments/assets/3eb78d84-e7e6-4209-9de9-eb850a8a96ea)

**Comment by timbo-tj** [comment]
Same here!

**Comment by busybox11** [comment]
Here's a userland workaround I used in order to get around it:

```typescript
import {
  defineConfig,
  type TanStackStartInputConfig,
} from "@tanstack/react-start/config";
import viteTsConfigPaths from "vite-tsconfig-paths";

type ViteConfig = TanStackStartInputConfig["vite"];
type PluginOption = Exclude<
  Exclude<ViteConfig, undefined | (() => ViteConfig)>["plugins"],
  undefined
>[number];

export default defineConfig({
  vite: {
    plugins: [
      // this is the plugin that enables path aliases
      viteTsConfigPaths({
        projects: ["./tsconfig.json"],
      }) as PluginOption,
    ],
  },
});
```

This might not be the best solution to achieve a similar result, I made it in 2mns, doesn't cause any type errors anymore and does not seem to impact tsserver's performance. Good enough for me - hope this will be useful to someone!
