### ISSUE TITLE
getRouteApi runtime error with non-nested routes

### ISSUE THREAD

**Issue by Xhale1** [TanStack/router#2595]
### Which project does this relate to?

Router

### Describe the bug

When using a non-nested route, the `getRouteApi` function appears to either have incorrect types or a runtime bug resulting in the error:
```
Invariant failed: Could not find an active match from...
```

### Your Example Website or App

https://stackblitz.com/edit/github-jjvhx7-qdnnpp?file=src%2FPostEditPage.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the reproduction link
2. Click "Post edit (failing)"
3. Observe error
4. Open `PostEditPage.tsx`
5. Comment out line 4, uncomment line 7
6. Observe that the runtime error is gone but a typescript error has been introduced

### Expected behavior

Non-nested routes are correctly typed with `getRouteApi` and have no runtime error.

### Platform

Reproduced in Stackblitz

**Comment by lhjt** [comment]
Thank you!
