### ISSUE TITLE
useSearch issue: Undefined is not an object (evaluating 'opts.select')

### ISSUE THREAD

**Issue by nathanaelphilip** [TanStack/router#2608]
### Which project does this relate to?

Router

### Describe the bug

There seems to be an issue with this line of code: https://github.com/TanStack/router/blob/5cc2f9f1b0cb6b7ca4d2f19382b3f08d6f3daa60/packages/react-router/src/useSearch.tsx#L35

I didn’t get this error a few days ago. If I override the `select` option, it works. It seems like useParams also has the same issue.

### Your Example Website or App

I can’t share

### Steps to Reproduce the Bug or Issue

I’m not sure how to reproduce other than install the package and try using the useSearch hook.

### Expected behavior

I shouldn’t get that error.

### Platform

- OS: macOS
- Browser: Safari
- Version: 1.74.4
- Node: 22.7.0

**Comment by nathanaelphilip** [comment]
If I change the code (in Chrome) to `opts?.select` it seems to work fine.

**Comment by schiller-manuel** [comment]
`useSearch` (and `useParams`) have a mandatory `opts` param, so you cannot just call `useSearch()`

**Comment by msantic** [comment]
In docs, it's still marked as optional https://tanstack.com/router/latest/docs/framework/react/api/router/useParamsHook

**Comment by schiller-manuel** [comment]
@msantic PRs are always welcome to fix docs
