### ISSUE TITLE
`createLink` produces `<a>` with incorrect `href`

### ISSUE THREAD

**Issue by lislon** [TanStack/router#2612]
### Which project does this relate to?

Router

### Describe the bug

When using `createLink` utility (example from https://tanstack.com/router/latest/docs/framework/react/guide/custom-link), the HTML URLs don't have the correct `href` and do match the URL where user is navigated when it's clicked

### Your Example Website or App

https://stackblitz.com/edit/github-7kxypo-h2pd55?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

Open reproducer and observe the difference between link generated by `createLink` and original `<Link>`.

```
      <NavigationLink
        from={'/'}
        ref={ref1}
        to={'/$queueType/$orderId'}
        params={{ queueType: 'typeA', orderId: 'order1' }}
      >
```

Produce:
```
    <a from="/" href="/"...>
```

### Expected behavior

Expected html:
```
  <a href="/typeA/order1">
```

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/79565ec5-7a49-41ff-af89-feb95293f85b)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment]
The docs were recently updated, see https://github.com/TanStack/router/pull/2506
please check if this helps

**Comment by lislon** [comment]
Yes, now it make sense. The `<Link` is not supposed to be inside `createLink` and we have to use `<a` or custom element. Thank you
