### ISSUE TITLE
Feature request: Make it possible to configure your own line ending or prettier config for generated routes files with the TanStackRouterVite

### ISSUE THREAD

**Issue by ThijsOnGitHub** [TanStack/router#2619]
### Which project does this relate to?

Router

### Describe the bug

When I create an route or I change the name of an file in the routes folder, the files gets changed to add the template code or change the route's path. This works great, however the line ending changes to LF while we use in our project and CRLF. When I look at the code I see that prettier is used to format the code, and you pass certain configs to prettier, however I can't change the line endings. Would it be possible to config your own line endings in the  config? And maybe it would be nice to pass your own prettier config, to format it to your own wishes.

https://github.com/TanStack/router/blob/9eac0f09e23d51e4a56a0d6b9bf41006d10ec29d/packages/router-generator/src/generator.ts#L67-L71 

### Your Example Website or App

This is using the file-based routing with custom settings
https://stackblitz.com/github/tanstack/router/tree/main/examples/react/quickstart?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Start Vite (with the TanStackRouterVite plugin configured)
2. Create an file in the routes folder 
    - You now have an file with template code and the line ending is changed to LF
  
**Other scenario where line ending is changed**
1. start Vite (with the TanStackRouterVite plugin configured)
2. Change the name of an file in the routes folder
    - The file is now in the LF format

### Expected behavior

As a user, I want to configure the line ending of the generated code by the TanStackRouterVite plugin, so it's conform my own prettier config

### Platform

- OS: Windows
- Browser:  Chrome

**Comment by schiller-manuel** [comment]
we stopped adding config options to the generator that affect code formatting.
we came to the conclusion that the file should just be ignored by whatever linter / formatter you use.
most likely, all formatting options will be removed in the next major version

**Comment by AnderssonPeter** [comment]
While i get that this file should be ignored, our `.gitattributes`
```
* text=auto eol=crlf
```
This causes git to detect a difference every time this file is generated..

So every time we switch branch we first have to stop the vite process, undo the changes and then switch branch, restart vite and so on..

It would be a huge timesaver if we could change linebreaks..

**Comment by rLindorfer** [comment]
@schiller-manuel 
And what about detected changes from CRLF to LF when this file is pushed into a GIT repository?
We checkout with CRLF line endings from our GIT repository, but the generator changes it back to LF.
How should we handle this?

**Comment by spider853** [comment]
Same issue, it's super annoying to have this file always checked out because of CRLF... needs a way to normalize the EOL...

**Comment by kopyl** [comment]
@schiller-manuel why the hell did you think it was a good idea to remove the configuration?

**Comment by schiller-manuel** [comment]
see https://github.com/TanStack/router/issues/2619#issuecomment-2430198179

also, watch your language please

**Comment by kopyl** [comment]
@schiller-manuel it does not answer this:

https://github.com/TanStack/router/issues/2619#issuecomment-3500988331

**Comment by DeadRobotDev** [comment]
> we came to the conclusion that the file should just be ignored by whatever linter / formatter you use

@schiller-manuel I think this would be okay if it just impacted `routeTree.gen.ts`, but it impacts files I'm working on within the `routes` directory.

And, as pointed out above:

> And what about detected changes from CRLF to LF when this file is pushed into a GIT repository?
> We checkout with CRLF line endings from our GIT repository, but the generator changes it back to LF.
> How should we handle this?

Considering formatting is currently offloaded to Prettier and `.editorconfig` is respected by a majority of editors, would it make sense to support the same properties they do, if nothing else?

- end_of_line
- indent_style
- indent_size/tab_width
- max_line_length

**Comment by schiller-manuel** [comment]
@DeadRobotDev can you please explain in more detail how route files are affected?

**Comment by DeadRobotDev** [comment]
Apologies, it might be a seperate issue.

If I start with the following, note the `;` after `return`:
```tsx
import { createFileRoute } from '@tanstack/react-router';

export const Route = createFileRoute({
	component: App,
});

function App() {
	return (
		<>
			<p>Hello, world!</p>
		</>
	);
}
```

I get the following, with trailing `^M`, after saving:
```tsx
import { createFileRoute } from '@tanstack/react-router';

export const Route = createFileRoute('/')({
	component: App,
});

function App() {
	return (
		<>
			<p>Hello, world!</p>
		</>
	)
}
```

If I remove the `;` after `return` before saving, I don't get the trailing `^M`.

I have disabled both `biome` and `ts_ls` in my Neovim config. I also tried in Notepad++.

Edit: I get the same behaviour if I rename the file. With the `;`, it adds the trailing `^M`.

**Comment by DeadRobotDev** [comment]
Sorry, the above does appear to be a seperate issue: https://github.com/TanStack/router/issues/7163
