### ISSUE TITLE
Start Document Components to not spread props to child html tag (Html, Head, Body) etc

### ISSUE THREAD

**Issue by drew-dulgar** [TanStack/router#2626]
### Which project does this relate to?

Start

### Describe the bug

The document components as part of @tanstack/start do not spread to children. That means for Html, Head, Body elements we cannot set lang="en", or unique data attributes. 

For now, I have worked around it by replacing what is rendered with the attributes i need, but obviously this should be applied to the component itself..

RootDocument.jsx (how I should be able to use it)
```js
const RootDocument = ({ children }) => (
  <Html lang="en" data-mantine-color-scheme="light">
    <Head>
      <Meta />
    </Head>
    <Body>
      {children}
      <Scripts />
    </Body>
  </Html>
);

export default RootDocument;
```

server-entry.jsx (have to replace html tag with the attributes expected from RootDocument)
```js
const html = ReactDOMServer.renderToString(
    <StartServer router={router} />
  );

  // Temp fix until <Html> tag supports passing props to the html element in src/RootDocument
  const fixedHtml = html.replace('<html>', '<html lang="en" data-mantine-color-scheme="light">');
```

### Steps to Reproduce the Bug or Issue

1. use tanstack start Html component
2. give it any attribute

### Expected behavior

props passed to Html should be included in the html tag after render

### Screenshots or Videos

Without fix:
![Image](https://github.com/user-attachments/assets/f98df7fa-7a39-41d9-ad01-0de03190e874)

With fix:

![Image](https://github.com/user-attachments/assets/6b9902fd-1de1-437c-8b11-34e143bcc0dc)

### Platform

- OS: [Linux Mint]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: "@tanstack/start": "^1.76.1"

**Comment by mackehansson** [comment]
This is a must to comply with WCAG: https://www.w3.org/WAI/WCAG21/Techniques/html/H57.html

**Comment by SeanCassiere** [comment]
We'll be dropping these custom components.

**Comment by SeanCassiere** [comment]
With the release of [v1.80.6](https://github.com/TanStack/router/releases/tag/v1.81.6), these custom components have been dropped.

This breaking change has been listed in the alpha breaking changes [discussion thread](https://github.com/TanStack/router/discussions/2403).
