### ISSUE TITLE
HMR not working in TanStack Start projects

### ISSUE THREAD

**Issue by aretrace** [TanStack/router#2630]
### Which project does this relate to?

Start

### Describe the bug

Hot Module Reloading is not working for TanStack Start when editing files outside of `routes` directory.

### Your Example Website or App

https://github.com/TanStack/router/tree/main/examples/react/start-basic

### Steps to Reproduce the Bug or Issue

1. Clone https://github.com/TanStack/router/tree/main/examples/react/start-basic
2. pnpm i
3. pnpm dev
4. Navigate to localhost:3000/this-route-does-not-exist
5. Edit app/components/NotFound.tsx
6. 😢

### Expected behavior

localhost:3000/this-route-does-not-exist should have automatically reloaded when app/components/NotFound.tsx was edited and saved.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 129

**Comment by schiller-manuel** [comment]
HMR is being worked on, we already have https://github.com/TanStack/router/issues/1992
