### ISSUE TITLE
@tanstack/start ignores vite.ssr.noExternal from app.config

### ISSUE THREAD

**Issue by ValeraS** [TanStack/router#2663]
### Which project does this relate to?

Start

### Describe the bug

The framework ignores user's `vite.ssr.noExternal` configuration from app.config.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-bqhlm4?file=app.config.ts

### Steps to Reproduce the Bug or Issue

https://github.com/TanStack/router/blob/82121880c0c3f0dcd9654a58479adbcae208f520/packages/start/src/config/index.ts#L475-L479

### Expected behavior

The framework takes into account `vite.ssr.noExternal` configuration from `app.config`.

### Platform

- Version: @tanstack/start@1.77.5

**Comment by schiller-manuel** [comment]
do you want to provide a PR for this?

**Comment by ValeraS** [comment]
Yes, sure.
