### ISSUE TITLE
When Router.basepath matches, it rewrites the URL in the same letter casing

### ISSUE THREAD

**Issue by sethlivingston** [TanStack/router#2672]
### Which project does this relate to?

Router

### Describe the bug

When `Router.basepath` matches the route but with a different case, the navigation succeeds but the basepath gets rewritten in the URL.

### Your Example Website or App

https://github.com/sethlivingston/tanstack-router/blob/862fe551ff139eacca86fa25eb6dbcbc9c84ef23/app/client.tsx#L7

### Steps to Reproduce the Bug or Issue

1. Set Router.basepath to `abc`
2. Navigate to `/aBC/...`
3. Note the URL gets rewritten to `/abc/...` instead of `/aBC/...`

### Expected behavior

As a user, I expect the URL to match the case as I entered it when I navigate.

### Platform

- OS: Windows
- Browser: Edge
- Version: 1.77.5

### Additional context

Related to the work done in #2637

**Comment by SeanCassiere** [comment]
This is something that's been there prior to the fixed applied for #2637.

**Comment by SeanCassiere** [comment]
After some investigation, this looks to be part of the browser's behaviour.

This same behaviour persists even in a sandbox using Remix's React Router - https://stackblitz.com/edit/github-tvepzp?file=README.md

Closing this.

If anyone in the future runs into this and has a possible solution, please create a new issue and/or PR referencing this issue.
