### ISSUE TITLE
ScrollRestoration doesn't reset the scroll position when the search params change since 1.77.3

### ISSUE THREAD

**Issue by GuillaumeLaroucheUQAT** [TanStack/router#2691]
### Which project does this relate to?

Router

### Describe the bug

The `<ScrollRestoration />` component no longer reset the scroll position when the search params change. This doesn't affect the path params.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-7afegt?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Scroll to the bottom of the page
2. Click on the "Next page" button
3. The search param is updated but the scroll position doesn't reset

### Expected behavior

As a user, I expected  the scroll position to be reset when the search params change like the path params.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 130.0

**Comment by FelixWiecz** [comment]
Any updates on this one @tannerlinsley ?

**Comment by Joshuan92** [comment]
Hi, @tannerlinsley is there a possibility to keep the behavior, before this changes? In our project, we want to stay on the same scroll position, when the parameters change. I have tried the variable 'resetScroll: false: on the navigate call, but it does not affect the behavior.

**Comment by schwartzmj** [comment]
> Hi, [@tannerlinsley](https://github.com/tannerlinsley) is there a possibility to keep the behavior, before this changes? In our project, we want to stay on the same scroll position, when the parameters change. I have tried the variable 'resetScroll: false: on the navigate call, but it does not affect the behavior.

Same here. `resetScroll={false}` does not appear to work.

If this is a bug, I discovered that if I do a browser refresh on the page in question, the first navigate will retain the scroll position but every navigation after that will jump back to the top of the page.

**Comment by schiller-manuel** [comment]
@Joshuan92  @schwartzmj  can you please open a new issue with a complete minimal example, e.g. by forking one of the existing examples?

**Comment by schwartzmj** [comment]
> [@Joshuan92](https://github.com/Joshuan92) [@schwartzmj](https://github.com/schwartzmj) can you please open a new issue with a complete minimal example, e.g. by forking one of the existing examples?

This example isn't the use case I have (changing search params on the same page), but seems to exhibit the same problem: https://tanstack.com/router/latest/docs/framework/react/examples/scroll-restoration

1. Scroll down on home page
2. Click About (No reset)
3. It should work if it is your first navigation
4. Go back to home page, scroll down again
5. Click About (No reset)
6. Doesnt work

I can create a new issue for this — but want to confirm this is actually broken and I'm not misunderstanding something.
