### ISSUE TITLE
Type safety breaks around Dates and other non standard objects when using server functions

### ISSUE THREAD

**Issue by AlexGaudon** [TanStack/router#2693]
### Which project does this relate to?

Start

### Describe the bug

Start Server Functions don't respect TanStack Router specified transformers.

See pictures below:

SuperJSON is specified
![Image](https://github.com/user-attachments/assets/89bd5844-9c9a-4ef1-ac67-73e5ba39fcc5)

Function returns a `Date`, with the proper type
![Image](https://github.com/user-attachments/assets/c86418cf-30ea-48b9-9c09-439ec22d46ba)

Loader gets the incorrect type (the actual value is just a stringified date)
![Image](https://github.com/user-attachments/assets/97a6035f-a2cb-429e-9e45-5a1a3856fb9e)

### Your Example Website or App

https://github.com/AlexGaudon/start-date-repro

### Steps to Reproduce the Bug or Issue

1. Clone the repo
2. Run `bun install`
3. Run `bun --bun run dev`
4. Navigate to http://localhost:3000 and observe the error

### Expected behavior

As a user, I expect server functions to automatically conform to the transformer specified.

### Platform

- OS: macOs
- Browser: Chrome + FireFox
- Version: latest

**Comment by aretrace** [comment]
I think a future test suite with various serializers (e.g., [Rich-Harris/devalue](https://github.com/Rich-Harris/devalue)) would be a good idea.

**Comment by SeanCassiere** [comment]
This should be getting addressed in the server functions PR.

**Comment by AlexGaudon** [comment]
Just for clarity, are you talking about https://github.com/TanStack/router/pull/2513

**Comment by SeanCassiere** [comment]
Added onto the backlog for Start related tasks.
