### ISSUE TITLE
`deps` type is not inferred when `loaderDeps` is defined below `loader`

### ISSUE THREAD

**Issue by dcgauld** [TanStack/router#2699]
### Which project does this relate to?

Router

### Describe the bug

The property order of the `loaderDeps` function vs the `loader` function within `createFileRoute` seems to affect whether the correct type is inferred within the `deps` parameter of `loader`.

When `loaderDeps` is defined below `loader`, the type of `deps` within the `loader` method is `{}`. However, when `loaderDeps` is defined above `loader`, the type seems to correctly pull through.

I'm not sure whether this is expected or a TypeScript quirk, but it feels like this might trip others up.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-mgoghq?file=src%2Froutes%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Open Stackblitz link.
2. Notice that the type of `deps` within the `loader` method is `{}`.
3. Move `loaderDeps` definition to above `loader.
4. Notice that the type is inferred correctly.

### Expected behavior

As a user, I expect the type of `deps.test` within the `loader` function to be inferred from `loaderDeps` correctly, irrespective of the order in which `loader` and `loaderDeps` are defined.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 1.77.8

**Comment by schiller-manuel** [comment]
this is a typescript limitation. we added an eslint rule specifically for this, see https://tanstack.com/router/latest/docs/eslint/create-route-property-order
