### ISSUE TITLE
Links with search params are not shown as active until after a rerender

### ISSUE THREAD

**Issue by allan-cannon** [TanStack/router#2714]
### Which project does this relate to?

Router

### Describe the bug

Link components that navigate to a route with search params do not appear as active until something triggers a rerender (e.g. an event like a click). I ran into this in my app and was able to reproduce it in a minimal app.

I modified the minimal example to add a posts route that displays a list of post titles and a post details route that displays the post. The selected post is identified with a search param. Navigating to the post details route via the posts button or refreshing the page when on the post details route will both cause no links to be active even though one is active.

### Your Example Website or App

https://stackblitz.com/edit/github-dgstnf?file=src%2Froutes%2Fposts.tsx

### Steps to Reproduce the Bug or Issue

1. Click on the home button
2. Click on the posts button
3. Notice no post link is active
4. Notice the default post is displayed
5. Click on one of the post links
6. Notice the selected post link is active
7. Refresh the page
8. Notice the post link is no longer active even though it is still selected (post is displayed)

### Expected behavior

I would expect the link to be active any time it matches the current route.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 130

**Comment by schiller-manuel** [comment]
This is not a router bug.
`post.id` is not a string but a number (see `typeof` log).

With 

```tsx
 search={{ postId: String(post.id) }}
```

the link will be marked as active.

see: https://stackblitz.com/edit/github-dgstnf-ti65vl

**Comment by schiller-manuel** [comment]
It seems to work for me, but maybe I am looking at the wrong thing. https://github.com/user-attachments/assets/ad94544d-f1ea-4a17-aed3-fe24a809c3e7
please describe what behavior you are looking for
