### ISSUE TITLE
The symbol "inWebWorker" has already been declared (TurboRepo)

### ISSUE THREAD

**Issue by Emyboy** [TanStack/router#2718]
### Which project does this relate to?

Router

### Describe the bug

![Image](https://github.com/user-attachments/assets/e856e379-5cd0-4a59-a482-aef33d6696ca)

I am currently running vite  react-ts in a Turbo Repo project.
Once I setup tan stack router with file-based routing following the docs [here](https://tanstack.com/router/latest/docs/framework/react/quick-start) I get the above error.

$ node -v
v20.10.0

$ npm -v
10.2.3

"vite": "^5.4.10"
"typescript": "~5.6.2",
"react": "^18.3.1",
"react-dom": "^18.3.1",

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

1. Create a turbo repo project
2. cd into the apps directory
3. run `npm create vite@latest my-app -- --template react-ts` to create  a vite project in ./apps
4. cd my-app and setup tanstack router following the guide [here](https://tanstack.com/router/latest/docs/framework/react/quick-start)

### Expected behavior

1. it should display the index.lazy.ts page

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/afc8a680-9ba8-4ac6-9f69-9ab98f4db226)

![Image](https://github.com/user-attachments/assets/8cbfe9bc-2f0a-43b5-a53b-7c0ee4859444)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Emyboy** [comment]
> can you please provide a complete reproducer GitHub repo?

https://github.com/Emyboy/tensillabs

there you go, I made i public.

**Comment by SeanCassiere** [comment]
@Emyboy you need to remove this instance of the react-refresh plugin since you've already got it set up after the `TanStackRouterVite` plugin.
This is the line that needs to be removed - https://github.com/Emyboy/tensillabs/blob/ab9212931bf1ecc841b10faa1c914a1f26e00e9e/apps/workspace-app/vite.config.ts#L9

**Comment by paulm17** [comment]
@SeanCassiere Link dead.  Next time please provide text solution.

**Comment by SeanCassiere** [comment]
@paulm17 the solution was specific to the OP's repo.

--- 

To summarize, the issue was the removal of a couple lines of code in the OP's `vite.config.ts`.

```diff
// vite.config.ts
import { defineConfig } from 'vite'
import viteReact from '@vitejs/plugin-react';
- import reactRefresh from '@vitejs/plugin-react';
import { TanStackRouterVite } from '@tanstack/router-plugin/vite';

export default defineConfig({
	plugins: [
		viteReact(),
		TanStackRouterVite(),
- 		reactRefresh()
	]
})

```

**Comment by Dax911** [comment]
this error seems to come up again when the `vite.config.ts` says

```ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import viteReact from "@vitejs/plugin-react";
import { TanStackRouterVite } from "@tanstack/router-plugin/vite";

// @ts-expect-error process is a nodejs global
const host = process.env.TAURI_DEV_HOST;

// https://vitejs.dev/config/
export default defineConfig(async () => ({
  plugins: [react(), TanStackRouterVite(), viteReact()],
  esbuild: {
    logOverride: { "this-is-undefined-in-esm": "silent" },
  },
  optimizeDeps: {
    include: ["@tanstack/react-router"],
  },
  define: {
    __dirname: '""',
    __filename: '""',
  },
  build: {
    commonjsOptions: {
      transformMixedEsModules: true,
    },
  },

  // Vite options tailored for Tauri development and only applied in `tauri dev` or `tauri build`
  //
  // 1. prevent vite from obscuring rust errors
  clearScreen: false,
  // 2. tauri expects a fixed port, fail if that port is not available
  server: {
    port: 1420,
    strictPort: true,
    host: host || false,
    hmr: host
      ? {
          protocol: "ws",
          host,
          port: 1421,
        }
      : undefined,
    watch: {
      // 3. tell vite to ignore watching `src-tauri`
      ignored: ["**/src-tauri/**"],
    },
  },
}));
```

It is unclear which should be removed in this case...

removing the standard `react()` plugin seems to have fixed it... not sure if this is the best way.

**Comment by SeanCassiere** [comment]
@Dax911 both `react()` and `viteReact()` refer to the same thing. It's what causing the error since the react-refresh plugin is attempting to transform code that has already been transformed earlier.

**Comment by Dax911** [comment]
Ahhh. Learn something new everyday. Thanks for clarifying.

**Comment by valen-dasilva** [comment]
@SeanCassiere thank you veeeeery much, i couldnt understand how to fix it

**Comment by msalahz** [comment]
Thanks @SeanCassiere, To clarify more 

**The original init `vite.config.ts` file look like the following:**
```ts
import react from '@vitejs/plugin-react

// https://vite.dev/config/
export default defineConfig({
    plugins: [react()],
})
```
**Expected change by TanStack [document](https://tanstack.com/router/latest/docs/framework/react/quick-start#configure-the-vite-plugin) the file should look like the following**

```ts
import {defineConfig} from 'vite'
import viteReact from '@vitejs/plugin-react'
import { TanStackRouterVite } from '@tanstack/router-plugin/vite'

// https://vite.dev/config/
export default defineConfig({
    plugins: [TanStackRouterVite(), viteReact()],
})
```
**The error was caused due to duplicate react-plugin integration if previous codes were merged together as following**
```ts
import {defineConfig} from 'vite'
import react from '@vitejs/plugin-react
import viteReact from '@vitejs/plugin-react'
import { TanStackRouterVite } from '@tanstack/router-plugin/vite'

// https://vite.dev/config/
export default defineConfig({
    plugins: [react(), TanStackRouterVite(), viteReact()],
})
```
