### ISSUE TITLE
Nested parameter routing renders parent route instead

### ISSUE THREAD

**Issue by jackmillward** [TanStack/router#2728]
### Which project does this relate to?

Router

### Describe the bug

When attempting to create a nested route with an identical parameter name as the parent route, Tanstack Router runs the correct route's loader but then renders the parent route's component instead.

### Your Example Website or App

https://stackblitz.com/edit/github-kao7su

I've put a few `console.log` statements in there, so check the devtools and you can see that the parent logs are being called if you call the `/blogs/1/edit` route.

### Steps to Reproduce the Bug or Issue

An example of my project's routing:

```
/blogs
/blogs/$blogId
/blogs/$blogId/edit
```

This resulted in a file layout that looks like:

```
src/routes/blogs/index.tsx
src/routes/blogs/$blogId/index.tsx
src/routes/blogs/$blogId/edit.tsx
```

I also tried with:

```
src/routes/blogs/index.tsx
src/routes/blogs/$blogId.tsx
src/routes/blogs/$blogId.edit.tsx
```

Either way results in the described issue above.

I've put logs in the loaders in `$blogId.tsx` and in `$blogId.play.tsx`. The router, currently, seems to:

1. Hit `$blogId.edit.tsx` and runs through the loader.
2. Goes up to the parent route.
3. Does not run the loader there.
4. Renders the component from the parent route (`$blogId.tsx`).
5. Ignores the component in `$blogId.play.tsx`.

### Expected behavior

I expected that the parent/child was just a way of organising routes and they shouldn't have any interactivity, and calling the child route shouldn't be calling the parent route as it has its own calls.

### Platform

- OS: Linux
- Browser: Firefox, can replicate on any browser
- Version: 1.58 - 1.81.1

### Additional context

The current workaround for this is to have file-based routing set up like so:
```
src/routes/blogs/index.tsx
src/routes/blogs/$blogId.tsx
src/routes/blogs/$blogId_/edit.tsx
```

A second (and not as good) workaround is to change the parameter name:
```
src/routes/blogs/index.tsx
src/routes/blogs/$blogId.tsx
src/routes/blogs/$thisBlogId.edit.tsx
```

**Comment by schiller-manuel** [comment]
the parent route must render an `<Outlet>`. otherwise the child will not be rendered

**Comment by jackmillward** [comment]
> the parent route must render an `<Outlet>`. otherwise the child will not be rendered

Yeah, that's fixed it in the example I've added.

So, the parent/child routing idea is more like a component rather than just a nested route? I've noticed it's now rendering all of the content from the parent route as well as the child routing content.

**Comment by schiller-manuel** [comment]
a child route will contain all of its parents' rendered output. if you don't want that, put that output in leaf routes (such as index route)

**Comment by EugenEistrach** [comment]
> a child route will contain all of its parents' rendered output. if you don't want that, put that output in leaf routes (such as index route)

@jackmillward This was also the thing I confused at the beginning and after I understood how it worked I closed my other issue.

**Comment by LinHanlove** [comment]
Does this mean that there are no nested parent-child routes and everything becomes a tiled route, or do I just want to simply render the content of the sub route page

**Comment by schiller-manuel** [comment]
@LinHanlove not sure what you mean. can you please create a new issue / discussion including an example to explain your questions ?

**Comment by LinHanlove** [comment]
> [@LinHanlove](https://github.com/LinHanlove) not sure what you mean. can you please create a new issue / discussion including an example to explain your questions ?

Firstly, I used code based routing. I created a 'parent component' - 【 Home 】, which can redirect normally. I also created a child component based on home - 【 homeChild 】, and their paths are as follows

-/home - Jump to the Home page

-/home/child - Jump to HomdChild under Home

However, this is incorrect, it cannot be redirected, Not Found

 follows： 
![Image](https://github.com/user-attachments/assets/0b4ccedb-0ac5-447f-bc38-10428b10f78f)
![Image](https://github.com/user-attachments/assets/06d1884e-8d92-4404-94ce-0c8082afcafd)
![Image](https://github.com/user-attachments/assets/4b7660d4-dd1b-4874-977d-6d757f23e29d)
