### ISSUE TITLE
Type inference inconsistency in route params based on declaration order

### ISSUE THREAD

**Issue by OrlovAlexei** [TanStack/router#2748]
### Which project does this relate to?

Router

## Bug Description
There's an inconsistency in type inference for route parameters depending on the order of `loader` and `params` declarations in the route configuration.

### Your Example Website or App

https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbwMZQKYEMaoEoQK5YA0KGWuEMuBqxamO+WUheAzqgArpToisC+cAGZQIIOACIAAjHQA7VrKQBrAPR0kMALSjqUCQCgDq1XAAWqADZhUUI6gAekWHBgBPG3AAqH1AFEARzx0SwAeL24Ac1QYQjgANRC8VAA+OABeOAAKcJSsgEoMtK84Ryw5ABNWbyiYgzg4AH44AEZ6uAAuOAAmQrLUSurcgqLvUodyqoSk1CbWzp725pgoZPauoRD2AG4jEzgjJAgFeFEKDLgSenJKRlQCo3dPLwgKiABJCovFKGA5SLgADJEAB9EEAIx4lVQFQ6Eheb0+En4h2Oiku0DQmioWC4PD4FyuZDuWQQ7Qa0RgeIGt2oHQK6TSZ1i5LgYEwZjhMFeEFYqgAbiFgBVVAASbmIioSQis9n41gdMkNZXKuXsek8ADueN4rEKjOyCFcPM+XS1Or4ADoJR8vuhqgjbXB+IV7RiTqz+DKVZYIOgKrZ6Qg5bqXYylSrlUcTnBBZZhV0fDZAsEwk9UBAhGzuLrrSaKnFHZ80pkVmsVV7WUdwMcafT8uGq2j4CGCZk2Jwc3xSayVSIxHDVDa+XHhWKbUjPfkjCro+jR7DvL4UyFQunM9n5XnJYX8yXXKtUJ6DC7UTG-kcoFjabiu9VMkSGNQeyrKdS5DfUPWDczvaqOVyPJ8n8C7jvm0qsr6-qBqSrYCA2KQRpG7rzkKi5Jv4QSruuWZwdutq7pK+5lkeyENHO8ALgAyisfyRImy5YWmvgbnhE4FnAPx0cRh6en+DRwYqvb-lA6pZOad76mkpLGpKZroNqd74Z8cBukWXynhW-EYjWch1gyiHCeRzabrqFwdharAvmRfaiCAg7DqoIFoWBkqGDZp5GShlFoQxyZMWuLG4Up7GEbaPHlmRFGxmhNG-P8fmYamgU2KxIX5nEXH-BFpHKiinkGNFuhYF4aCzJkzKWv6FQAMJmMAlgVGgchZAA2pe144p28qEBemKoNidyWQAutOhUmegYBgF1UCEnQxJ6NZDTFagpWoEeBUBkgljcLMICvHglizAA5DI8iKOgKjqBgmg6HcUDHYgBgAJB-EwmxILM2CoJEwCKLYT3Pc9K1QF0OGqVNM27M9+VAA

### Steps to Reproduce the Bug or Issue

# Type inference inconsistency in route params across loader and component

## Bug Description
There's an inconsistency in type inference for route parameters that affects both the `loader` and `component`. The issue appears when the `params` declaration comes after the `loader` in the route configuration, and also affects the `useParams` hook in the component.

## Reproduction
```typescript
import {createRoute, createRootRoute, createRouter, useParams} from "@tanstack/react-router"

type TodoId = string & {__branded: "TodoId"}

// Works correctly - params before loader and component
const correctRouteParams = createRoute({
    getParentRoute: () => root,
    path: "todos/valid/$todoId",
    params: {
        parse: (rawParams) => ({ todoId: rawParams.todoId as TodoId }) as const
    },
    loader: ({params}) => {
        const valid: TypeEqual<typeof params.todoId, TodoId> = true // OK
    },
    component: () => {
        const params = useParams({
            from: "/todos/valid/$todoId"
        })
        const valid: TypeEqual<typeof params.todoId, TodoId> = true // OK
    }
})

// Fails - params after loader
const incorrectRouteParams = createRoute({
    getParentRoute: () => root,
    path: "todos/invalid/$todoId",
    loader: ({params}) => {
        const valid: TypeEqual<typeof params.todoId, TodoId> = true // Error
        const validString: TypeEqual<typeof params.todoId, string> = true // OK but shouldn't be
    },
    params: {
        parse: (rawParams) => ({ todoId: rawParams.todoId as TodoId })
    },
    component: () => {
        const params = useParams({
            from: "/todos/invalid/$todoId"
        })
        const valid: TypeEqual<typeof params.todoId, TodoId> = true // Error
        const validString: TypeEqual<typeof params.todoId, string> = true // OK but shouldn't be
    }
})

### Expected behavior

The type should be preserved across all usages within the route definition ?

### Screenshots or Videos

_No response_

### Platform

latest react-router and ts

### Additional context

_No response_

**Comment by schiller-manuel** [comment]
yes, this is a typescript limitation.

this is why we have added an eslint plugin for this

https://tanstack.com/router/latest/docs/eslint/create-route-property-order
