### ISSUE TITLE
Start server function validator only supports the `ValidatorFn` shape (so things like Zod don't work as expected)

### ISSUE THREAD

**Issue by marbemac** [TanStack/router#2759]
### Which project does this relate to?

Start

### Describe the bug

On the Start v1.81.7, the server function validator middleware does not actually support the options described by its typings.

It accepts `AnyValidator` (https://github.com/TanStack/router/blob/main/packages/react-router/src/validators.ts#L62-L67).

However, the actual implementation assumes the validator is the `ValidatorFn` shape (https://github.com/TanStack/router/blob/main/packages/start/src/client/createServerFn.ts#L325-L330).

Looks like `nextMiddleware.options.validator` in that `createServerFn.ts` has the `any` type - any ways to cleanup the types in there as well? If `nextMiddleware.options.validator` were set to `AnyValidator`, the issue would have been surfaced right away.

### Your Example Website or App

NA

### Steps to Reproduce the Bug or Issue

Attempt to use zod, or zod + @tanstack/zod-adapter, with a server function validator and it'll throw.

### Expected behavior

The server function validator supports the validator shapes described in [@tanstack/zod-adapter](https://github.com/TanStack/router/blob/main/packages/react-router/src/validators.ts#L62-L67).

### Platform

- OS: mac
- Browser: chrome

**Comment by schiller-manuel** [comment]
do you have a minimal example that we can use to debug this?

**Comment by schiller-manuel** [comment]
thanks.
yes we will probably reuse this from router.
if you want, you can also create a PR for this

**Comment by marbemac** [comment]
Happy to - will open it shortly. Just wanted to confirm ya'll are OK exporting and re-using that function from router.

**Comment by schiller-manuel** [comment]
exporting it does not really mean it is public API IMO. it's public when we add API docs (which we don't do here)

**Comment by tannerlinsley** [comment]
I just pushed a "mostly" fix for this, but as we've been discussing the adoption of the "Standard Validation" schema internally, it might need to be massaged for backwards compatibility.

**Comment by marbemac** [comment]
Getting familiar with the typings for functions / middleware's will take me longer than I have right now, but just one more pitch to somehow get things like `nextMiddleware.options.validator` typed correctly if possible - even though it's internal, would help to catch this kind of issue in the future especially as there is so much code churn happening in Start atm. I know ya'll have a lot on your plate though and it's prob low priority which is ok.

**Comment by tannerlinsley** [comment]
Also, if you know how to fix the types, be my guest and PR. It's a high priority, but I just have so much on my plate right now I need to personally defer.

**Comment by marbemac** [comment]
Sounds good! Re the types I'll see if I can take a look but at first glance it looks like there's a high up front cost just to get familiar with the approach to types in router/start. Might not have enough time today, but perhaps in the next few days.

**Comment by schiller-manuel** [comment]
is this resolved with the latest releases?

**Comment by marbemac** [comment]
Yes, but Tanner mentioned "I'm sure he can whip up a proper fix when he gets back" so I wasn't sure if the current fix is temporary.

**Comment by schiller-manuel** [comment]
ok then let's keep this open until @chorobin is back

**Comment by schiller-manuel** [comment]
@chorobin told me to close this
