### ISSUE TITLE
Building this repo `build:all` fail at `@tanstack/start:build`

### ISSUE THREAD

**Issue by CanRau** [TanStack/router#2763]
### Which project does this relate to?

Start

### Describe the bug

```sh
   ✖  nx run @tanstack/start:build
      > @tanstack/start@1.81.8 build /Users/Can/Projects/Can/Coding/forks/tanstack-router/packages/start
      > vite build && pnpm build:config && pnpm build:router-manifest

      vite v5.4.11 building for production...
      src/client/createServerFn.ts:312:20 - error TS2571: Object is of type 'unknown'.

      312     const result = validator['~validate']({ value: input })
                             ~~~~~~~~~~~~~~~~~~~~~~

      Please fix the above type errors
       ELIFECYCLE  Command failed with exit code 1.
```

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

Just pulled up until https://github.com/TanStack/router/commit/83cb148a96fa3470a8bcf57ebc81fe4e253520e6
Ran `pnpm install`
then `pnpm run build:all`

### Expected behavior

successfull build

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/8e067544-697f-4bdf-9e72-35dfc1b4773d)

### Platform

- OS: macOS 12.7.6

**Comment by marbemac** [comment]
Fixed in https://github.com/TanStack/router/pull/2762
