### ISSUE TITLE
Not navigating properly even the url path is existing `Invariant failed: Could not find an active match from "/(authenticated)/_authenticated/(dashboard)/_dashboard/dashboard/(teams)/teams/$id/settings"

### ISSUE THREAD

**Issue by moshOntong-IT** [TanStack/router#2768]
### Which project does this relate to?

Router

### Describe the bug

I am trying to navigate this `http://localhost:4323/dashboard/teams/cm3ilux6u00025xf3jyjarsve/info` but the error is `Invariant failed: Could not find an active match from "/(authenticated)/_authenticated/(dashboard)/_dashboard/dashboard/(teams)/teams/$id/settings"` Why it message /$id/settings? I did not even go to that page
[Recorded](https://drive.google.com/file/d/1ujEYMbOPkHJM-Gz0h647Tq5XAML6wMf9/view?usp=sharing)

### Your Example Website or App

https://drive.google.com/file/d/1ujEYMbOPkHJM-Gz0h647Tq5XAML6wMf9/view?usp=sharing

### Steps to Reproduce the Bug or Issue

Just locate the page I recored

### Expected behavior

It should be redirected to my destined path since it exist and I even use the devtool it exist actually

### Screenshots or Videos

https://drive.google.com/file/d/1ujEYMbOPkHJM-Gz0h647Tq5XAML6wMf9/view?usp=sharing

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SeanCassiere** [comment]
@moshOntong-IT please attach a reproduction of the issue. Without a reproduction, we cannot locate the issue.
---
Also, please make sure that, 
- The Router Plugin has been configured  - https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing#installation
- The dev server is running
- The Route ID in the corresponding file is correct (i.e. that string in `createFileRoute`)

**Comment by schiller-manuel** [comment]
closing as no reproducer was presented. please open a new issue when you have a reproducer
