### ISSUE TITLE
Start: middleware context property type gets merged instead of overridden

### ISSUE THREAD

**Issue by acastroviejo** [TanStack/router#2780]
### Which project does this relate to?

Start

### Describe the bug

If I try to override a context property on a second middleware the types get merged together instead of overridden.

### Your Example Website or App

https://github.com/acastroviejo/start-merge-middleware-context

### Steps to Reproduce the Bug or Issue

1. Open the `~/app/routes/index.tsx` file and inspect the type of `context.session` (line 25)

### Expected behavior

I expected the type of overridden context properties to be overridden and not merged together.

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/1fb827ca-57bc-4cc8-85f1-234b00200d13)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

### Additional context

A real world use case is a `sessionMiddleware` that uses a `maybeSessionMiddleware` internally updating the type of session from `Session | undefined` to `Session`, but now it stays as possibly undefined

**Comment by SeanCassiere** [comment]
cc @chorobin
