### ISSUE TITLE
All documentation API reference links return 404

### ISSUE THREAD

**Issue by markogajic** [TanStack/router#2788]
### Which project does this relate to?

Router

### Describe the bug

When you go to the [API reference page](https://tanstack.com/router/latest/docs/framework/react/api/router), clicking on any of those links leads to a 404 page.

For example, clicking "createFileRoute" leads to https://tanstack.com/router/latest/docs/framework/react/api/router/router/createFileRouteFunction.md instead of https://tanstack.com/router/latest/docs/framework/react/api/router/createFileRouteFunction

This issue doesn't happen if you open the link in a new tab, or copy link address.

### Your Example Website or App

https://tanstack.com/router/latest/docs/framework/react/api/router

### Steps to Reproduce the Bug or Issue

1. Go to https://tanstack.com/router/latest/docs/framework/react/api/router
2. Click on createFileRoute
3. Non existing https://tanstack.com/router/latest/docs/framework/react/api/router/router/createFileRouteFunction.md page is opened

### Expected behavior

https://tanstack.com/router/latest/docs/framework/react/api/router/createFileRouteFunction should be opened instead.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 130.0.6723.117

**Comment by SeanCassiere** [comment]
This has been fixed.
