### ISSUE TITLE
Random invariant failed while using framer-motion

### ISSUE THREAD

**Issue by AndreiTS** [TanStack/router#2803]
### Which project does this relate to?

Router

### Describe the bug

For context, I am using framer-motion to animate the transitions between routes (https://github.com/TanStack/router/discussions/823)
In the new versions of the router, users started getting randomly  "Invariant Failed" errors while navigating routes.
I was able to solve this by replacing the custom component to Outlet.

### Your Example Website or App

-soon-

### Steps to Reproduce the Bug or Issue

1- Navigate between differents routes
2- Error is throw

### Expected behavior

To not throw a error.

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/a4434409-bb7c-41a0-a0d9-2cf50feef002)
![Image](https://github.com/user-attachments/assets/00ed24db-260a-41f0-8cde-757c0e02eef7)

![Image](https://github.com/user-attachments/assets/6f8b3f85-ff48-4f86-9ad3-9d275351ab7a)
![Image](https://github.com/user-attachments/assets/9024360b-16a4-4f28-a7f2-b09de1d4bee3)

### Platform

- OS: Windows 11
- Browser: Chrome, Firefox
- Version: Chrome 131, 109 Firefox 132

### Additional context

The error is from here:
https://github.com/TanStack/router/blob/809ca432cc74e29e169480033d399045e6b55da2/packages/react-router/src/router.ts#L1465

**Comment by AndreiTS** [comment]
I don't know how to reproduce this, I just removed framer-motion and it's working. Closing for now

**Comment by mslxl** [comment]
I met the same problem. This error first appear at version `1.18.10`.
But I did not have free time to tear up my code to make a minimal reproduction. Anyone who met the same error could downgrade to `1.18.9`.

I will open a new issue later when I am free.
