### ISSUE TITLE
Documentation error in Route Mask

### ISSUE THREAD

**Issue by ipassynk** [TanStack/router#2810]
### Which project does this relate to?

Router

### Describe the bug

In https://tanstack.com/router/latest/docs/framework/react/guide/route-masking there is a typo. No "," after  "/photos/$photoId"

```
<Link
  to="/photos/$photoId/modal"
  params={{ photoId: 5 }}
  mask={{
    to: "/photos/$photoId"
    params: {
      photoId: 5,
    },
  }}
>
  Open Photo
</Link>
```

The same in navigate - no comma after  to: '/photos/$photoId'

```
  navigate({
    to: '/photos/$photoId/modal',
    mask: {
      to: '/photos/$photoId'
      params: {
        photoId: 5,
      },
    }
  })
```

Plus navigate misses required  params: {photoId: 5}

### Your Example Website or App

https://tanstack.com/router/latest/docs/framework/react/guide/route-masking there 

### Steps to Reproduce the Bug or Issue

Go to https://tanstack.com/router/latest/docs/framework/react/guide/route-masking

### Expected behavior

Axpect to have correct documentation

### Platform

Any

**Comment by schiller-manuel** [comment]
please create a PR for the docs

**Comment by ipassynk** [comment]
Created PR
