### ISSUE TITLE
File based route always expect to return export Route

### ISSUE THREAD

**Issue by ipassynk** [TanStack/router#2821]
### Which project does this relate to?

Router

### Describe the bug

in examples/react/basic-file-based/src/routes/posts.tsx change

from:
```
export const Route = createFileRoute('/posts')({
```

to:
```
export const RoutePosts = createFileRoute('/posts')({
```

Start the application and see routeTree.gen.ts generates import with Route:
```
import { Route as PostsImport } from './routes/posts'
```

![Image](https://github.com/user-attachments/assets/133db57a-d6e1-46e2-8d66-69cb8c97d041)

### Your Example Website or App

examples/react/basic-file-based/src/routes

### Steps to Reproduce the Bug or Issue

Change export Route to export AnyRoute

### Expected behavior

Able to use different name for export

### Platform

MacOS

**Comment by schiller-manuel** [comment]
this is the expected behavior. the export must be named Route.

**Comment by ipassynk** [comment]
@schiller-manuel This is probably should be specified in the documentation? 

In config base you can do 
```
const postIdRoute = createRoute({
  path: '/blog/post/$postId',
})

const link = (
  <Link from={postIdRoute.fullPath} to="../categories">
    Categories
  </Link>
)
```
So i was assumed that in file based you an do the same.

**Comment by schiller-manuel** [comment]
can you provide a PR for the documentation please?
