### ISSUE TITLE
Zod discriminated union ts issues

### ISSUE THREAD

**Issue by dragansavevski** [TanStack/router#2824]
### Which project does this relate to?

Router

### Describe the bug

When trying to have a zod discriminated union I cannot achieve full type safety. See the example app (__root.tsx and about.tsx). Basically I tried 3 approaches. Setting the undesired parameters to undefined, never and omitting them. Each of these approaches causes a different error:

1. If I use z.never type issues occur at About 2 link
2. If I use z.undefined type issues in the search middleware in the about route
3. If I omit them and not have them at all the loader cannot be typed.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-qm8eay?file=src%2Froutes%2F__root.tsx,src%2Froutes%2Fabout.tsx&preset=node

### Steps to Reproduce the Bug or Issue

See the about.tsx component and its search params.
See the about.tsx component and the links inside.

### Expected behavior

I expect to have a proper discriminated union type.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 131.0.6778.86

**Comment by chorobin** [comment]
TypeScript is correct to type error here. If you think through what is happening.

`search` is a tagged union where `start_date` and `end_date` has to be `string` in one member ('schedule-appointment') of the union and has to be `undefined` in the second member or the union 'request-appointment' | 'manual-booking'

The result of `next(search)` is also the same union. This means its possible at runtime for `search` to have `start_date` as `string` (''schedule-appointment') but the result from `next` could have `start_date` as `undefined` ('request-appointment' | 'manual-booking'). When you spread these two together `start_date` would be `string` which does not satisfy the original type as it is required to be `undefined` with a tag type of ( 'request-appointment' | 'manual-booking').

You can narrow to set these to `undefined` explicitly if this is what you truly want or you can make the schema looser

https://stackblitz.com/edit/tanstack-router-ky9zwb?file=src%2Froutes%2Fabout.tsx

**Comment by dragansavevski** [comment]
Thanks for the explanation 🙏
