### ISSUE TITLE
serverOnly return type should consider parameters of the passed function

### ISSUE THREAD

**Issue by revosw** [TanStack/router#2828]
### Which project does this relate to?

Start

### Describe the bug

serverOnly does not return the correct type.

As of v1.82.4, serverOnly is declared like this.
```ts
export declare function serverOnly<T>(value: () => T): () => T | undefined;
```

This means that when I have a serverOnly function like this:
```ts
import { serverOnly } from "@tanstack/start";

export const getPokemon = serverOnly(async (pokemon: string) => {
  return await fetch(`https://pokeapi.co/api/v2/pokemon/${pokemon}`).then(res => res.json());
});
```

getPokemon is inferred to have the type `() => Promise<any> | undefined`, which means passing the `pokemon` parameter leads to a typescript error
```ts
export const Route = createRootRoute({
  beforeLoad: async () => {
    const pokemon = await getPokemon("ditto");
                                     // ^ Expected 0 arguments, but got 1. (2554)
    return {pokemon}
  },
  component: RootComponent,
});
```

## Alternative method
You can wrap the anonymous function inside another anonymous function to get the correct return type
```ts
import { serverOnly } from "@tanstack/start";

// Notice () => async () => {}
export const getPokemon = serverOnly(() => async (pokemon: string) => {
  return await fetch(`https://pokeapi.co/api/v2/pokemon/${pokemon}`).then(res => res.json());
});
```

But you will have to "unwrap" once
```ts
export const Route = createRootRoute({
  beforeLoad: async () => {
    const pokemon = await getPokemon?.()("ditto");
    return { pokemon };
  },
  component: RootComponent,
});
```

### Your Example Website or App

https://stackblitz.com/edit/github-avg9mj-9r1rad?file=app%2Froutes%2F__root.tsx

### Steps to Reproduce the Bug or Issue

1. Go to __root.tsx
2. Observe that I can't pass "ditto" as an argument to getPokemon, even if the function passed to serverOnly has a parameter of type string

### Expected behavior

getPokemon should be inferred as `(pokemon: string) => Promise<any> | undefined`

### Platform

- OS: Windows
- Browser: Microsoft Edge
- Version: Version 131.0.2903.51 (Official build) (64-bit)

**Comment by EskiMojo14** [comment]
fix released in https://github.com/TanStack/router/releases/tag/v1.87.1
