### ISSUE TITLE
ServerFn validator not inferring inputs for consumers

### ISSUE THREAD

**Issue by mckamyk** [TanStack/router#2833]
### Which project does this relate to?

Start

### Describe the bug

When making a `createServerFn()` and using `.validator()` chain, types are inferred for the following `.handler()` call, but not for any consumers of the serverFn later on.

```ts
const dataSchema = z.object({
  foo: z.literal('bar'),
})

type DataType = z.infer<typeof dataSchema>

const zodDirect = createServerFn()
  .validator(dataSchema)
  .handler(({ data }) => data.foo) // type inference is fine here

const zodVerbose = createServerFn()
  .validator((d: unknown) => dataSchema.parse(d))
  .handler(({ data }) => data.foo) // type inference is fine here

const manual = createServerFn()
  .validator((d: unknown) => {
    if (typeof d !== 'object' || d === null)
      throw new Error('data must be an object')

    if (!('foo' in d)) throw new Error('data must have a foo property')

    if (d.foo !== 'bar') throw new Error('data.foo must be "bar"')

    return d as DataType
  })
  .handler(({ data }) => data.foo) // type inference is fine here

// @ts-expect-error
const r1 = zodDirect({ data: { bad: 42 } }) // incorrect input data, but no error thrown
//                       ^ 'unknown' type

// @ts-expect-error
const r2 = zodVerbose({ data: { bad: 42 } }) // incorrect input data

// @ts-expect-error
const r3 = manual({ data: { bad: 42 } }) // incorrect input data
```

### Your Example Website or App

https://github.com/mckamyk/serverfn-no-inference

### Steps to Reproduce the Bug or Issue

1. clone the repo
2. open editor to `app/routes/index.tsx` -or- run `bun tsc`, `npm run tsc`, etc.
3. the `// @ts-expect-error` statements trip `tsc`, because there are not errors by the invalid calls

### Expected behavior

In this case, 

1. `bun tsc` should result in no error`s
2. hovering over the `data` portion in `zodDirect({ data: ... })` should have type hints, but it does not
3. Editors should get suggestion as to the keys of the `data` object inside the function call.

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/3abcb9ab-26b5-4b73-9c48-0287dd26e1e0)

### Platform

- OS: macOS Sanoma 14.7
- Browser: NA
- Version: 1.82.6

**Comment by mckamyk** [comment]
@schiller-manuel

**Comment by schiller-manuel** [comment]
unfortunately for zod you need an adapter package to correctly infer input types

```tsx
import { zodValidator } from "@tanstack/zod-adapter";

const dataSchema = zodValidator(z.object({
  foo: z.literal("bar"),
}));
```

then it works as expected
![Image](https://github.com/user-attachments/assets/e80b34a5-18e2-4ce4-8c79-7d8057a3e2a9)

**Comment by mckamyk** [comment]
Still seems to be the case with the manual typing?

Copy-pasting the example from the docs for manual validation doesn't lead to inferred inputs.

```ts
export const greet = createServerFn({ method: 'GET' })
  .validator((person: unknown): Person => {
    if (typeof person !== 'object' || person === null) {
      throw new Error('Person must be an object')
    }

    if ('name' in person && typeof person.name !== 'string') {
      throw new Error('Person.name must be a string')
    }

    return person as Person
  })
  .handler(
    async ({
      data, // Person
    }) => {
      return `Hello, ${data.name}!`
    },
  )

function test() {
  greet({ data: { name: 'John' } }) // OK
  greet({ data: { name: 123 } }) // No error here
//        ^ unknown
}
```

**Comment by schiller-manuel** [comment]
The input type is specified as `unknown` currently. You would have to provide another, more narrow input type to get the error you expect. 
Trivial one would be:
```tsx
validator((person: Person): Person => { 
```

**Comment by mckamyk** [comment]
I think I understand now.

validator's input type -> consumer's arg type
validator's output type -> .handler(...) arg type
