### ISSUE TITLE
How to use nested routing in a code based manner

### ISSUE THREAD

**Issue by LinHanlove** [TanStack/router#2835]
### Which project does this relate to?

Router

### Describe the bug

首先我用的是基于代码的路由，我创建了 '父组件' -- 【Home】,他可以正常跳转，我也创建了基于home的子组件 -- 【homeChild】,所有他们的路径如下 
- /home --- 跳转到Home页面
- /home/child --- 跳转到Home下的HomdChild
但是，这是错误的，跳转不过去，Not Found

### Your Example Website or App

https://stackblitz.com/edit/github-gcuesq?file=src%2Fhome%2Findex.tsx

### Steps to Reproduce the Bug or Issue

- /home --- 跳转到Home页面
- /home/child --- 跳转到Home下的HomdChild
但是，这是错误的，跳转不过去，Not Found

### Expected behavior

The expected result should be/home navigating to the Home page,/home/child navigating to [HomeChild] under [Home]

### Screenshots or Videos

 follows： 
![Image](https://github.com/user-attachments/assets/0b4ccedb-0ac5-447f-bc38-10428b10f78f)
![Image](https://github.com/user-attachments/assets/06d1884e-8d92-4404-94ce-0c8082afcafd)
![Image](https://github.com/user-attachments/assets/4b7660d4-dd1b-4874-977d-6d757f23e29d)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment]
path of child was wrong

```tsx
const homeChildRoute = createRoute({
  getParentRoute: () => homeRoute,
  path: 'child',
}).lazy(() => import('./home/homeChild').then((d) => d.HomeChild));
```

have a look at https://stackblitz.com/edit/github-gcuesq-ch7m7n?file=src%2Fmain.tsx,src%2Fabout.tsx

![Image](https://github.com/user-attachments/assets/0dd94b84-a2a0-4899-8f51-dcf96e27cffb)

**Comment by LinHanlove** [comment]
> 孩子的道路是错误的
> 
> const homeChildRoute = createRoute({
>   getParentRoute: () => homeRoute,
>   path: 'child',
> }).lazy(() => import('./home/homeChild').then((d) => d.HomeChild));
> 看看https://stackblitz.com/edit/github-gcuesq-ch7m7n?file=src%2Fmain.tsx,src%2Fabout.tsx
> 
> ![Image](https://github.com/user-attachments/assets/0dd94b84-a2a0-4899-8f51-dcf96e27cffb)


I have a layout component where the outlet controls the global layout rendering. However, if I write it this way, I have to write an outlet on the home page as well. But this way, when I navigate to/home/child, home will appear and the content of the page will also be rendered. However, if it is like other frameworks such as vureroute, this situation will not occur. This is very confusing. I just want to use a globally unified outlet, and when I navigate to home/child, please do not display the content of the home parent component. How can I do this
