### ISSUE TITLE
`useLoaderState` returns `undefined` after `router.invalidate()` is called

### ISSUE THREAD

**Issue by datner** [TanStack/router#2846]
### Which project does this relate to?

Start

### Describe the bug

Following the _Getting Started_ guide this snippet is presented for copy-pasting:
```tsx
function Home() {
  const router = useRouter()
  const state = Route.useLoaderData()

  return (
    <button
      type="button"
      onClick={() => {
        updateCount({ data: 1 }).then(() => {
          router.invalidate()
        })
      }}
    >
      Add 1 to {state}?
    </button>
  )
}
```
upon clicking the button, you are presented with "_Add 1 to ?_" in the UI. Refreshing the page presents the expected number.
Inspecting `state` shows that once the component rerenders, supposedly due to `router.invalidate`, it returns `undefined`.
Placing a console.log in the `loader` shows that its executed on page load and then never again, regardless of invalidation.

### Your Example Website or App

None. The examples don't work, stackblitz won't let me fork the examples either.

### Steps to Reproduce the Bug or Issue

1. follow the _Getting Started_ guide to the end
2. fix the `index.tsx` not working because browsers remove trailing `/` for root routes making it unreachable since it's `exact` by changing it to something like `home.tsx`
3. click on `Add 1 to ?`
4. refresh the page
5. click on `Add 1 to 1?`
6. It becomes `Add 1 to ?`

### Expected behavior

`router.invalidate` triggers another call to the route `loader`, and `useRouteState` does not return `undefined`

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/1a43aff1-019f-487f-af06-16e7c25530ed)

### Platform

- OS: macOS
- Browser: Arc
```
dependencies:
@tanstack/react-router 1.82.2
@tanstack/router-devtools 1.82.2
@tanstack/start 1.82.6
react 18.3.1
react-dom 18.3.1
vinxi 0.4.3

devDependencies:
@tanstack/router-plugin 1.81.9
@types/react 18.3.12
@types/react-dom 18.3.1
@vitejs/plugin-react 4.3.3
vite 5.4.11
```

### Additional context

I've encountered multiple bugs immediately out of the gate without even starting to write any code of my own.
I know it's beta, but that was a bit rough even for beta imho..

**Comment by SeanCassiere** [comment]
Just tried this out and I'm not seeing this bug.

Could you confirm that your route file is similar to this? https://github.com/TanStack/router/blob/main/examples/react/start-counter/app/routes/index.tsx

Or are you doing anything different here?

Also, it could be a long shot, but you could try upgrading the `@tanstack/react-router` and `@tanstack/start` packages.

**Comment by datner** [comment]
It ended up being some weird interaction between many moving part, long-story short, what ended up solving it was removing an `index.html` file I had from before upgrading to Start. 
Odd, huh?

**Comment by schiller-manuel** [comment]
is this reproducible?
