### ISSUE TITLE
createServerFn must be called with a function that is marked with the 'use server' pragma

### ISSUE THREAD

**Issue by hahnrobert** [TanStack/router#2849]
### Which project does this relate to?

Start

### Describe the bug

> Invariant failed: createServerFn must be called with a function that is marked with the 'use server' pragma. Are you using the @tanstack/start-vite-plugin ?

```typescript
"use server"

export const getCurrentUser = createServerFn()
  .handler(async () => {
    "use server";  // Also fails without this

    let user = await getAuth(getWebRequest());
    return user?.userId
  });
```

```typescript
// __root.tsx
 ...
 beforeLoad: async (ctx) => {
    return { ...ctx, user: await getCurrentUser() }
  },
   ...
```

```
    "@tanstack/react-query": "5.61.3",
    "@tanstack/react-query-devtools": "5.61.3",
    "@tanstack/react-router": "1.82.8",
    "@tanstack/react-router-with-query": "1.82.8",
    "@tanstack/router-devtools": "1.82.8",
    "@tanstack/router-zod-adapter": "^1.81.5",
    "@tanstack/start": "1.82.8",
    "@tanstack/start-vite-plugin": "1.82.5",
```

### Your Example Website or App

Followed the official Tanstack Clerk example

### Steps to Reproduce the Bug or Issue

Setup Clerk with Tanstack.

### Expected behavior

The server funciton can be called.

### Platform

- OS: macOS
- Browser: Arc
- Version: See above

**Comment by hahnrobert** [comment]
Strangely, removing ALL "use server" annotations resolves the problem.

**Comment by schiller-manuel** [comment]
you don't need to add any use server directives as start will do this for you

**Comment by hahnrobert** [comment]
Closing since technically there is a workaround. Just strange that it fails if "use server" is explicitly used.

**Comment by adgang** [comment]
This happens because of [this line](https://github.com/TanStack/router/blob/fe8d7cbab17dbf4d9619e59f763e3be935a9b1e0/packages/start/src/client/createServerFn.ts#L222)

To satisfy the handler, we have to convert this

```
export const getCurrentUser = createServerFn()
  .handler(async () => {
    "use server";  // Also fails without this

    let user = await getAuth(getWebRequest());
    return user?.userId
  });
```

to this:

```
const fn = async () => {
    let user = await getAuth(getWebRequest());
    return user?.userId
  };
fn.url = 'blah';
export const getCurrentUser = createServerFn()
  .handler(fn);
```

There is no need for 'use server'

I believe this bit of code is unintended and need a clarification if not a fix.
