### ISSUE TITLE
Infinite recursion loop (Router.routeMatches<->controlledPromise.resolve)

### ISSUE THREAD

**Issue by ondrejvelisek** [TanStack/router#2871]
### Which project does this relate to?

Start

### Describe the bug

Hi,

another day another bug report from me.

When I access a route with redirect in beforeLoad JS ends up in infinite recursion loop (see attached perf devtool flamechart)

Related code is here:
https://github.com/ondrejvelisek/peoples-budget/tree/infinite-loop-bug/app/pages/~2024

I hope I'm helpful.

### Your Example Website or App

https://peoples-budget-git-infinite-loop-bug-ondrejveliseks-projects.vercel.app

### Steps to Reproduce the Bug or Issue

1. go to https://peoples-budget-git-infinite-loop-bug-ondrejveliseks-projects.vercel.app
2. click second menu link "Vládní rozpočet 2024"
3. freeze

### Expected behavior

It correctly redirects without freezing a browser.

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/6c65adf0-88fc-45cb-bd07-3ca060eaf99e)

### Platform

- OS: macOS
- Browser: Safari and Firefox, Chrome is sometimes ok.
- Version: One of the latest versions

### Additional context

Happens on both production and dev server builds.
Better to debug with Firefox. Safari devtools freezes together with page.

**Comment by schiller-manuel** [comment]
it would be very helpful if the reproducer could be trimmed down so we know what's going on here (e.g. does it only happen with splat routes?). can you please use one of the existing router example on stackblitz and modify it so it fails as well?

**Comment by ondrejvelisek** [comment]
Currently I have no idea what it causes. So I need some time to investigate
this. Hopefully within 2 weeks. Its just a hobby project.

If you will have time sooner, feel free to investigate on your own. So we
know sooner. In that case please write here so I know I dont need to spend
time on it. Thx.

**Comment by ondrejvelisek** [comment]
Hi, finally had some time to look into.

It was my mistake. I expected undefined when cookie is not deifned. But lib returned empty string.
https://github.com/ondrejvelisek/peoples-budget/commit/9f88a1f489280c2c0adb3a31ed4bdf382651cb71
It causes infinite redirect loop.

It was kind of hard to debug. For better DX we can make it easier to spot those bugs in TanStart. Two ideas:
1/ limit redirect depth. e.g. max 50 redirects in a row.
2/ restrict when redirecting to the same url.

Still my mistake though. Thank you for your hard work.

We can close this issue.

**Comment by schiller-manuel** [comment]
Thanks for looking into this
