### ISSUE TITLE
TanStack Start development server fails when embedding a Sanity studio

### ISSUE THREAD

**Issue by alexanbj** [TanStack/router#2897]
### Which project does this relate to?

Start

### Describe the bug

Hello,

I'm attempting to embed a Sanity studio in a newly setup TanStack Start app.

I'm followed the [TanStack Start getting started guide](https://tanstack.com/router/latest/docs/framework/react/start/overview) and [Sanity's embedding studio guide](https://www.sanity.io/docs/embedding-sanity-studio). However, an exception is thrown if I navigate to that route when using the development server. I've created a reproduction repo.

The error seems to occur in `vite-plugin-tanstack-start-dead-code-elimination`. See the full error in the reproduction steps or the reproduction repo.

No error is thrown when building the app for production.

### Your Example Website or App

https://github.com/alexanbj/tanstackstart-embedded-sanity-reproduction/tree/main

### Steps to Reproduce the Bug or Issue

1. Create a new TanStack Start app following these instructions https://tanstack.com/router/latest/docs/framework/react/start/getting-started
2. Create a new route where a Sanity studio is embedded https://www.sanity.io/docs/embedding-sanity-studio
3. Run the dev server and navigate to that route
4. It fails with an exception along the lines of
```
[vite] Internal server error: Property left of ForOfStatement expected node to be of a type ["VariableDeclaration","LVal"] but instead got undefined
  Plugin: vite-plugin-tanstack-start-dead-code-elimination
  File: /Users/alexanbj/Code/Hacking/tanstackstart-sanity-reproduction/node_modules/.vinxi/cache/client/deps/chunk-XONAPM26.js?v=ffa86631
```

### Expected behavior

Able to embed the Sanity studio in development.

### Platform

- OS: macOS
- Browser: Firefox
- TanstackStart and Router versions: 1.85.0

**Comment by schiller-manuel** [comment]
can you please run `TSR_VITE_DEBUG=true npm run build` and provide the output as a gist?

**Comment by schiller-manuel** [comment]
I created a bug at https://github.com/pcattori/babel-dead-code-elimination/issues/32 for this

**Comment by schiller-manuel** [comment]
fixed with https://github.com/pcattori/babel-dead-code-elimination/releases/tag/v1.0.8
