### ISSUE TITLE
Navigations not adding trailing slash when using virtual routes in tsr.config.json

### ISSUE THREAD

**Issue by davidturissini** [TanStack/router#2930]
### Which project does this relate to?

Router

### Describe the bug

I did a search in the repo but couldn't find any related issue.

I am trying to do a simple navigation from `/` to `/withslash/`. I have the following [code](https://stackblitz.com/edit/vitejs-vite-lxqqv4?file=src%2Froutes%2FHome.tsx):

```
<Link to="/withslash/">Go to /withslash/</Link>
```

My expectation is that when I click this link, I should navigate to `/withslash/`. However, the trailing slash is dropped when I get to the next page. 

I am using [virtual routes](https://stackblitz.com/edit/vitejs-vite-lxqqv4?file=tsr.config.json) with the following configuration:

```
{
  "routesDirectory": "./src/routes",
  "generatedRouteTree": "generated/routeTree.gen.ts",
  "trailingSlash": "always",
  "virtualRouteConfig": {
    "type": "root",
    "file": "__root.tsx",
    "children": [
      {
        "type": "index",
        "file": "Home.tsx"
      },
      {
        "type": "route",
        "path": "/withslash",
        "children": [
          {
            "type": "index",
            "file": "WithSlash.tsx"
          }
        ]
      }
    ]
  }
}

```

Based on the [documentation](https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing#directory-routes), I would expect that defining an `index` route would add the trailing slash. I would also expect `trailingSlash` config to do the same but I might be misunderstanding what that is doing.

It is worth nothing that this works as expected with file-based routes.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-lxqqv4?file=tsr.config.json

### Steps to Reproduce the Bug or Issue

1. Go to https://stackblitz.com/edit/vitejs-vite-lxqqv4?file=tsr.config.json
2. In preview panel, click on `Go to /withslash/`
3. Observe that next screen reads `Current pathname: /withslash`

### Expected behavior

Next screen should read `Current pathname: /withslash/`

### Platform

- OS: [macOS]
- Browser: [Chrome]
- Version: [131

**Comment by schiller-manuel** [comment]
`trailingSlash` defaults to `"never"`.
when setting it to `"always"` it will be added, see https://stackblitz.com/edit/vitejs-vite-bg46ds

> It is worth nothing that this works as expected with file-based routes.
no, it behaves the same way
https://stackblitz.com/edit/tanstack-router-gznvuy?file=src%2Froutes%2Findex.tsx&preset=node

**Comment by davidturissini** [comment]
> `trailingSlash` defaults to `"never"`. when setting it to `"always"` it will be added, see https://stackblitz.com/edit/vitejs-vite-bg46ds
> 
> > It is worth nothing that this works as expected with file-based routes.
> 
> no, it behaves the same way https://stackblitz.com/edit/tanstack-router-gznvuy?file=src%2Froutes%2Findex.tsx&preset=node

Ah ok ok, so `trailingSlash` is applied to the router, not in `tsr.config.ts` then. Can close as simple user error. thanks!
