### ISSUE TITLE
`serverOnly` uses wrong types

### ISSUE THREAD

**Issue by datner** [TanStack/router#2938]
### Which project does this relate to?

Start

### Describe the bug

the `serverOnly` function gets swapped for client builds with
```ts
() => {
  invariant(false, "serverOnly() functions can only be called on the server!");
}
```
while the type signature is
```ts
declare function serverOnly<T>(value: () => T): () => T | undefined;
```
and the implementation is
```ts
const serverOnly = _ => _
```
This is a problem for multiple reasons:
1. `invariant` is not a valid ambient, and an import is not patched into the file, so the actual error seen is `Uncaught ReferenceError: invariant is not defined`
2. according to typescript semantics, the type must stay `() => T`, there is no scenario for `undefined` because we throw. This just promotes needlessly defensive programming in otherwise valid states
3. because of the `undefined` leak, there's the assumption that in clientside environments, it counts as a `noop`, but in reality we shouldn't expect any fallback behaviors because we don't return `undefined`, we throw.
4. The Implementation is much broader than a `() => T`, it's any `T`.

### Your Example Website or App

https://github.com/datner/router/tree/datner%2FserverOnly

### Steps to Reproduce the Bug or Issue

```sh
pnpm i && pnpm build:all && pnpm -F tanstack-start-example-basic dev
```
1. load page
2. trigger `beforeLoad` clientside (like move a page)

### Expected behavior

As a user, I expected to get `undefined` but U an seeing an error

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/4fdc4a4c-44f4-4a9e-ae79-6fae80fee8be)

### Platform

- OS: macOS
- Browser: Arc
- Version: 1.85.7

**Comment by EskiMojo14** [comment]
fix released in https://github.com/TanStack/router/releases/tag/v1.87.1
