### ISSUE TITLE
Missing allowed types in start's defineConfig "react.babel.plugins"

### ISSUE THREAD

**Issue by busybox11** [TanStack/router#2952]
### Which project does this relate to?

Start

### Describe the bug

The type definition and schema validation of some fields in `@tanstack/start/config`'s exported `defineConfig` is seemingly unnecessarily narrowed down.

```TS
defineConfig({
  react: {
    babel: {
      plugins: (string | [string, any])[] | undefined
    }
  }
})
```

The definition exported in `@vite/plugin-react` is `PluginItem[] | null | undefined`.
`PluginItem` is defined by the following:
```TS
export type PluginItem =
    | ConfigItem
    | PluginObj<any>
    | PluginTarget
    | [PluginTarget, PluginOptions]
    | [PluginTarget, PluginOptions, string | undefined];
```

This does match the zod schema used by Start, exported by `defineConfig`, narrowing down the allowed type definition to a subset of `PluginItem`, but restricts the use of a custom object imported inside `app.config.ts`, as it gets rejected by both the type definition and by Zod at runtime.

This is the only config field I needed, in order to make use of [Jotai's fast refresh plugin with Vite](https://jotai.org/docs/guides/vite). I haven't checked other config fields, there might be other ones that are also narrowed down in such a way that it restricts some use of a custom Vite config.

### Your Example Website or App

https://github.com/busybox11/ts-start-repro-babel/

### Steps to Reproduce the Bug or Issue

1. Install the modules
2. Open `app.config.ts` in your editor => **You should have type errors on the `plugins` array** (line 15, field annotated)
3. Run the dev server => **You should see Zod runtime errors in the console** (also annotated)

### Expected behavior

`defineConfig` should allow the use of custom objects as babel plugins.

### Screenshots or Videos

![Image](https://github.com/user-attachments/assets/9ec4071a-86a0-44ea-ac36-5d5fb48c8fe3)

### Platform

- OS: Linux
- Browser: Zen (Firefox), Chrome
- Version: 1.0.1-t.19 (Firefox 132.0.2), 131.0.6778.108

**Comment by busybox11** [comment]
Wow, this was fast. Thank you so much!

**Comment by schiller-manuel** [comment]
unfortunately, npm is having issues, so the release is pending until that is resolved

**Comment by busybox11** [comment]
That's OK. Wouldn't have been able to dig more into the code and submit a PR before you did.

**Comment by schiller-manuel** [comment]
it was released in https://github.com/TanStack/router/releases/tag/v1.87.1
