### ISSUE TITLE
All Tanstack documentations are dead, including the router.

### ISSUE THREAD

**Issue by caner-cetin** [TanStack/router#2981]
### Which project does this relate to?

Router

### Describe the bug

-

### Your Example Website or App

https://google.com

### Steps to Reproduce the Bug or Issue

go to https://tanstack.com/router/latest
click get started
get navigated to https://tanstack.com/router/latest/docs/framework/react/overview
error
<img width="312" alt="Image" src="https://github.com/user-attachments/assets/eaeafadb-baaf-4164-b406-0f75eab3815c" />
go to https://tanstack.com/virtual/latest
dead
<img width="1677" alt="Image" src="https://github.com/user-attachments/assets/3ed613e5-f6d5-4c4d-bbc9-eb3652e1b23d" />

### Expected behavior

read docs and leave

### Platform

Latest version of macOS and Safari.

### Additional context

i can still read an archived copy https://web.archive.org/web/20241129155650/https://tanstack.com/router/latest/docs/framework/react/quick-start

**Comment by SeanCassiere** [comment]
You may have gotten caught in a bad cache purge whilst we were playing with the CDN settings. This should be resolved now.

**Comment by caner-cetin** [comment]
@SeanCassiere yes it all works fine now. just unlucky moment. thank you
