### ISSUE TITLE
"autoCodeSplitting" having issues when using sentry source maps

### ISSUE THREAD

**Issue by wuifdesign** [TanStack/router#2991]
### Which project does this relate to?

Router

### Describe the bug

When i use the automatic code spitting (https://tanstack.com/router/v1/docs/framework/react/guide/code-splitting#enabling-automatic-code-splitting) and upload the source maps to sentry ever error is mapped to a total wrong file/line (but always the same for all errors).

![Image](https://github.com/user-attachments/assets/ecbf4ae7-e7d0-40aa-be7e-be880b42fd46)

In this example i throw an error on an undefined function on a button click, but the error shows some total different file.

When i disable the "autoCodeSplitting" everything works fine.

### Your Example Website or App

can't provide any as it is an internal sentry

### Steps to Reproduce the Bug or Issue

1. enable autoCodeSplitting (https://tanstack.com/router/v1/docs/framework/react/guide/code-splitting#enabling-automatic-code-splitting)
2. enable sentry (https://docs.sentry.io/platforms/javascript/guides/react/features/tanstack-router/)
3. upload sourcemaps to sentry (https://docs.sentry.io/platforms/javascript/sourcemaps/uploading/vite/)

### Expected behavior

Mapping to error should be correct when using `autoCodeSplitting`. 

### Platform

- Sentry 24.9.0

**Comment by schiller-manuel** [comment]
how does your vite config look like?
maybe it's a matter of plugin order. sentry probably needs to be executed last.

**Comment by wuifdesign** [comment]
i tried both, adding it on first position and on last position, didn't change anything.

i tried:

```
plugins: [
      react(),
      sentryVitePlugin({
        authToken: process.env.SENTRY_AUTH_TOKEN,
        url: '..',
        org: 'sentry',
        project: '....',
        telemetry: false,
        sourcemaps: {
          assets: './dist/**',
          filesToDeleteAfterUpload: ['./dist/**/*.map'],
        },
        release: {
          name: `react@${version}`,
          dist: undefined,
        },
      }),
      TanStackRouterVite({
        autoCodeSplitting: true,
      }),
    ],
```

and 

```
plugins: [
      TanStackRouterVite({
        autoCodeSplitting: true,
      }),
      react(),
      sentryVitePlugin({
        authToken: process.env.SENTRY_AUTH_TOKEN,
        url: '..',
        org: 'sentry',
        project: '....',
        telemetry: false,
        sourcemaps: {
          assets: './dist/**',
          filesToDeleteAfterUpload: ['./dist/**/*.map'],
        },
        release: {
          name: `react@${version}`,
          dist: undefined,
        },
      }),
    ],
```

**Comment by schiller-manuel** [comment]
can you find out if the `sentryVitePlugin` is really executed last? order in the plugin array is not the only thing that determines order of execution in vite.

**Comment by wuifdesign** [comment]
how would i find out if it is executed last?

**Comment by wuifdesign** [comment]
ok, may seam to be an issue with the sourcemaps rather than just sentry, i will try to create a demo repo and find out more about this

**Comment by schiller-manuel** [comment]
I fixed on issue w.r.t. source maps in https://github.com/TanStack/router/releases/tag/v1.87.13

can you please try again with that version?

**Comment by wuifdesign** [comment]
yeah, thx you for the quick fix.

i can confirm it works now 🙂 so i do not have to create a test repo 😅
