### ISSUE TITLE
Allow non standard array returns in createServerFn

### ISSUE THREAD

**Issue by nikitavoloboev** [TanStack/router#3019]
### Which project does this relate to?

Start

### Describe the bug

I have this type error:

<img width="858" alt="Image" src="https://github.com/user-attachments/assets/daf413f8-53df-4d9a-b06f-2835e117e3d8" />

```js
export const $simpleGetOfRoninData = createServerFn({
  method: "GET",
}).handler(async () => {
  try {
    const posts = await get.posts()
    return {
      posts,
    }
  } catch (error) {
    throw new Error("Failed to get data")
  }
})
```

The reason is this:

<img width="1127" alt="Image" src="https://github.com/user-attachments/assets/97120bca-7b5e-4920-a179-c77e6eaa863d" />

Please allow this in types so there are no type errors for such returns.

Thank you. 

### Your Example Website or App

https://github.com/nikitavoloboev/ronin-test

### Steps to Reproduce the Bug or Issue

1. clone repo
2. open https://github.com/nikitavoloboev/ronin-test/blob/main/web/app/actions/actions.ts and see type error

### Expected behavior

Server function is typed properly as it is valid.

**Comment by nikitavoloboev** [comment]
Even simpler reproduction is this:

```js
export const $simpleServerFn = createServerFn({
  method: "GET",
}).handler(() => {
  //          ^? This will show a type error
  const invalidArr = new Array<number>() as Array<number> & {
    foo: string
  }

  return {
    posts: invalidArr,
  }
})
```

<img width="871" alt="Image" src="https://github.com/user-attachments/assets/be851a0a-8659-4183-ad0d-f9f72cec64b4" />

This should work.

**Comment by NuroDev** [comment]
To provide a bit more context for the TanStack team on the reasoning behind this: When making a query with the `ronin` client that returns multiple results, we return an array with cursor properties appended to the array. For example:
```ts
import { get } from 'ronin';

const posts = await get.posts();

posts.moreAfter;
//      ^? string
posts.moreBefore;
//      ^? string

const morePosts = await get.posts.after(posts.moreAfter);
```

**Comment by EskiMojo14** [comment]
to my knowledge, the request is serialised as JSON, so the client will not receive the special Array subclass. the typescript error prevents you from returning anything that will not be serialised correctly.

**Comment by EskiMojo14** [comment]
@nikitavoloboev if you ignore the TS error and try logging the special properties, do they actually exist on the client?

**Comment by nikitavoloboev** [comment]
> if you ignore the TS error and try logging the special properties, do they actually exist on the client?

This is what gets sent to client:

<img width="601" alt="Image" src="https://github.com/user-attachments/assets/611b6595-ef99-454e-8028-384366553bdd" />

**Comment by EskiMojo14** [comment]
and is that a standard array, or does it have the extra properties added by Ronin?

**Comment by EskiMojo14** [comment]
as a workaround, you can return something that *will* serialise:
```ts
const { moreBefore, moreAfter } = posts
return { posts: [...posts], moreBefore, moreAfter }
```

**Comment by nikitavoloboev** [comment]
I am going to wait for @NuroDev to answer this as I am out of my depth here

I basically just want to use ronin queries that return `[]` and have it work, all typed like it did in earlier tanstack start versions with serverFn

**Comment by EskiMojo14** [comment]
![Image](https://github.com/user-attachments/assets/23d59c06-0f29-4851-8ff9-8c4dc4585392)

**Comment by EskiMojo14** [comment]
> as a workaround, you can return something that _will_ serialise:
> 
> const { moreBefore, moreAfter } = posts
> return { posts: [...posts], moreBefore, moreAfter }
> // or
> return { posts: posts as Array<Post>, moreBefore, moreAfter }
> // since you know that it'll serialise to an array properly, just without the extra properties

you could make a reusable util for this to avoid repetition:
```ts
type QueryPaginationOptions = {
  moreBefore?: (string | null) | undefined;
  moreAfter?: (string | null) | undefined;
};

const ensureSerializeable = <T,>(
  specialArray: ReadonlyArray<T> & QueryPaginationOptions,
): { records: ReadonlyArray<T> } & QueryPaginationOptions => ({
  records: specialArray,
  moreBefore: specialArray.moreBefore,
  moreAfter: specialArray.moreAfter,
});
```
![Image](https://github.com/user-attachments/assets/8a5a8142-75ac-420a-ae46-5d883ff82b05)
![Image](https://github.com/user-attachments/assets/0878aa74-1251-4fef-bc16-b225d7375b6b)

**Comment by nikitavoloboev** [comment]
Thank you lots @EskiMojo14, for now I am doing the `[...roninRecords]` trick and it works for me.

Will close the issue as this will be fixed by RONIN team and @NuroDev in near future.
