### ISSUE TITLE
Whole app flickers when use Lazy loaded component or Route

### ISSUE THREAD

**Issue by arikchakma** [TanStack/router#3038]
### Which project does this relate to?

Router

### Describe the bug

When I try to use any lazy-loaded component or even lazy route the whole body remounts, and shows a flicker. I have attached a video of the bug.

### Your Example Website or App

https://github.com/arikchakma/tanstack-router-flicker-bug

### Steps to Reproduce the Bug or Issue

1. Run the app -> `pnpm dev`
2. Open the preview
3. Click the `Show Bar` button
4. You will see a flicker of the whole page.

### Expected behavior

As a user, I expect it might be just a flicker for the `Bar` component, not the whole app.

### Screenshots or Videos

https://github.com/user-attachments/assets/dbee0dc0-0cba-4d66-bab2-47a49c6d073e

### Platform

- OS: macOS
- Browser: Brave (Chrome)
- Version:  1.73.101 Chromium: 131.0.6778.139 (Official Build) (arm64)

**Comment by schiller-manuel** [comment]
you need to add a suspense barrier:

``tsx
<Suspense>
      <Foo />
</Suspense>
```

otherwise, the whole route component will suspend

**Comment by arikchakma** [comment]
> you need to add a suspense barrier:
> 
> <Suspense>
>       <Foo />
> </Suspense>
> otherwise, the whole route component will suspend

Thanks a lot🙏 My skill issue 😆
