### ISSUE TITLE
Error importing a re-exported MUI icon

### ISSUE THREAD

**Issue by NickR49** [TanStack/router#3063]
### Which project does this relate to?

Start

### Describe the bug

Spin up the basic TanStack Start example, install `@mui/icons-material@5 @emotion/react @emotion/styled` and on any page add -
```
import { Print } from '@mui/icons-material'
```
and
```
<Print />
```
and it works as expected.

However, create an `Icons.tsx` file with -
```
import PdfIcon from '@mui/icons-material/Print'

export { PdfIcon }
```
and update the page to use -
```
import { PdfIcon } from '~/components/Icons'
```
and
```
<PdfIcon />
```
and the icon no longer renders and the following is shown -

```
Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-fnmojlvh?file=app%2Froutes%2Findex.tsx,package.json,app%2Fcomponents%2FIcons.tsx&preset=node

### Steps to Reproduce the Bug or Issue

1. On the Welcome page see that directly using the MUI print icon renders successfully
2. In the `index.tsx` file import and render `PdfIcon` instead
3. The icon fails to render and an error displays -

```
ServerFn Response: 500
 - Payload: {"$error":{"message":"Context is not available","stack":"Error: Context is not available\n    at Obj...

Warning: React.jsx: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
 ```

### Expected behavior

I was hoping that re-exporting the MUI icon would work the same as it has for me within other Next and Vite apps

### Platform

- OS: MacOS 15.2
- Browser: Chrome 131 and Opera 114

**Comment by NickR49** [comment]
If I switch to using a named import in the `Icons.tsx` file it works -
```
import { Print as PdfIcon } from '@mui/icons-material';

export { PdfIcon };
```

**Comment by schiller-manuel** [comment]
most likely a dead-code-elimination bug

**Comment by schiller-manuel** [comment]
during SSR, vite uses ESM. the `@mui/icons-material` has an `esm` folder, but it misses an `exports` section in the `package.json`.

There are a few solutions to resolve this, one would be to manually configure vite to use the correct ESM files:

```tsx
import { defineConfig } from '@tanstack/start/config'

export default defineConfig({
  vite: {
    resolve: {
      alias: {
        '@mui/icons-material': '@mui/icons-material/esm',
      },
    },
    ssr: {
      noExternal: ['@mui/icons-material'],
    },
  },
})
```

Another option is to patch the `package.json` of the packge to include the `exports` section.
