### ISSUE TITLE
Unable to override basepath for api routes

### ISSUE THREAD

**Issue by aarjithn** [TanStack/router#3080]
### Which project does this relate to?

Start

### Describe the bug

It is sometimes required to setup tanstack start app with a basepath.
For the router, it is possible to pass a `basepath` to `createTanStackRouter`
For server fns, it is possible to set this in app.config.ts

```
  routers: {
    server: {
      base: '/path/_server',
    },
```

However, the config apiBase doesn't seem to work with a custom basepath.

```
tsr: {
    apiBase: '/api',
    // apiBase: '/path/api', <- throws 503 Server unavailable
  },
```

And this makes it impossible to define api routes inside a subpath.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-rfnhqhpv?file=app.config.ts

### Steps to Reproduce the Bug or Issue

1. In attached stackblitz, update apiBase with a base url (uncomment line 25 - /path/api)
2. Note error 503 Server Unavailable

### Expected behavior

Should be able to provide a custom basepath for api routes, like the router itself

### Screenshots or Videos

<img width="1293" alt="Image" src="https://github.com/user-attachments/assets/7efaf476-2dd8-4656-ba58-b0963af6aa48" />

### Platform

- OS:  macOS
- Browser: Chrome

**Comment by SeanCassiere** [comment]
Once you've changed the `apiBase` to `/path/api`, you need to change and update your API route files to match the new pathing.

So, these files need to have their locations changed as well. So in `app/routes`,

<table>
<tr>
 <td>Old Location</td>
 <td>New Location</td>
 <td>Alternate Location</td>
</tr>
<tr>
 <td>api/users.ts</td>
 <td>path/api/users.ts</td>
 <td>path.api/users.ts</td>
</tr>
<tr>
 <td>api/users.$id.ts</td>
 <td>path/api/users.$id.ts</td>
 <td>path.api/users.$id.ts</td>
</tr>
</table>

**Comment by aarjithn** [comment]
@SeanCassiere Thank you for responding - do you think it is a bit confusing because we don't have to do that for file routes, only API routes?

**Comment by SeanCassiere** [comment]
> @SeanCassiere Thank you for responding - do you think it is a bit confusing because we don't have to do that for file routes, only API routes?
> 
> i.e, for file routes base path prefix is "automatic" once added in config, no need to rename files themselves 

Not in my opinion, since file routing also uses the similar keys which require changes to your file structure.

That being said, we are exploring other ways doing API routes that could make this easier.

**Comment by omridevk** [comment]
@SeanCassiere also seems the case that this doesn't work for API routes defined in the same file as the file route, I assume I am expected to move those to a different location, but seems weird, I would like to have those in the same file as technically they have the same URL

**Comment by SeanCassiere** [comment]
> [@SeanCassiere](https://github.com/SeanCassiere) also seems the case that this doesn't work for API routes defined in the same file as the file route, I assume I am expected to move those to a different location, but seems weird, I would like to have those in the same file as technically they have the same URL

I’m not sure I quite understand what you mean here.

Either ways, you can’t have both a component route and a server route live at the same path since that’d be a route matching conflict.

If you’ve found a bug you may want to open a new issue, or pop in on Discord and ask a question there.
