### ISSUE TITLE
error TS2344: Type 'TGenerics' does not satisfy the constraint 'Partial<DefaultGenerics>'

### ISSUE THREAD

**Issue by mickdelaney** [TanStack/router#322]
### Describe the bug

Compiler error when I try to build a distribution using typescript & vite 

 

### Your Example Website or App

https://github.com/mickdelaney/relay-recoil-post

### Steps to Reproduce the Bug or Issue

yarn install
yarn build

### Expected behavior

expect it to build. 
it runs fine when I use _yarn dev_

### Screenshots or Videos

![Uploading image.png…]()

### Platform

- OS: macOS & Linux
- Browser: [e.g. Chrome, Safari, Firefox]
- node: v16.16.0
- Version: 
@tanstack/react-location": "^3.7.4"
@tanstack/react-location-devtools": "^3.4.4"

### Additional context

it runs fine on **yarn dev**

**Comment by gius** [comment]
Might be related to the latest typescript version. Happened to me after upgrading dependencies.

**Comment by gius** [comment]
Meanwhile, you can add `"skipLibCheck": true` to your tsconfig.json

**Comment by tannerlinsley** [comment]
TanStack Router has much better generics now.
