### ISSUE TITLE
Text in devtools get progressively smaller

### ISSUE THREAD

**Issue by josh-degraw** [TanStack/router#329]
### Describe the bug

In the devtools panel, many elements are styled with `0.9em`. Since this is the relative size of the text around it, the effect of this is that nodes get progressively smaller until it becomes unreadable. I believe that updating it to `0.9rem` should accomplish the desired effect.

### Steps to Reproduce the Bug or Issue

1. Add react location
2. Add the `react-location-devtools` to the project
3. Add a few levels of nested routing
4. Open the devtools and expand the items

### Expected behavior

I should be able to read the items in the devtools

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/18509575/191849812-82299ecc-2ba4-42dd-bece-17662955c1ab.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by tannerlinsley** [comment]
Should be fixed. Thanks!
