### ISSUE TITLE
Router docs say `<title>Overview | TanStack Table Docs</title>`

### ISSUE THREAD

**Issue by tordans** [TanStack/router#330]
### Describe the bug

The title tag of the router docs say "table" instead of "router"

### Your Example Website or App

https://tanstack.com/router/v4/docs/guide/introduction

### Steps to Reproduce the Bug or Issue

`view-source:https://tanstack.com/router/v4/docs/guide/introduction` => `<title>Overview | TanStack Table Docs</title>`

### Expected behavior

It says `<title>Overview | TanStack Router Docs</title>`

### Platform

./.

**Comment by tannerlinsley** [comment]
Fixed!
