### ISSUE TITLE
Vite throws Uncaught ReferenceError: regeneratorRuntime is not defined when using cache

### ISSUE THREAD

**Issue by wsfuller** [TanStack/router#337]
### Describe the bug

Having bug when trying to use SimpleCache with Vite. My route runs as expected when not use cache, but as soon as it's used get the following error:

<img width="793" alt="Screen Shot 2022-10-12 at 3 24 33 PM" src="https://user-images.githubusercontent.com/3144419/195459196-89f9560d-9c0e-4136-bc8a-b74ef6f31fae.png">

First example will be working, second will be what throws the error

```
App.tsx (working without simple cache)

const routes: Route[] = [
  {
    path: "/",
    element: <Home />,
  },
  {
    path: "items",
    element: <Items />,
    loader: async () => ({
      items: await getItems(),
    }),
    pendingElement: async () => (<div>...</div>),
    pendingMs: 1000,
  }
];

function App() {
  return (
    <div className="App">
      <Router routes={routes} location={location}>
        <Root />
        <ReactLocationDevtools initialIsOpen={false} />
      </Router>
    </div>
  );
}

export default App;
```

```
App.tsx (breaks using simple cache)

import { ReactLocationSimpleCache } from "@tanstack/react-location-simple-cache";

const routeCache = new ReactLocationSimpleCache();

const routes: Route[] = [
  {
    path: "/",
    element: <Home />,
  },
  {
    path: "items",
    element: <Items />,
    loader: routeCache.createLoader(async () => ({
      items: await getItems(),
    })),
    pendingElement: async () => (<div>...</div>),
    pendingMs: 1000,
  }
];

function App() {
  return (
    <div className="App">
      <Router routes={routes} location={location}>
        <Root />
        <ReactLocationDevtools initialIsOpen={false} />
      </Router>
    </div>
  );
}

export default App;
```

I've tried using the suggestions in https://github.com/TanStack/router/issues/227 with using `regeneratorRuntime` at the top level of the app but that doesn't seem to do anything.

Opening this bug here as it only happens when using SimpleCache and doesn't get thrown otherwise

### Your Example Website or App

https://github.com/TanStack/router/issues/227

### Steps to Reproduce the Bug or Issue

1. `yarn create vite --template react-ts`
2. `yarn`
3. `yarn add @tanstack/react-location @tanstack/react-location-simple-cache`
4. Wrap working loader in cache

### Expected behavior

Would assume following the docs this would work 🤷 

### Platform

- OS: macOS
- Browser: Chrome
- Version: 106

**Comment by tannerlinsley** [comment]
You'll need to include the babel runtime.
