### ISSUE TITLE
Install command shown on TanStack docs does not work

### ISSUE THREAD

**Issue by StevenStavrakis** [TanStack/router#338]
### Describe the bug

Running:  `npm install @tanstack/router --save` results in a 404 error.

```
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@tanstack%2frouter - Not found
npm ERR! 404 
npm ERR! 404  '@tanstack/router@*' is not in this registry.
```

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

1. Go to [https://tanstack.com/router/v4/docs/guide/installation](https://tanstack.com/router/v4/docs/guide/installation)
2. Follow NPM installation instructions
3. Error

### Expected behavior

I would expect the installation to work

### Platform

- OS: WSL 2
- Browser: n/a
- Version: n/a

**Comment by wsfuller** [comment]
+1, was trying to replace the `@tanstack/react-location` installation with `yarn add @tanstack/router` and it is not found in the registry

**Comment by slashwhatever** [comment]
Same. Kinda feels like this should be a priority? :D

**Comment by Moshyfawn** [comment]
Check out [the latest BETA router version](https://tanstack.com/router/v1/docs/adapters/react-router): `npm install @tanstack/react-router`
