### ISSUE TITLE
React Router adapter docs do not exist?

### ISSUE THREAD

**Issue by obouchari** [TanStack/router#343]
### Describe the bug

I get a 404 when I try to view any of the adapters docs.

### Your Example Website or App

https://tanstack.com/router/v4/docs/adapters/react-router

### Steps to Reproduce the Bug or Issue

1. go to https://tanstack.com/router/v4/docs/adapters/react-router
2. you will see a 404.

### Expected behavior

Finding an actual doc?

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by tannerlinsley** [comment]
They’re not done yet. Sorry!

Tanner Linsley
Sent with Spark

**Comment by tannerlinsley** [comment]
fixed!
