### ISSUE TITLE
Link in polymorphic component

### ISSUE THREAD

**Issue by totomakers** [TanStack/router#352]
### Describe the bug

Using `router.Link` in Polymorphic make a TS error. But look like render well

### Your Example Website or App

https://codesandbox.io/s/cocky-sanderson-mnl8r1?file=/src/Example.tsx

### Steps to Reproduce the Bug or Issue

1. Go to Example.tsx

### Expected behavior

`ExampleButton` should work and render as `a`

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/284379/200863885-6287bd12-4229-48dd-b178-0233a4e4106d.png)

### Platform

- OS: Windows
- Browser: Chrome

**Comment by tannerlinsley** [comment]
Polymorphic component types are problematic regardless of router. I don’t plan on supporting them. You can use the router.linkProps() function instead.
