### ISSUE TITLE
React Location dev tools isn't hidden in production

### ISSUE THREAD

**Issue by mhesham32** [TanStack/router#356]
### Describe the bug

I have dev tools from React Query and React Location and when I deployed the app to production only react query dev tools was hidden but react location dev tools wasn't

### Your Example Website or App

https://heartfelt-lokum-be0567.netlify.app/

### Steps to Reproduce the Bug or Issue

put the tools component under the Router component
```
<ReactLocationDevtools position="top-right" />
```

### Expected behavior

I'm expecting it to be not included in the prod build same as React Query tools

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/26179375/201170437-19123284-53f1-4b6b-9667-df6ee95c48fd.png)
![image](https://user-images.githubusercontent.com/26179375/201171684-4fb1d5e5-72ae-4750-bb15-04be703f228a.png)

### Platform

- OS: Windows
- Browser:Chrome
- Version: 107

**Comment by tannerlinsley** [comment]
https://tanstack.com/router/v1/docs/devtools#only-importing-and-using-devtools-in-production

**Comment by mhesham32** [comment]
thanks, I think I will use that. but shouldn't it be hidden in production even if it was imported at the top

**Comment by mhesham32** [comment]
also, I'm using this two packages
```js
import { Router, ReactLocation } from '@tanstack/react-location';
import { ReactLocationDevtools as RLD } from '@tanstack/react-location-devtools';
```
the one mentioned in the link is `@tanstack/react-router-devtools` which one should I use?

**Comment by tannerlinsley** [comment]
You can accomplish the same pattern with the react-location imports. Should work fine!

**Comment by mhesham32** [comment]
thanks, I got an error doing that so I ended up importing it like this
```js
const ReactLocationDevtools =
  process.env.NODE_ENV === 'production'
    ? () => null // Render nothing in production
    : lazy(() =>
        import('@tanstack/react-location-devtools').then((m) => ({
          default: m.ReactLocationDevtools,
        }))
      );
```

**Comment by IanVS** [comment]
FWIW, it looks like the name has changed from `ReactLocationDevtools` to `TanStackRouterDevtools`.  Thanks for the tip about the `default` export, @mhesham32.

**Comment by nktnet1** [comment]
The documentation has been moved here:
- https://tanstack.com/router/v1/docs/framework/react/devtools#only-importing-and-using-devtools-in-development
