### ISSUE TITLE
Nested params typescript

### ISSUE THREAD

**Issue by XpamAmAdEuS** [TanStack/router#365]
### Describe the bug

All working very nice when params are at last place and typescript not complain.

`const {
    navigate,
    search: { musicView },
  } = router.useMatch('/admin/music/list');`

`function navigateToMusicId(id: EntityId) {
    navigate({ to: '/admin/music/:musicId', params: { musicId: id } });
  }`

Problem comes if using  params in middle of route, 
TS2339: Property 'customerId' does not exist on type 'Record '.
 but params are there and working as they should.

`const {
    navigate,
    params: { customerId, customerTitle },
    search: { sitesView },
  } = router.useMatch('/customer/:customerId/:customerTitle/sites/list');`

Anotther issue its about using Link or navigate when params are in middle then we get route without params /customer/:customerId/:customerTitle/sites/wizard

`function navigateToWizard(customerId,customerTitle) {
    navigate({
 to:`/customer/:customerId/:customerTitle/sites/wizard`, 
params: { customerId: customerId,customerTitle: customerTitle } });
}`
this generate link as without values

`/customer/:customerId/:customerTitle/sites/wizard`

 but passing param values directly working

` const navigateToWizard = () => {
    // @ts-ignore
    navigate({
      to: `/customer/${customerId}/${customerTitle}/sites/wizard`,
    });
  };` 

### Your Example Website or App

*

### Steps to Reproduce the Bug or Issue

*

### Expected behavior

Typescript not complain and params can be in middle

### Platform

*

### Additional context

sry for my bad english and no  example app

**Comment by jrobeson** [comment]
It's not just middle, but it's also at the beginning (which i guess counts as middle with `/`)

**Comment by XpamAmAdEuS** [comment]
Closed as this example much better describe problem https://github.com/TanStack/router/issues/368

**Comment by XpamAmAdEuS** [comment]
Closed as this example much better describe problem https://github.com/TanStack/router/issues/368
