### ISSUE TITLE
params in nested route cause TypeScript errors

### ISSUE THREAD

**Issue by MarkLyck** [TanStack/router#368]
### Describe the bug

I found a TypeScript error with using params through `useMatch` in a nested route.

When you have 2 routes e.g.:

```ts
export const manageRoute = rootRoute.createRoute({
  path: 'manage/:resource',
})
export const manageCreateRoute = manageRoute.createRoute({
  path: 'create',
  component: CreateComponent,
})
```

and you want to access `:resource` from params in `useMatch` all 3 ways I have tried resulted in different errors.

- Method 1, using the direct route:

```ts
const {
    params: { resource },
  } = router.useMatch(manageCreateRoute.id);
```

TypeScript Error: `Property 'resource' does not exist on type 'Record<never, string>'.`

- Method 2, using the parent route:

```ts
const {
    params: { resource },
  } = router.useMatch(manageRoute.id);
```

This has no TypeScript errors, but instead throws an error because it could be an unintended route:
I believe this is intended behavior.

error:
```
@tanstack_react-router.js?v=de1a6e7f:780 Uncaught Error: Invariant failed: useMatch('/manage/:resource') is being called in a component that is meant to render the '/manage/:resource/create' route. Did you mean to 'useMatch(/manage/:resource, { strict: false })' or 'useRoute(/manage/:resource)' instead?
```

- Method 3, using `{ strict: false }`

```ts
const {
    params: { resource },
  } = router.useMatch(manageRoute.id, { strict: false });
```

TypeScript error:

```
Property 'params' does not exist on type 'RouteMatch<AllRouteInfo<RouteConfig<"__root__", string, string, "", {}, AnyLoaderData, {}, unknown, unknown, {}, AnySearchSchema, {}, {}, Record<never, string>, {}, RouteConfig<...>[]>>, RouteInfo<...>> | undefined'.
```

---

Method 1 and 3 both "work" in that `resource` actually does exist on the params. But TypeScript insists it does not.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-beajhl?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

1. Go to https://stackblitz.com/edit/vitejs-vite-beajhl?file=src/App.tsx
2. run `npm install && npm run dev`
3. Append the Stackblitz URL with: `/manage/test-resource-1/create`
4. See `ManageCreate test-resource-1` being rendered, but notice TypeScript error in the code.
5. Try the 2 other methods that are commented out and see their errors.

### Expected behavior

if `resource` exists on `params` I would expect there not to be a TypeScript error saying it doesn't exist. 

### Platform

- OS: macOS
- Browser: Brave
- Version: 1.45.143

**Comment by tannerlinsley** [comment]
Fixed in latest version! Ping here if you find otherwise.

**Comment by MarkLyck** [comment]
Thanks, this seems to be working now in beta.23
