### ISSUE TITLE
Trailing and non trailing slash URLs match differently

### ISSUE THREAD

**Issue by jprosevear** [TanStack/router#370]
### Describe the bug

URLs ending in / do match the same as without the /

Examples:
https://tanstack-router-qubofu--3000.local-credentialless.webcontainer.io/posts
https://tanstack-router-qubofu--3000.local-credentialless.webcontainer.io/posts/

Original discord thread
https://discord.com/channels/719702312431386674/1007702008448426065/1042574527592402994

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-qubofu?file=src/main.tsx

### Steps to Reproduce the Bug or Issue

1. Go to https://tanstack-router-qubofu--3000.local-credentialless.webcontainer.io/
2. Click on PostsNoSlash and PostsNoSlash
3. See that Level 2 renders on one and not the other (also note in the latter, both are marked active)

### Expected behavior

As a user I expected to see Level2 present in both.

### Platform

React 17

**Comment by tannerlinsley** [comment]
Pretty sure this is fixed in the latest version. Ping me if not!

**Comment by jprosevear** [comment]
@tannerlinsley updated the version in the stackblitz, same problem

**Comment by dcastil** [comment]
I have the same problem on `@tanstack/react-router@0.0.1-beta.25`.
