### ISSUE TITLE
`navigate({ search })` Typescript error

### ISSUE THREAD

**Issue by MarkLyck** [TanStack/router#371]
### Describe the bug

I upgraded from beta.16 to beta.23 and my implementation from `navigate({ search })` is now throwing the following typescript error on all pages:

```
Type '(old: never) => any' is not assignable to type '(current: never) => never'.
  Type 'any' is not assignable to type 'never'.
```

example:

```ts
const { search, navigate } = useMatch(dashboardRoute.id)

const onClick = (item: any) => {
  navigate({
    search: (old) => ({
      ...old,
      selected: item.id,
    }),
    replace: true,
  })
}
```

Minimal reproducible route for the errror

```ts
export const dashboardRoute = layoutRoute.createRoute({
  path: '/',
  component: Dashboard,
  validateSearch: z.object({
    selected: z.number().optional(),
  }),
})
```

in beta.16 this would not throw a TypeScript error.

### Your Example Website or App

Let me know if you need a full reproduction.

### Steps to Reproduce the Bug or Issue

```ts
const { search, navigate } = useMatch(dashboardRoute.id)

const onClick = (item: any) => {
  navigate({
    search: (old) => ({
      ...old,
      selected: item.id,
    }),
    replace: true,
  })
}
```

### Expected behavior

should not throw a typescript error.

### Platform

"@tanstack/react-router": "0.0.1-beta.23",

**Comment by tannerlinsley** [comment]
Should be fixed in latest version (give it a minute to release)
