### ISSUE TITLE
`errorComponent` is missing prop types.

### ISSUE THREAD

**Issue by MarkLyck** [TanStack/router#373]
### Describe the bug

The `errorComponent` on a route passes the following props by default:

```
{
    "error": {},
    "info": {
        "componentStack": "... stack here ..."
    }
}
```

But if you try to use `error` or `info` it will throw a TypeScript error like:

```
Property 'error' does not exist on type '{} | undefined'.
Property 'info' does not exist on type '{} | undefined'.
```

Example route:

```
export const indexRoute = roorRoute.createRoute({
  path: '/',
  component: Index,
  errorComponent: ({ error }) => {
    return <div>error: {error.message}</div>
  }
})
```

Looking at the router code it uses this type:

```
errorComponent?: GetFrameworkGeneric<'Component'> 
```

same as `component`. This should have a type that includes the error props.

### Your Example Website or App

see simple route example above

### Steps to Reproduce the Bug or Issue

1. use `errorComponent` with error prop

### Expected behavior

error and info should exist on errorComponent props

### Platform

"@tanstack/react-router": "0.0.1-beta.23",

**Comment by MarkLyck** [comment]
![Screen Shot 2022-11-19 at 11 32 58](https://user-images.githubusercontent.com/6841110/202861472-0c419bcf-671a-417a-b467-92907bca4b0e.png)

**Comment by tannerlinsley** [comment]
You sure that’s the latest version?

Tanner Linsley

**Comment by MarkLyck** [comment]
You're right, I made this comment at the same time as the other issue. Clearing node_modules & re-installing fixed it.
