### ISSUE TITLE
navigate({ search }) TypeScript error in beta.25

### ISSUE THREAD

**Issue by MarkLyck** [TanStack/router#375]
### Describe the bug

After upgrading to beta.25 all uses of `navigate({ search })` now results in the following TS error:

```
Type 'any' is not assignable to type 'never'.
```

example:
```ts
navigate({
      search: (old) => ({
        ...old,
        resource: newResource,
        selected: undefined,
      }),
      replace: true,
    })
```

### Your Example Website or App

see example above, let me know if you need a StackBlitz

### Steps to Reproduce the Bug or Issue

![Screen Shot 2022-11-19 at 11 48 44](https://user-images.githubusercontent.com/6841110/202862167-43575a41-b5db-4fbb-b4ca-5cc81e7e4743.png)

Note this happens both with `useNearestMatch()` and `useMatch(route.id)`

### Expected behavior

Should not cause TS error

### Platform

"@tanstack/react-router": "0.0.1-beta.25",

**Comment by tannerlinsley** [comment]
A stackblitz would be great.

**Comment by MarkLyck** [comment]
@tannerlinsley Sorry this was my bad, I had an outdated node_modules.

I can still reproduce an issue but only with `useNearestMatch()` now, which I imagine is the same problem as https://github.com/TanStack/router/issues/372

Here's a stackblitz where search gives a TypeScript error for `useNearestMatch()`

https://stackblitz.com/edit/tanstack-router-af8ox9?file=src/main.tsx

**Comment by StringKe** [comment]
So can search be empty?

**Comment by tannerlinsley** [comment]
I believe you should have a much better experience now. Give it a shot!
