### ISSUE TITLE
basepath breaks route matching

### ISSUE THREAD

**Issue by kbrah** [TanStack/router#381]
### Describe the bug

adding basepath to the router causes all routes  to not match at all. 

Also in the basic stackblitz example, the index route does not match even in the current state (without basepath)

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-gdpsep?file=src/main.tsx

### Steps to Reproduce the Bug or Issue

Add basepath to the basic stackblitz example provided in the docs.

### Expected behavior

routes to match normally

### Platform

Linux, Chrome

**Comment by tannerlinsley** [comment]
This should be fixed in the latest version!
