### ISSUE TITLE
route errors cannot recover by navigating to a "safe" route.

### ISSUE THREAD

**Issue by MarkLyck** [TanStack/router#383]
### Describe the bug

When an error happens that is Caught by the @tanstack/react-router ErrorBoundary it will render the errorComponent correctly.

But if the error is only on a specific route, As a user I would expect to be able to go to another route that doesn't have an error, and have the router and app recover.

However right now, if a route error happens, then navigating to other routes does not make the error go away. The error will stay visible and it looks like the routing breaks completely?

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-9ynm2n?file=src/main.tsx

### Steps to Reproduce the Bug or Issue

1. go to https://stackblitz.com/edit/tanstack-router-9ynm2n?file=src/main.tsx
2. See error coming from the `Index` component
3. Try to navigate to the /posts route (which does not cause an error normally)
4. Error still exists and user cannot see the Posts route.

### Expected behavior

When a Route error component is rendered at a specific route, but other routes do work. I expect to be able to click on a Link to another working route and for the router and app to recover and be useable.

In the above example I caused en error by trying to use `useLocation()` from another router, inside a component not wrapped in it. This specific example is not important I think? Just that it causes a breaking error.

### Platform

"@tanstack/react-router": "0.0.1-beta.25",

**Comment by tannerlinsley** [comment]
The latest version and setup should fix this scenario. Here's an example: https://stackblitz.com/edit/tanstack-router-u3upzj?file=src%2Fmain.tsx,package.json

Note that the `RouterProvider` no longer accepts children and the root route's `component` should be used instead.
