### ISSUE TITLE
Link onClick preventDefault doesn't work

### ISSUE THREAD

**Issue by fnn** [TanStack/router#387]
### Describe the bug

The usage of event.preventDefault() inside an onClick handler on the Link component will not prevent the navigation.
This works with HTML anchors and react-location Link component.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-kqww9m?file=src/main.tsx

### Steps to Reproduce the Bug or Issue

1. Add onClick handler with preventDefault() to Link component
2. Click link

### Expected behavior

As a user I expected, that the page navigation will be prevented but it got triggered anyway.

### Platform

- OS: Linux
- Browser: Chromium
- Version: 104.0.5112.79

**Comment by wizzymore** [comment]
On `<Link />` elements try to use onClickCapture to prevent the event.

**Comment by tannerlinsley** [comment]
This should be fixed on the latest version 👍
