### ISSUE TITLE
Bad docs link

### ISSUE THREAD

**Issue by s-cork** [TanStack/router#403]
### Describe the bug

Docs for route-paths has a bad link to layout-routes

### Your Example Website or App

https://tanstack.com/router/v1/docs/guide/route-paths

### Steps to Reproduce the Bug or Issue

See: https://tanstack.com/router/v1/docs/guide/route-paths
- At the bottom click the link to Layout Routes
- observe the link takes you to https://tanstack.com/router/v1/docs/layout-routes
  rather than: https://tanstack.com/router/v1/docs/guide/layout-routes

### Expected behavior

correct link

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by Moshyfawn** [comment]
It has been fixed
