### ISSUE TITLE
adding a `basepath` breaks nesting

### ISSUE THREAD

**Issue by she11sh0cked** [TanStack/router#406]
### Describe the bug

adding a `basepath` to the `<Router />` component breaks nesting. the error element is used instead of the nested element.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-bug?file=App.tsx

### Steps to Reproduce the Bug or Issue

1. create a `<Router />` with a set `basepath`
2. add a route with a nested child
3. navigate to the nested route
4. see white (or error element if provided)

If you remove the `basepath` it works as expected again.

### Expected behavior

Nested routes should work whether a `basepath` is set or not.

### Platform

- OS: EndeavourOS Linux x86_64
- Browser: Firefox 107.0.1 (64-bit)
- Version: @tanstack/react-location@^3.7.4

**Comment by she11sh0cked** [comment]
#381 Seems connected

**Comment by tannerlinsley** [comment]
This is fixed in the latest version of @tanstack/router
