### ISSUE TITLE
`<Link to='PATH'>` is not type safe (i.e `any`) 

### ISSUE THREAD

**Issue by scarf005** [TanStack/router#416]
### Describe the bug

in `<Link to='/'>`, type of `to` is `any`.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-e6p9jc?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

1. create a new `react-ts` instance on https://vitejs.dev/guide/#trying-vite-online
2. install `npm install @tanstack/react-router@beta --save`
3. copy and paste example at https://tanstack.com/router/v1/docs/quick-start to `App.tsx`
4. when hovering over `<Link to='/'>`, type of `to` is `any`.

### Expected behavior

parameter `to` is type safe.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/54838975/205577593-af0f1d7a-f44d-45ea-962f-9926dd16acd5.png)

### Platform

- OS: Linux
- Browser: Firefox
- Version: 108.0b9

**Comment by tannerlinsley** [comment]
Try registering your router like so: https://github.com/TanStack/router/blob/beta/examples/react/kitchen-sink-single-file/src/main.tsx#L817

**Comment by scarf005** [comment]
yes, it works now, thank you. however, is this declaration mandatory for all projects? or have the changes haven't made into main branch?

**Comment by tannerlinsley** [comment]
Beta is the primary branch right now.

**Comment by scarf005** [comment]
installed beta branch with `npm install @tanstack/react-router@beta --save`.
version on `package.json` is ` "@tanstack/react-router": "^0.0.1-beta.28",`.
then is it fixed in primary branch?

**Comment by tannerlinsley** [comment]
Yes, this is fixed!

**Comment by scarf005** [comment]
could you check them again? `to` is still `any` unless given module declaration in `0.0.1-beta.36`
repro: https://stackblitz.com/github/tanstack/router/tree/beta/examples/react/quickstart?file=src/main.tsx

**Comment by tannerlinsley** [comment]
You need the declaration merging.

**Comment by scarf005** [comment]
could you elaborate? I'm not sure how to merge them, do I import their types into one file?
