### ISSUE TITLE
ReactLocationDevTools visible in production

### ISSUE THREAD

**Issue by tumbledwyer** [TanStack/router#417]
### Describe the bug

Firstly, I'm using React Location, but there doesn't seem to be a repo anymore as the links all point here.

ReactLocationDevTools is only supposed to be visible when NODE_ENV="development" however, even when the env is set to production when serving after a yarn build, the dev tools are still visible.
Interestingly, the ReactQueryDevTools do disappear when the env changes to prod, as expected.

Replicated this in codesandbox as well as in my app.

### Your Example Website or App

https://codesandbox.io/s/stupefied-rui-5f476q

### Steps to Reproduce the Bug or Issue

Run `yarn build`
Run `serve -s build`

### Expected behavior

Dev tools should not be visible, however, they are.

### Platform

- OS: [Windows with WSL]
- Browser: [Chrome, Firefox]
- Version: [3.4.4]

**Comment by jameshiester** [comment]
Did you try these steps: https://tanstack.com/router/v1/docs/devtools#only-importing-and-using-devtools-in-production should be similar for the legacy React Location devtools based on https://github.com/TanStack/router/issues/356

**Comment by tannerlinsley** [comment]
Although React Query works this way, the solution above is the new suggested way. Create a lazy import and only render it in development (or production behind a flag or admin button)

**Comment by tumbledwyer** [comment]
Awesome, that works. Thanks for all the quick replies. Looking forward to Tanstack router getting out of Beta!

**Comment by nktnet1** [comment]
P.s. docs have been moved here:
- https://tanstack.com/router/v1/docs/framework/react/devtools#only-importing-and-using-devtools-in-development
