### ISSUE TITLE
Quick start fails with `Property 'children' does not exist on type`

### ISSUE THREAD

**Issue by scarf005** [TanStack/router#425]
### Describe the bug

`RouterProvider` complains that it does not have property 'children', which makes even the example quick start unable to run.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-ff88yw?file=src/App.tsx

### Steps to Reproduce the Bug or Issue

1. install latest package version (^0.0.1-beta.32)
2. copy and paste [example code](https://tanstack.com/router/v1/docs/quick-start) from documentation 

### Expected behavior

there should not be an type error.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/54838975/206079370-40fbd975-7ec9-4566-8054-8f0a2f37f3cc.png)

### Platform

- OS: Linux
- Browser: Firefox 
- Version: 108.0b9

### Additional context

error log:
```ts
Type '{ children: Element[]; router: Router<RouteConfig<"__root__", string, string, "", {}, AnyLoaderData, {}, {}, unknown, unknown, {}, AnySearchSchema, {}, {}, Record<never, string>, {}, (RouteConfig<...> | RouteConfig<...>)[]>, AllRouteInfo<...>, unknown>; }' is not assignable to type 'IntrinsicAttributes & RouterOptions<RouteConfig<"__root__", string, string, "", {}, AnyLoaderData, {}, {}, unknown, unknown, {}, AnySearchSchema, ... 4 more ..., (RouteConfig<...> | RouteConfig<...>)[]>, unknown> & { ...; }'.
  Property 'children' does not exist on type 'IntrinsicAttributes & RouterOptions<RouteConfig<"__root__", string, string, "", {}, AnyLoaderData, {}, {}, unknown, unknown, {}, AnySearchSchema, ... 4 more ..., (RouteConfig<...> | RouteConfig<...>)[]>, unknown> & { ...; }'.(2322)
```

**Comment by Moshyfawn** [comment]
`RouterProvider` doesn't accept children as `Root` `Outlet` as of [`0.0.1-beta.30`](https://github.com/TanStack/router/releases/tag/v0.0.1-beta.30), I believe.

You you pass your "`Root`" component as `component` prop to `createRouteConfig` like
```js
const rootRoute = createRouteConfig({
  component: () => (
    <>
      <Outlet />
      <TanStackRouterDevtools />
    </>
  )
})
```
