### ISSUE TITLE
useMatch Invariant failed with react 17

### ISSUE THREAD

**Issue by kbrah** [TanStack/router#434]
### Describe the bug

I'm using React 17. I have `const match = useMatch(addRoute.id)` in my component. When I navigate to a different route. I get Invariant failed.
![image](https://user-images.githubusercontent.com/10815813/206446126-ae0c0af3-7320-4a1d-8e9d-4b7f8a57ea4a.png)
Also this error
![image](https://user-images.githubusercontent.com/10815813/206446792-32f4070e-bdcc-4dad-94e9-368b126335f4.png)

My route is like this
```
export const addRoute = rootRoute.createRoute({
  path: "add",
  component: Add,
  validateSearch: z
    .object({
      ids: z.array(z.string()).optional(),
    })
    .optional(),
});
```

The navigation and all the functionality works however. 

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-nyjcvm?file=src/main.tsx

### Steps to Reproduce the Bug or Issue

In the basic example, change the React version to 17. (done in the linked stackblitz) 
Navigate from posts to home tab

### Expected behavior

no errors

### Platform

- OS: Linux
- Browser: Chromium
- Version: 0.0.1-beta.36

**Comment by kbrah** [comment]
I do expect it to always match. Anyways if I add `strict: false`, I still get a lot of errors in the console.

**Comment by tannerlinsley** [comment]
Fixed now.
