### ISSUE TITLE
Siblings to Outlet do not get rendered in RouterProvider

### ISSUE THREAD

**Issue by jameshiester** [TanStack/router#435]
### Describe the bug

When rendering the RouterProvider, only the Outlet is being rendered, other siblings will not be.  

 ```ts
<RouterProvider router={router} history={memoryHistory}>
     (This will not be rendered)
     <Outlet />
 </RouterProvider>
```

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

 ```ts
<RouterProvider router={router} history={memoryHistory}>
     (This will not be rendered)
     <Outlet />
 </RouterProvider>
```

### Expected behavior

I would expect all children of RouterProvider to be rendered 

(I am aware as an alternative I could use a layout route at the root of my config, but this behavior breaks the typical understanding of React components that accept children)

### Platform

- OS: Windows
- Browser: Chrome
- Version: beta.36

**Comment by tannerlinsley** [comment]
The RouterProvider no longer accepts children. Instead, utilize the root route component: https://github.com/TanStack/router/blob/beta/examples/react/basic/src/main.tsx#L21-L50
