### ISSUE TITLE
API details page is 404

### ISSUE THREAD

**Issue by netanelben** [TanStack/router#440]
### Describe the bug

Hey, awesome work! but please can you fix the 404 on page:
https://tanstack.com/router/v1/docs/api/core

would be helpful to read and understand each function specs.

Thanks

### Your Example Website or App

https://tanstack.com/router/v1/docs/api/core

### Steps to Reproduce the Bug or Issue

1. go to https://tanstack.com/router/v1/docs/api/core

### Expected behavior

none

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
Any.

**Comment by tannerlinsley** [comment]
Docs are getting fixed now. Thanks!
