### ISSUE TITLE
Docs: Title for example say `*React Virtual*`

### ISSUE THREAD

**Issue by tordans** [TanStack/router#446]
### Describe the bug

On https://tanstack.com/router/v1/docs/examples/react/basic?file=src%2Fmain.tsx it says

```
<title>React Virtual Basic Example | TanStack Virtual Docs</title>
```

On https://tanstack.com/router/v1/docs/examples/react/with-react-query?file=src%2Fmain.tsx it says

```
<title>React Virtual With React Query Example | TanStack Virtual Docs</title>
```

--- 

Ping https://github.com/TanStack/router/issues/330

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

-

### Platform

-

**Comment by judicaelandria** [comment]
@tannerlinsley fix for the react router example
https://github.com/TanStack/tanstack.com/pull/68

**Comment by judicaelandria** [comment]
this is now fixed @tordans , you can close this issue now thanks :)
