### ISSUE TITLE
preSearchFilter doesn't add provided search params to URL or search state

### ISSUE THREAD

**Issue by Moshyfawn** [TanStack/router#454]
### Describe the bug

With preSearchFilter specified, accessing route directly via URL doesn't add specified search params to the URL / search state.

When navigating to the route that's supposed to have default search params, the URL has the specified param, but the search state from `useMatch` doesn't contain the param value

### Your Example Website or App

https://codesandbox.io/p/sandbox/router-search-default-o7q8tu?selection=%5B%7B%22endColumn%22%3A41%2C%22endLineNumber%22%3A47%2C%22startColumn%22%3A41%2C%22startLineNumber%22%3A47%7D%5D&file=%2Fsrc%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Go to [repro](https://codesandbox.io/p/sandbox/router-search-default-o7q8tu?selection=%5B%7B%22endColumn%22%3A41%2C%22endLineNumber%22%3A47%2C%22startColumn%22%3A41%2C%22startLineNumber%22%3A47%7D%5D&file=%2Fsrc%2FApp.tsx)
2. Notice `?floor=1` is not in the URL / controlled "floor" input is empty **_<--(this is the first behaviour repro)_**
3. Go to "`/additional`" route _(Click "Additional" link next to the "floor" input)_
4. Go back to `"/"` route _(Click "Main" link)_
5. See URL contains `?floor=1` but the controlled "floor" input is empty  **_<--(this is the second behaviour repro)_**

### Expected behavior

I expect
1. To hit a route via URL and see default search params in both URL and search state
2. Search params in URL to by synced to search params state

### Screenshots or Videos

https://user-images.githubusercontent.com/16290753/207154033-dae4acd7-2cce-408b-915e-19ee5dec8616.mp4

### Platform

- OS: macOS
- Browser: Firefox
- Version: 108.0b9
    

### Additional context

```json
"dependencies": {
  "@tanstack/react-router": "0.0.1-beta.38",
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
  "zod": "^3.20.1"
}
```

**Comment by Moshyfawn** [comment]
Possibly related to #453

**Comment by jameshiester** [comment]
I'm also seeing this behavior.  Also, if I set default values in validateSearch, those values will appear in match.routeSearch but not when using useSearch.

**Comment by Moshyfawn** [comment]
Using [zod `.default()` operator](https://github.com/colinhacks/zod#default) negates the issue _(which is probably a better way of managing default search params)_. [Here's an example sandbox](https://codesandbox.io/p/sandbox/router-search-default-forked-gmeiu1?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A43%2C%22endLineNumber%22%3A51%2C%22startColumn%22%3A43%2C%22startLineNumber%22%3A51%7D%5D)

With the usage of `preSearchFilters`, the behaviour is less of an error, but more confusing: defaulting search param to a value does not set default search param in the URL, but is passed down the component as a value. Going to a different route and coming back yields the same result. [Here's an example sandbox](https://codesandbox.io/p/sandbox/router-search-default-forked-gnk80g?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A34%2C%22endLineNumber%22%3A51%2C%22startColumn%22%3A34%2C%22startLineNumber%22%3A51%7D%5D).

I'd expect `preSearchFilters` to update the URL search params.

Please, let me know what you think.

I'm gonna keep the issue open, but feel free to close it. I'd love either a clear guide on how to manage default search params "the right way" or a "fix" to the behaviour before the issue is closed, though.

**Comment by tannerlinsley** [comment]
This is a long running regression to bug. It’ll be fixed soon.

Tanner Linsley

**Comment by tannerlinsley** [comment]
Fixed in the next release!
