### ISSUE TITLE
Search params types are "global"

### ISSUE THREAD

**Issue by Moshyfawn** [TanStack/router#455]
### Describe the bug

While TS Router allows providing `validateSearch` per individual routes, the `search` state type when retrieving via `useMatch` grows with all `validateSearch` schema types provided to all routes

### Your Example Website or App

https://codesandbox.io/p/sandbox/wizardly-keldysh-eg821k?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A18%2C%22endLineNumber%22%3A40%2C%22startColumn%22%3A18%2C%22startLineNumber%22%3A40%7D%5D

### Steps to Reproduce the Bug or Issue

1. Go to [repro App.tsx line 51](https://codesandbox.io/p/sandbox/wizardly-keldysh-eg821k?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A63%2C%22endLineNumber%22%3A51%2C%22startColumn%22%3A63%2C%22startLineNumber%22%3A51%7D%5D)
2. Notice search def is
```ts
const search: {
  page?: number | undefined;
}
```

### Expected behavior

The search type retrieved from `useMatch` for a specific route matches the `validateSearch` schema type provided to the route

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/16290753/207366275-b2c87b44-2858-4730-88a5-c7658efe9d56.png)

### Platform

- OS: macOS
- Browser: Firefox
- Version: 108.0b9

### Additional context

```json
"dependencies": {
  "@tanstack/react-router": "0.0.1-beta.38",
  "react": "^18.2.0",
  "react-dom": "^18.2.0",
  "zod": "^3.20.2"
}
```

**Comment by tannerlinsley** [comment]
Because search params *are* global by nature, and there is still a valid possibility of them  present outside of their validation hierarchy, any  indirect search params are included in the schema on purpose, but only as optional.

Tanner Linsley

**Comment by Moshyfawn** [comment]
> Because search params *are* global by nature, and there is still a valid possibility of them  present outside of their validation hierarchy, any  indirect search params are included in the schema on purpose, but only as optional. Tanner Linsley
> […](#)
> On Dec 13, 2022 at 7:54 AM -0700, moshyfawn ***@***.***>, wrote: Describe the bug While TS Router allows providing validateSearch per individual routes, the search state type when retrieving via useMatch grows with all validateSearch schema types provided to all routes Your Example Website or App https://codesandbox.io/p/sandbox/wizardly-keldysh-eg821k?file=%2Fsrc%2FApp.tsx&selection=%5B%7B%22endColumn%22%3A18%2C%22endLineNumber%22%3A40%2C%22startColumn%22%3A18%2C%22startLineNumber%22%3A40%7D%5D Steps to Reproduce the Bug or Issue 1. Go to repro App.tsx line 51 2. Notice search def is const search: { page?: number | undefined; } Expected behavior The search type retrieved from useMatch for a specific route matches the validateSearch schema type provided to the route Screenshots or Videos Platform • OS: macOS • Browser: Firefox • Version: 108.0b9 Additional context "dependencies": { ***@***.***/react-router": "0.0.1-beta.38", "react": "^18.2.0", "react-dom": "^18.2.0", "zod": "^3.20.2" } — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

Ok, I see. My only concern is: where should I define my `validateSearch` schema? In a root route or still go by individual route?

**Comment by tannerlinsley** [comment]
Closest ancestor to where they are used

**Comment by Moshyfawn** [comment]
Ok, it settles this then. Apreciate for the swift response!
