### ISSUE TITLE
Customizable trailing slash behaviour

### ISSUE THREAD

**Issue by tombuntus** [TanStack/router#458]
### Describe the bug

Currently the router always adds a trailing slash to the basepath.

So if you are at `mysite.com/page/one` with `basepath: '/page/one'` and you try to use `navigate` to update the search params then you end up at `mysite.com/page/one/?param=value`

Same thing applies if you have no basepath set, so `mysite.com` would become `mysite.com/?param=value`

### Your Example Website or App

https://stackblitz.com/edit/github-kf59by?file=src/main.tsx

### Steps to Reproduce the Bug or Issue

In the example above, just load the page (in a new tab so you can see the query string) and take a look at the address bar.

### Expected behavior

I'd expect to be able to specify not add the slash, so that you would end up at `mysite.com/page/one?param=value`

### Platform

All platforms

### Additional context

Opening this issue at @tannerlinsley's request. Related discord thread here: https://discord.com/channels/719702312431386674/1052911561032880148

**Comment by judicaelandria** [comment]
can you update your project and retry if the issue has been solved please?

**Comment by tannerlinsley** [comment]
At the very least, trailing slashes are *not* the default any more, so there's that. However, there still isn't an option to *force* trailing slashes. I'm content with that for now since they are mostly (in my opinion) useless. I'm sure someone will eventually ask for that option enough that I'll add it, but not until then.

**Comment by matclayton** [comment]
Hey @tannerlinsley!

We'd love to see this as an option, we have a huge site (100's Millions of pages) which all the a trailing slash on them, as this was previously enforced. We'd like to move to tanstack router, however we dont want to go through the whole SEO process of needing to redirect all the old pages moping up all the issues that causes along the way. Woudl it be possible to make this a controllable option?

**Comment by matclayton** [comment]
We've moved this comments into a new discussion https://github.com/TanStack/router/discussions/1469
