### ISSUE TITLE
router-cli generates imports using '\' instead of '/' on windows

### ISSUE THREAD

**Issue by jjones315** [TanStack/router#465]
### Describe the bug

When using the router-cli in a windows environment the import statements in both the generated code and the src code use back slashes instead of forward. Additionally, in the "src/routes.generated/routeConfig.ts" the back slashes are not escaped leading to invalid imports. 

### Your Example Website or App

https://github.com/TanStack/router/tree/beta/examples/react/basic-ssr

### Steps to Reproduce the Bug or Issue

Using a windows environment
Delete "./src/routes.generated" folder.
Run "npm run dev"
Generated imports will use windows style slash instead of POSIX.
Vite will give an error similar to the one shown in the screenshot.

### Expected behavior

As a user I expect POSIX style imports in ts/tsx code but am seeing windows style imports. If windows style imports do remain the routeConfig.ts imports needs to be properly escaped.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/39281771/209408757-5d3f9705-68a9-4b30-8dc2-54d98664323a.png)
![image](https://user-images.githubusercontent.com/39281771/209408791-b9ce6316-a469-4266-b96f-c0de66a1214f.png)
![image](https://user-images.githubusercontent.com/39281771/209408805-36d0319b-2f61-425b-bd25-8518d9c99663.png)

### Platform

- OS: Windows
- Browser: Chrome
- Version: 108

**Comment by judicaelandria** [comment]
saw that there is ```path.posix.relative()``` but doesn't seem to solve the issue, this was a problem with ```path.relative``` , but we can try and replace ```\``` like ```path.relative().replace(/||/gi,'/')```
wdyt @tannerlinsley  ? I can send a pr

**Comment by tannerlinsley** [comment]
Yeah, let’s give it a try

**Comment by judicaelandria** [comment]
it's working, tested it on windows

**Comment by judicaelandria** [comment]
perhaps we can close this @tannerlinsley
