### ISSUE TITLE
Basic React Example is broken

### ISSUE THREAD

**Issue by mikemorton** [TanStack/router#470]
### Describe the bug

The 'Basic' React Example is broken.  

Nothing shows in the 'Preview' area.  Clicking around in the files, syntax errors show in Main.tsx. `Module '"@tanstack/react-router"' has no exported member 'useLoaderData'.(2305)` is the first error, which causes an implicit any error further down.

This example is using the latest version of tanstack react router `"0.0.1-beta.38"`.  Looking at the code for this version in npm, `useLoaderData` is not defined at all:  https://www.npmjs.com/package/@tanstack/react-router/v/0.0.1-beta.38?activeTab=explore

I tried poking around in the cjs, umd and esm folders and also in the src folder, but it was not to be found.

Perhaps this is a build error where it is grabbing the wrong branch to publish the npm package?

### Your Example Website or App

https://tanstack.com/router/v1/docs/examples/react/basic?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

Open the link in chrome and note that the preview does not show any content.

Click over to Main.tsx to see the source of the example with the TS error.

### Expected behavior

As a user I am seeing a syntax error with `useLoaderData` in the example but judging by the code in the repo, it seems like it should be working.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 108.0.5359.125 (Official Build) (64-bit)

**Comment by mikemorton** [comment]
Further investigation indicates that `useLoaderData` was added on December 17th, which included changes for the examples to use it, but beta 38 was published on December 8th.  So I think the solution here is to get a new beta pushed to NPM.

**Comment by judicaelandria** [comment]
I think you can close this? seems like its fixed
