### ISSUE TITLE
<Link> falsy param values aren't included in the final url

### ISSUE THREAD

**Issue by hornta** [TanStack/router#472]
It seems like falsy values in the params prop are ignored and not interpolated into the url. This code snippet is taken from my app and I'm using the beta 38 version. In my case I'm passing a numeric `0` in `structure.position` which evaluates to falsy.

```ts
<Link to={"structure/$position"} params={{ position: structure.position }}>

export const structureRoute = gameLayoutRoute.createRoute({
  path: "/structure/$position",
  component: StructurePage,
  parseParams: ({ position }) => ({ position: Number(position) }),
  stringifyParams: ({ position }) => ({ position: `${position}` }),
});
```

In the meantime I can always cast it to a string like so, then I'm getting the correct url `structure/0`:

```ts
<Link to={"structure/$position"} params={{ position: `${structure.position}` }}>
```

**Comment by judicaelandria** [comment]
hi @hornta !
this is now fixed! parseParams now only accept type `string`
