### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by luke-john** [TanStack/router#474]
### Describe the bug

When running `npm install @tanstack/react-router@beta --save` npm fails to install the dependency.

### Your Example Website or App

https://github.com/luke-john/router-npm-install-demo/actions/runs/3814851291/jobs/6489444755

### Steps to Reproduce the Bug or Issue

1. run the command `npm install @tanstack/react-router@beta --save`

### Expected behavior

As a user, I expected it to install, but instead I see the following console message

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:^

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2023-01-01T02_41_12_816Z-debug-0.log
```

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/848525/210159644-db198479-8563-42d4-92c6-129c7caa1261.png)

### Platform

- OS: macOS, Linux

### Additional context

I've setup a minimal repro at https://github.com/luke-john/router-npm-install-demo/actions/runs/3814851291/jobs/6489444755

**Comment by zelid** [comment]
Same error happens with `pnpm`. The reason is `https://github.com/TanStack/router/blob/beta/packages/react-router/package.json#L45`. Probably `^` is only valid with `yarn`.

**Comment by nedgrady** [comment]
Same for me on windows with npm/pnpm.

**Comment by luke-john** [comment]
I just re ran the github action I set up as a reproduction -- and the error no longer presents -- so looks like it has now been fixed thanks.

![image](https://user-images.githubusercontent.com/848525/210526322-45af7a9c-21e1-4234-b47d-56803e94df6d.png)
