### ISSUE TITLE
Stop creating boundaries for paths not providing pending or error components

### ISSUE THREAD

**Issue by kdubb** [TanStack/router#477]
### Describe the bug

Currently it appears the router creates a `Suspense` boundary for each parent route with <Anonymous/> as the fallback if no `pendingComponent` is provided. It seems more intuitive to just not render the suspense boundary for any route without a `pendingComponent` , which would then automatically use the nearest suspense boundary and its configured fallback.

The same idea should be done for `errorComponent`. Currently the router is creating a `CatchBoundary` even if no `errorComponent` is provided.

This should remove the need for configuring a `defaultPendingComponent` and/or `defaultErrorComponent` instead they would just be defined on the root route.

### Your Example Website or App

https://discord.com/channels/719702312431386674/1055081579761893496/1055081579761893496

### Steps to Reproduce the Bug or Issue

1. Create a route structure such as `__root__ > section > index`.
1. Provide a `pendingComponent` on the `root` route.
1. Add a `loader` to the `index` route.

### Expected behavior

When the `loader` is running I expect the nearest path with a `pendingComponent` to be displayed.

Currently, `Anonymous` (blank) component is rendered because it is defined on the `section` route, due to there being no explicit `pendingComponent` provided.

### Platform

macOS, Chrome

**Comment by tannerlinsley** [comment]
This is now fixed. Routes that do not provide an errorComponent will not get wrapped with an errorBoundary. By default, all routes will get wrapped with suspense though. If you don't want a route to get wrapped with suspense, you can pass the react-router-only option `wrapInSuspense: false` to the route options.
