### ISSUE TITLE
useLoaderData hook doesn't return updated data after navigation (with parameter)

### ISSUE THREAD

**Issue by frank-kolesik** [TanStack/router#478]
### Describe the bug

the error occurs on a route with a parameter (e.g. /post/$id),
e.g. after navigating from /post/1 to /post/2:
the loader function runs and the component rerenders but the useLoaderData hook doesn't return updated data after navigation (with parameter)

### Your Example Website or App

https://stackblitz.com/edit/github-91qsrn

### Steps to Reproduce the Bug or Issue

1. Go to /post via the Post Link in the Navigation
2. Select a post, e.g Post 1
3. Select another post, e.g. Post 2

### Expected behavior

As a user I expected the component to render the updated data but it doesn't.

### Platform

- OS: Windows 11
- Browser: Chrome
- Version: 108.0.5359.125

**Comment by frank-kolesik** [comment]
After playing around I found out something interesting. It is the useLoaderData hook which causes the problem.
When using the useMatch hook and accessing the value match.store.loaderData it returns the correct data.

**Comment by kdubb** [comment]
I'm seeing the same issue with a parent route that has no parameters. Using `useMatch({from: 'route', strict: false })?.store?.loaderData` seems to work but there is a noticeable delay in the update.

**Comment by tannerlinsley** [comment]
This should be very fixed with the move to the new `loaders` and `react-loaders` packages.
