### ISSUE TITLE
Beta-45, lost search param reactivity and broken Navigation

### ISSUE THREAD

**Issue by SeanCassiere** [TanStack/router#479]
### Describe the bug

Please rename the title to something better. These are just all the stuff I found got when moving from `beta-38` to `beta-45`.

These are both issues I've encountered and seen in the [Router discussion](https://discord.com/channels/719702312431386674/1007702008448426065) channel on discord with **beta 45**.

### 1. Unexpected `console.logs` from the React adapter. (saying: "set", "current")
<img width="367" alt="image" src="https://user-images.githubusercontent.com/33615041/210655903-3e801937-3925-49b2-b36c-2488c8edbc4f.png">

<img width="458" alt="image" src="https://user-images.githubusercontent.com/33615041/210655388-8847153e-4151-44f9-9469-472337e14295.png">

### 2. The search params from useSearch no longer remain reactive.
Often requiring a page refresh. `<Link />`, `useRouter() => router.navigate`, and `useNaivgate => navigate()` all do not update the search params.

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/33615041/210656341-782f9652-598a-412f-bc1e-b1efe1fb5b05.png">

### 3. Error I only saw in Stackblitz.
<img width="715" alt="image" src="https://user-images.githubusercontent.com/33615041/210655516-de72fb80-a646-48b9-9394-9a0ff2f2aafd.png">

### 4. Error I got everytime the app booted.
<img width="713" alt="image" src="https://user-images.githubusercontent.com/33615041/210655651-8c46d9ed-d04d-4d71-8357-7ad13ed9680a.png">

### 5. Error I got when trying to Navigate using the `<Link />` component.
<img width="820" alt="image" src="https://user-images.githubusercontent.com/33615041/210655823-b8100e47-8da7-43fc-85cd-bb823b9463f5.png">

### 6. Error I got, when using `navigate` from `useNavigate` to update the search params.
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/33615041/210656082-500ff0f6-d338-4e77-861a-bcdefbfe0d8d.png">

### Your Example Website or App

https://github.com/SeanCassiere/tanstack-router-beta-45-repro

### Steps to Reproduce the Bug or Issue

1. Use the reproduction repo. The screenshots above can be matched to the action descriptions.

### Expected behavior

As a user, I'm expecting:
* Working navigation
* Reactive search params
* Not have unexpected `console.log`s in production

but unfortunately with beta-45 these problems were introduced.

### Platform

- OS: `macOS`
- Browser: `Chrome`
- Version: `0.0.1-beta.45`

**Comment by vixducis** [comment]
For item 6, I already created a PR with a fix:
https://github.com/TanStack/router/pull/482

Item 2 was already broken on beta 38, IIRC

**Comment by SeanCassiere** [comment]
> For item 6, I already created a PR with a fix:
> https://github.com/TanStack/router/pull/482
> 
> Item 2 was already broken on beta 38, IIRC

Item 2, worked for sure in beta 38. I have an app running with it. I simply `JSON.stringify` the search params, as a React `key` to definitely ensure the rerender.

Although, it would be nice to not have to do that.

**Comment by jtiala** [comment]
I'm on beta 38 and can reproduce item 2. 

I'm trying to create a filtered list view that would work like this:
1. Navigate to unfiltered view -> route loader preloads the data using tanstack query
2. Fill in filter form and send it -> router navigates to the same view but with the form values URL search params
3. Route loader preloads filtered data and re-renders

Stackblitz: https://stackblitz.com/edit/tanstack-router-b8wuzy?file=src/main.tsx
Demo: 
1. Once the app is running, open the page in a new tab as stackblitz doesn't show you the full URL. Open console.
2. Go to posts page
3. Type in the filter: dolor
4. Click filter button
5. URL changes, loader does its thing (see console), but it cannot access the new search params yet
6. Clicking send again works (if you filter something else, it uses the previous value)
7. Refreshing also works

**Comment by SeanCassiere** [comment]
Regarding item 2, I'm starting to wonder if is it an issue with Stackblitz? Or somehow I keep getting a golden working version of beta-38.

Since both on local and the deployment, I've got search params working just fine, with me ensuring a rerender using React keys.

I can't really share the credentials, I'm using rather I can explain the flow with how I've got the search params working:

1. The `filters` object is destructured from the `useSearch` hook, and [put into an object](https://github.com/SeanCassiere/nv-rental-clone/blob/master/src/pages/AgreementsSearch/AgreementsSearchPage.tsx#L26-L41) (NON state), for me simply have some defaults.
2. My SearchFIlters component, has a very [simple React key](https://github.com/SeanCassiere/nv-rental-clone/blob/master/src/pages/AgreementsSearch/AgreementsSearchPage.tsx#L113) set on it stringifying the search filters and forcing a rerender on-change. 
3. When the user hits 'Submit' in the SearchFilters component, it then simply uses the `router` from `useRouter` and does a `router.navigate(...)` to the new page with the [search filters in the URL](https://github.com/SeanCassiere/nv-rental-clone/blob/master/src/components/PrimaryModule/ModuleSearchFilters.tsx#L147).

At no point in this flow does the submit button call a `refetch` or even interact with react-query. Rather, react-query detects the change in the destructured `filters` object from the useSearch hook, and then sets a new queryKey ( `["search", JSON.stringify(searchFilters) ]`). That's it.

https://user-images.githubusercontent.com/33615041/211414268-85cb4b3f-6f12-40bd-91a4-73aca17788f5.mp4

**Comment by jtiala** [comment]
> Regarding item 2, I'm starting to wonder if is it an issue with Stackblitz? Or somehow I keep getting a golden working version of beta-38.

My bug reproduces locally also, I don't think it is related to Stackblitz.

In my use case, I need to access the search params in the route's `loader`, before the page even renders. In your case, you need them when calling useQuery in the component, if I'm correct.

**Comment by SeanCassiere** [comment]
@jtiala Yes, you are correct.

**Comment by rburgst** [comment]
by trial and error I found that the last version where `searchParams` worked properly is beta35. All newer versions wont update when you change the searchParams via `navigate`

**Comment by SeanCassiere** [comment]
All issues were addressed with beta-52.
