### ISSUE TITLE
Lots of console.log in current beta version

### ISSUE THREAD

**Issue by rikbrown** [TanStack/router#494]
### Describe the bug

Console is spammed with console.log coming out of this library

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

Follow the basic examples of this library.

### Expected behavior

No console.log spam.

### Screenshots or Videos

<img width="445" alt="image" src="https://user-images.githubusercontent.com/2906188/212573634-a74ce5e3-725c-4f17-b259-aba0675ff65d.png">

### Platform

macOS / Chrome

### Additional context

Looks like some console.log lines have been left in the latest beta version. The main documentation for this library recommends using the beta version, but I wouldn't expect it to have console.log spam which is difficult to silence.

**Comment by tannerlinsley** [comment]
Yep. They’ll go away soon

Tanner Linsley

**Comment by rikbrown** [comment]
Thanks for fast response.
