### ISSUE TITLE
Error when there are any child routes (Route Configs example broken)

### ISSUE THREAD

**Issue by bjornhauge** [TanStack/router#496]
### Describe the bug

> This issue only exists in `beta39` onwards. I'm experiencing it in an Nx monorepo with a somewhat custom babel/webpack configuration, and can't so far replicate it in a fresh CRA with the same versions of the relevant packages. For now I'm running `beta38` with no problems.

Whenever using `.addChildren()` with a non-empty array, I get the following error on page load:
```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'length')
    at d (index.production.js:11:2951)
    at m (index.production.js:11:3159)
    at index.production.js:11:5446
    at index.production.js:21:13291
    at m (index.production.js:11:3149)
    at Object.load (index.production.js:21:13165)
    at mount (index.production.js:21:12067)
    at commitHookEffectListMount (react-dom.development.js:23150:1)
    at commitPassiveMountOnFiber (react-dom.development.js:24926:1)
    at commitPassiveMountEffects_complete (react-dom.development.js:24891:1)
```
If I comment out all the children, that error disappears. Using the example on the [Route Config docs page](https://tanstack.com/router/v1/docs/guide/route-configs), turn this:
```tsx
let rootRoute = createRouteConfig()

const indexRoute = rootRoute.createRoute({ path: '/' })
const blogRoute = rootRoute.createRoute({ path: 'blog' })
const postRoute = blogRoute.createRoute({ path: '$slug' })

const routeConfig = rootRoute.addChildren([
  indexRoute,
  blogRoute.addChildren([postRoute]),
])
```
into this:
```tsx
let rootRoute = createRouteConfig()

// const indexRoute = rootRoute.createRoute({ path: '/' })
// const blogRoute = rootRoute.createRoute({ path: 'blog' })
// const postRoute = blogRoute.createRoute({ path: '$slug' })

const routeConfig = rootRoute.addChildren([
  // indexRoute,
  // blogRoute.addChildren([postRoute]),
])
```
The first will yield that error upon page load, the second won't.

### Your Example Website or App

unable to share repo

### Steps to Reproduce the Bug or Issue

refresh page

### Expected behavior

I should be able to configure and consume a basic hierarchy of routes.

### Platform

- OS: Windows
- Browser: Edge
- Version: 109.0.1518.52

**Comment by SalahAdDin** [comment]
In my case, the children is not rendered.

**Comment by bjornhauge** [comment]
> In my case, the children are not rendered

Is it possible that you aren't using separate index routes?

This router works slightly differently in that *all* routes up and down the hierarchy get rendered (the ones that have a `component`, rather) &mdash; not just the last. You need to use a separate "index" route at each level for the content that should only get rendered if the URL path stops at that level. Otherwise, the intent is that the higher-level route components use the `<Outlet/>` to nest child content within them during rendering.

So instead of this:
- `/user/:userId` `component`
  - `/album/:albumId` `component`

Do this:
- `/user/:userId` (no component)
  - `/` `component` (putting the component here will mean it doesn't "capture" the render and prevent the album from showing)
  - `/album/:albumId` `component`

Does that help?

**Comment by SalahAdDin** [comment]
> > In my case, the children are not rendered
> 
> Is it possible that you aren't using separate index routes?
> 
> This router works slightly differently in that _all_ routes up and down the hierarchy get rendered (the ones that have a `component`, rather) — not just the last. You need to use a separate "index" route at each level for the content that should only get rendered if the URL path stops at that level. Otherwise, the intent is that the higher-level route components use the `<Outlet/>` to nest child content within them during rendering. There is a [docs section](https://tanstack.com/router/v1/docs/guide/route-paths#rootindex-paths-vs-normal-paths) about it, but it's not all that clear.
> 
> So instead of this:
> 
>     * `/user/:userId` `component`
>       
>       * `/album/:albumId` `component`
> 
> 
> Do this:
> 
>     * `/user/:userId` (no component)
>       
>       * `/` `component` (putting the component here will mean it doesn't "capture" the render and prevent the album from showing)
>       * `/album/:albumId` `component`
> 
> 
> Does that help?

I tried it with `react-router` and certainly, it would be the case, we require to have and index for that route.

Thanks for your answer.

**Comment by tannerlinsley** [comment]
This should be clearer in the docs now.
