### ISSUE TITLE
Not working with vitest (seems to be an ESM / CJS issue)

### ISSUE THREAD

**Issue by danielholmes** [TanStack/router#497]
### Describe the bug

When running vitest on a simple example I'm getting the following error:

```
Error: require() of ES Module /home/runner/work/tanstack-router-vitest/tanstack-router-vitest/node_modules/@solidjs/reactivity/dist/index.js not supported.
Instead change the require of index.js in null to a dynamic import() which is available in all CommonJS modules.
 ❯ Object.<anonymous> node_modules/@tanstack/react-router/build/cjs/index.js:18:18
```

### Your Example Website or App

https://github.com/danielholmes/tanstack-router-vitest

### Steps to Reproduce the Bug or Issue

1. Create a standard vite + react + js template: `npm create vite@latest`
2. Add `@tanstack/react-router` (at time of writing, version `0.0.1-beta.48`)
3. [Use the tanstack router quickstart example](https://tanstack.com/router/v1/docs/quick-start)
4. Add vitest
5. Create a simple test that results in an import of `@tanstack/react-router`
6. Try and run vitest

### Expected behavior

That tanstack router can be imported within the vitest test environment.

### Platform

- OS: reproduced on macOS + Ubuntu
- Node: 18.13.0

### Additional context

Failed github actions run is also available to see:

https://github.com/danielholmes/tanstack-router-vitest/actions/runs/3935277674/jobs/6730820615

**Comment by SalahAdDin** [comment]
Don't tell me this please, I'm using vitest too!
