### ISSUE TITLE
router.reload() adds /undefined to url

### ISSUE THREAD

**Issue by hornta** [TanStack/router#499]
### Describe the bug

-

### Your Example Website or App

https://stackblitz.com/edit/github-mzt8nn?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Click on click me
2. /undefined is appended to the url

### Expected behavior

-

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by judicaelandria** [comment]
we can close this now too @hornta @tannerlinsley
