### ISSUE TITLE
query params are empty in the loader for preload='intent'

### ISSUE THREAD

**Issue by SeanCassiere** [TanStack/router#501]
### Describe the bug

The search query parameters are empty in the loader during the `preloading Loader stage`, for `<Link preload='intent' />`.

This happens when your `router = new ReactRouter({ routeConfig })` and `<RouterProvider router={router}  />` do not have the `defaultPreload` set.

Then, when you create a `<Link preload='intent'>somewhere</Link>`, and get to the `loader` the `ctx.search` comes out as `{}`.
```js
loader: async (ctx) => {
  console.log(ctx.search)
  //  prints       ^ {}
  return {}
}
```

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-nhxnyz?file=src/main.tsx

### Steps to Reproduce the Bug or Issue

Go through the Stackblitz reproduction.

#### Note:
1. This **ONLY** happens during `preloading stage`, when the user navigates to the page, it then recognizes the search parameters just fine.
2. `router` must NOT have `defaultPreload` set, therefore it is `undefined`.
3. `RouterProdiver` must NOT have `defaultPreload` set, therefore it is `undefined`.
4. `<Link preload='intent'>somewhere</Link>` to a route with a `loader`.

### Expected behavior

As a user, I expected the query search parameters to being defined with the appropriate `validateSearch` validation, and `preSearchFilters` filling added and being provided into the loader under `ctx.search`, but instead I am seeing the search parameters being printed as `{}`.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/33615041/213840690-68dc66b1-2f59-46df-95a7-5ca3861d84a7.png)

Above, the first and second `loader ctx.search {}` and printed out to the console from the loader during the preloading stage (hovering on <Link preload='intent'>somewhere</Link>).

The console log for `loader ctx.search {foo:'bar',...}` is printed out to the console from the loader once the user has navigated to the page.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 0.0.1-beta.53

**Comment by SeanCassiere** [comment]
Still persists with `0.0.1-beta.56`.

**Comment by SeanCassiere** [comment]
@tannerlinsley this seems to persist in `beta.61`.

As you can see between points `6` and `7`, all the search params aren't being loaded in (i.e the `filters` object), even though it is defined in the Link before preload (point 5).

1. Router config
<img width="720" alt="image" src="https://user-images.githubusercontent.com/33615041/214955930-b01bf072-220c-4e4c-b788-1e4b52b03cef.png">

2. Route config
<img width="391" alt="image" src="https://user-images.githubusercontent.com/33615041/214957437-b61d9e99-c3f6-414b-95bc-854a938dde08.png">

<img width="649" alt="image" src="https://user-images.githubusercontent.com/33615041/214957358-e48f89fe-6d5b-4c47-a2ab-2d88e1bac20b.png">

4. Zod query params definition
<img width="528" alt="image" src="https://user-images.githubusercontent.com/33615041/214956820-37e09082-2ca1-4f38-a55c-dc7f49d9394d.png">

5. Link props, spread over a `<Link />`
<img width="701" alt="image" src="https://user-images.githubusercontent.com/33615041/214956290-60d03dfe-a0f9-469c-8ce2-b24abe38eea9.png">

6. Console log the preload, i.e. hover over `<Link />`
<img width="489" alt="image" src="https://user-images.githubusercontent.com/33615041/214957156-f40a7980-5b22-4f07-bf14-e7b1aa14b1ac.png">

7. Console log on full route load, i.e actually clicked the `<Link />`
<img width="516" alt="image" src="https://user-images.githubusercontent.com/33615041/214957269-0f08f352-4b5a-4d25-91b6-b01d04a743c6.png">

**Comment by tannerlinsley** [comment]
Interesting. I must have missed something in my testing.

**Comment by tannerlinsley** [comment]
I believe this should be fixed now. Can you attempt your example again?

**Comment by SeanCassiere** [comment]
Can confirm, this is now fixed.
