### ISSUE TITLE
Quick Start instructions seem to be broken. Potential issues with beta0.60

### ISSUE THREAD

**Issue by WonderPanda** [TanStack/router#505]
### Describe the bug

I feel like this is a crazy codemod gone wrong or something but I'm just trying to follow along with the [quickstart](https://tanstack.com/router/v1/docs/quick-start) and it doesn't work at all.

``` typescript
const new Route({ getParentRoute: () => indexRoute = rootRoute,
  path: '/',
  component: Index,
})
```

This doesn't appear to be valid code. Also, when switching between the latest beta versions 60 I get errors that `createRouteConfig` doesn't exist. Dropping down a few beta versions seems to get me back to using the import but none of the types match anything that I can find in the docs to kickstart a new project using Tanstack Router.

Wondering if this is maybe some churn as you're starting to transition over to using classes for better type inference?

### Your Example Website or App

https://tanstack.com/router/v1/docs/quick-start

### Steps to Reproduce the Bug or Issue

Attempt to follow the minimal getting started on the QuickStart

### Expected behavior

Following the directions in the QuickStart should get me up and running with a minimal but functional app using the router

### Platform

Linux, Chrome

**Comment by tannerlinsley** [comment]
You nailed it. Bad codemod and churn. It’s fixed locally. I’ll push asap.

Tanner Linsley

**Comment by WonderPanda** [comment]
Thanks! Keep up the great work, you're an inspiration
