### ISSUE TITLE
[WIP] How to better structure Route <-> Router to avoid circular references

### ISSUE THREAD

**Issue by Newbie012** [TanStack/router#510]
### Describe the bug

Given the following setup:

```ts
// src/routes/a.tsx

import { Route } from "@tanstack/react-router";
import { rootRoute } from "./_root";
import { router } from "./_router";

export const aRoute = new Route({
    getParentRoute: () => rootRoute,
    component: () => <></>
    path: "a",
    beforeLoad: () => {
        console.log(router.basepath); // <--- note this line
    }
});
```

```ts
// src/routes/_router.tsx

import { ReactRouter } from "@tanstack/react-router";
import { aRoute } from "./a";
import { rootRoute } from "./_root";

export const routeTree = rootRoute.addChildren([aRoute]);
export const router = new ReactRouter({ routeTree });
```

```ts
// src/routes/_root.tsx

import { RootRoute } from "@tanstack/react-router";

export const rootRoute = RootRoute.withRouterContext()();
```

Each time I save the file `a.tsx`, I get the following error (due to an attempt of HMR):

![image](https://user-images.githubusercontent.com/10504365/215334560-512aefec-ea72-4fb0-b66a-d51b3c2af86e.png)

This makes sense since they all reference each other in a circular way. In order to fix that, I need to use the `router` that I get inside `beforeLoad` instead. But the problem is that it's `AnyRouter` which isn't type-safe.

### Your Example Website or App

https://github.com/Newbie012/tanstack-router-circular-reference

### Steps to Reproduce the Bug or Issue

1. Clone https://github.com/Newbie012/tanstack-router-circular-reference
2. Run `pnpm install`
3. Run `pnpm dev`
4. Open browser, and navigate to http://localhost:5173/a
5. Attempt to modify the file `src/routes/a.tsx`
6. See an error (image above) in the console:
```
ReferenceError: Cannot access 'aRoute' before initialization
    at _router.tsx:5:49
[hmr] Failed to reload /src/routes/a.tsx. This could be due to syntax errors or importing non-existent modules. (see errors above)
```

### Expected behavior

Should not throw that error

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/10504365/215334885-0088e6e4-fac1-42c7-a8c9-eb7404b2b449.png)

### Platform

- OS: Windows (WSL2 Ubuntu)
- Browser: Chrome
- Version: Version 109.0.5414.120 (Official Build) (64-bit)

### Additional context

Really cool library.

**Comment by tannerlinsley** [comment]
I'm not seeing this any where, do you have a reproduction?

**Comment by tannerlinsley** [comment]
I am having a difficult time getting this to reproduce locally.

**Comment by Newbie012** [comment]
If it helps, I recorded my reproduction:

[screen-recording (2).webm](https://user-images.githubusercontent.com/10504365/216613040-31d94451-ce50-47a2-a308-5bed1dcf3dc7.webm)

**Comment by tannerlinsley** [comment]
That second error is now fixed, but I'm still looking into the first issue.

**Comment by tannerlinsley** [comment]
Please try the latest version. If it still persists, could you link me to a stackblitz example that up to date?

**Comment by XpamAmAdEuS** [comment]
issue mentioned its just circular error in vite HMR there nothing to do in router to avoid it its how vite works.

**Comment by Newbie012** [comment]
@tannerlinsley sorry it took a while for me to respond back. Here's a reproduction on stackblitz:

1. go to https://stackblitz.com/edit/github-ok3khj?file=src%2Froutes%2Fa.tsx
2. navigate to `/a`
3. open chrome console (or any other inspect tool)
4. open `a.tsx`
5. modify the file
6. see the following error:

![image](https://user-images.githubusercontent.com/10504365/217789277-81be69d1-a414-4742-9079-de4bedee9092.png)


@XpamAmAdEuS while you're right, it does impact DX, which I believe is one of the main goals of this library.

**Comment by XpamAmAdEuS** [comment]
`import { Route } from '@tanstack/react-router';
import { rootRoute } from './_root';

export const aRoute = new Route({
  getParentRoute: () => rootRoute,
  component: A,
  path: 'a',
  beforeLoad: () => {
    console.log(3);
    console.log('no circular xDD');
    //console.log(router.basepath);
  },
});

type Props = {};

export default function A({}: Props) {
  return <div>a</div>;
}`

Vite HMR works if u not importing router inside route just comment ot console.log(router.basepath);, and try
What u did its import router and try to use it inside route which its a part of same router soo u make a circular dependancy  and u get exactly this error,really have nothing to do with router library.
In production everything will work just fine.
Btw why u even want to access router instance inside beforeLoad: ?

**Comment by Newbie012** [comment]
I know that I'm what I'm trying to do and I understand why the error occurs. I understand that the error doesn't come from the library itself. The issue I wrote above is not specifically about this error or its cause. I'll rephrase my intentions so everything will be clearer.

While creating a `RootRoute`, we can create a [`RootRoute.withRouterContext`](https://tanstack.com/router/v1/docs/guide/router-context#typed-router-context) which creates a router with context.

Sometimes, you may want to access the root router context (such as API, auth, etc) inside `beforeLoad`. If it's not enough to convince you of this usefulness, you may want to look at this example from the official examples:

https://github.com/TanStack/router/blob/89640dcdf09378d5fca87af98342c20702579ca2/examples/react/kitchen-sink-single-file/src/main.tsx#L804-L808

There are few solutions that may solve it:

1. allow accessing `context` inside beforeLoad (just like in onLoad).
2. the `router` property in `beforeLoad` arg should be typed as the root router rather than `AnyRouter` (assuming it's the actual root router).

**Comment by austincollinpena** [comment]
I can confirm I have this issue on `0.0.1-beta.82`

**Comment by ArnaudBarre** [comment]
Hi everyone, coming here from the opened issue on the React plugin repo.

I didn't have a chance to play with Tan stack router yet and I don't know if the example is the recommended pattern, but this pattern is really bad for React HMR. To get most out of it, a file that contains one or more component should only export React components (and the route export is not one). More info here: https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/README.md#consistent-components-exports.

I wrote this eslint rule to catch this kind of patterns (not perfect but would warn against that): https://github.com/ArnaudBarre/eslint-plugin-react-refresh

The solution is to export the page component and construct the route objects in another file (either the main router of intermediate files for big apps)

**Comment by XpamAmAdEuS** [comment]
This issue its becouse of bad early stage examples

route imports some view and then this view again imports route to ask for route .id... and thats bad pattern and its circular dependency problem

If using this any hook that need route id by entering just string and not importing route to ask for id  everything works just nice
good example
const search = useSearch({ from: "/admin/customers/list" });
becouse we dont make circular import problem.

but if we use like in examples then we got problem.
const search = useSearch({ from: customersRoute.id });

its simple and easy fixable if not making any circular imports everything goes just nice with vite.

**Comment by arpadgabor** [comment]
Can still confirm the issue, but the fix is simple if you keep close attention. As @XpamAmAdEuS also mentioned, it's a circular dependency.

I created a separate file `_root.tsx` that declares my root and that's where I import it from all other routes, then the main `routes.tsx` file also imports that _root. Otherwise if you declare `root` inside `routes.tsx` and then you import the `root` in your route files, you get this error because it tries to access a variable that was not initialized yet.

I'm just starting out with tanstack router, wondering how imports end up when you have many nested routes, but for now this works well.

**Comment by tannerlinsley** [comment]
As of right now, the official solution to this issue is to rely on the global imports from `@tanstack/[framework]-router` instead of attempting to import routes around. This doesn't apply to importing parent routes into child ones, since this should still be fine.

**Comment by jasongerbes** [comment]
@tannerlinsley could you please provide some more guidance on how circular imports can be avoided?

I'm having issues with [Authenticated Routes](https://tanstack.com/router/v1/docs/guide/authenticated-routes#redirecting), where the `router` needs to be used for the `redirect` search param (as per the documented example).

It also seem problematic if all routes are defined in the `router.tsx` file as some routes may need to be imported to access the `id` property for things like:

-  `useSearch({ from: myRoute.id })`
- `routerState.matchIds.includes(myRoute.id)`

This can lead to a circular dependency where `router.tsx` depends on the `my-page.tsx` for `new Route({ component: MyPage })`, and `my-page.tsx` depends on `router.tsx` for the `myRoute.id`

**Comment by tannerlinsley** [comment]
Are you running into errors of variables being accessed before instantiating? Or just circular import warnings during bundling?

**Comment by jasongerbes** [comment]
I've only recently started integrating Tanstack Router, but have run into undefined variable issues the past due to circular dependencies.

The examples are helpful, but they mostly use a single `main.tsx` file for all routes and pages which avoids the circular dependency issues. It would be great if you could provide an example with separate files for each page, with dependencies between them for things like search params, route ID matching, authenticated route redirects, etc

**Comment by fnn** [comment]
I'm experiences "access before initialization" errors after HMR.

**Comment by jameshoward** [comment]
In case it helps anyone, I ended up splitting routes into separate files and avoiding circular dependencies by exporting a builder function rather than the route itself. This way the parent route setup file can pass its own route in, which becomes the parent route:

```
// routes/dashboard.tsx

const createDashboardRoute = <T extends AnyRoute>(parentRoute: T) =>
  new Route({
    getParentRoute: () => parentRoute,
    path: '/',
    component: Dashboard,
  });

export default createDashboardRoute;
```

```
// routes/index.tsx
import rootRoute from './root.tsx';
import createDashboardRoute from './dashboard';

// this is the `routeTree` for the router.
export rootRoute.addChildren([
  createDashboardRoute(rootRoute)
]);
```

**Comment by bohdancho** [comment]
> I imagine I'm about to run into issues with not being able to import and use those routes (e.g. `<Link to={dashboardRoute.id}>…`) though 🤔

you actually can use routes without importing them, via the RouteApi helper class:
```
import { RouteApi } from '@tanstack/react-router'
const routeApi = new RouteApi({ id: '/my-route' })

export function MyComponent() {
  const loaderData = routeApi.useLoaderData()
  //    ^? { foo: string }

  return <div>...</div>
}
```
 https://tanstack.com/router/v1/docs/guide/code-splitting#accessing-route-apis-in-code-split-files-with-the-routeapi-class

**Comment by jameshoward** [comment]
I think a better approach would be to assign the parent route from above, a bit like how the generated file-based routes work:

```
// src/routeTree.gen.ts

Object.assign(IndexRoute.options, {
  path: "/",
  getParentRoute: () => rootRoute,
})

Object.assign(AboutRoute.options, {
  path: "/about",
  getParentRoute: () => rootRoute,
})
```

**Comment by mmeluch** [comment]
> I've only recently started integrating Tanstack Router, but have run into undefined variable issues the past due to circular dependencies.
> 
> The examples are helpful, but they mostly use a single `main.tsx` file for all routes and pages which avoids the circular dependency issues. It would be great if you could provide an example with separate files for each page, with dependencies between them for things like search params, route ID matching, authenticated route redirects, etc

The point of @jasongerbes still stands after 2 years - the docs contain exclusively examples of components mangled together into one huge `main.tsx` file. Which apart from being unmaintainable also compromises the React fast refresh functionality mentioned by @ArnaudBarre earlier.

New users (like me) have no idea what's the recommended setup, since all examples are either trivial (1 huge file) or straight up missing. The only options AFAIK (after 2 days of debugging) are:
1. Ignore the fast refresh warnings and declare your route directly in the component file. This potentionally also leads to a mess of various variables and interfaces defined in a single file in case of more complex components
2. Use this weird syntax: `const Route = getRouteApi('/main-layout/$category/$item')` (why is the pathless layout name required??)
3. Use this even weirder syntax: `const navigate = useNavigate({ from: '/$category/$item' })` (the layout name suddenly isn't required..)

In either case, good luck with refactoring once a route name or parameter name changes. There is no way my junior colleagues would find their way out of this mess.
