### ISSUE TITLE
Parent route components rerender when child routes change

### ISSUE THREAD

**Issue by mer10z** [TanStack/router#521]
### Describe the bug

With nested routes, when navigating between child routes within the same parent, or navigating between the same child route with different search params, all of the ancestor route components in the route hierarchy rerender. 

### Your Example Website or App

 https://stackblitz.com/edit/tanstack-router-ayc4dj?file=src/main.tsx

### Steps to Reproduce the Bug or Issue

Within the "Home" page I have two links that go the active route with different searches and if you look at the console logs you can see that every level of the route hierarchy is getting remounted. 

### Expected behavior

Parent route components should not remount when child routes change

### Platform

- OS: macOS
- Browser: Chrome
- Version: 109.0.5414.119

### Additional context

"@tanstack/react-router": "0.0.1-beta.80"

**Comment by geoff-harper** [comment]
> If you've used Remix or Next.js, you may be used to the idea that data loading only happens for routes on the page that change when navigating. eg. If you were to navigate from /posts to /posts/1, the loader/getServerSideProps function for /posts would not be called again. This is not the case with TanStack Router. Every route's loader function will be called every time a route is loaded.

https://tanstack.com/router/v1/docs/guide/data-loading#the-loader-route-option

**Comment by tannerlinsley** [comment]
This is no longer the case in the latest version.
