### ISSUE TITLE
Routes that share parts of the path are not matched

### ISSUE THREAD

**Issue by lenhosseini** [TanStack/router#528]
### Describe the bug

When creating multiple routes that have some part of the path in common and have the same parent, some routes are not matched

Example:
```typescript
const indexRoute = new Route({
  getParentRoute: () => rootRoute,
  path: '/',
  component: () => <h1>Home Page</h1>,
});

const blogRoute = new Route({
  getParentRoute: () => rootRoute,
  path: 'blog',
  component: () => <h1>Blog Page</h1>,
});

const postsRoute = new Route({
  getParentRoute: () => rootRoute,
  path: 'blog/posts',
  component: () => <h1>Posts Page</h1>,
});

const authorsPage = new Route({
  getParentRoute: () => rootRoute,
  path: 'blog/posts/authors',
  component: () => <h1>Authors Page</h1>,
});

const routeTree = rootRoute.addChildren([
  indexRoute,
  blogRoute,
  postsRoute,
  authorsPage,
]);
```

In this example the path the following matches happen:

:white_check_mark: `/` matches the `indexRoute`
:white_check_mark: `/blog` matches the `blogRoute` 
:x: `/blog/posts` matches the `blogRoute` 
:x: `/blog/posts/authors` matches the `blogRoute`

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-inner-path-slashes-bug?file=src/main.tsx

### Steps to Reproduce the Bug or Issue

1. create a vite app with the react-ts starter template
2. add @tanstack/react-router v0.0.1-beta.82
3. create multipe routes on the root level that have some parts of the path in common

See the reproduction stackblitz link.

### Expected behavior

Every route should match its path and only the route with the matching path should be displayed (if they all have the rootRoute as parent):

:white_check_mark: `/` matches the `indexRoute`
:white_check_mark: `/blog` matches the `blogRoute` 
:white_check_mark: `/blog/posts` matches the `postsRoute` 
:white_check_mark: `/blog/posts/authors` matches the `authorsRoute`

### Screenshots or Videos

https://user-images.githubusercontent.com/96687967/218681088-9f445181-17ff-4933-bbe0-238d2ec242fb.mov

### Platform

- OS: macOS
- Browser: chrome
- Version: 0.0.1-beta.82

**Comment by LeNei** [comment]
This bug also appears if you chain the routes together with `addChildren`: https://stackblitz.com/edit/tanstack-router-inner-path-slashes-bug-arspz1?file=src%2Fmain.tsx

**Comment by vixducis** [comment]
> This bug also appears if you chain the routes together with `addChildren`: https://stackblitz.com/edit/tanstack-router-inner-path-slashes-bug-arspz1?file=src%2Fmain.tsx

I have the same issue when the routes with the shared path are added in parallel instead of as children, so I doesn't really seem to matter.

**Comment by tannerlinsley** [comment]
I’ll get this fixed ASAP

**Comment by julian-gargicevich** [comment]
This bug makes the library pretty much unusable for a lot of use cases

**Comment by tannerlinsley** [comment]
Again, I realize this is a blocker for many and it's at the top of my list to fix. Hang in there.

**Comment by tannerlinsley** [comment]
Fixed!

**Comment by queicherius** [comment]
Sadly the fix does not seem to work for me with `0.0.1-beta.97`, neither for static nor dynamic paths. (It's also completely possible that's user error, I tried to follow the getting started example as close as I could).

- Static paths: https://stackblitz.com/edit/tanstack-router-inner-path-slashes-bug-6eaeuj
- Dynamic paths: https://stackblitz.com/edit/tanstack-router-inner-path-slashes-bug-naif4i
- Minimal: https://stackblitz.com/edit/tanstack-router-inner-path-slashes-bug-mtidnv

**Comment by tannerlinsley** [comment]
I'm afraid you have forgotten to add `<Outlet />` to a few of your routes. Here's a fixed example: https://stackblitz.com/edit/tanstack-router-inner-path-slashes-bug-djujqy?file=package.json,src%2Fmain.tsx

**Comment by queicherius** [comment]
> I'm afraid you have forgotten to add `<Outlet />` to a few of your routes. Here's a fixed example: https://stackblitz.com/edit/tanstack-router-inner-path-slashes-bug-djujqy?file=package.json,src%2Fmain.tsx

🤦‍♂️ Thank you, I was so used to Next's routing that I completely forgot about the nesting behaviour. What I wanted to do boiled down to this:

```ts
const indexRoute = new Route({ getParentRoute: () => rootRoute, path: '/', component: Index });
const blogRoute = new Route({ getParentRoute: () => rootRoute, path: 'blog', component: Blog });
const blogPostRoute = new Route({ getParentRoute: () => rootRoute, path: 'blog/$postId', component: BlogPost });

const routeTree = rootRoute.addChildren([
  indexRoute,
  blogRoute,
  blogPostRoute,
]);
```

**Comment by mjh316** [comment]
Issue seems to pop up in [this repo](https://github.com/mjh316/cool-husky-games)

## Repro Steps
1) Clone, `npm install`
2) `npm run dev`
3) Go to /games/pong, will render the empty /games route instead.

What it should do in step 3 is render the /games/$game route, and have a Play Now button on the page. Can test routing by clicking on the pong game image on the home page. (Am using window.location for imperative routing as `useNavigate` throws an exception for some reason).

**Comment by schiller-manuel** [comment]
@mjh316  you are missing the `<Outlet>` in the games component.
see the docs https://tanstack.com/router/latest/docs/framework/react/guide/outlets

**Comment by mjh316** [comment]
Oh, I had assumed that the parent route was the root route - thank you!
