### ISSUE TITLE
Few links on the docs does not work

### ISSUE THREAD

**Issue by VarunSAthreya** [TanStack/router#529]
### Describe the bug

Some of the pages on the docs under the ReactRouter tab do not exist (i.e return 404).

- [ReactRouter](https://tanstack.com/router/v1/docs/api/react/ReactRouter)
- [route](https://tanstack.com/router/v1/docs/api/react/route)

### Your Example Website or App

https://tanstack.com/router/v1/docs/api/react/route

### Steps to Reproduce the Bug or Issue

1. Go to  [ReactRouter](https://tanstack.com/router/v1/docs/api/react/ReactRouter) or [route](https://tanstack.com/router/v1/docs/api/react/route).
2. The page does not exist i.e it returns the status code 404. 

### Expected behavior

As a user, I expect it to have respective documentation of API.

### Screenshots or Videos

![ReactRouter](https://user-images.githubusercontent.com/64711780/218682654-411ed3b3-81fc-48f4-832d-164cfd8ec28f.png)

![route](https://user-images.githubusercontent.com/64711780/218682513-d9df8e77-3ff9-4771-9521-502b888e5211.png)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 110.0.5481.90

### Additional context

Also, the link [https://tanstack.com/router/v1/docs/api/react/route](https://tanstack.com/router/v1/docs/api/react/route) routes to 2 API.

![image](https://user-images.githubusercontent.com/64711780/218683310-70d31b99-6d4b-4656-a53c-57872c158a88.png)

**Comment by judicaelandria** [comment]
Thanks for the feedback, since React router is still in beta some of the pages are still not done yet, but we will add it for sure

**Comment by nicko-winner** [comment]
Showing an empty page that says even if it says "more information coming soon" inspires more confidence than lots of broken links and none-functional examples. None functional documentation without an examination is corrosive to the project credibility.

**Comment by tannerlinsley** [comment]
I've cleaned up a lot of the TODOs, removed pages and fixed broken links. This should be much better as we continue to improve the docs.
