### ISSUE TITLE
Index child route search params type issue

### ISSUE THREAD

**Issue by vixducis** [TanStack/router#536]
### Describe the bug

Consider the following scenario:

- I have a documentsRoute which does have a path, but is's just an Outlet.
- There's a documentRoute, which is a child of documentsRoute, which is the index (path: "/") for the parent as well
- The documentRoute has a search param year, validated by zod
- When using useNavigate(documentRoute.id) in the documentRoute, and using the resulting navigate function without a to, you get a type error.

If you have a look at the minimum repro in the stackblitz, the issue should be fairly obvious.

### Your Example Website or App

https://stackblitz.com/edit/github-fbut9a?file=src/Document.tsx

### Steps to Reproduce the Bug or Issue

Have the stackblitz compile and have a look at the Document.tsx file. The navigate function shows a type error.

### Expected behavior

The `navigate` function should not result in a type error. 

### Platform

- OS: Windows
- Browser: Firefox
- Version: 110

**Comment by vixducis** [comment]
I'm aware that that would solve the issue, but imho, it's just a workaround. I get that `/documents/` is not a valid path, but it's downright confusing that you have to use the `fullPath` for the from in `useNavigate` and the `id` for other hooks. 

If this is the way that it should work, fine, but then at least let's make this very clear in the provided examples as well.

**Comment by tannerlinsley** [comment]
I’m working on a way to for id to work as from. It messes with relative paths right now, but it’s required for search params to work right. I’ll figure it out soon.

**Comment by vixducis** [comment]
The issue seems to persist on beta 84: https://stackblitz.com/edit/github-fbut9a-k4gyfs?file=src%2FDocument.tsx%3AL8

**Comment by tannerlinsley** [comment]
I think I fixed this. Stay tuned

**Comment by vixducis** [comment]
I don't think this is fixed. I have updated the stackblitz to the new router version and I still get a type error on the useNavigate function in `Document.tsx`: https://stackblitz.com/edit/github-fbut9a-xyzkf1?file=src%2Fmain.tsx,src%2FDocument.tsx

**Comment by tannerlinsley** [comment]
The stackblitz above is still using route.id. Try route.fullPath

**Comment by hosmelq** [comment]
Hello @tannerlinsley. Should we use the fullPath property instead of the id?

**Comment by tannerlinsley** [comment]
Yes
