### ISSUE TITLE
ReferenceError: can't access lexical declaration `route` before initialization

### ISSUE THREAD

**Issue by ghost** [TanStack/router#539]
### Describe the bug

When updating any component that belongs to a route (for me /pages), the Router cannot update the page as it gets an error: `ReferenceError: can't access lexical declaration 'indexRoute ' before initialization`.

`Router.tsx`
```ts 
import React from "react";
import {
  RouterProvider,
  RootRoute,
  ReactRouter,
  Navigate,
  Outlet,
  Route,
  Link,
} from "@tanstack/react-router";

import { indexRoute } from "src/pages/IndexPage";

export const rootRoute = new RootRoute({
  component: () => <Outlet />,
});

const routeTree = rootRoute.addChildren([
  indexRoute,
]);
const router = new ReactRouter({ routeTree });

const Router = () => {
  return <RouterProvider router={router} />;
};

export default Router;

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
```

`IndexPage.tsx`
```ts
import React from "react";
import { Link, Route } from "@tanstack/react-router";
import { rootRoute } from "src/contexts/Router";

const IndexPage = () => {
  return (
    <>
      <Link to="/l">Login</Link>
      <Link to="/r">Register</Link>
    </>
  );
};

export const indexRoute = new Route({
  path: "/",
  component: IndexPage,
  getParentRoute: () => rootRoute,
});
```

I am probably dumb but I am so confused. Half of the documentation does not work and most month old videos are already outdated so having a hard time switching from `react-router-dom`.

### Your Example Website or App

https://stackblitz.com/edit/github-ohfen9?file=src%2Fpages%2FIndexPage.tsx

### Steps to Reproduce the Bug or Issue

1. Change any react component after intial render.

### Expected behavior

I expected for the component to update like it would if the router was not there. However, I experience an error which stops it from rerendering.
NOTE: I sometimes experience infinite rerenders however I am unsure if that is related to this.

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/93608862/219448188-06822e5e-c0fb-462a-807a-a100b7cdce1a.png)

### Platform

- OS: Windows 11
- Browser: Firefox( 109.0.1 ) + Chrome( 109.0.5414.120 )

**Comment by ulnk** [comment]
## Issue Resolved
I had to move the routes declaration outside of the IndexPage.tsx

**Comment by lunacrafts** [comment]
> I had to move the routes declaration outside of the IndexPage.tsx

It solved my issue with: "Cannot access X before initialization" and with Vite HMR (#510) as well.

Do you mind reopening this issue?

**Comment by ulnk** [comment]
> 

To fix I made a seperate _routes.ts file and moved all my projects
```ts
export const indexRoute = new Route({
  path: "/",
  component: IndexPage,
  getParentRoute: () => rootRoute,
});
```
inside of it.
![image](https://user-images.githubusercontent.com/93608862/220374218-23599cf5-4197-4e03-92f5-8f187ec9ebf8.png)

**Comment by geoff-harper** [comment]
I was able to resolve this by moving the `RootRoute` creation into it's own file outside of the file where `Router` is created. I left adding children to the root as well as the ts module declaration in the main router file however

**Comment by tannerlinsley** [comment]
Let's track this in #510
