### ISSUE TITLE
Page hash is being replaced into route's url on page refresh/visit(not with router link)

### ISSUE THREAD

**Issue by farefray** [TanStack/router#542]
### Describe the bug

When navigating to some page with already defined hash, it is being replaced with hashed route information, even when hash router is not in use.

### Your Example Website or App

https://stackblitz.com/edit/github-eeczki-y12evn?file=src/main.tsx

### Steps to Reproduce the Bug or Issue

1. Click on the [About page with hash](https://githubeeczkiy12evn-uowj--3000.local-credentialless.webcontainer.io/about#valid_hash) link in example app
2. Take a look on page hash outputted into layout - Current hash: #valid_hash
3. Navigate to Home by link in header
4. Click on third link('a' link with hash which wont work as expected) which is an <a> link to about page with hash set
5. Pay attention that hash is not correct after that visit. (You can also skip steps 3-5 and refresh the page in example right after second step)

### Expected behavior

As a user I expected my hash to stay stable between page refreshes or in site visits with the hash defined in urls.

### Platform

- OS: Windows
- Browser: Chrome
- Version: 110.1

**Comment by tannerlinsley** [comment]
This should be fixed now.
