### ISSUE TITLE
opts are optional in useSearch but treated as required

### ISSUE THREAD

**Issue by lsmurray** [TanStack/router#552]
### Describe the bug

If you don't pass an empty object to `useSearch` you get an error.

https://github.com/TanStack/router/blob/83d8bff6009629d1ca4091dcdf602cc1835f7dd1/packages/router/src/react.tsx#L455

Should be something like `opts ?? {}` or make the type opts required.

### Your Example Website or App

NA

### Steps to Reproduce the Bug or Issue

NA

### Expected behavior

NA

### Screenshots or Videos

NA

### Platform

NA

**Comment by judicaelandria** [comment]
are you using the latest version? I can't reproduce this one, or can you provide an example that reproduce this? please

**Comment by judicaelandria** [comment]
oh yeah, you're right, let me fix it

**Comment by tannerlinsley** [comment]
This should now be fixed.
