### ISSUE TITLE
Type Error for routes

### ISSUE THREAD

**Issue by ghost** [TanStack/router#555]
### Describe the bug

I have working routes when using my app that work perfectly, however when using <Link /> or <Navigate />, the routes do not exist.

```
Type '{ children: Element[]; to: "/app"; className: string; }' is missing the following properties
from type 'CheckPathError<RoutesInfo<RootRoute<{}, RouteContext, RouterContext>>, "/app">': Error,
'Valid Route Paths'
```

### Your Example Website or App

xxx

### Steps to Reproduce the Bug or Issue

`routes.tsx`
```ts
import { Outlet, RootRoute, Route } from "@tanstack/react-router";
import IndexPage from "@/pages";
export const rootRoute = new RootRoute({
  component: Outlet,
});
const appRoute = new Route({
  path: "/app",
  getParentRoute: () => rootRoute,
});
const appIndexRoute = new Route({
  path: "/",
  component: () => (
    <Layout>
      <IndexPage />
    </Layout>
  ),
  getParentRoute: () => appRoute,
});
rootRoute.addChildren([
  appRoute.addChildren([
    appIndexRoute,
  ]),
]);
```

`router.tsx`
```ts
import React from "react";
import { ReactRouter, RouterProvider } from "@tanstack/react-router";
import { rootRoute } from "./_routes";
const router = new ReactRouter({
  routeTree: rootRoute,
});
export const Router = () => <RouterProvider router={router} />;
declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
```
```ts
<Link to={"/app"}>
  Go to app
</Link>
Type '{ children: Element[]; to: "/app"; className: string; }' is missing the following properties from 
type 'CheckPathError<RoutesInfo<RootRoute<{}, RouteContext, RouterContext>>, "/app">': Error, 'Valid Route Paths'
```

### Expected behavior

As a user I expected there not to be an issue with typing. 

### Screenshots or Videos

![image](https://user-images.githubusercontent.com/93608862/222589623-1b897ddb-4be0-41ed-8955-a162a0c5be1f.png)

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by balAdamT** [comment]
I notice this exact same behavior when trying to create nested routes.


```typescript
const homeRoute = new Route({
  getParentRoute: () => rootRoute,
  path: "/",
  component: HomeComponent,
});

const moduleRoute= new Route({
  getParentRoute: () => rootRoute,
  path: "module",
  component: ModuleComponent,
});

const subRoute = new Route({
  getParentRoute: () => moduleRoute,
  path: "sub",
  component: SubComponent,
});

const routeTree = rootRoute.addChildren([
  homeRoute,
  moduleRoute
]);

moduleRoute.addChildren([subRoute]);

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
```

This works but creates the same type error as in the top comment when trying to create a Link component pointing to "/module/sub".

Curiously, if I add subRoute directly to rootRoute then the typings are correctly generated for "/module/sub" but understandably the router throws an error when trying to initializing the routes:

```typescript
const homeRoute = new Route({
  getParentRoute: () => rootRoute,
  path: "/",
  component: HomeComponent,
});

const moduleRoute= new Route({
  getParentRoute: () => rootRoute,
  path: "module",
  component: ModuleComponent,
});

const subRoute = new Route({
  getParentRoute: () => moduleRoute,
  path: "sub",
  component: SubComponent,
});

const routeTree = rootRoute.addChildren([
  homeRoute,
  moduleRoute,
  subRoute,
]);

declare module "@tanstack/react-router" {
  interface Register {
    router: typeof router;
  }
}
```

**Comment by bsell93** [comment]
I'm getting the same type error as well when using `useNavigate`
```
Argument of type '{ to: "/my-route/info"; }' is not assignable to parameter of type 'MakeLinkOptions<"/", "/my-route/info">'.
  Type '{ to: "/my-route/info"; }' is missing the following properties from type 'CheckPathError<RoutesInfo<Route<any, "/", "/", string, "__root__", {}, {}, {}, {}, RouterContext, RouterContext, RouteContext, RouterContext & RouteContext, RouterContext, (Route<...> | Route<...>)[], DefaultRoutesInfo>>, "/self-service/info">': Error, 'Valid Route Paths'ts(2345)
```

usage:
```ts
navigate({
    to: MyRoute.id,
});
```

**Comment by bsell93** [comment]
@ulnk try using the route id directly instead of a string and see if that works
`to={appIndexRoute.id}`

**Comment by dwamianm** [comment]
Adding the following fixed the issue for me

```
declare module '@tanstack/router' {
  interface RegisterRouter {
    router: typeof router;
  }
}
```

I am not sure why using `RegisterRouter` vs `Register` as per the examples in the documentation helps, but the error is now gone.

**Comment by bsell93** [comment]
@dwamianm I'm not seeing a type of `RegisterRouter` in tanstack/router code; I did find `RegisteredRoute`. I changed it to what you suggested as well as `RegisteredRoute` and it got rid of the typing error, but now I have not typing declaration for any router code. From what I'm seeing it just changes it to `any`, which of course will allow you to do anything without errors.

**Comment by marklai1998** [comment]
give it a little push

**Comment by tannerlinsley** [comment]
The examples are up to date with the best practices for type-safety and this the proper way to register your router:

```tsx
// Register your router for maximum type safety
declare module '@tanstack/router' {
  interface Register {
    router: typeof router
  }
}
```

**Comment by bzbetty** [comment]
> I am not sure why using RegisterRouter vs Register as per the examples in the documentation helps, but the error is now gone.

pretty sure it's because it falls back to making the router any typed so you get no typing at all at that stage.

for me the issue was I needed to update both @tanstack/react-router and @tanstack/router-cli to the latest beta (and make sure their versions lined up).
