### ISSUE TITLE
Cancelling navigation with `usePrompt` does not reset search params

### ISSUE THREAD

**Issue by tu4mo** [TanStack/router#560]
### Describe the bug

Cancelling navigation with `usePrompt` does not reset search params. As seen in the code, only pathname is reset.

https://github.com/TanStack/router/blob/33c8bdbf3737d23e6026fcb6f318d6669caebd53/packages/react-location/src/index.tsx#L1735-L1740

### Your Example Website or App

https://codesandbox.io/s/elastic-sanderson-uu29mv?file=/src/index.tsx

### Steps to Reproduce the Bug or Issue

1. Click Save
2. Cancel prompt
3. Edit text in input
4. `foo` changes to `true`

### Expected behavior

`foo` stays `false`.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 111

**Comment by tannerlinsley** [comment]
This is for react-location, which I don't plan on working on much any more. Please try TanStack Router with `Blocker` and `useBlocker` to get a better experience.
