### ISSUE TITLE
Path after a param is not matched

### ISSUE THREAD

**Issue by GyanendroKh** [TanStack/router#562]
### Describe the bug

For the following routes
- `/`
- `/$id`
- `/$id/edit`

`/1/edit` matches `/$id` not `/$id/edit`

Route Tree:
```typescript
const indexRoute = new Route({
  getParentRoute: () => rootRoute,
  path: '/',
  component: () => <h1>Home Page</h1>,
});

const blogRoute = new Route({
  getParentRoute: () => rootRoute,
  path: '$id',
  component: () => {
    const { id } = useParams({ from: '/$id' });
    return <h1>Blog Page {id}</h1>;
  },
});

const blogEditRoute = new Route({
  getParentRoute: () => rootRoute,
  path: '$id/edit',
  component: () => {
    const { id } = useParams({ from: '/$id/edit' });
    return <h1>Blog Edit Page {id}</h1>;
  },
});

const routeTree = rootRoute.addChildren([blogRoute, blogEditRoute]);

const router = new ReactRouter({ routeTree });
```

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-9sc5p3?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Create a React Project with `@tanstack/react-router@^0.0.1-beta.83`
2. Use the following code for the `RouteTree`
```typescript
const indexRoute = new Route({
  getParentRoute: () => rootRoute,
  path: '/',
  component: () => <h1>Home Page</h1>,
});

const blogRoute = new Route({
  getParentRoute: () => rootRoute,
  path: '$id',
  component: () => {
    const { id } = useParams({ from: '/$id' });
    return <h1>Blog Page {id}</h1>;
  },
});

const blogEditRoute = new Route({
  getParentRoute: () => rootRoute,
  path: '$id/edit',
  component: () => {
    const { id } = useParams({ from: '/$id/edit' });
    return <h1>Blog Edit Page {id}</h1>;
  },
});

const routeTree = rootRoute.addChildren([indexRoute, blogRoute, blogEditRoute]);

const router = new ReactRouter({ routeTree });
```
3. Navigate to `/1/edit`

### Expected behavior

- `/1` should match `/$id` (`blogRoute`)
- `/1/edit` should match `/$id/edit` (`blogEditRoute`)

### Platform

- OS: macOS
- Browser: Chrome
- Version: ^0.0.1-beta.83

**Comment by GyanendroKh** [comment]
https://github.com/TanStack/router/blob/7d3bfbfe3942220931c68f9c26169c6e0c84097a/packages/router/src/path.ts#L225-L232

I found out that the above is responsible for matching path with params.
And to my understanding, there is no check for when the route segment with the param is the last one but the base segment is not.
However there is an overall path check for fuzzy matching at https://github.com/TanStack/router/blob/7d3bfbfe3942220931c68f9c26169c6e0c84097a/packages/router/src/path.ts#L235-L237 It seems that this is the issue.

A naive way to solve this is to not fuzzy match when there is a path param, like I did [here](https://stackblitz.com/edit/vitejs-vite-h335s7?file=src%2Fmain.tsx) with `patch-package`

Whether a path should be fuzzy matched comes from https://github.com/TanStack/router/blob/7d3bfbfe3942220931c68f9c26169c6e0c84097a/packages/router/src/router.ts#L604
I don't have the full understanding for why this is choosen so it will be nice if someone can please help with this

**Comment by kdubb** [comment]
@Harrisonl according to https://tanstack.com/router/v1/docs/guide/route-matching that seems on purpose...

> This means that regardless of the order your route tree is defined, routes will always be sorted to this order:
>
> Index Routes
> Static Routes (longest to shortest)
> Dynamic Routes (longest to shortest)
> Splat/Wildcard Routes

**Comment by paavohuhtala** [comment]
I was really surprised to see that these kinds of routes do not work, either by design or because of a bug. They are extremely common in web applications - for example, the URL of this very page (`/$userName/$repositoryName/issues/$issueId`) would not be implementable with TanStack Router.

**Comment by CanRau** [comment]
No idea what I'm talking about, though in Remix you'd need to have an `<Outlet />` within a subpath like `/$id/edit` so the `$id` file needs to contain `<Outlet />` somewhere for `edit` to be able to show.

Though Next for example doesn't need this 🤷🏻‍♂️

**Comment by tannerlinsley** [comment]
This issue should now be fixed. Please try it out and let me know if I've failed your expectations ;)
