### ISSUE TITLE
useSearch invariant failed on React 17

### ISSUE THREAD

**Issue by kbrah** [TanStack/router#566]
### Describe the bug

In some cases I get invariant failed error when using useSearch hook with prop { from: route.id }.
It seems that this happens with routes that have search params validation. 

### Your Example Website or App

pre-configured stackbliz fails installing dependencies

### Steps to Reproduce the Bug or Issue

The tricky thing is that I'm not sure how to reproduce this as it doesn't always seem to happen at least in my app. I have a micro frontend application and this problem seems to appear when I navigate outside of my tanstack router mfe, refresh the page, navigate back to the mfe with tanstack router, then inside the mfe navigate from a component where the hook useSearch({ from: route.id}). It only happens if route has a search params validation.

### Expected behavior

no error

### Platform

Linux
Chromium

**Comment by tannerlinsley** [comment]
This is likely fixed now.
