### ISSUE TITLE
Using a `lazy()`-loaded component throws an error

### ISSUE THREAD

**Issue by happycollision** [TanStack/router#567]
### Describe the bug

I think this is a problem that resides inside the router and not with `lazy`, but when you create a lazy component, then try to navigate to that route, you get `this.router.options.loadComponent is not a function`.

As suggested by the _original_ title (I changed it in case I am slightly off the mark: "Setting `.preload` on a `RouteComponent` throws an error") the problem seems to occur when the component has a `.preload` property.

### Your Example Website or App

https://stackblitz.com/edit/github-x9l1s9?file=src%2Fmain.tsx%3AL37&v=1

### Steps to Reproduce the Bug or Issue

1. visit the provided stackblitz link
2. click on "about" in the running app

### Expected behavior

Haha. I expected the route to load, but instead...

```
this.router.options.loadComponent is not a function
```

### Screenshots or Videos

<img width="457" alt="CleanShot 2023-03-24 at 10 17 08@2x" src="https://user-images.githubusercontent.com/3663628/227548218-822f8fd0-b6cf-42e4-bb88-1cdee0a054c1.png">

![CleanShot 2023-03-24 at 10 15 45](https://user-images.githubusercontent.com/3663628/227547421-b7e99ab3-e5c9-460a-a3c1-3f297ba023d1.gif)

### Platform

- OS: macOS
- Browser:  Firefox

**Comment by greatcrypter** [comment]
@happycollision  temporary fix example:

import { Router } from '@tanstack/react-router';

const routeTree = rootRoute.addChildren([]);

new Router({
  routeTree,
  loadComponent: async (component) => {
    if (component.preload) {
      await component.preload();
    }

    return component;
  },
});

**Comment by sicksid** [comment]
thank you much @greatcrypter 

i was able to also get it working, so far I'm loving this router I have a nextjs setup as a SPA for this and is a delight to be able to quickly add stuff to my project  http://github.com/sicksid/reminders
