### ISSUE TITLE
Global wrapInSuspsense option

### ISSUE THREAD

**Issue by Reilley64** [TanStack/router#569]
### Describe the bug

Can't globally set wrapInSuspense to false so that routes go to the nearest route with a pendingComponent by default for the app. Would be good to allow setting this so it is inline with how ErrorBoundaries work. Seems like this was set up as apart of this [issue](https://github.com/TanStack/router/issues/477).

### Your Example Website or App

https://discord.com/channels/719702312431386674/1007702008448426065/1090132410391334922

### Steps to Reproduce the Bug or Issue

1. Create router
2. Give router a defaultPendingComponent
3. Implement routes
4. Give a parent of a child a pendingComponent
5. Don't give the child wrapInSuspense
6. Child renders defaultPendingComponent and not it's parents pendingComponent

### Expected behavior

I expect the ability to choose on the Router constructor if I want routes to go to the nearest parents pending component or the defaultPendingComponent.

### Platform

N/A

**Comment by tannerlinsley** [comment]
Happy to look at a PR for this feature. Triaging this for now though.
