### ISSUE TITLE
useSearch is triggered for all consumers when query parameters changed

### ISSUE THREAD

**Issue by aboeglin** [TanStack/router#572]
### Describe the bug

I'm currently working on an app where we use some query strings as part of our state and thus `useSearch` is used in a few key places, including some expensive components. Now the issue we have is that whenever we use `navigate` to update the search, it triggers all consumers of `useSearch` even if they read different keys. That is to be expected with the current API. So I'd expect to be able to do something like what you could do with most state managers that connect to react, having a selector API in between that only triggers a re-render when the selected slice changes. So something like:
```javascript
const slice = useSearch(({ neededKey }) => neededKey);
```

Now, that being said, maybe there's already a way to achieve something similar and we've just been missing it or designing things poorly, in which case, what would the solution be like?

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

-

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by tannerlinsley** [comment]
The latest version out now has `selector` and `track` props that allow you return a slice to watch instead of the whole set. Let me know how it works out for you!
