### ISSUE TITLE
Layout Routes break route sorting

### ISSUE THREAD

**Issue by xyng** [TanStack/router#584]
### Describe the bug

When using layout routes the `/` path is not matched correctly. The first route with a `path` will be used, even if its path does not match and a matching route exists. 
It appears that usage of layout routes between routes and root breaks the route sorting advertised in the docs

### Your Example Website or App

https://stackblitz.com/github/xyng/ts-router-sorting-bug

### Steps to Reproduce the Bug or Issue

1. Open StackBlitz Site
2. Compare `Current Path` with `Current Matches`. You will notice that `/login` is matched and rendered while the path is actually `/`
3. Swap lines `48` and `49`. If `layoutB` is added before `layoutA`, the correct route `/` is matched.

### Expected behavior

I expected that the layout-routes would be flattened and component-routes would be sorted as stated in the docs [here](https://web.archive.org/web/20230416205852/https://tanstack.com/router/v1/docs/guide/route-matching) (Web-Archive Link for future reference) and match the correct paths.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 112.0.5615.121 (arm64)
- Router Version: 0.0.1-beta.83

### Additional context

If you can give me a hint where that problem could be caused I'm happy to try help fixing it.

**Comment by Anjianto** [comment]
This is because your layoutA doesn't have component or you doesn't set default component on options. And it has been explain on the docs.

Documentation: https://tanstack.com/router/v1/docs/guide/routes#outlets

https://github.com/TanStack/router/blob/8d7f9e314a061cf9650fd64528fd679100669ebc/packages/router/src/react.tsx#L600

**Comment by xyng** [comment]
@Anjianto thanks for trying to help - but that is not the problem here.
The component for the layout routes was left out just to simplify of the reproduction.

`Outlet` is the default fallback (is seen in your linked code snippet).
and even if you would add a `component: () => <div><Outlet /></div>` to the layout Routes the Problem persists.

This problem is about the routes not being flattened and sorted as described in the documentation (linked in issue).

**Comment by tannerlinsley** [comment]
This should be fixed as of beta-90
