### ISSUE TITLE
Loader instances doesn't inherit defaults properly

### ISSUE THREAD

**Issue by pawelblaszczyk5** [TanStack/router#586]
### Describe the bug

Loader instances settings related to caching doesn't seem to be inherited from defaults after the newest `84` beta version. You need to explicitly provide them to Loader instances, despite defaults being set on LoaderClient initialiization. 

### Your Example Website or App

https://github.com/pawelblaszczyk5/react-tanstack-playground

### Steps to Reproduce the Bug or Issue

1. Navigate between `home` and `about` routes
2. See that the `about` route loader is re-executed every single navigation
3. Uncomment specific loader settings in `loader-client` file - these are the same as defaults
4. Navigate between routes again
5. See that data is more aggressively cached 

### Expected behavior

Instances should properly inherit defaults and in this case the data shouldn't be refetched

### Platform

These doesn't seem to be applicable here
- OS: MacOS
- Browser: Arc (Chromium under the hood)
- Version: Chromium version 112.0.5615.121

### Additional context

Thanks for the awesome library 😊

**Comment by tannerlinsley** [comment]
Pretty sure that should be fixed now. Let me know if it isn't after this release goes out.

**Comment by pawelblaszczyk5** [comment]
Thanks a lot! Will check after version is pushed
