### ISSUE TITLE
"tanstack" react-router.js does not provide an export named 'useNavigate'

### ISSUE THREAD

**Issue by ssjunior** [TanStack/router#591]
### Describe the bug

The docs references the useNavigate

https://tanstack.com/router/v1/docs/api/react/useNavigate

but, it is not possible to import it

### Your Example Website or App

any url

### Steps to Reproduce the Bug or Issue

Declare:

import { useNavigate } from "@tanstack/react-router";

### Expected behavior

import useNavigate should happen

### Screenshots or Videos

caught SyntaxError: The requested module '/node_modules/.vite/deps/@tanstack_react-router.js?v=0246f1cf' does not provide an export named 'useNavigate'

### Platform

- OS: macOS
- Browser: Chrome
- Version: 112.0.5615.137 (Official Build) (x86_64)

### Additional context

Maybe I am missing something, but, can't find any references to this. :( Maybe the docs are wrong?

**Comment by bsell93** [comment]
@ssjunior what version are you using?

When I added it I had to explicitly specify the version

Example of what I ran
`yarn add @tanstack/react-router@0.0.1-beta.83`

**Comment by ssjunior** [comment]
@bsell93 thank you for answering. I'm using the same version.

>  pnpm install @tanstack/react-router@beta
Packages: +7
+++++++
Progress: resolved 442, reused 412, downloaded 0, added 0, done

dependencies:
+ @tanstack/react-router 0.0.1-beta.83

Does this version have useNavigate?

**Comment by bsell93** [comment]
@ssjunior interesting. I'm using useNavigate with that version and no type issues like the one you are seeing. 

I recommend creating a codesandbox of your exact dependencies and see if you can replicate the issue.

**Comment by ssjunior** [comment]
@bsell93 after some hours digging in this issue, I think the problem was related to migrating from an old beta version to this new one. I was using a createRouterConfig too that does not exists anymore.

The docs are very confusing and useNavigate is working now, but, useSearch is not working anymore (cannot destructure property 'track' of 'opts' as it is undefined ). I deleted all from node_modules and started again..

The library is fantastic, but the issues with documentation and breaking changes (expected in beta) causes some unexpectated downturns. 

Thank you very much for your promptly attention to this issue.
