### ISSUE TITLE
Some links on website broken

### ISSUE THREAD

**Issue by foxylion** [TanStack/router#596]
### Describe the bug

On the website docs (https://tanstack.com/router/v1/docs) some links are broken:

- "React" points to 404 on https://tanstack.com/router/v1/docs/adapters/router
- "Core API" points to 404 on https://tanstack.com/router/v1/docs/api/core
- "Router" points to 404 on https://tanstack.com/router/v1/docs/api/react/Router
- "route" points to 404 on https://tanstack.com/router/v1/docs/api/react/route
- "useLoader" points to 404 on https://tanstack.com/router/v1/docs/api/react/useLoader

### Steps to Reproduce the Bug or Issue

Open the website and use the navigation on the left to see the 404 pages.

### Expected behavior

The pages should not show 404, at least "no contents yet" should be displayed.
Currently the documentation draws a picture of "not mature enough to try".

### Platform

Firefox on Ubuntu 22.04

**Comment by AO19** [comment]
@tannerlinsley could you remove the redirect to tanstack router, I would like to access react-location. Where can I access the old docs?

**Comment by michaelboyles** [comment]
Similarly, I notice that both 'React Routers > route' and 'React Components > Route' both get highlighted on the left when either one is selected.

Presumably because the URL/name of both are the same, when considered case-insensitively

**Comment by tannerlinsley** [comment]
Cleaned this up significantly. Thanks for the input! The docs will just keep getting better.
