### ISSUE TITLE
Does not support query params starting with "0" ie: "01234"

### ISSUE THREAD

**Issue by nicko-winner** [TanStack/router#601]
### Describe the bug

Zero characters are stripped from query params by the qs.encode() function.  Query param containing value of  "01234" will become "1234", passing a different encode methods to: `parseSearchWith()` does not work,  as the value is stripped out earlier in qs.encode(), so one must over ride the entire query parsing functionality. 

### Your Example Website or App

https

### Steps to Reproduce the Bug or Issue

1. Pick a query param value that starts with a 0 ie: 01234
2. notice the value returned from router is 1234

### Expected behavior

If query param value is 01234,  when it pulled from the router is should as 01234, not 1234

### Platform

- OS: Any
- Browser: Chrom/Node
@tanstack/react-location: "^3.7.4",

**Comment by tannerlinsley** [comment]
Sounds like we'll need to get in the middle of this a bit more. Maybe we offer some inversion of control for number parsing.

**Comment by tannerlinsley** [comment]
Tracked in #537
