### ISSUE TITLE
Link component requires search property when dynamic props are passed

### ISSUE THREAD

**Issue by dexcabigting** [TanStack/router#606]
### Describe the bug

When passing Link properties such as "to" from a functional component (e.g. <CustomComponent to={'/hello'} /> to the Link component, typescript finds an error.

![image](https://github.com/TanStack/router/assets/84834319/6efcb295-4dbd-4a2c-9911-beea7b6a8cb4)
![image](https://github.com/TanStack/router/assets/84834319/f38f53e9-cb4f-4eaa-b46f-193caadc185c)

### Your Example Website or App

https://stackblitz.com/edit/github-2ukgln?file=src%2FNavLink%2Findex.tsx

### Steps to Reproduce the Bug or Issue

1. Create a functional component that receives props to be used by Link component
2. See error

### Expected behavior

As a developer, it is expected for the Link component to omit the error due to the search property that is not being used in the component itself

### Platform

- OS: macOS
- Browser: Chrome
- Version: 113.0.5672.126

**Comment by twiddler** [comment]
@tyleralbee I don't see how your answer relates to the bug. Can you post a stackblitz or something similar?

**Comment by tyleralbee** [comment]
> @tyleralbee I don't see how your answer relates to the bug. Can you post a stackblitz or something similar?

Let me try to break it down further instead. 

The bug outlined in the original post is something like this:

- A child component utilizing `Link` requires a prop to determine where it should link to. 
- In OP's case, he or she has a prop named `to` that evaluates to `/hello`. 
- In doing so, the TypeError in the original post is raised.

The TypeError is indicating that a `search` property is required for the Link component - but this isn't necessarily true. In OP's case, it looks like `/hello` doesn't require any route params (nor any `search` params).

I've worked around this in my own codebases in one of two ways.

In OP's case, he or she could define the `to` prop as a union of the values that the string could be:
```jsx
interface Props {
    to: "/hello" | "/example" | "/test";
    children: string;
}

const Example: React.FC<Props> = ({ to, children }) =>
    <Link
        to={to}
    >
        {children}
    </Link>
```

Or, as I wrote above in my other reply, you can pass the route object itself to the component instead. If your route has params (e.g. `/hello/$id`), I haven't found a way _other_ than doing it like this (if the Link is receiving dynamic props):

Imagine I have some route defined:

```jsx
import { Route } from "@tanstack/router";

import Example from "../../pages/Example";
import { rootRoute } from "../RootRoute";

export const exampleRoute = new Route({
    getParentRoute: () => rootRoute,
    path: "/example",
    component: Example,
});
```

I'd then pass `exampleRoute` as a prop to `Example` and set the `Link` `to` prop to `exampleRoute.fullPath`:

```jsx
const Example: React.FC<Props> = ({ route, children }) =>
    <Link
        to={route.fullPath}
    >
        {children}
    </Link>
```

**Comment by dexcabigting** [comment]
I appreciate the concerns @tyleralbee @twiddler and as well as the suggestions. I did pass the route object itself with some minor tweaks on the type annotations on the parent component where the routes come from, and to child components that utilize the link, and it pretty much solved the issue! 

Parent component:
![image](https://github.com/TanStack/router/assets/84834319/181b9389-369b-47fd-8a94-e15aa0c79034)

Child component:
 
![image](https://github.com/TanStack/router/assets/84834319/d0989724-0e04-46ec-a97e-e86902b27035)

**Comment by twiddler** [comment]
It'd be interesting to know whether this is the intended behaviour then. :thinking:

**Comment by tannerlinsley** [comment]
Any time you abstract `Link` to receive open-ended props, you're throwing type-safety out the window unless you build it back in. The easiest and best way to keep link type-safety is to not abstract it at all and just work with the types where you are composing them.

https://github.com/TanStack/router/blob/beta/examples/react/kitchen-sink-single-file/src/main.tsx#L162-L193

The solutions here look good enough to work around for now. I'll start collecting these type patterns in the docs for future reference.
