### ISSUE TITLE
Link not working on first click

### ISSUE THREAD

**Issue by edgar0011** [TanStack/router#609]
### Describe the bug

Link, not working properly, on first click, only the second click will change url params

can be seen in the examples:
https://tanstack.com/router/v1/docs/examples/react/basic

### Your Example Website or App

https://tanstack.com/router/v1/docs/examples/react/basic

### Steps to Reproduce the Bug or Issue

go to : https://tanstack.com/router/v1/docs/examples/react/basic
click on Home, Posts, or any post

### Expected behavior

Expect Link to work on the frist click

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

any

**Comment by tannerlinsley** [comment]
Fixed in latest
