### ISSUE TITLE
Double click problem to links

### ISSUE THREAD

**Issue by Rozygeldiyew-git** [TanStack/router#619]
### Describe the bug

Hello Everyone!.  I started using @tanstack/router for the first time and loved it. But there is a problem with it. For example, I have two Link components. Normally, when I click on one, the page should render and change, but if I click twice, these things happen. I have to click twice to go from that page to this page.

### Your Example Website or App

localhost

### Steps to Reproduce the Bug or Issue

on localhost

### Expected behavior

run once i click

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]
- Vite v4.3.9 + React v18.2.0 + Typescript v5.0.2 + @tanstack/router v0.0.1-beta.89

**Comment by Soufou69** [comment]
Hey,
seems similar to #597 
Its fixed in latest

**Comment by tannerlinsley** [comment]
Fixed in latest commit
