### ISSUE TITLE
Possible regression: Trailing and non trailing slash URLs match differently

### ISSUE THREAD

**Issue by AkshayPathak** [TanStack/router#625]
### Describe the bug

URLs ending in `/` do match the same as without the `/`. Possible regression of #370. 

### Your Example Website or App

https://tanstack.com/router/v1/docs/examples/react/kitchen-sink-multi-file?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to `Dashboard` and `Invoices`
2. Observe that `Create a new Invoice` section is visible
3. Add a trailing slash to the URL 

The `Create a new Invoice` section disappears. 

### Expected behavior

Content of trailing slashes should match as non-trailing slash urls. 

### Platform

- OS: Linux
- Browser: Chrome

**Comment by tannerlinsley** [comment]
Good catch. I’ll check it out.

Tanner Linsley

**Comment by tannerlinsley** [comment]
I can't replicate in the latest version. The page comes up for both non and trailing slash versions.

**Comment by AkshayPathak** [comment]
Seems like this was fixed in latest version.

**Comment by SuchMonkey** [comment]
I'm sorry to revive this but it seems to be broken again.
Or maybe I'm just misunderstanding the intended behavior.

**Reproduction using the Kitchen Sink Multi File example**
go to `/dashboard` -> dashboard page comes up
go to `/dashboard/` -> dashboard page comes up

go to `/expensive` -> expensive page comes up
go to `/expensive/` -> **no expensive** page comes up

**In summary**
If there is no index page assigned to a route it will not match if there is a trailing slash. Maybe this is intended but I find it confusing.

**A little motivation on why they should match**
We want to integrate our app in a Wordpress page. However WP really likes to rewrite URLs and they always end up with a trailing slash which results in a 404 in our app (we utilize a catch all route).

**Tested versions**
0.0.1-beta.134
0.0.1-beta.133
0.0.1-beta.119

Also, thanks for the great library and all the good work you put in :)

**Comment by tannerlinsley** [comment]
This is an easy fix. I’ll get on it

Tanner Linsley

**Comment by sobigyan** [comment]
Is this not fixed in the latest version?

I tested on the latest verion `v0.0.1-beta.145` with Quick Start example.

Routes with trailing slash are still not rendering
