### ISSUE TITLE
Loader data for wildcard routes is somehow being cached

### ISSUE THREAD

**Issue by manelio** [TanStack/router#626]
### Describe the bug

I previously reported a bug where the loader would only run the first time for wildcard paths. It seems that this problem is fixed.

But now it happens that, although the loader runs, the value of the `*` parameter does not change after the first run.

You can clearly see the problem in the codesandbox example.

This does not work correctly:

```
const catchAllRoute = new Route({
  getParentRoute: () => rootRoute,
  path: "*",
  component: CatchAll,
  loader: ({ params }) => {
    console.log(`Loader for ${params["*"]}`);
    // LOADER PARAMS DO NOT CHANGE ON SUBSEQUENT RUNS
    return { data: `Loaded data for ${JSON.stringify(params)}` };
  }
});
```

However, this works without problems (with the problem that it does not match nested routes):

```
const catchAllRoute = new Route({
  getParentRoute: () => rootRoute,
  path: "$*",
  component: CatchAll,
  loader: ({ params }) => {
    console.log(`Loader for ${params["*"]}`);
    return { data: `Loaded data for ${JSON.stringify(params)}` };
  }
});
```

### Your Example Website or App

https://codesandbox.io/s/gifted-herschel-4xthvm?file=/src/App.js

### Steps to Reproduce the Bug or Issue

Click on page 1 and see the loader params. Then click on page 2. Loader params did not change.

### Expected behavior

Loader params should change for each Link.

### Platform

Ubuntu Linux
Node 18
React 18

Edit: I traced the issue to here in `route.ts`:

```
      // Waste not, want not. If we already have a match for this route,
      // reuse it. This is important for layout routes, which might stick
      // around between navigation actions that only change leaf routes.
      return (existingMatches.find((d) => d.id === matchId) ||
        new RouteMatch(this, route, {
          id: matchId,
          params: allParams,
          pathname: joinPaths([this.basepath, interpolatedPath]),
        })) as RouteMatch
```

Edit 2: dirty patched `interpolatePath` to account for wildcards. Now it works, but I'm not sure there is no collateral damage.

```
export function interpolatePath(
  path: string | undefined,
  params: any,
  leaveWildcard?: boolean,
) {
  const interpolatedPathSegments = parsePathname(path)

  console.log(interpolatedPathSegments, params)

  return joinPaths(
    interpolatedPathSegments.map((segment) => {
      if (['$', '*'].includes(segment.value) && !leaveWildcard) {
        return ''
      }

      // Added this

      if (leaveWildcard && segment.type === 'wildcard') {
        return params![segment.value] ?? ''
      }

      if (segment.type === 'param') {
        return params![segment.value.substring(1)] ?? ''
      }

      return segment.value
    }),
  )
}
```

**Comment by tannerlinsley** [comment]
This was the change I made as well, but there were some other repercussions that I needed to iron out. It should be fixed in the release that's going out right now.
