### ISSUE TITLE
Nested path not working at all 

### ISSUE THREAD

**Issue by lorenzocorallo** [TanStack/router#628]
### Describe the bug

In nested routes, it returns the first one which has a component declared

Providing three cases

### Case 1: static/dynamic
- index
- customers (with component)
  - $customer

on `/customers/$customer` it renders `/customers` components
**note** -  if `customers` didn't have a component, it would render correctly the `$customer` route component

### Case 2: dynamic/static
- index
- $customer (with component)
  - profile

on `/$customer/profile` it renders `/$customer` components
**note** - if `$customer` didn't have a component, it would render correctly the `profile` route component
**note 2** - putting a static route at the begging without a component defined it doesn't change anything, but with a defined component it falls back to case 1

### Case 3: dynamic/dynamic
- index
- $customer (with component)
  - $invoice

on `/$customer/$invoice` it renders `/$customer` components
**note** - if `$customer` didn't have a component, it would render correctly the `$invoice` route component
**note 2** - putting a static route at the begging without a component defined it doesn't change anything, but with a defined component it falls back to case 1

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-6oq5wf?devToolsHeight=33&file=src%2FApp.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the stackblitz provided
2. Use the navigation to go deep into the routes
3. Check that when the url reaches the error case provided, it's rendering the wrong route

Repeat the procedure for all the three routes included in the codebase:
in `App.tsx:9` is possible to switch between `router1` `router2` `router3`
(switching can cause type problems, but it doesn't influence the bug described, which can also be reproduced using independently one of the router in a separated stackblitz)

### Expected behavior

In all of the three cases, on the most deep path it should render the most deep route

### Platform

- OS: Linux
- Browser: Brave
- Version: 1.52.122 Chromium: 114.0.5735.110 (Official Build) (64-bit)

### Additional context

Tested on the version `v0.0.1-beta.93` including the a65b71d8a6cf5e48bdf41bfd250367da179e22a1 commit fixing the #528 and it seems not to have really fixed it

**Comment by tannerlinsley** [comment]
You forgot to add an Outlet to your customers route: https://stackblitz.com/edit/stackblitz-starters-bgeff1?devToolsHeight=33&file=package.json,src%2Froutes%2Frouter1.tsx%3AL55

**Comment by lorenzocorallo** [comment]
@tannerlinsley I see, but is there any way to load the child component "overriding" the parent using the root Outlet?
Reference of this thing done in `react-router`: https://stackblitz.com/edit/stackblitz-starters-casmii?file=src%2FApp.tsx

**Comment by tannerlinsley** [comment]
Yeah that looks like a pretty basic layout route. I don’t see why you can’t do that here.

Tanner Linsley

**Comment by tannerlinsley** [comment]
There's lots of ways to slice it. Here is the one you're likely looking for: https://stackblitz.com/edit/stackblitz-starters-r4zupp?devToolsHeight=33&file=package.json,src%2Froutes%2Frouter1.tsx

**Comment by senicko** [comment]
@tannerlinsley Hi, I have encountered exactly the same issue. The example you have sent doesn't work at the moment (router 3 with invoices). This is a huge blocker for me (which I didn't expect). Is there any way to achieve this behaviour?

I would like to have routes like

- /clients 
- /clients/$clientId
- /clients/$clientId/invoices

And potentially deeper. /clients/$clientId/invoices route does not share anything with /clients/$clientId. The former could be some view for managing invoices for the client, the latter just details about the client.

**Comment by ChuckJonas** [comment]
@senicko did you figure this out?  I'm completely baffled how this is honestly not documented in the "getting started" docs.

**Comment by karstenpedersen** [comment]
@senicko, @ChuckJonas I could make it work with the following file structure:

- clients/
  - index.tsx
  - $id/
    - index.tsx
    - invoices.tsx

**Comment by Ylandolsi** [comment]
@karstenpedersen  it works thank you
