### ISSUE TITLE
Pathless layout routes after dynamic segments are not supported

### ISSUE THREAD

**Issue by queicherius** [TanStack/router#629]
### Describe the bug

If a pathless layout route is defined after a dynamic segment, this

1. causes the route not be recognized as a valid route path
2. causes a runtime error (cannot read properties of undefined) in `interpolatePath`

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-inner-path-slashes-bug-vkbrcs?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

See reproduction link. You can comment out L60 to see the type error mentioned in (1).

### Expected behavior

The types work without the workaround and there is no runtime error.

### Platform

N/A
`"@tanstack/router": "0.0.1-beta.97"`

**Comment by tannerlinsley** [comment]
Latest version fixes this shenanigans. I also made you a better working example to show it off :) 

https://stackblitz.com/edit/tanstack-router-inner-path-slashes-bug-ucmgak?file=package.json,src%2Fmain.tsx

**Comment by queicherius** [comment]
Amazing, thank you! 😄
