### ISSUE TITLE
Incorrect Route Matching with Layout Route and Wildcard Route

### ISSUE THREAD

**Issue by 4everTonyStark** [TanStack/router#633]
### Describe the bug

My app uses Single Sign-On, so I have the following route/component structure:

- Root Route, which renders an outlet
  - `/login/handler` Login callback handler route, which handles the sign-in redirect from SSO
  - Pathless Layout route (id `baseLayout`), which has an authentication boundary and provides a navigation drawer
    - `/` Index route, which renders a dashboard page
    - Content routes, which make up the pages of my app
    - `*` Wildcard route for "Not Found" page

With this route structure, the `/login/handler` route is not matched correctly. Opening the Devtools shows that instead of matching `/login/handler`, the router matches `/`, `/baseLayout`, and `/baseLayout/*login/callback`. Essentially, the router seems to be combining the wildcard route inside the layout route with the login callback route. 

In the example Stackbiltz, clicking on "Login" in the top bar should take you to the `/login/handler` page, but it instead renders the wildcard route.

Removing the wildcard route allows everything to match correctly.

### Your Example Website or App

https://stackblitz.com/edit/github-m6gcbx?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Create a root route that renders an outlet.
2. Create a "login" route with the root route as its parent.
3. Create a pathless layout route with the root route as its parent.
4. Create an index route/content routes with the layout route as their parent.
5. Create a wildcard route with the layout route as its parent.
6. Add all routes to the route tree.

### Expected behavior

When navigating to `/login/handler`, the `/login/callback` route should be matched, and the login handler component should be rendered.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 114.0.5735.198

**Comment by bsell93** [comment]
Seems like a legit issue.

This may not be ideal, but a potential workaround is you can extract the base layout component and then move the wildcard to have the root route as the parent and then just render the base layout component inside the wildcard component
https://stackblitz.com/edit/github-m6gcbx-omht3o?file=src%2Fmain.tsx
