### ISSUE TITLE
Race condition on context being set to route match

### ISSUE THREAD

**Issue by pawelblaszczyk5** [TanStack/router#640]
### Describe the bug

Hello 👋
I've been using context for meta and breadcrumbs handling and from the latest beta (108) it seems to be off. Apart from being renamed (which is fine 😄) it seems like there is a race condition of context being set and route being rendered. I used `currentMatches` to iterate through all matched routes and read context from each of them. Now it seems like `context` property is being undefined sometimes (rarely on refresh, often on SPA navigation). Although if I log it, it seems like route match is being mutated after a moment, because the context is present. Types also indicates that `context` should always be declared here.

### Your Example Website or App

https://stackblitz.com/edit/github-f7rmub-scmvwf?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to reproduction link
2. Refresh or navigate to different page (it may doesn't happen every time)
3. See error

### Expected behavior

Context being available while rendering

### Screenshots or Videos

<img width="507" alt="image" src="https://github.com/TanStack/router/assets/54995479/502a5793-40a1-470d-8405-2b88c98015cf">

https://github.com/TanStack/router/assets/54995479/82667cc9-6fee-42aa-992a-01cdadc80245

### Platform

- OS: macOS 14 beta
- Browser: Safari
- Version: 17

**Comment by tannerlinsley** [comment]
Fixed on latest. Thanks!
