### ISSUE TITLE
`ToOptions` references route IDs for `from` and `to` but only works with route full paths

### ISSUE THREAD

**Issue by queicherius** [TanStack/router#645]
### Describe the bug

In the documentation for [Navigation](https://tanstack.com/router/v1/docs/guide/navigation#tooptions-interface), the `ToOptions` interface references the "route ID" for the `from` and `to` options. However, in reality only the `useNavigate` hook's `from` property accepts route IDs, everything else does not.

### Your Example Website or App

https://stackblitz.com/edit/github-muxzpw?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Open above StackBlitz link
2. See type errors in lines 53, 58 and 62

### Expected behavior

Either the ID should be accepted for all `from` and `to` properties, or the documentation should be updated to reference `route.fullPath` instead of `route.id` (and `useNavigate` should probably not accept the route ID either).

### Platform

- OS: Any
- Browser: Any
- Version: `0.0.1-beta.108`

**Comment by tannerlinsley** [comment]
Do not use `route.id`, instead use `route.fullPath`. Along with the latest fixes, you're golden :)
