### ISSUE TITLE
Fixed in latest commit

### ISSUE THREAD

**Issue by LonelyFellas** [TanStack/router#647]
Fixed in latest commit

_Originally posted by @tannerlinsley in https://github.com/TanStack/router/issues/619#issuecomment-1622621654_
        double click proble to linked, i use latest @beta108, i found no fixed up this problem

**Comment by LonelyFellas** [comment]
i have to keep use react-router

**Comment by tannerlinsley** [comment]
This not a properly formatted issue. Regardless, can’t replicate what it eludes to. Please resubmit with a CodeSandBox or stackblitz replication.
