### ISSUE TITLE
Route matches ID include "undefined"

### ISSUE THREAD

**Issue by fnn** [TanStack/router#648]
### Describe the bug

Match IDs include an "undefined" string.

### Your Example Website or App

https://stackblitz.com/edit/github-b9agtn?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

Look at the matches IDs in the router dev tools or console log the ID from "useMatch()" (StackBlitz example include console log for about page)

### Expected behavior

Match IDs should not include "undefined" string

### Platform

- OS: Linux
- Browser: Chrome
- Version: 115.0.5790.90

**Comment by tannerlinsley** [comment]
The latest version no longer suffers from this issue. Thanks!
