### ISSUE TITLE
Search param serialization is applied to non-complex types

### ISSUE THREAD

**Issue by queicherius** [TanStack/router#654]
### Describe the bug

Following the documentation about [custom search param serialization](https://tanstack.com/router/v1/docs/guide/custom-search-param-serialization#using-jsurl2), this causes search params that are strings (and supposed to stay strings, not serialized JSON) to be parsed as if they were JSON.

### Your Example Website or App

https://stackblitz.com/edit/github-uj9eef?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Open the StackBlitz link
2. Observe that the string `SOME_STRING_THAT_SHOULD_NOT_BE_PARSED` is parsed in JSUrl2 format, which results in `SOME STRING THAT SHOULD NOT BE PARSED`.

### Expected behavior

I'm not sure if this is the expected behaviour, a documentation issue or an issue with when the search param parsing is applied via `parseSearchWith`. I can see that the logic there is "if it's a string try to parse and if that doesnt have an error take that result". Maybe it should also have a "if the result is not a string"?

### Platform

- OS: Any
- Browser: Any
- Version: 0.0.1-beta.119

**Comment by tannerlinsley** [comment]
I think this is solved with #679
