### ISSUE TITLE
Changing search parameters ends up with invoking the loader with initial parameters

### ISSUE THREAD

**Issue by stunaz** [TanStack/router#668]
### Describe the bug

The search params seem to be resolved to default after being updated.
1 -initial load is correct
2 - I change the search parameter, I can see in the console log the fetch being done with the right parameter
3 - there is an extra fetch with the initial search params (which breaks the expected behaviour)

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-baz8pk?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

use this https://stackblitz.com/edit/tanstack-router-baz8pk?file=src%2Fmain.tsx
click on "1" or "2", we have the same posts being displayed.

### Expected behavior

having the next 2 posts, when I click on "2"

### Platform

- OS: macOS
- Browser: chrome

**Comment by tannerlinsley** [comment]
Pushing a release to fix the search params being stale. Also, refer to this example to see the new suggested way of structuring reusable route data 😄 : https://stackblitz.com/edit/tanstack-router-xpiy1j?file=src%2Fmain.tsx,package.json

**Comment by stunaz** [comment]
Tested! working well. using `useContext` 💯
