### ISSUE TITLE
Directly nested pathless routes' beforeLoads called before parent beforeLoad completes

### ISSUE THREAD

**Issue by mekodes** [TanStack/router#675]
### Describe the bug

Hi there,

In the documentation for [authenticated routes](https://tanstack.com/router/v1/docs/guide/authenticated-routes#the-routebeforeload-option) it states `It's important to know that the beforeLoad function for a route is called before any of it's child routes' beforeLoad functions. It is essentially a middleware function for the route and all of it's children.`. 

I have a route setup where there are two directly nested pathless routes (e.g. `/pathless-1/pathless-2/`) which both have `beforeLoad` set with async calls and I noticed that both run in parallel instead of `pathless-1` running first followed by `pathless-2` running second.

I've added a minimal stackblitz to hopefully demonstrate the issue.

You can see in the console that the beforeLoads of the nested pathless routes are not sequential. I was hoping that the beforeLoad expectation would hold for pathless routes but I'm not sure if this is by design.

Thanks in advance.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-km22pw?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to Stackblitz
2. Let it run
3. Open console
4. You should see logs as follows:

- layout-3 beforeLoad finished (should log third)
- layout-1 beforeLoad finished (should log first)
- layout-2 beforeLoad finished (should log second)

### Expected behavior

I expected the pathless child route beforeLoad to only be called once the parent beforeLoad completed. The log in the stackblitz should be the following:

- layout-1 beforeLoad finished (should log first)
- layout-2 beforeLoad finished (should log second)
- layout-3 beforeLoad finished (should log third)

### Platform

- OS: macOS
- Browser: Chrome
- Version: 115.0.5790.170

**Comment by tannerlinsley** [comment]
Just pushed a release for this. Let me know if it's still an issue!

**Comment by mekodes** [comment]
Just confirmed, working like a charm with beta148, thank you @tannerlinsley, really appreciate it
