### ISSUE TITLE
The package is missing published types (regression)

### ISSUE THREAD

**Issue by queicherius** [TanStack/router#676]
### Describe the bug

Since `0.0.1-beta.147` the `build/types/index.d.ts` file only contains the license header and no actual types.

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

1. Install the package
2. `cat node_modules/@tanstack/router/build/types/index.d.ts`

### Expected behavior

The types are published as before (last good version was `0.0.1-beta.146`)

### Platform

- OS: Any
- Browser: Any
- Version: 0.0.1-beta.147-0.0.1-beta.150

**Comment by tannerlinsley** [comment]
Use `@tanstack/react-router` instead. https://github.com/TanStack/router/blob/beta/packages/router/src/index.ts#L3

**Comment by tannerlinsley** [comment]
Fixed
