### ISSUE TITLE
Link / navigate prop State is not being passed to the "navigated to" location

### ISSUE THREAD

**Issue by ao-Barbosa** [TanStack/router#680]
### Describe the bug

As described in Issue #445, the state prop, used in both link and navigate, is not being correctly passed to the location.

Accessing LocationState at the "navigated to" location only reveals an { id: string, key?: string } object.

Is this intended?

Does the router recommend any other way of passing down state to a given specific route? Preferably a type-safe way of doing so.

### Your Example Website or App

https://stackblitz.com/edit/github-hqyitv?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

Clicking on the about way reveals the LocationState object, which only contains the id key.

### Expected behavior

The display object should contain the value provided as prop (```{"test":"value"}```).

### Platform

- OS: Windows
- Browser: Chrome
- Version: 115.0.5790.171

**Comment by hjbolide** [comment]
Raised: https://github.com/TanStack/router/pull/690

**Comment by hjbolide** [comment]
Fixed in https://github.com/TanStack/router/releases/tag/v0.0.1-beta.155
