### ISSUE TITLE
Many executions for route `getContext`

### ISSUE THREAD

**Issue by fnn** [TanStack/router#684]
### Describe the bug

The `getContext` function for a route is executed multiple times. In the example provided around 10 times. In my project it is between 4-50 executions.

### Your Example Website or App

https://stackblitz.com/edit/github-8jqg94

### Steps to Reproduce the Bug or Issue

1. Go to index route
2. Open dev-tools
3. See all the log messages from `getContext`

### Expected behavior

`getContext` is only executed once.

### Platform

- OS: Linux
- Browser: Chrome
- Version: 115.0.5790.90

**Comment by tannerlinsley** [comment]
`getContext` is part of the `matchRoute` logic, which is run quite a bit. It powers:
- Link Generation
- Preloading
- Route Matching
- Route Loading

Long-story short, don't be alarmed. You shouldn't be doing much heavy lifting getContext regardless

**Comment by fnn** [comment]
@tannerlinsley, thanks for your answer. I see your point and I don't want to optimize too early.

I just saw the `react-query` example where you use `getContext` to create the query options and it felt wrong to create multiple query options objects 50 times (in my case) per route.
