### ISSUE TITLE
Root Route getContext & useLoader missing Types when using createRootRoute

### ISSUE THREAD

**Issue by vyrotek** [TanStack/router#685]
### Describe the bug

When using `new RouterContext<RootContext>` and `routerContext.createRootRoute` the context type is not provided to `getContext` of the Root Route.

### Your Example Website or App

https://stackblitz.com/edit/github-pw3mlo?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

See repro proj sections labeled // Expected...

### Expected behavior

I expected the useContext on the Root Route to be typed based on the RootContext type specified.

### Platform

- OS: Windows
- Browser: Edge

**Comment by tannerlinsley** [comment]
Looks like a bug. I'll get on it

**Comment by vyrotek** [comment]
Thanks @tannerlinsley. I just noticed another similar issue and updated this repo.

`useLoader` doesn't seem to reflect the data type when using `loader` on a Root component created with `createRootRoute` either.

**Comment by SeanCassiere** [comment]
The context values also aren't typed in the `loader` function for the `RouterContext`.
The values are available, just not typed.
<img width="1679" alt="image" src="https://github.com/TanStack/router/assets/33615041/cb3eba0a-7bba-4b4c-b14c-04d2536e94cd">
