### ISSUE TITLE
TS2589: Type instantiation is excessively deep and possibly infinite

### ISSUE THREAD

**Issue by vitzalt** [TanStack/router#686]
### Describe the bug

When the project has too many routes, or too much route nesting, the TypeScript compiler runs into issues and the build fails with the following error:

`TS2589: Type instantiation is excessively deep and possibly infinite.`

I've been experimenting with the router on an existing project and migrating across, but I kept running into this error. I thought at first it was due to circular references, but I've managed to narrow it down to the cause being the complexity of the `Route` type.

In an empty project, I made a flat, single-level router with no nesting. I deduced that, for my build, 234 child routes would build (although very slowly), while 235 child routes would fail with the type error. But only if you try to reference a route, eg to use a `Link` component.

This error is trigger by the TS compiler when `instantiationCount >= 5000000`. In the source code there's a function called `instantiateTypeWithAlias`, which has this comment:
```
// We have reached 100 recursive type instantiations, or 5M type instantiations caused by the same statement
// or expression. There is a very high likelyhood we're dealing with a combination of infinite generic types
// that perpetually generate new type identities, so we stop the recursion here by yielding the error type.
```

I think because there's so much recursive typing in the `Route` type, it gets too heavy for it once you get a couple of hundred routes.

I've added a Stackblitz with 235 routes - it doesn't crash Stackblitz, but you can see that the `Link` usage has a type warning with the same message.

Hoping it's not a fundamental issue as I was really enjoying the typed router 🙌

### Your Example Website or App

https://stackblitz.com/edit/github-jh8qhu?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. In a simple project, add a child route to the root route
2. Add a `<Link>` pointing to that route
3. through 236. Add another child route
237. Observe type error in console and in IDE

### Expected behavior

Expected the app to build, but observed a type error

### Screenshots or Videos

![tanstack-router-types](https://github.com/TanStack/router/assets/142844690/6131badd-0937-4de9-a61f-62c3671cb511)

### Platform

- OS: macOS
- Browser: Chrome
- React: 18.2.0
- TypeScript: 4.9.5

**Comment by tannerlinsley** [comment]
Looking into this.  It has to do with the autocomplete types in `ToOptions`

**Comment by tannerlinsley** [comment]
https://twitter.com/tannerlinsley/status/1694017673095737828?s=20

**Comment by tannerlinsley** [comment]
As far as I know, this is now fixed. https://stackblitz.com/edit/github-jh8qhu-b6ekrd?file=src%2Fmain.tsx
