### ISSUE TITLE
Type-safety regressions in the latest beta

### ISSUE THREAD

**Issue by pawelblaszczyk5** [TanStack/router#693]
### Describe the bug

[This commit](https://github.com/TanStack/router/commit/133c6780c5d14132c0e1405d99a7ccdcf9c10fb6) seems to make the type checking much faster, however there're few regressions in cases of typechecking.

- `redirect` method types aren't using `RegisteredRouter` types.
- `RouterState` matches aren't using `RegisteredRouter` types. I am using something like this  `export const useMatches = () => useRouterState({ select: state => state.matches });` currently instead of the built-in `useMatches`, because the workaround had proper types. Now both of them don't use our router type.

### Your Example Website or App

https://stackblitz.com/edit/github-kmrmjb?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

Redirect being untyped: 
1. Import `redirect` from router
2. Try to invoke `redirect` with inexistent path
3. It doesn't type-error

useRouterState matches and/or useMatches
1. Use the hook
2. Try to access matches' e.g. context
3. Observe incorrect types

### Expected behavior

Redirect should have proper types based on `RegisteredRouter`.
There should be a way to access `matches` in a type-safe way, e.g. to access all rendered routes contexts.

### Platform

- OS: macOS
- Browser: Safari
- Version: 17.0 beta

**Comment by tannerlinsley** [comment]
Easily fixable with the new types

**Comment by pawelblaszczyk5** [comment]
The `redirect` seems to be fixed, `RouterState` matches doesn't though.
Updated playground to latest router version: https://stackblitz.com/edit/github-kmrmjb?file=src%2Fmain.tsx
