### ISSUE TITLE
Latest version now causes Router instance to show an error of: 'router' implicitly has type 'any'

### ISSUE THREAD

**Issue by vyrotek** [TanStack/router#694]
### Describe the bug

The last version introduced some sort of type issue. Router instance now has a TS error:

> 'router' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

### Your Example Website or App

https://stackblitz.com/edit/github-ythixe?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

Open untouched stackblitz repro and look at VSCode errors. No need to run.

### Expected behavior

No error

### Platform

OS: Windows
Browser: Edge
Version: Beta 159

**Comment by tannerlinsley** [comment]
Fixed!
