### ISSUE TITLE
Types are not safe in `useNavigate` `search`

### ISSUE THREAD

**Issue by lsmurray** [TanStack/router#702]
### Describe the bug

The types for the `search` param in `useNavigate => navigate({search})` resolve to any.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-3czs9l?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

Open `main.tsx`. Check out line 398. The types for search and the param to search are not safe in the `navigate` function returned by `useNavigate`. Check out line 415. The types for search and the param to search are safe in a `Link` component. I'm not sure what this difference is between `Link` and `useNavigate`. The types look like they resolve to the same thing but `Link` is strongly typed but `useNavigate` is not.

### Expected behavior

I would expect the types for `old` to be strongly typed.

```
old: {
    showNotes?: boolean | undefined;
    notes?: string | undefined;
    usersView?: {
        sortBy?: "id" | "name" | "email" | undefined;
        filterBy?: string | undefined;
    } | undefined;
    userId?: number | undefined;
    redirect?: string | undefined;
}
```

instead the type is `old: any`.

### Platform

Reproducible in stackblitz and chrome.

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by lsmurray** [comment]
I think the issue has to do with the definition of `useNavigate`. Somehow the line in the `React.useCallback`

`opts?: NavigateOptions<RegisteredRouter['routeTree'], TFrom, TTo>`

is resolving the registered router to the type `any` instead of picking up the registered router.

**Comment by tannerlinsley** [comment]
Fixed
