### ISSUE TITLE
Remove errant console log for `resetScroll`

### ISSUE THREAD

**Issue by SeanCassiere** [TanStack/router#703]
### Describe the bug

Removing this console log statement that prints "resetScroll".

The log is being emitted at [this line](https://github.com/TanStack/router/blob/beta/packages/router-core/src/router.ts#L1713).

### Your Example Website or App

https://github.com/TanStack/router/blob/beta/packages/router-core/src/router.ts#L1713

### Steps to Reproduce the Bug or Issue

1. Add the <ScrollResetoration /> component into your app.
2. Navigate from one route to another.
3. Check the console for the log.

### Expected behavior

As a user, I shouldn't be seeing any `info` or `warn` level console logs from this library when in production.

### Screenshots or Videos

<img width="1678" alt="image" src="https://github.com/TanStack/router/assets/33615041/d1e45c73-f422-4ea1-b584-91cfc9141295">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 116

**Comment by tannerlinsley** [comment]
Fixed
