### ISSUE TITLE
Runtime Error While Routing : Uncaught runtime errors: ERROR Cannot read properties of undefined (reading 'routeId')

### ISSUE THREAD

**Issue by baki-kucukcakiroglu** [TanStack/router#704]
### Describe the bug

I'm having this runtime error while routing a heavyweight page and go back immediately after the page loads. This problem only occurs on local webpack-dev-server but not on production build which is deployed on cloud. Routing on local dev server works slower than production, this may be the reason why this problem only occurs on local dev server. Also, this problem not occurs on the pages that is lightweight(fast loading), also not every time occurs in a heavyweight page. All these reasons make me believe tanstack router checks a resource before it is not available. 

Runtime error message changes by browser but I think they indicate the same thing:

**Chrome**
![](https://cdn.discordapp.com/attachments/1146103240392462408/1146103240769937548/Screenshot_2023-08-29_at_18.23.38.png)

**Firefox**
<img width="1726" alt="Screenshot 2023-08-30 at 15 20 42" src="https://github.com/TanStack/router/assets/113987895/a42e09cc-7cef-472e-96a9-50ae3c8c35ad">

**Safari**
<img width="1752" alt="Screenshot 2023-08-30 at 15 30 53" src="https://github.com/TanStack/router/assets/113987895/733f30b4-5111-478b-8ca9-ab5eec0c20eb">

I added null checks anywhere routeId is used like x.routeId in node_modules/@tanstack/react-router/build/umd/index.production.js to see if the problem will be solved. Now the error is changed. I attached the image of the error message to this message.

![](https://cdn.discordapp.com/attachments/1146103240392462408/1146123066783563796/Screenshot_2023-08-29_at_19.43.26.png)

### Your Example Website or App

//

### Steps to Reproduce the Bug or Issue

"dependencies": {
    "@coreui/coreui": "^4.3.0",
    "@coreui/react": "^4.9.2",
    "@emotion/react": "^11.11.1",
    "@emotion/styled": "^11.11.0",
    "@mui/base": "^5.0.0-beta.13",
    "@mui/icons-material": "^5.14.7",
    "@mui/lab": "^5.0.0-alpha.142",
    "@mui/material": "^5.14.7",
    "@mui/x-data-grid": "^6.12.0",
    "@mui/x-date-pickers": "^6.12.0",
    "@tanstack/match-sorter-utils": "^8.8.4",
    "@tanstack/react-router": "^0.0.1-beta.173",
    "@tanstack/react-table": "^8.9.3",
    "@tanstack/router-devtools": "^0.0.1-beta.173",
    "chart.js": "^4.2.1",
    "classnames": "^2.3.2",
    "core-js": "^3.29.0",
    "cronstrue": "^2.31.0",
    "export-to-csv": "^0.2.1",
    "history": "^5.3.0",
    "jsonschema": "^1.4.1",
    "jszip": "^3.10.1",
    "less": "^4.2.0",
    "match-sorter": "^4.1.0",
    "material-react-table": "^1.14.0",
    "moment": "^2.29.1",
    "moment-timezone": "^0.5.33",
    "path-browserify": "^1.0.1",
    "prismjs": "^1.29.0",
    "prop-types": "^15.7.2",
    "query-string": "^8.1.0",
    "react": "^18.2.0",
    "react-beautiful-dnd": "^13.1.1",
    "react-chartjs-2": "^5.2.0",
    "react-contextmenu": "^2.14.0",
    "react-copy-to-clipboard": "^5.0.2",
    "react-dom": "^18.2.0",
    "react-js-cron": "^4.1.0",
    "react-query": "^3.39.3",
    "react-redux": "^8.1.2",
    "react-simple-code-editor": "^0.13.1",
    "react-syntax-highlighter": "^15.5.0",
    "react-type-animation": "^2.1.2",
    "reactstrap": "^8.4.1",
    "redux": "^4.2.1",
    "redux-logger": "^3.0.6",
    "redux-thunk": "^2.4.2",
    "socket.io-client": "^4.7.2",
    "url": "^0.11.0",
    "vis-data": "^7.1.2",
    "vis-network": "^9.0.2",
    "xmldom": "^0.5.0",
    "xpath": "0.0.32"
  },
  "devDependencies": {
    "@babel/cli": "^7.21.0",
    "@babel/core": "^7.21.3",
    "@babel/preset-env": "^7.20.2",
    "@babel/preset-react": "^7.18.6",
    "@pmmmwh/react-refresh-webpack-plugin": "^0.5.10",
    "babel-loader": "^8.1.0",
    "css-loader": "^6.8.1",
    "file-loader": "^6.2.0",
    "html-webpack-plugin": "^5.5.0",
    "less-loader": "^11.1.3",
    "react-refresh": "^0.14.0",
    "sass": "^1.66.1",
    "sass-loader": "^13.3.2",
    "style-loader": "^3.3.3",
    "terser-webpack-plugin": "^5.3.9",
    "url-loader": "^4.1.1",
    "webpack": "^5.88.2",
    "webpack-bundle-analyzer": "^4.4.0",
    "webpack-cli": "^5.1.4",
    "webpack-dev-server": "^4.15.1"
  }

### Expected behavior

Shouldn't give a runtime error while routing a page and go back immediately after page loaded. 

### Platform

- OS: [ macOS]
- Browser: [ Safari, Firefox]

**Comment by JohnnyCrazy** [comment]
Reproducible example: https://stackblitz.com/edit/tanstack-router-qkfkjb?file=src%2Fmain.tsx

1. Added a `pendingComponent` to `postsRoute`
2. Go to `Posts` -> Select first post
3. Reload the page (small icon top left in stackblitz)
4. Error `Cannot read properties of undefined (reading 'routeId')` is shown

There are also other ways to trigger it, but that seems to be the most reliable one. Locally, I can also reproduce it by just adding a `pendingComponent` to a route and switchting to it.

It seems to be related to this block:
https://github.com/TanStack/router/blob/4a3d1615812d10c72c7966a262dd330beae58228/packages/react-router/src/react.tsx#L682-L691

`match` is undefined, `state.status` is `pending` and `state.pendingMatches` has entries.

**Comment by baki-kucukcakiroglu** [comment]
Good job! Were you also experiencing this error?

**Comment by baki-kucukcakiroglu** [comment]
I installed "@tanstack/react-router": "^0.0.1-beta.185" but still having this problem.

**Comment by rodgrolop** [comment]
Did you manage to solve this? I´m having the same error both when developing and after build.

**Comment by alexstanbury** [comment]
Also seeing this issue, using ` "@tanstack/react-router": "^0.0.1-beta.194",`

**Comment by baki-kucukcakiroglu** [comment]
I can confirm that I'm having this issue in "@tanstack/react-router": "^0.0.1-beta.225" , "@tanstack/react-router": "^0.0.1-beta.334".

**Comment by grmkris** [comment]
i think i am expiriencing similar, but just in the prod build, in dev mode all works
