### ISSUE TITLE
SSR rendering error raised because of cprc.getContext

### ISSUE THREAD

**Issue by Assone** [TanStack/router#706]
### Describe the bug

Using the official ssr streaming template, an error occurs when running pnpm dev.

<img width="628" alt="image" src="https://github.com/TanStack/router/assets/14324389/6d097a0e-82ba-412e-a5fb-9ab9051fda61">

Going through the error stack information, I found that the error occurs in the place where the package @gisatcz/cross-package-react-context is referenced. It seems that it is not exporting by default, but exporting the context under the default object.

<img width="613" alt="image" src="https://github.com/TanStack/router/assets/14324389/5a8dbf92-5ab6-4484-93fe-209b8beef08d">

<img width="583" alt="image" src="https://github.com/TanStack/router/assets/14324389/5a07a130-89a6-429d-ae0e-6c187598d21e">

### Your Example Website or App

https://codesandbox.io/p/sandbox/frosty-platform-mgrxkl?file=%2Fpackage.json%3A1%2C1

### Steps to Reproduce the Bug or Issue

1. pnpm install
2. pnpm dev
3. view preview window

### Expected behavior

I want to be able to use ssr rendering normally

### Screenshots or Videos

<img width="1512" alt="image" src="https://github.com/TanStack/router/assets/14324389/1dfd159b-a8d3-4408-8f90-459def756c5a">

### Platform

- OS: macOS
- Browser: Chrome
- Version: 116.0

**Comment by omridevk** [comment]
same here

**Comment by Assone** [comment]
I still have this problem, and the ssr streaming demo under example cannot run.
<img width="691" alt="image" src="https://github.com/TanStack/router/assets/14324389/071e2dd1-0ea2-4402-9465-0a75c01688fe">

**Comment by simply-alliv** [comment]
Yes, it is still creating this problem. Do you have any way of resolving this?
