### ISSUE TITLE
Navigate with search params is not working

### ISSUE THREAD

**Issue by XantreGodlike** [TanStack/router#710]
### Describe the bug

I just trying to change params with `useNavigate`, but it is not working

### Your Example Website or App

https://stackblitz.com/edit/github-pr9hza?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Press change params
2. Nothing changes

If update page, inital value is correct

### Expected behavior

As a user I expect that params will actually change and component will rerender

### Platform

- OS: Windows
- Browser: Chrome
- Version: [0.0.1-beta.179](https://www.npmjs.com/package/@tanstack/react-router/v/0.0.1-beta.179)

**Comment by XantreGodlike** [comment]
However its working with beta173

**Comment by manelio** [comment]
Same problem here.

@XantreGodlike thanks for referencing the latest working version. I just downgraded while waiting for a fix.

**Comment by tothandras** [comment]
Seems to be fixed in: [0.0.1-beta.183](https://www.npmjs.com/package/@tanstack/react-router/v/0.0.1-beta.183)

**Comment by tannerlinsley** [comment]
Should be fixed now
