### ISSUE TITLE
Click on the browser UI clears up hash from URL, also router cleans `=` from the search params after gets loaded

### ISSUE THREAD

**Issue by RIP21** [TanStack/router#716]
### Describe the bug

I enter an email address, and it generates a magic link and sends it via email.
When I open the URL I can clearly see the original URL modified.

URL in email: `http://localhost:3001/login/verify?rid=passwordless&preAuthSessionId=BFlgIXUWCVPUZymtQP4DDQXQXUZlfea73rLC0vAmIOw=&tenantId=public#Hc_cyDxbe-8yzMZ5o0CWcywtpOuuBni5oAAl0L-H2vM=`

URL after it's being loaded and touched:
`http://localhost:3001/login/verify?rid=passwordless&preAuthSessionId=BFlgIXUWCVPUZymtQP4DDQXQXUZlfea73rLC0vAmIOw&tenantId=public`
It removes `=` at the end of  `preAuthSessionId` which breaks the auth callback, and also the hash, but on blur.

### Your Example Website or App

https://stackblitz.com/edit/github-yhavr5?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Open reproduce it in the tab
2. Click on Verify Link or just Verify (this one will open it in another tab using just `a` tag)
3. If you click on the address bar, or will change tabs back and forth, this will cause the hash to disappear (basically a blur event, so clicking inside the devtool also removes the hash).

### Expected behavior

Hash should not randomly disappear without a good reason like proper navigation. `=` should also probably stay?

### Platform

- OS: macOS
- Browser: Chrome
- Version: 115.0.5790.170

### Additional context

After migrating from `react-router-dom` verify auth URL stopped working, for Google auth it still works tho, as it just uses URL params without hash. In `react-router` it was working just fine.

**Comment by Shajansheriff** [comment]
@RIP21 using special characters `=` in search parameter value is tricky. Did you try encoding the values? For example, you can try [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) 

Note: Under the hood, the router uses [decodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURIComponent) to decode the search parameter values, so you do not have to worry about it.

**Comment by RIP21** [comment]
@Shajansheriff yeah, = should be encoded. But that's what supertokens.com return. They've already admitted it's a bug on their side, but low priority. Although disappearance of hash is a bit weird :)

**Comment by tannerlinsley** [comment]
The hash appears to persist now :)
