### ISSUE TITLE
fetching in beforeLoad fails in Safari when refreshing the page

### ISSUE THREAD

**Issue by Roystbeef** [TanStack/router#719]
### Describe the bug

Following the steps for an authenticated route on https://tanstack.com/router/v1/docs/guide/authenticated-routes and found that any `beforeLoad` logic that calls `fetch` on this route will error in Safari when refreshing the page. As a result, it will always call `throw redirect()`

The fetch call will fail with the error message: `"Fetch API cannot load <url> due to access control checks.`. However, this is not a CORs issue as this will happen even on same-origin requests / requests that work outside of refreshing the page.

Instead, I believe this is happening due to a Webkit quirk where the fetch call is canceled due to the pending navigation. [relevant stackoverflow](https://stackoverflow.com/questions/76040372/safari-fetch-api-cannot-load-url-due-to-access-control-checks-on-same-orig)

A stackblitz is linked, but the relevant snippet is:
```tsx
const privateRoute = new Route({
  getParentRoute: () => rootRoute,
  path: '/private',
  component: Private,
  beforeLoad: async () => {
    try {
      const response = await fetch('https://dog.ceo/api/breeds/image/random');
      await response.json();
    } catch (e) {
      console.error(e);
      throw redirect({ to: '/login' });
    }
  },
});

const loginRoute = new Route({
  getParentRoute: () => rootRoute,
  path: '/login',
  component: Login,
});
```

### Your Example Website or App

https://stackblitz.com/edit/github-cbs1ex?file=src/main.tsx

### Steps to Reproduce the Bug or Issue

1. Open the app in safari
2. Navigate to an authenticated route (`'/private'` in the linked stackblitz)
3. Assert that the route loads
4. Refresh the page
5. See that it's now getting redirected to the login route because the fetch fails in `beforeLoad`

### Expected behavior

Refreshing the authenticated page should resolve to rendering the authenticated page instead of getting redirected to the login page

### Screenshots or Videos

https://github.com/TanStack/router/assets/6136959/f47b6643-91e4-440b-85bf-4480c0fd090c

### Platform

- OS: macOS
- Browser: Safari
- Version: 16.4

**Comment by tannerlinsley** [comment]
I haven't been able to test this yet. Any updates if this is still the case?
