### ISSUE TITLE
Route loader errors stopped bubbling up to nearest error component

### ISSUE THREAD

**Issue by geoff-harper** [TanStack/router#724]
### Describe the bug

Up until a recent-ish beta version (not sure which specifically), errors would bubble up the route tree until it hit a route with an `errorComponent` or the root. Now it doesn't bubble and uses some boilerplate UI unless I put the custom error component where the error actually happens.

### Your Example Website or App

https://stackblitz.com/edit/github-gtqdb6

### Steps to Reproduce the Bug or Issue

1. open `/about` route

### Expected behavior

The error UI div should be rendered instead of the boilerplate

### Platform

Everywhere

**Comment by tannerlinsley** [comment]
Error bubbling is back!

**Comment by geoff-harper** [comment]
I'm still noticing the issue on v1

**Comment by zavarka** [comment]
@tannerlinsley, thank you for taking a look. I too am still seeing this issue in `1.15.22`.

**Comment by schiller-manuel** [comment]
can you please find out which version introduced this bug again? this would help fixing this issue.

**Comment by schiller-manuel** [comment]
is this still relevant?

**Comment by GuillaumeLaroucheUQAT** [comment]
The issue is still present in `1.19.2`. When an error is thrown in a route that doesn't have an error component, the `defaultErrorComponent` is used instead of the nearest parent route `errorComponent`.

**Comment by tien** [comment]
I'm also experiencing this issue right now

**Comment by ahkohd** [comment]
I can confirm this bug has been fixed in @tanstack/react-router@1.22.3

**Comment by GuillaumeLaroucheUQAT** [comment]
This bug is not fix for me in `@tanstack/react-router@1.26.13`. I have the same behavior as my last comment instead of the one  on the section [Pathless / Layout Routes](https://tanstack.com/router/latest/docs/framework/react/guide/routing-concepts#pathless--layout-routes) from the documentation :

> Provide fallbacks for error components or pending elements to child routes

**Comment by felipelube** [comment]
I can confirm this is not working in 1.33.6. I have a errorComponent set in the root router and throwing an error in a beforeLoad handler in a pathless route does not render the error component, instead I get a WSOD.
