### ISSUE TITLE
Fix routeTree.gen when --moduleResolution is `node16` or `nodenext`

### ISSUE THREAD

**Issue by jonandgon** [TanStack/router#729]
### Describe the bug

My App has a file-based router and it uses moduleResolution: "nodenext". See below for my tsconfig.json

```js
{
  "compilerOptions": {
    "target": "esnext",
    "module": "nodenext",
    "lib": ["dom", "dom.iterable", "esnext", "ScriptHost"],
    "types": ["vite/client", "node", "chrome"],
    "allowJs": true,
    "skipLibCheck": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "isolatedModules": true,
    "noFallthroughCasesInSwitch": true,
    "resolveJsonModule": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "baseUrl": ".",
    "paths": {
      "@src/*": ["src/*"],
      "@assets/*": ["src/assets/*"]
    }
  },
  "include": [
    "src",
    "utils",
    "../../packages/sdk/src/walletconnect",
    "../../packages/sdk/src/data/walletconnect.ts",
    "src/popup/routeTree.gen.ts",
    "src/popup/routes/index/.html.tsx"
  ]
}
```

Import statements in nodenext require file extensions. I am getting the following errors in `routeTree.gen.ts`:
- `Relative import paths need explicit file extensions in ECMAScript imports when --moduleResolution is node16 or 'nodenext'. Did you mean './routes/index.js'?`

<img width="427" alt="CleanShot 2023-09-12 at 14 27 55@2x" src="https://github.com/TanStack/router/assets/75697675/ffae3a29-96e5-40fc-8221-8b0337510e66">

To get around this problem, I watch the `routeTree.gen.ts` for changes, and then run the following [sed regex code](https://www.gnu.org/software/sed/manual/html_node/Regular-Expressions.html):
- `sed -i -n '' '/\.js"$/!s/\(import.*from.*\)"$/\1.js"/g' src/popup/routeTree.gen.ts`

It would be great if Tanstack Router just supported moduleResolution: nodenext out of the box.

### Your Example Website or App

n/a

### Steps to Reproduce the Bug or Issue

- Create a React app where the module resolution is "nodenext". 
- Add a Tanstack File Router to the app. 
- Run tsr watch.
- Get errors because `treeRoute.gen.ts` imports do not have the `.js` file extension included.

### Expected behavior

As a user of `tsr watch`, I expected the imports in `treeRoute.gen.ts` to not have import errors.

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 116.0

**Comment by FugiTech** [comment]
Using `moduleResolution: "bundler"` will give you most of the benefits of `nodenext` while retaining the relaxed import rules of not requiring explicit file extensions. https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#moduleresolution-bundler
