### ISSUE TITLE
All React Examples Broken on Microsoft Edge

### ISSUE THREAD

**Issue by RicardoAALL** [TanStack/router#733]
### Describe the bug

Clicking the examples in the documentation results in `npm install && npm run dev` being executed for a second or two, followed by a sad face icon being shown in the middle of the vm screen.

### Your Example Website or App

https://tanstack.com/router/v1/docs/examples/react/quickstart?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. go to [https://tanstack.com/router/v1/docs/examples/react/quickstart?file=src%2Fmain.tsx](https://tanstack.com/router/v1/docs/examples/react/quickstart?file=src%2Fmain.tsx)
2. select any of the other examples as well

### Expected behavior

As a user, I expect to be able to use the provided examples (seeing running application and files) but instead the vm shows a gray screen with a sad face icon centered.

### Screenshots or Videos

<img width="1918" alt="image" src="https://github.com/TanStack/router/assets/77858159/da169843-4c75-4506-a896-f0fe5e93e8c6">

### Platform

- OS: Windows
- Browser: Edge
- Version: 116.0.1938.76 (Official build) (64-bit)

**Comment by SeanCassiere** [comment]
This could be something wrong with your machine/browser.

I've got the embedded Stackblitz iframe on the Tanstack router documentation website loading on **Chrome**, **Safari**, **Firefox**, and **Arc**. However, Safari and Firefox, have issues with running WebContainers (the iframe still works as expected).

Also, found [this issue](https://answers.microsoft.com/en-us/microsoftedge/forum/all/microsoft-edge-is-blocking-javascript-from-running/8bff0a10-f7d3-46c0-b948-3cd038f04167) on Microsoft about Edge which could be what is affecting you.

Chrome:
<img width="1680" alt="image" src="https://github.com/TanStack/router/assets/33615041/004452a3-2ddf-4e1d-ad9c-1b11ad2b476f">

Safari:
<img width="1680" alt="image" src="https://github.com/TanStack/router/assets/33615041/d60cea1c-ca5a-4f65-abc1-dee5c2ed809d">

Firefox:
<img width="1680" alt="image" src="https://github.com/TanStack/router/assets/33615041/c7321e76-411c-4734-870c-653ac37ca83e">

Arc:
<img width="1680" alt="image" src="https://github.com/TanStack/router/assets/33615041/9ec02742-e18d-4e67-b7b4-2ef65c81f1cb">

**Comment by revosw** [comment]
As of Edge version 117.0.2045.31, this is no longer the case

**Comment by RicardoAALL** [comment]
Thanks everyone, appreciate the help!
