### ISSUE TITLE
`useLoader` unable to infer loader return type when using object method syntax

### ISSUE THREAD

**Issue by revosw** [TanStack/router#734]
### Describe the bug

useLoader is not correctly inferred when you use the syntax below for RootRoute and FileRoute
```
loader() {
  return {name: "Kyle"}
}
```
However, this works fine
```
loader: () => {
  return {name: "Kyle"}
}
```

### Your Example Website or App

https://codesandbox.io/p/sandbox/goofy-jasper-q2h42p?file=/src/routes/__root.tsx:11,10

### Steps to Reproduce the Bug or Issue

Create a root router
```ts
export const route = new RootRoute({
  // useLoader is type <TSelected = unknown>(opts?: { select?: ((search: unknown) => TSelected) | undefined; } | undefined) => TSelected
  component: ({ useLoader }) => <p>Welcome {useLoader().name}</p>,

  // Works completely fine
  //   loader: () => {
  //     return {
  //         name: "Kyle"
  //     }
  //   },

  // For some reason does not work
  loader() {
    return {
      name: "Kyle",
    };
  },
});
```

### Expected behavior

Using `loader() {}` syntax should work exactly like `loader: () => {}`

### Platform

- OS: Windows
- Browser: Microsoft Edge Version 
- Version: 116.0.1938.81 (64-bit)

**Comment by smolattack** [comment]
This helped me! A fix would be nice but a note in the docs would also be sufficient (at least in the interim).

**Comment by smolattack** [comment]
it seems route.loader is no longer a thing in the latest version

**Comment by bzbetty** [comment]
https://twitter.com/tannerlinsley/status/1722043520020820287

**Comment by tannerlinsley** [comment]
Looks to work fine in the latest version:
<img width="552" alt="Screen Shot 2023-12-11 at 1 41 13 PM" src="https://github.com/TanStack/router/assets/5580297/3cde4ef4-dd61-4af1-933d-2d7d116a75b8">
