### ISSUE TITLE
Hash history type appends multiple `#`'s to url on initial load and refresh

### ISSUE THREAD

**Issue by andrejilderda** [TanStack/router#735]
### Describe the bug

When using the hash history type, I've noticed that upon the initial page load and subsequent refreshes, multiple # hash symbols are being appended to the URL.

### Your Example Website or App

https://stackblitz.com/edit/vitejs-vite-zho5z8?file=src%2Fmain.tsx&terminal=dev

### Steps to Reproduce the Bug or Issue

1. Go to [this Stackblitz](https://stackblitz.com/edit/vitejs-vite-zho5z8?file=src%2Fmain.tsx&terminal=dev) and press 'Open in new tab' (so that you can inspect the url).
2.  Notice that the hash is added twice: `<url>/##/`
3. Refresh the page. Notice that `/#/#/` is appended to the url: `<url>/##/#/#/`.
4. `#/#/` is appended on susequent refreshes.

### Expected behavior

As a user I expected the url to have a single hash and that the matched about route is displayed, but this is not the case.

### Screenshots or Videos

https://github.com/TanStack/router/assets/487182/455463e7-9c03-4d0b-8664-f68a6e3092c1

### Platform

- OS: macOS
- Browser: Firefox
- Version: 117.0.1

**Comment by eblanchette** [comment]
I'm in the same boat.  It looks like the hashHistory is broken.  It's adding %23/ at the end of the URL.

http://...../ng#%23/

**Comment by eblanchette** [comment]
Looks like it started happening with 0.0.1-beta.186

**Comment by worc** [comment]
the hashRouter is just using the browserRouter, but with custom getHref and createHref functions. but i can't quite make heads or tails of it.

what really stands out to me is the hashRouter is already removing its `#` symbol in getHref, but parseLocation seems to be expecting a hash? 

- [Removing the hash](https://github.com/TanStack/router/blob/v0.0.1-beta.194/packages/router-core/src/history.ts#L228)
- ["Parsing" the location](https://github.com/TanStack/router/blob/v0.0.1-beta.194/packages/router-core/src/history.ts#L185)
- [But expecting a hash in the custom href string?](https://github.com/TanStack/router/blob/v0.0.1-beta.194/packages/router-core/src/history.ts#L273)

there's the nested ternary and `-1` checks [in parseLocation](https://github.com/TanStack/router/blob/v0.0.1-beta.194/packages/router-core/src/history.ts#L278-L292) that make me think the hashRouter is trying to support query params as well? it seems like a lot of work to avoid using `window.location` directly, but i really don't have the full context on this one.

[there's a previous fix for extra hashes that might be relevant](https://github.com/TanStack/router/pull/561)

**Comment by eblanchette** [comment]
Still happening with the latest release (0.0.1-beta.198)

**Comment by itsjoeoui** [comment]
Yepp I can also confirm this issue here. It completed broke the router for Electron. (Since only HashRouter works on Electron, and it is broken)

**Comment by lorenzocorallo** [comment]
@tannerlinsley have you had time to check this issue?

**Comment by alvesvaren** [comment]
I also have this issue

**Comment by tannerlinsley** [comment]
Just pushed a fix!
