### ISSUE TITLE
useParams returns wrong data when used with lazy components

### ISSUE THREAD

**Issue by xeinebiu** [TanStack/router#737]
### Describe the bug

When I have a url like "/lazy/$id" and I also use the lazy routing as 
```
return new Route({
        id: `/lazy`,
        path: '/lazy/$id',
	getParentRoute: () => rootRoute,
	component: lazyRouteComponent(() => import('./lazy.route')),
});
```

```
// id=1 on first load
const { id } = useParams({
	from: lazyRoute.id
);
```

Now, whenever I navigate back and navigate again to the same route but different $id, the last $id is used instead.

### Your Example Website or App

https://stackblitz.com/edit/github-fq8xdu?file=src%2Flazy.route.tsx,src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Open the stackblitz example
2. Navigate to route ID=5
3. Press the navigate back button
4. Navigate to route ID=6
5. Press the navigate back button
6. Navigate to route ID=5

while repeating the steps, you will see even when you land on lazy/5, you still will get {6} as params.

### Expected behavior

The useParams should return the correct path arguments.

### Platform

- OS: [macOS]
- Browser: [Chrome]
- "@tanstack/react-router": "0.0.1-beta.191"

### Additional context

It looks like when using   `` router.history.back();``, the useParams becomes corrupted when navigating to the same route but different params.

_No response_

**Comment by tannerlinsley** [comment]
Your lazy route had both and ID and a path configured on it. Just pushed a fix to warn about this in development mode. Thanks!
