### ISSUE TITLE
Loader is calling API too many times

### ISSUE THREAD

**Issue by jan144** [TanStack/router#740]
### Describe the bug

I'm trying to implement a basic user list, with one filter (search param).

Following this pattern:
- In my route, `beforeLoad` returns loaderOptions, using `createLoaderOptions`
- The route's `loader`loads the data using `routeContext.loaderOptions`
- The route's component gets the user data like so:
```
const routeContext = settingsUsersRoute.useRouteContext();
const users = useLoaderInstance({ ...routeContext.loaderOptions, strict: false }).data ?? [];
```

When I select a filter from the datalist (Filter by name), it causes a search param update, resulting in an API call with that filter now set.

> 🚨 **However, instead of only fetching data _once_ from the API, it performs at least 6 calls to the same endpoint.**

### Your Example Website or App

https://stackblitz.com/edit/stackblitz-starters-fd75no?file=src%2Froutes%2Fapp%2Fsettings%2Fusers%2Froute.tsx

### Steps to Reproduce the Bug or Issue

1. Inspect the network tab.
2. Select a value from the Filter by name datalist.
3. See that the `jsonplaceholder` API is called 6 times.

### Expected behavior

I expect the endpoint to be called only once, after search param change.

### Screenshots or Videos

https://github.com/TanStack/router/assets/9975110/af9a6548-f73f-40dd-9e2a-b97e516147d8

### Platform

- OS: macOS
- Browser: Chrome
- Version: 116.0.5845.187

### Additional context

I tried to `useLoader({from: settingsRoute.id})` to retrieve the data (instead of `useLoaderInstance`). It eliminates this specific problem. However, that causes data invalidation to stop working.

I.e. in my real-world app I have an action which creates a new user (the form opens up in a modal on top of the user list). The user save action has `onEachSuccess` which calls `loaderClient.invalidateLoader({ key: 'usersLoader' })`. User list only gets fresh data if I `useLoaderInstance`, so I cannot `useLoader` as a workaround for this bug.

**Comment by tannerlinsley** [comment]
Loaders have been deprecated and the new built-in loaders have been audited for this use case vigorously. Thanks!
