### ISSUE TITLE
SSR examples on site not working

### ISSUE THREAD

**Issue by matt-erhart** [TanStack/router#743]
### Describe the bug

Go to eg https://tanstack.com/router/v1/docs/examples/react/with-loaders-ssr?file=src%2Fentry-server.tsx in chrome on windows and the example won't run. Same for the SSR examples.

### Your Example Website or App

https://tanstack.com/router/v1/docs/examples/react/with-loaders-ssr?file=src%2Fentry-server.tsx

### Steps to Reproduce the Bug or Issue

Go to eg https://tanstack.com/router/v1/docs/examples/react/with-loaders-ssr?file=src%2Fentry-server.tsx in chrome on windows and the example won't run. Same for the other SSR examples.

### Expected behavior

:)

### Platform

- OS: [e.g. macOS, **Windows**, Linux]
- Browser: [e.g. **Chrome**, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by tannerlinsley** [comment]
All of the examples have been updated and reworked. Thanks!
