### ISSUE TITLE
On mobile, link component doesn't set the search change properly

### ISSUE THREAD

**Issue by gynekolog** [TanStack/router#745]
### Describe the bug

On the mobile device, tapping the link triggers a change in the search values, but the new values are presumably set in the context, not in the URL.

The useNavigate search change trigger works correctly.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-hcrpgf?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Try change the search params by Link component on a mobile device.
2. Take a look at the URL or TanStack dev tools. There will be no change.

### Expected behavior

Change the search params.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 0.0.1-beta.192

### Additional context

The issue didn't exist with the 0.0.1-beta.173 version. It could relate to [#710].

**Comment by tannerlinsley** [comment]
Merged and fixed :)
