### ISSUE TITLE
useRouteContext returning undefined, can't destructure

### ISSUE THREAD

**Issue by bgentry** [TanStack/router#752]
### Describe the bug

I'm attempting to update to v0.0.1-beta.193 / 5fdf465ecf2241086b853a9b1cc68eba24255345 and I'm encountering an issue converting routes with search params:

```
Cannot destructure property 'queryOptions' of 'useRouteContext(...)' as it is undefined.
```

It appears that `useRouteContext` is returning `undefined` and thus can't be destructured with `useRouteContext` as the docs & examples show.

### Your Example Website or App

This example is barely modified from the stock example, just adding the declaration for `useRouteContext` within the `component` function call and then using it on the subsequent line with an attempt to destructure the result:

https://stackblitz.com/edit/github-17erph?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

See the attached StackBlitz, note the error.

### Expected behavior

I should be able to access values returned by `useRouteContext` as the docs show.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 116

**Comment by tannerlinsley** [comment]
Fixed in latest!
