### ISSUE TITLE
`missing params` Typescript error when trying to update search parameter from sub-route

### ISSUE THREAD

**Issue by larrifax** [TanStack/router#753]
### Describe the bug

I'm trying to update a search parameter through `Link` or `useNavigate` in a sub-route of a route containing params.
If I interpret the docs correctly, it should only be necessary to supply the `from` & `search` parameters to `Link`/`useNavigate` in this case.  
This was also the behavior prior to version `0.0.1-beta.190`, but after upgrading I get a Typescript error `Property 'params' is missing in type '{ search: { entry: number; }; }' but required in type '{ params: true | ParamsReducer<{ postId: string; }, { postId: string; }>; }'`.  

_If I supply `params={true}`, Typescript is happy again but I can't find any documentation of what the `true` part actually means/what the effect of it is.._

See https://stackblitz.com/edit/tanstack-router-xfrkjw?file=src%2Fmain.tsx for a reproduction of the problem (in the `postRouteSub` route).

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-xfrkjw?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the code for `postRouteSub` in the reproduction
2. Observe Typescript errors in both the `navigate()`-call and the `<Link>` node

### Expected behavior

I would expect that `params={...}` would be unnecessary in this case, as we're merely attempting to update a search parameter in a route which already has the `$postId` parameter assigned.

### Platform

- @tanstack/react-router version `0.0.1-beta.190+` (I've tested it on the current `0.0.1-beta.194` too)

**Comment by tannerlinsley** [comment]
I'm not sure why this is the case, but instead of using the `route.id`, just use a string and let auto-complete do it's job. I'll look into this more.
