### ISSUE TITLE
The "Processing Accumulated Route Context" example does not work

### ISSUE THREAD

**Issue by brncsk** [TanStack/router#757]
### Describe the bug

I was trying to adapt the ["Processing Accumulated Route Context" example](https://tanstack.com/router/v1/docs/guide/router-context#processing-accumulated-route-context) to my own use case by collecting `title` crumbs from nested routes and then `join()`ing them into the final title:

```ts
  const matchesWithTitle = router.state.matches.filter(match => match.routeContext?.title);
  const title = matchesWithTitle.map(match => match.routeContext.title);

  document.title = title.join(' &middot; ');
```

The problem is that `routeContext` is not available on matches (anymore?), even though I do return stuff from `beforeLoad()`.

The `context` member is there, but it won't let me access per-route context elements, only the accumulated context where matches down the route tree seem to overwrite keys in the context inherited from their parent routes.

Is there any way to access per-route context or should I implement my own accumulation logic?

### Your Example Website or App

-

### Steps to Reproduce the Bug or Issue

-

### Expected behavior

As a user, I expected the `routeContext` member to be available on `router.state.matches[number]`

### Platform

- OS: macOS
- Browser: Chrome
- Version: 117.0.5938.132 (Official Build) (x86_64)

**Comment by tannerlinsley** [comment]
`routerContext` is back :)
