### ISSUE TITLE
tsr generate/watch keeps updating to single quotes

### ISSUE THREAD

**Issue by itsjoeoui** [TanStack/router#758]
### Describe the bug

It would be great if tsr can respect my formatter's setting. 
My prettier's default is using double quote, but `tsr generate` or `tsr watch` always update my `index.tsx` file to use single quote, which is a bit annoying.

### Your Example Website or App

https://stackblitz.com/edit/github-o5cwoh

### Steps to Reproduce the Bug or Issue

1. `npm format` (prettier . --write) will update the content in `src/routes/index.tsx` to use double quote.
2. `tsr generate` will change it back to single quote.
3. `npm format` (prettier . --write) will again update the content in `src/routes/index.tsx` to use double quote.

### Expected behavior

ideally, it should respect my formatter's settings.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by tannerlinsley** [comment]
Happy to accept a PR for this, but detecting and using prettier in a babel plugin is non-trivial.

**Comment by ikupenov** [comment]
Since it's difficult to detect the project's preferred quote style a good workaround might be to allow setting a preferred quote style through the `tsr` config file. It's not a PITA but it's a bit annoying getting a bunch of red squiggly lines after running `tsr generate` or `tsr watch`.
