### ISSUE TITLE
Incorrectly routes generated after running tsr watch

### ISSUE THREAD

**Issue by UnseenNinja** [TanStack/router#761]
### Describe the bug

When running the "tsr watch" task, paths are incorrectly recognized, thus generating an incorrect "tree.gen.ts".

![ad64bd1f-b9f8-482b-bba3-9cbb0064adf9](https://github.com/TanStack/router/assets/141142677/59acdedd-24a2-4c5d-9218-8c4b943c8c2a)

### Your Example Website or App

...

### Steps to Reproduce the Bug or Issue

...

### Expected behavior

...

### Platform

- OS: [Windows]
- Browser: [Chrome]

**Comment by tannerlinsley** [comment]
I'll need a codesandbox or stackblitz to debug this.
