### ISSUE TITLE
Nested route always render the first level route

### ISSUE THREAD

**Issue by McDaddy** [TanStack/router#765]
### Describe the bug

for this issue I have searched in `issues`
#398 #628 

but none of these helps

I think it's a very simple case. I have route `/something`  and `/something/detail` and I place `<Outlet />` in my root route

when I visit `/something/detail` it alway get `/something` be rendered.

the only way to show `/something/detail` is add `<Outlet />`  at  `/something`  page. 

but I don't want to link these two page together.

I know there is a config property `exact` in react-router v5.  is there any config could do the same thing? Or any other solution?

### Your Example Website or App

https://stackblitz.com/edit/github-kp2zee?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

click `about/detail` link

### Expected behavior

display `<AboutDetail />`

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: 0.0.1-beta.194

**Comment by jonybekov** [comment]
The same issue here

**Comment by mamedinfo** [comment]
same

**Comment by schiller-manuel** [comment]
You can add another index route:

```typescript
const aboutRoute = new Route({
  getParentRoute: () => rootRoute,
  path: '/about',
});

const aboutIndexRoute = new Route({
  getParentRoute: () => aboutRoute,
  path: '/',
  component: function About() {
    return <div className="p-2">Hello from About!</div>;
  },
});

const aboutDetailRoute = new Route({
  getParentRoute: () => aboutRoute,
  path: 'detail',
  component: function AboutDetail() {
    return <div className="p-2">Hello from About detail!</div>;
  },
});
```
see https://stackblitz.com/edit/github-kp2zee-xkh1zr?file=src%2Fmain.tsx

**Comment by McDaddy** [comment]
> You can add another index route:
> 
> ```ts
> const aboutRoute = new Route({
>   getParentRoute: () => rootRoute,
>   path: '/about',
> });
> 
> const aboutIndexRoute = new Route({
>   getParentRoute: () => aboutRoute,
>   path: '/',
>   component: function About() {
>     return <div className="p-2">Hello from About!</div>;
>   },
> });
> 
> const aboutDetailRoute = new Route({
>   getParentRoute: () => aboutRoute,
>   path: 'detail',
>   component: function AboutDetail() {
>     return <div className="p-2">Hello from About detail!</div>;
>   },
> });
> ```
> 
> see https://stackblitz.com/edit/github-kp2zee-xkh1zr?file=src%2Fmain.tsx

Thx @schiller-manuel , seems it works for my case. I'm wondering is it the official solution? Maybe we need more detailed docs for this

**Comment by tannerlinsley** [comment]
This is the official solution. Hoist the route with a path of `/about/detail` and place it under the root.

**Comment by kruyvanna** [comment]
What about file based route?

**Comment by mmoehrlein** [comment]
> What about file based route?

I found the solution here in the docs https://tanstack.com/router/latest/docs/framework/react/guide/route-trees#flat-routes

You need to add a ".index.ts" to the file. In the case of the example "something.index.ts" which is then only rendered on the exact match.

**Comment by mnpenner** [comment]
I tried `balances.update.index.tsx` but that apparently maps to `/balances/update/` with a trailing slash and still loads the `/balances` route.

The answer is actually `balances_.update.tsx`

![image](https://github.com/TanStack/router/assets/1112998/d3f37d19-4267-4421-8ecb-54024a691f09)

https://tanstack.com/router/latest/docs/framework/react/guide/route-trees#flat-routes

**Comment by mversic** [comment]
> I tried `balances.update.index.tsx` but that apparently maps to `/balances/update/` with a trailing slash and still loads the `/balances` route.

you are doing it wrong. You should have defined `balances.index.tsx`. Although non-nested routing also works, but I wonder if there are some consequences of such approach (e.g. that you loose parameter propagation)
