### ISSUE TITLE
When setting the basepath to "/", the router changes it to "//".

### ISSUE THREAD

**Issue by BennieCopeland** [TanStack/router#766]
### Describe the bug

The router does not properly handle the `basepath` when it is manually set to "/". It changes it to "//" breaking the routes.

### Your Example Website or App

https://stackblitz.com/edit/github-pcpdid-5v6uwf?file=src%2Fmain.tsx%3AL66

### Steps to Reproduce the Bug or Issue

1. Set the `basepath` value in either the `Router` options, or the `RouteProvider` prop to "/".
2. Inspect the Router devtools, and observe that the `basepath` is set to "//".

### Expected behavior

I expected the basepath to be "/".

### Platform

- OS: Windows
- Browser: Chrome
- Version: 0.0.1-beta.194

**Comment by tannerlinsley** [comment]
Fixed in latest.
