### ISSUE TITLE
useSearch: Typescript Error "Property 'email' does not exist on type '{} | {} | {} | { email: string; }'"

### ISSUE THREAD

**Issue by ps73** [TanStack/router#767]
### Describe the bug

I've got a typescript error using the useSearch hook.

Property 'email' does not exist on type '{} | {} | {} | { email: string; }'

### Your Example Website or App

https://stackblitz.com/edit/github-kwyacs?file=src%2FLoginOtp.tsx

### Steps to Reproduce the Bug or Issue

My Routes:
```js
const rootRoute = new RootRoute();

const authRoute = new Route({
  path: '/auth',
  getParentRoute: () => rootRoute,
  component: AuthLayout,
});

const loginRoute = new Route({
  path: '/',
  getParentRoute: () => authRoute,
  component: LoginScreen,
});

const loginOtpRoute = new Route({
  path: 'otp',
  getParentRoute: () => authRoute,
  component: LoginOtpScreen,
  validateSearch: (search) => {
    return {
      email: search.email as string,
    };
  },
});

const routeTree = rootRoute.addChildren([
  authRoute.addChildren([loginRoute, loginOtpRoute]),
]);

export const router = new Router({ routeTree });
```

My Component:

```js
export function LoginOtpScreen() {
  const { email } = useSearch({ from: '/auth/otp' }); // <-- Here it throws the type error: Property 'email' does not exist on type '{} | {} | {} | { email: string; }'
  
  //...
  
  return (
    <form onSubmit={handleSubmit}>
      <Input
        value={code}
        type="text"
        placeholder="Login Code"
        required
        onInput={(e) => {
          setCode(e.currentTarget.value);
        }}
      />
      <Button type="submit" loading={loading}>
        Login
      </Button>
    </form>
  );
}
```

### Expected behavior

It should not throw error since useSearch should only return Object of type `{ email: string; }`

### Screenshots or Videos

<img width="1124" alt="Screenshot 2023-10-12 at 09 56 29" src="https://github.com/TanStack/router/assets/17291660/2f9b6e64-5170-4651-ba7c-402552915f75">

### Platform

- OS: macos
- Browser: Chrome
- Tanstack-Router-Version: 0.0.1-beta.194

**Comment by DoubleJ-G** [comment]
I get the same TypeError, it appears to happen when using the string version of the path, the error doesnt happen when using the object.id

**Comment by medzzP** [comment]
Same

**Comment by emilianomon** [comment]
Same.

**Comment by shansmith01** [comment]
I found a workaround which should be something like:
`  const { email } = useSearch({ from: loginOtpRoute.id  }); // nameOfRoute.id `

**Comment by jezikk** [comment]
This error still occurs in v211.

**Comment by TrentsPC** [comment]
Another workaround would be
`const { email } = useSearch({ from: '/auth/otp' as const });`

**Comment by tannerlinsley** [comment]
If you use a plain string for `from`, you'll need to do `as const`. I have no idea why TS can't figure this one out because it's already a constraint that it MUST be one of the valid routes. Could be something with how the `RouteById` helper type works, but I don't know how else to fix it out without being extremely unperformant.
