### ISSUE TITLE
Outdated docs on Reading search params

### ISSUE THREAD

**Issue by mvacha** [TanStack/router#774]
### Describe the bug

Since [v0.0.1-beta.193](https://github.com/TanStack/router/releases/tag/v0.0.1-beta.193) search and hash properties have been removed from the object passes to loader (as mentioned here [7d7b03a](https://github.com/TanStack/router/commit/5fdf465ecf2241086b853a9b1cc68eba24255345)), but the documentation on reading search parameters has still mentions them https://tanstack.com/router/v1/docs/guide/search-params#reading-search-params.

### Your Example Website or App

https://tanstack.com/router/v1/docs/guide/search-params#reading-search-params

### Steps to Reproduce the Bug or Issue

1. Use `loader: ({ search }) => {...}` in ^v0.0.1-beta.193
2. `search` is `undefined`

### Expected behavior

Should mention the new router context api

### Platform

-

**Comment by sysmat** [comment]
- Documentation is very bad
- useSearch from produce the empty object {}
```typescript
useSearch({ from: allProductsRoute.id })
```

**Comment by tannerlinsley** [comment]
It’s in beta and still in flux. If you want stable docs, wait for the stable release.

**Comment by CHE1RON** [comment]
@mvacha Late to the party, but fwiw just check the source code, there's `loader: ({ location }) => {/* ... */}` which holds `location.search` 🤷

**Comment by tannerlinsley** [comment]
> @mvacha Late to the party, but fwiw just check the source code, there's `loader: ({ location }) => {/* ... */}` which holds `location.search` 🤷

This is an unholy escape hatch lol. If you use search params from here instead of from deps, you won’t have any reactivity to the param changing.
