### ISSUE TITLE
Error when installing latest beta

### ISSUE THREAD

**Issue by adem-pointsharp** [TanStack/router#783]
### Describe the bug

When I run `npm install @tanstack/react-router@beta` as advised in the "Installation" page, I get the following error:

```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @tanstack/history@0.0.1-beta.194.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\AppData\Local\npm-cache\_logs\2023-10-27T19_59_42_518Z-debug-0.log
```

### Your Example Website or App

http://localhost:5173 (host doesn't matter)

### Steps to Reproduce the Bug or Issue

1. Run `npm install @tanstack/react-router@beta` in a fresh project

### Expected behavior

Tanstack Router is installed

### Platform

- OS: Windows 11
- Browser: irrelevant
- Version: irrelevant

**Comment by tannerlinsley** [comment]
Fixed
