### ISSUE TITLE
Hovering on Link causes search to change on current route

### ISSUE THREAD

**Issue by mer10z** [TanStack/router#791]
### Describe the bug

With `preload="intent"`, hovering on Link components that set search will change the value returned by `useSearch`.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-x91tl7?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

In the linked stack blitz,
1. hover over the various links
2. notice that the value returned by useSearch changes

### Expected behavior

search should not change until the link is clicked

### Platform

- OS: macOS
- Browser: Chrome
- Version: 118.0.5993.88

**Comment by tannerlinsley** [comment]
Fixed in latest :)

**Comment by keeganteetaert** [comment]
I'm currently experiencing this same behaviour.

Version: @tanstack/react-router@1.26.1
OS: Windows
Browser: Chrome (123.0.6312.86 (Official Build) (64-bit) (cohort: Stable))

**Comment by schiller-manuel** [comment]
> I'm currently experiencing this same behaviour.
> 
> Version: @tanstack/react-router@1.26.1
> OS: Windows
> Browser: Chrome (123.0.6312.86 (Official Build) (64-bit) (cohort: Stable))

can you please create a new issue including a minimal complete example?
