### ISSUE TITLE
ScrollRestoration gone missing from exports

### ISSUE THREAD

**Issue by XEngine** [TanStack/router#794]
### Describe the bug

It was working fine until 204 but in 205 I guess comments should be enabled? 
https://github.com/TanStack/router/commit/4a792144eb56500ed5d5d3216210c0a396e2e796#diff-4b7bcfa664e2289d7fb38960024f689ab5c7b82541cc416ecae2891c81f5cdb3

![image](https://github.com/TanStack/router/assets/6682465/20dd83b2-3d60-401d-b530-afd650c3dfbc)

### Your Example Website or App

None

### Steps to Reproduce the Bug or Issue

import {Outlet, RootRoute, ScrollResoration} from "@tanstack/react-router";

try to import ScrollRestoration

### Expected behavior

ScrollRestoration is not exported, it should.

### Platform

Windows, latest chrome

**Comment by tannerlinsley** [comment]
Temporarily disable while we rearrange the architecture and APIs.

Tanner Linsley

**Comment by XEngine** [comment]
closing this issue as it will get fixed probably next beta release or so I think 👍
