### ISSUE TITLE
Type error when route's beforeLoad contains a throw without a return

### ISSUE THREAD

**Issue by ancpetras** [TanStack/router#796]
### Describe the bug

When using `throw redirect` inside a route's beforeLoad, Typescript complains that the options on that route are not compatible with RouteOptions type (with the error located in the rootRoute.addChildren method). When the routeTree is in this complaining state, useSearch (and friends) doesn't infer any types.

In my local environment, returning anything at all from the beforeLoad makes the error go away. So does leaving beforeLoad completely empty. Types on useSearch come back instantly when I do this.

I've set up a codesandbox that shows the type error, but for some reason I can't get any type inference on useSearch there no matter what I do.

This is not a newly introduced bug, it has been around since the version number was 2 digits I think, but not certain.

### Your Example Website or App

https://codesandbox.io/s/sad-easley-gc4csx

### Steps to Reproduce the Bug or Issue

1. Examine error on line 57 of index.tsx
2. Return anything from beforeLoad after the throw redirect on line 47 of index.tsx and the error goes away

### Expected behavior

I expect that throwing is sufficient to correctly type the beforeLoad. The docs on Authenticated routes show this exact usage of throw redirect as an example.

### Platform

- OS: macOS
- Browser: Firefox
- Version: 104.0b7

**Comment by tannerlinsley** [comment]
Yeah, this is problematic because a function that *always* throws is typed as returning `never`, which will send more than just TanStack Router into a tizzy :)

To solve this, you would need to return something other than `never`. When you filed this issue, that wasn't possible, but as of 5 minutes ago, it is now :)

```tsx
beforeLoad: () => {
  return redirect(...)
}
```

**Comment by schiller-manuel** [comment]
FYI this is now possible as of https://github.com/TanStack/router/releases/tag/v1.1.11
