### ISSUE TITLE
'loaderContext' does not exist in type 'RouteOptions'

### ISSUE THREAD

**Issue by shansmith01** [TanStack/router#798]
### Describe the bug

Since the implementation of loaderContext in 0.0.1-beta.193 loaderContext does not seem to be a valid option. Here is my code..

`export const siteHomePageRoute = new Route({
  getParentRoute: () => publicSitesLayout,
  path: '$site_id',
  validateSearch: (search: Record<string, unknown>): SitesSearchParams => {
    return { token: search.token as string }
  },
  loaderContext: ({ search: { token } }) => ({
    token,
  }),
  component: SiteHomePage,
})`

This produces a TS error
`Object literal may only specify known properties, and 'loaderContext' does not exist in type 'RouteOptions<Route<Route<RootRoute<unknown, {}, RouteContext, {}>, "/public", "/public", string, "/public", unknown, {}, {}, {}, {}, RouteContext, RouteContext, ... 4 more ..., AnyRoute>, ... 15 more ..., AnyRoute>, ... 11 more ..., RouteContext & { ...; }> & { ...; } & { ...; }'.`

I note that the search params are actually there

### Your Example Website or App

https://stackblitz.com/edit/github-rup7qo?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. go to main.tsx line 34
2. See red line under loaderContext

### Expected behavior

I expect no TS error

### Platform

- OS: [e.g. macOS, ]
- Browser: [e.g. Chrome, Safari, Firefox]

- All versions of Tanstack router after 0.0.1-beta.193

**Comment by tannerlinsley** [comment]
Loader context has been removed. Use beforeLoad now.

Tanner Linsley

**Comment by shansmith01** [comment]
Thanks @tannerlinsley. Love tyour work. Follow up question here if you have time https://github.com/TanStack/router/discussions/800
