### ISSUE TITLE
The search-fn property "prev" of navigate does not contain the validated search

### ISSUE THREAD

**Issue by wuarmin** [TanStack/router#799]
### Describe the bug
The `prev` property of the navigate-search-fn does not contain the validated-search.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-thggwk?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to [https://stackblitz.com/edit/tanstack-router-thggwk?file=src%2Fmain.tsx](https://stackblitz.com/edit/tanstack-router-thggwk?file=src%2Fmain.tsx)
2. Open the console of the dev tools
3. Click on the `navigate`-button at the `posts`-route
![image](https://github.com/TanStack/router/assets/9987680/e0d79b5d-fe16-4308-9dfb-f10f0a555944)
4. See the console output 
![image](https://github.com/TanStack/router/assets/9987680/2498b771-3e0f-429f-a33f-bc87e30ff75e)

### Expected behavior

The `prev`-prop should contain the search, which was validated.

### Platform

- OS: Linux Ubuntu
- Browser: Firefox
- Version 120.0b7 (64-bit)

**Comment by schiller-manuel** [comment]
This issue still exists as of beta 246.
