### ISSUE TITLE
Returning <Navigate> causes the URL to change but not the content

### ISSUE THREAD

**Issue by ancpetras** [TanStack/router#801]
### Describe the bug

When returning `<Navigate>` from a component, it will update the URL but return the content of the original URL. However, when the `<Navigate>` is returned conditionally, it works fine.

E.g. I have a condition in my login route component. If logged in, return `<Navigate>` to an authenticated route. If not logged in, return the login form. If I was not logged in, and I use the returned form to log in, which updates the state and causes the `<Navigate>` to now be returned, it works. But if I was already logged in when I navigated to the login route, it partially navigates and breaks.

I've set up both scenarios in the linked codesandbox. It's not affected by changing strict mode.

### Your Example Website or App

https://codesandbox.io/s/cool-ace-fz4t2s

### Steps to Reproduce the Bug or Issue

1. Open file routes/loginRoute.ts . Observe that a Navigate will be returned every time.
2. Navigate to /login in the browser. Observe that the URL changes to /home but the home route's component is not shown.
3. Open file routes/loginRoute2.ts . Observe that the Navigate is conditional on a state change.
4. Navigate to /login2 in the browser. The login "form" is rendered. Click the "Log In" button. Observe that the state changes and the condition to return the Navigate is met. The URL updates to /home **and** the content updates to /home.

### Expected behavior

As a user, I expect that returning `<Navigate>` from a component will always cause a successful navigation.

### Platform

- OS: macOS
- Browser: Firefox
- react-router versions: 205-214+

**Comment by mmmarsela** [comment]
+1, also experiencing this

**Comment by pjaydev** [comment]
Same here.
I use the `useNavigate()` hook in my component as a workaround since it does not seem to be affected.

**Comment by pjaydev** [comment]
Yes, now after updating from beta 214 to beta 240, the problem with `<Navigate />`seems to be fixed, but now my `useNavigate()` approach does not work anymore (causing an infinite render loop when called on load). 

Also some other parts of our site where I use manually triggered `useNavigate()`, the navigation does not work anymore - but on some other parts it still does. I need to do some more investigation here and might open another issue about this.

**Comment by tannerlinsley** [comment]
I just pushed an update that fixes this.

**Comment by pjaydev** [comment]
Awesome!
@tannerlinsley Thanks for your great work.

**Comment by dongnez** [comment]
Returning <Navigate> causes the URL to change but not the content

its valid again now

**Comment by schiller-manuel** [comment]
@dongnez please create a new issue including a complete minimal example
