### ISSUE TITLE
Flash of protected routes before redirect in beforeLoad

### ISSUE THREAD

**Issue by Angusross111** [TanStack/router#805]
### Describe the bug

Im attempting to protect all my routes except for the login page, but I seem to be getting a flash of the protected routes before it redirects to the login page.
In the docs it states 
> If you throw an error in beforeLoad, none of its children will attempt to load.

Does that also apply to `throw redirect` ? or am I missing something with my setup.

### Your Example Website or App

https://stackblitz.com/edit/github-v3z5us?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

On first load of the repo you will see a flash of the protected components. 
Clicking the link to `/` will also show a flash.

### Expected behavior

All protected/child routes shouldnt load when beforeLoad throws a redirect

### Platform

- OS: Linux
- Browser: Chrome
- Version: 119.0.6045.105

**Comment by huzaifahj** [comment]
I'm experiencing this issue too. Queries in protected pages start to be executed too. Doesn't look good as the recommended way to do authentication is via this method. Worth nothing that this doesn't happen in development for me, only in production.

**Comment by ibrahimbutt** [comment]
Having the same problem. It's a blocker for me due to the end users experience.

**Comment by tannerlinsley** [comment]
This seems to have been fixed. https://stackblitz.com/edit/github-v3z5us-s6atqh?file=package.json,src%2Fmain.tsx

**Comment by alexcloudstar** [comment]
It's still happening for me

**Comment by schiller-manuel** [comment]
@alexcloudstar please open a new issue and please provide a minimal complete example by forking one of the examples on stackblitz.
