### ISSUE TITLE
Unmounted routes do not lose params

### ISSUE THREAD

**Issue by JakeHedman** [TanStack/router#811]
### Describe the bug

Navigating away from a route does not affect `useParams` used in other components.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-8wswvp?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

Change route, reload and change route again. Uncomment line 40 to make it work.

### Expected behavior

Text should change

### Platform

- v0.0.1-beta.209

**Comment by tannerlinsley** [comment]
Fixed latest!
