### ISSUE TITLE
Cannot use Params on Link Component

### ISSUE THREAD

**Issue by xeinebiu** [TanStack/router#814]
### Describe the bug

On the link component, I am not able to use the Params props if I do not want type safety. I dont really care about type safety on the router, and also I have the routes spread on different files instead which makes it hard for typescript to infer the types, therefore I never overrided the types of Router. Tho, on version 194 the Link Component allowed me to pass any Params I wanted, but on the latest version that throws a typing error.

![Untitled](https://github.com/TanStack/router/assets/50703441/aabc5640-4343-4949-9c3b-f48522edbf4a)

### Your Example Website or App

_blank_

### Steps to Reproduce the Bug or Issue

Try to use Link component without overriding the types of router.

### Expected behavior

I can use the Params on Link Component without the need to override router types.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by tannerlinsley** [comment]
Seems to work just fine on the latest version:
<img width="337" alt="Screen Shot 2023-12-11 at 7 43 05 PM" src="https://github.com/TanStack/router/assets/5580297/1560f717-cbb0-47a5-92d8-9ab891078f0b">
<img width="510" alt="Screen Shot 2023-12-11 at 7 42 58 PM" src="https://github.com/TanStack/router/assets/5580297/75dacc24-7f4d-4751-9ffe-07eaf17a3e90">
