### ISSUE TITLE
Duplicate Router Events

### ISSUE THREAD

**Issue by dannyb** [TanStack/router#816]
### Describe the bug

I am experiencing duplicate routing events when opening a new page, refreshing the app page and when going to links inside the application.  I am on the latest beta version 0.0.1-beta.212.  I don't remembering experiencing this on beta.194, I tried reverting but the API has changed.

I made a bare-bone app with just vite, react and the router to re-create this issue.  Below is an example in the console:

![image](https://github.com/TanStack/router/assets/155541/27eac0b0-8a2c-42ac-af54-f13771f9b3ed)

### Your Example Website or App

https://6dn5n2-5173.csb.app/ and https://codesandbox.io/p/sandbox/router-duplicate-events-6dn5n2

### Steps to Reproduce the Bug or Issue

I built a sandbox where you can re-produce it https://codesandbox.io/p/sandbox/router-duplicate-events-6dn5n2

### Expected behavior

Only expecting the code to be run once in the console logs.

### Platform

- OS: macOS
- Browser: chrome
- Version: 212

**Comment by tannerlinsley** [comment]
Is this with React Strict Mode on?

**Comment by dannyb** [comment]
> Is this with React Strict Mode on?

@tannerlinsley yes strict mode is on.  here are my compiler options from tsconfig.

```
  "compilerOptions": {
    "target": "esnext",
    "useDefineForClassFields": true,
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": false,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "noFallthroughCasesInSwitch": true
  }
```

**Comment by dannyb** [comment]
Update: I have updated to 0.0.1-beta.214 and it is still doing the duplicate routing events.

**Comment by tannerlinsley** [comment]
I upgraded the deps to latest and it looks fine now. 🎉
