### ISSUE TITLE
Issue with catch-all under a route

### ISSUE THREAD

**Issue by baegmon** [TanStack/router#820]
### Describe the bug

I posted this on discord but it looks like there is an issue with catch-all paths directly under a specific route.

This doesn't seem to work:
```
export const authRoute = new Route({
  getParentRoute: () => rootRoute,
  path: 'auth',
  component: () => {
    return <h3>Auth</h3>;
  },
});

// Expected Path: "/auth/*"
// this doesn't work
export const redirectAuthRoute2 = new Route({
  getParentRoute: () => authRoute,
  path: '*',
  component: () => {
    return <Navigate to="/auth" />;
  },
});
```

This does work:
```
export const authRoute = new Route({
  getParentRoute: () => rootRoute,
  path: 'auth',
  component: () => {
    return <h3>Auth</h3>;
  },
});

// Expected Path: "/auth/*"
export const redirectAuthRoute = new Route({
  getParentRoute: () => rootRoute,
  path: 'auth/*',
  component: () => {
    return <Navigate to="/auth" />;
  },
});
```

### Your Example Website or App

https://stackblitz.com/edit/github-yj2twt?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Type /auth/aaa or any invalid path
2. Observe that the "Navigate" code trigger to re-direct the user back to /auth

### Expected behavior

Expect re-direction after typing an invalid path under the /auth route.

### Platform

- OS: Any
- Browser: Chrome, Firefox
- Version: latest

**Comment by tannerlinsley** [comment]
After upgrade deps to latest, this seems to work fine. 🎉
