### ISSUE TITLE
Store onUpdate cannot poll isFetching from #gc instances

### ISSUE THREAD

**Issue by 3rdManRun** [TanStack/router#828]
### Describe the bug

When gcMaxAge is set, a gcTimeout is set to #gc (clearInstance) which updates the store by setting the value of the instance key to `undefined`.
https://github.com/TanStack/router/blob/b99130d79a526ee856398c225262b7bf17399559/packages/loaders/src/index.ts#L371

onUpdate runs immediately to update `isFetching` by iterating instances over Object.values but since instance has already been cleared, onUpdate throws "cannot access isFetching on undefined"
https://github.com/TanStack/router/blob/b99130d79a526ee856398c225262b7bf17399559/packages/loaders/src/index.ts#L105

### Steps to Reproduce the Bug or Issue

set gcMaxAge to 15e3 or lower

### Expected behavior

onUpdate should filter cleared instances before polling for isFetching.

### Platform

- OS: Any
- Browser: Any
- Version: Any

**Comment by tannerlinsley** [comment]
Long-term cache behavior has been removed from the router. So this issue is irrelevant now.
