### ISSUE TITLE
File-based routing doesn't support nested routes

### ISSUE THREAD

**Issue by Swizec** [TanStack/router#832]
### Describe the bug

Not sure if this is a bug report or a feature request.

Nested routes don't seem to work out of the box with file-based routing. The CLI uses the `root` as every route's parent, regardless of directory structure.

### Your Example Website or App

https://codesandbox.io/p/github/Swizec/tanstack-router-example/main

### Steps to Reproduce the Bug or Issue

Run `tsr generate` and you get this config:

```typescript
Object.assign(IndexRoute.options, {
  path: "/",
  getParentRoute: () => rootRoute,
});

Object.assign(StoryIdRoute.options, {
  path: "/story/$id",
  getParentRoute: () => rootRoute,
});
```

### Expected behavior

Expected config based on file structure would be:

```typescript
Object.assign(IndexRoute.options, {
  path: "/",
  getParentRoute: () => rootRoute,
});

Object.assign(StoryIdRoute.options, {
  path: "/story/$id",
  getParentRoute: () => IndexRoute,
});
```

### Platform

Platform independent, I think

**Comment by tannerlinsley** [comment]
I believe this is either an outdated dependency or a weird bug I can't reproduce. @Swizec, if you could clone down one of the working examples and test with that, it would be great.

**Comment by ismail-codar** [comment]
For example: https://github.com/TanStack/router/tree/beta/examples/react/basic-file-based/src/routes
`/posts.index.tsx` is good but `/posts/index.tsx` not working

**Comment by tannerlinsley** [comment]
Hmmm. We have directory based routes in our examples that work.... I swear they work... brb.

**Comment by tannerlinsley** [comment]
After speaking with @Swizec, this was just a lapse in documentation. Thanks Swi!

**Comment by shreddish** [comment]
> After speaking with @Swizec, this was just a lapse in documentation. Thanks Swi!

what was the lapse in documentation? I am seeing this where all my nested routes parents are being set to the rootRoute

**Comment by shreddish** [comment]
> After speaking with @Swizec, this was just a lapse in documentation. Thanks Swi!

@tannerlinsley 
what was the lapse in documentation? I am seeing this where all my nested routes parents are being set to the rootRoute. Not sure if I have something configured incorrectly though.

**Comment by shreddish** [comment]
@tannerlinsley any follow up on this? I am running into issues now with creating breadcrumbs as all my nested routes are getting their parent set to the rootRoute so my breadcrumbs aren't accurate.

**Comment by RicardoAALL** [comment]
Running into this issue as well. Every route is being set to the rootRoute instead of the parent.

**Comment by QVladislav** [comment]
Any updates on this issue? It's working as @shreddish described, but there must be a cleaner way by using route.tsx files in each directory.

**Comment by ruiaraujo012** [comment]
Same here, what could we do?
<img width="316" alt="image" src="https://github.com/TanStack/router/assets/16304685/47392b45-917c-461b-ae5e-d1d42de39f4d">
<img width="456" alt="image" src="https://github.com/TanStack/router/assets/16304685/b57a80b0-1ed5-45d8-99fe-befcb7c6aa4c">

**Comment by antebandov** [comment]
@tannerlinsley The issue is still reproducable with the current version. Could you please reopen this issue?

**Comment by judgemavi** [comment]
@tannerlinsley Let me know if I pieced it together right as by doing so the structure is as expected
/root
-/routeA
--index.tsx.   (parent -> root) (url -> /routeA)
--/sub-route1
---index.tsx (parent -> root) (url -> /routeA/sub-route1)

-routeB.tsx (parent -> root) (url -> /routeB)
-/routeB
--sub-route1.tsx (parent -> routeB) (url -> /routeB/sub-route1)
--/sub-route2
---index.tsx (parent -> routeB) (url -> /routeB/sub-route2)

it seems like as long parent route has its own named file every route in matching folder name inherit it as parent

**Comment by schiller-manuel** [comment]
@antebandov  can you please open a new issue and provide a minimal complete example by forking one of the examples on stackblitz based on the latest router version?

**Comment by judgemavi** [comment]
I created an example on top of an existing guide
https://stackblitz.com/edit/tanstack-router-kd1vj9

checkout routes products and apples

event though directory structure is in place $productId doest have products as parent route

**Comment by schiller-manuel** [comment]
@judgemavi this is expected as there is no explict `products` route.
I added that explicit route and now the parent is set: https://stackblitz.com/edit/tanstack-router-b3hjee?file=src%2Froutes%2F%24lang%2F_auth%2Fproducts%2Froute.tsx,src%2FrouteTree.gen.ts

**Comment by ruiaraujo012** [comment]
I agree with you @judgemavi. I think that for each route, the folder structure should be used if there were at least one index route.

**Comment by schiller-manuel** [comment]
@judgemavi 
sorry, I just looked at the generated route tree. you are right, `route.tsx` was incorrect here.
In this case, it could be an empty route (since the default component is an `<Outlet >`):

https://stackblitz.com/edit/tanstack-router-1pflw1?file=src%2Froutes%2F%24lang%2F_auth%2Fproducts%2Froute.tsx,src%2Froutes%2F%24lang%2F_auth%2Fproducts%2Findex.tsx

> but doesnt the index.tsx represent the products route?
no, `index.ts` is the route that is displayed for the path `/$lang/products/`.
There is **no** products route unless you define it. If you don't define it, all the routes you put into the `products` folder simply share the same prefix, but that's all.


However, I don't understand why you would **need** the products route to be an actual route. Why does this matter?

**Comment by judgemavi** [comment]
currently our need is to have /products page where all products are listed as a table. when you click on a row you are navigated to products/$productId for specific product

primarily the relationship is important to build breadcrumbs

**Comment by judgemavi** [comment]
I tried to follow the guide in docs for breadcrumbs using routecontext but if parent routes are not properly linked then there is always just 1 entry despite directory nesting

**Comment by ruiaraujo012** [comment]
Exact same need here. I manage to do the breadcrumbs by hand, for each route I create an array of items for the breadcrumbs with `label` and `path`. But nested routes would be better.

**Comment by judgemavi** [comment]
my attempt is each page set a value in context, then my breadcrumb component utilize useMatches hook to get all matching routes.
`export const Header = ({ children }: Props) => {
  const matches = useMatches();

  const breadcrumbs = matches
    .filter((match) => match.context.title)
    .map((match) => {
      return {
        title: match.context.title,
        path: match.pathname,
      };
    });

  return (
    <div className="flex flex-col gap-4">
      {breadcrumbs.length > 0 && (
        <Breadcrumb>
          <BreadcrumbList>
            {breadcrumbs.map((breadcrumb, index) => (
              <Fragment key={index}>
                <BreadcrumbItem>
                  <BreadcrumbLink asChild>
                    <Link to={breadcrumb.path}>{breadcrumb.title}</Link>
                  </BreadcrumbLink>
                </BreadcrumbItem>
                {index !== breadcrumbs.length - 1 && <BreadcrumbSeparator />}
              </Fragment>
            ))}
          </BreadcrumbList>
        </Breadcrumb>
      )}
      <h1 className="text-2xl font-bold">{children}</h1>
    </div>
  );
};`

unfortunately parent routes are not in matches since they are not connected properly

**Comment by ruiaraujo012** [comment]
I did try the same with the same result. So I went doing all by myself.

```tsx
interface BreadcrumbsContext {
  label: Leaves<CustomTypeOptions['resources']['breadcrumbs']>;
  path?: RoutePaths<typeof routeTree>;
}

interface RouterContext {
  breadcrumbs: BreadcrumbsContext[];
}
```

```tsx
export const Route = createFileRoute('/_area-publica/contactos')({
  component: () => <ContactsPage />,
  loader: ({ context }) => {
    context.breadcrumbs = [
      {
        label: 'home',
        path: '/',
      },
      {
        label: 'help',
      },
      {
        label: 'contacts',
        path: '/contactos',
      },
    ];
  },
});
```
Then in each page that I want to show the breadcrumbs, I put 
```tsx
export const RouterBreadcrumbs = () => {
  const { t } = useTranslation(['breadcrumbs']);

  const matches = useRouterState({ select: (state) => state.matches });

  const breadcrumbs = useMemo(() => matches.at(-1)?.context?.breadcrumbs, [matches]);

  if (!breadcrumbs || breadcrumbs.length === 0) {
    return null;
  }

  return (
    <Breadcrumbs
      aria-label='breadcrumb'
      separator={<NavigateNext fontSize='small' />}
    >
      {breadcrumbs.map((breadcrumb, index) => (
        <RouterLink
          disabled={!breadcrumb.path}
          key={index}
          sx={{
            ':hover': {
              textDecoration: breadcrumb.path ? 'underline' : 'none',
            },
            textDecoration: 'none',
          }}
          to={breadcrumb?.path}
        >
          <Typography
            sx={{
              fontSize: 14,
              fontWeight: index === breadcrumbs.length - 1 ? '600' : undefined,
            }}
            variant='body2'
          >
            {t(breadcrumb.label)}
          </Typography>
        </RouterLink>
      ))}
    </Breadcrumbs>
  );
};
```
