### ISSUE TITLE
useBlocker firest multiple confirm dialogs

### ISSUE THREAD

**Issue by Jarzka** [TanStack/router#834]
### Describe the bug

Hi

I'm trying to block navigation with a confirm dialog with a simple code like this:

```ts
const [isViewDirty, setIsViewDirty] = useState<boolean>>(false);
useBlocker("Are you sure?", isViewDirty);
```

I have checked that the `setIsViewDirty` is called once so that the view becomes dirty. After navigation, the browser fires a confirm dialog. I click either "OK" or "Cancel", but then fires it again. Usually two dialogs is enough, but sometimes multiple dialogs are fired.

Any ideas what could cause this issue?

**EDIT:**

It seems that the bug still occurs even if I use hardcoded state like this:

```ts
useBlocker("Are you sure?", true);
```

**EDIT 2:** 

It seems that it the number of dialogs depends on where I'm navigating. For some pages, only one confirm dialog is shown, and many for others. 🤔 

### Expected behavior

The confirm dialog is dismissed when clicking "OK" instead of firing another dialog.

### Platform

@tanstack/react-router": "0.0.1-beta.185"

**Comment by Jarzka** [comment]
I can "solve" this issue by introducing my own `useBlocker` with timeout, like so:

```ts
function useBlockerWithTimeout(message: string, condition: boolean) {
  const [lastBlockTimestamp, setLastBlockTimestamp] = useState<number | undefined>(undefined);
  const router = useRouter();

  useEffect(() => {
    if (!condition) return;

    const unblock = router.history.block((retry) => {
      const isEnoughTimePassedFromLastBlock =
        lastBlockTimestamp === undefined || new Date().getSeconds() >= lastBlockTimestamp + 1;

      if (isEnoughTimePassedFromLastBlock) {
        if (window.confirm(message)) {
          unblock();
          retry();
        }

        setLastBlockTimestamp(new Date().getSeconds());
      } else {
        unblock();
        retry();
      }
    });

    // eslint-disable-next-line consistent-return
    return unblock;
  });
}
```

However, this does not feel right.

**Comment by tannerlinsley** [comment]
This should be fixed in latest. 🎉

**Comment by itsam** [comment]
is this actually fixed? It's still an issue at least on 1.20.1

**Comment by Jarzka** [comment]
I agree, it still happens occasionally. 😢

**Comment by Jarzka** [comment]
It seems that in Chrome the confirm dialog is always fired again if "OK" button is clicked too fast 😂 

https://github.com/TanStack/router/assets/5528061/c3633c4b-3ead-4f5f-af65-4d92bb2aa0b8

**Comment by itsam** [comment]
What I am actually facing is slightly different (although what you are describing it happens to me as well).

In my case the confirm dialog appears as it should be. I click OK (expecting to leave the page) but the confirm dialog appears again. Only when I click on OK once more  then it navigates back... 

1. My path is `http://localhost:5173/incoming`. 
2. Click on a link to `/dashboard`. Confirm dialog appears. 
3. Click OK. 
4. URL changes to `http://localhost:5173/` but no navigation. <-- this is strange
5. The confirm dialog appears again 
6. Click OK, the URL changes eventually to http://localhost:5173/dashboard


```
  const blockRules = (): boolean => {
    const isDirty = Object.keys(dirtyFields).length > 0;
    return isDirty;
  };

  useBlocker(
    () =>
      window.confirm(
        "Leave page?"
      ),
    blockRules()
  );
```

**Comment by itsam** [comment]
It seems it was a forgotten redirect after all

```typescript
export const Route = createFileRoute("/")({
  beforeLoad: async () => {
    //if logged the redirect to /dashboard
    const oidc = await prOidc;
    if (oidc.isUserLoggedIn) {
      throw redirect({
        to: "/dashboard",
      });
    }
  },
  component: HomePage,
});
```

But, now, as @Jarzka mentions, I am facing (as the video shows) the problem when clicking very fast the OK button (in Chrome)...

**Comment by itsam** [comment]
Well, it seems that problem is fixed "magically". After restarting my mac after lots of days running and in Chrome Version 123.0.6312.59 (Official Build) (arm64) block it works as expected...

**Comment by Jarzka** [comment]
In my project the double-blocking sometimes never happens and sometimes it happens all the time, and I cannot figure out what could be the difference between those cases. Anyway, I now have my workaround in place (never call `window.confirm` is less than one second has passed since the last call) fixes this.

**Comment by itsam** [comment]
@Jarzka taking the opportunity as I understand that you have digged a lot in the matter...  Any ideas how to allow navigation to external links? I am using keycloak and when session expires which normally should lead to the login (external) page, the navigation is getting blocked and everything is a mess...

Thank you in advance

**Comment by Jarzka** [comment]
We solved this problem by setting a `isSessionExpired` flag on when any one of our networks requests fail with a certain status code. We then know when session has expired and use this flag as a condition for the `useBlocker` hook.

**Comment by itsam** [comment]
Yes, makes sense. Thanks for your prompt reply, I appreciate it. I will give this approach a try
