### ISSUE TITLE
Link with hash not causing scrolling

### ISSUE THREAD

**Issue by HernanFdez** [TanStack/router#837]
### Describe the bug

When specifying the `hash` property for the `Link` component, the URL fragment gets appended, but no scrolling ever occurs. 
In case this is intended behaviour (which I don't think should be), what should be done to achieve actual scrolling?

Please find below the very minimal example to reproduce the issue

```typescript
// main.tsx

import React from 'react';
import ReactDOM from 'react-dom/client';
import {
  RouterProvider,
  Link,
  Router,
  RootRoute,
} from '@tanstack/react-router';

const rootRoute = new RootRoute({
  component: () => (
    <>
      <Link hash="id"> LINK </Link>
      <section id="id" className="my-[1000px]">
        SECTION
      </section>
    </>
  ),
});

const router = new Router({ routeTree: rootRoute });

const rootElement = document.getElementById('app')!;
if (!rootElement.innerHTML) {
  const root = ReactDOM.createRoot(rootElement);
  root.render(<RouterProvider router={router} />);
}
```

### Your Example Website or App

https://stackblitz.com/edit/github-ufty9x?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Click on `LINK`
2. Notice how, even though the `#id` fragment gets appended to the browser URL, it does not actually scroll to the `section` with that `id`

### Expected behavior

As far as I understand, the expected behaviour when specifying the `hash` property for the `Link` component is to cause navigation to the DOM element with the corresponding `id`, meaning both: 

- appending the fragment to the browser URL
- triggering the necessary scrolling. 

### Platform

OS: Windows
Browser: Chrome

**Comment by tannerlinsley** [comment]
Fixed in latest 🎉

**Comment by HernanFdez** [comment]
Thanks! I see it now works, but only in the case where the fragment hasn't already been added to the URL. I see this is intentional behaviour implemented in **line 182** of _packages/react-router/src/RouterProvider.tsx_ on commit [a98c823](https://github.com/TanStack/router/commit/a98c823e6e5c4cc1af2dbcf3e4dacc9aa9194200)

I don't understant the motivation for this decision, instead of simply replicating the native html anchor element's behaviour of always scrolling into view (regarless of the current URL), which is what I would expect. But anyhow, even if this is to remain default behaviour, I think it would be nice to have the option to choose, aka making this a customizable condition through some prop, instead of a hard-written one. 
For me at least, I find it important. Would you agree?

... or is there already some way to achieve this that I haven't found?
Thanks again!

**Comment by tannerlinsley** [comment]
Absolutely. Happy to simply just make it behave correctly. Wanna open a PR?

**Comment by tannerlinsley** [comment]
Merged 🎉

**Comment by queicherius** [comment]
This behaviour is correct for Links (i.e. the same as HTML links) but it's a bit annoying when using `router.navigate`.

I'm using `router.navigate` to set the search state when changing a dropdown, while trying to keep the hash intact for reloads. This causes the page to scroll to the hash even when the hash does not change and no link is clicked:

```ts
await router.navigate({
  search: (prev) => ({ ...prev, ...search }),
  hash: location.hash,
  params: true,
})
```

**Comment by schiller-manuel** [comment]
can you please create a new issue containing a minimal example on e.g. codesandbox?

**Comment by Iessenti** [comment]
It would be overly useful to make el.scrollIntoView() with smooth behavior?

**Comment by naps62** [comment]
This seems to not be working. on `@tanstack/start` 1.103 and `@tanstack/react-router` 1.102.5 I'm getting the behaviour described earlier where if the url + hash already match the Link props, nothing actually happens

Should be reproducible here:
https://site-git-features-ethui-dev.vercel.app/

- scroll down a bit, the navbar should show up.
- click the logo to go back to `/#hero`, which should scroll back to the top
- repeating the same steps, the link should no longer work
