### ISSUE TITLE
Link active state doesn't work

### ISSUE THREAD

**Issue by jezikk** [TanStack/router#844]
### Describe the bug

The active state of Link component doesn't work after updating to the latest beta version. Active state works correctly after reloading page, but if I change route dynamically without page reloading the active state of Link component is not changed. Data attribute status is not changed too. I don't know what to change, because as I said everything works after page reloading.

### Your Example Website or App

https://github.com/jezikk/router-example

### Steps to Reproduce the Bug or Issue

1. Go to the repo code
2. Click to the link

### Expected behavior

Active state of Link component is changed

### Screenshots or Videos

![image](https://github.com/TanStack/router/assets/7671531/20f75c14-419c-4518-800d-ba6322e6ff94)

### Platform

- OS: macOS
- Browser: Chrome
- Version: Latest

**Comment by tannerlinsley** [comment]
Fixing now!

**Comment by tannerlinsley** [comment]
Fixed in latest. In fact, its even better as it will only rerender the link component when active status changes 😉
