### ISSUE TITLE
Incorrect matching of dynamic route 

### ISSUE THREAD

**Issue by jerriep** [TanStack/router#847]
### Describe the bug

I have an issue where a dynamic route is prioritised over a static route.

### Your Example Website or App

https://stackblitz.com/edit/github-wtkw8q?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Click on the "Collection Item" navigation link. The app will navigate correctly to the detail page for collection item 1
2. Click on the "Create Collection" navigation link. The app will also navigate to the collection item detail page instead of the create collection
3. Now update the `routeTree` and comment out the `collectionsDetailIndexRoute`, e.g.
    ```
    const routeTree = rootRoute.addChildren([
      indexRoute,
      collectionsRootRoute.addChildren([
        collectionsIndexRoute,
        collectionsCreateRoute,
        collectionsDetailRootRoute.addChildren([
          // collectionsDetailIndexRoute,
          collectionsDetailGeneralRoute,
        ]),
      ]),
    ]);
    ```
4. Refresh the app and click on the "Create Collection" navigation link again. This time, the app will navigate correctly to the Create Collection page

### Expected behavior

I expect the app to navigate correctly to the create collection route when I go to `/collections/create` instead of to the collections detail page.

### Platform

- OS: Windows
- Browser: Firefox
- Version: 0.0.1-beta.265

**Comment by schiller-manuel** [comment]
This issue is fixed in beta.279, see
https://stackblitz.com/edit/github-wtkw8q-p9hidz?file=src%2Fmain.tsx
