### ISSUE TITLE
console.log in RouterProvider.tsx

### ISSUE THREAD

**Issue by jezikk** [TanStack/router#848]
### Describe the bug

```
if ((document as any).querySelector) {
        console.log('hello', routerState.location.hash)
        const el = document.getElementById(
          routerState.location.hash,
        ) as HTMLElement | null
        if (el) {
          el.scrollIntoView()
        }
      }
```

Remove console.log before releasing version 1.0.  ;)

### Your Example Website or App

https://github.com/TanStack/router/blob/beta/packages/react-router/src/RouterProvider.tsx

### Steps to Reproduce the Bug or Issue

Go to the file and remove console.log

### Expected behavior

No log message in console

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment]
can be closed as https://github.com/TanStack/router/pull/849 is merged
