### ISSUE TITLE
useSearch bug: renders 'undefined' in between re-renders

### ISSUE THREAD

**Issue by saibs** [TanStack/router#850]
### Describe the bug

I see is useSearch() re-renders the component on change with the following
- new updated value
- undefined
- new updated value

On a full refresh with query param this works as expected
- new updated value

![image](https://github.com/TanStack/router/assets/1705639/b233a394-6c39-4aaf-b060-a171e0035b01)

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-5lbt2p?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

From the repro stackblitz link
- goto dashboard
- invoice tab
- click on one of the invoice
- click show notes
- check console log

### Expected behavior

similar to full refresh, once the useSearch renders an updated values, it shouldn't re-render with undefined and then render again with updated value

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. v0.0.1-beta.266]

### Additional context

link to [discord](https://discord.com/channels/719702312431386674/1007702008448426065/1184177066736893992) discussion

**Comment by mer10z** [comment]
I'm having trouble with the same issue. To be more precise, useSearch is not returning undefined, it's returning the previous search value. In the example above, if you click on "close notes", you'll see that search first returns an empty object as expected, then returns the previous `{showNotes: true}`, and then again empty object. I have a case where I'm watching search and syncing local state with search, and the intermediate stale search is breaking that.

**Comment by tannerlinsley** [comment]
Well that’s not good. I’ll fix this

**Comment by tannerlinsley** [comment]
Can't replicate in latest any more, so it seems it's fixed!

**Comment by gabrielbuii** [comment]
I can still reproduce it, even with @saibs's example. I upgraded to the latest version though
