### ISSUE TITLE
Static paths are not preferred if they are alongside a dynamic path

### ISSUE THREAD

**Issue by konstantinkreft** [TanStack/router#862]
### Describe the bug

First of all, @tannerlinsley let me thank you for this awesome router. I really like the direction this library is heading! Typed and validated path/search params are a godsend.

I found that on the latest beta (`v0.0.1-beta.282`) static route paths are not preferred over dynamic route paths. 

If there a two routes e.g.

```
/posts/create
/posts/$postId
```
And you navigate to `/posts/create` then `/posts/$postId` is matched. 

The [docs](https://tanstack.com/router/v1/docs/guide/route-matching) could be outdated but I think it should be possible to have static paths alongside dynamic paths, right?

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-jq8jx3?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to 'Posts'
2. Click on 'Create a new post'
3. Error appears 

### Expected behavior

As a user I am expecting the create route (`/posts/create`) to be rendered but the dynamic route (`/posts/$postId`) is rendered.

### Platform

- OS: macOS
- Browser: Chrome
- Version: 120

**Comment by konstantinkreft** [comment]
For some reason after reopening the stackblitz example in a new tab it works. In my old stackblitz tab it looks like this:

![static-path-bug](https://github.com/TanStack/router/assets/13020574/253e9b56-b4ed-43fb-9832-62f1471478b6)

**Comment by schiller-manuel** [comment]
> For some reason after reopening the stackblitz example in a new tab it works. In my old stackblitz tab it looks like this:

maybe:
- a fast refresh / hot reloading issue?
- an old version of react-router? a related issue was fixed in https://github.com/TanStack/router/releases/tag/v0.0.1-beta.279

**Comment by konstantinkreft** [comment]
Yep, I had an old version (pre `beta.279`) hanging around in my `package-lock.json` locally. Not sure why I was able to reproduce the issue on stackblitz initally.
