### ISSUE TITLE
RouteApi routeId issues

### ISSUE THREAD

**Issue by V1RE** [TanStack/router#881]
### Describe the bug

The actual id for a route can differ from the RouteApi's constructor ids shown from TS when using routegen and "layouts"

### Your Example Website or App

https://stackblitz.com/~/github.com/V1RE/tanstack-router-route-api-issue

### Steps to Reproduce the Bug or Issue

The layout-a page shows issues when trying to find the route based on the ts autocompleted route id.

### Expected behavior

As a user I expect the autocompletions for the routeApi to resolve to the correct route id's

### Screenshots or Videos

<img width="512" alt="image" src="https://github.com/TanStack/router/assets/20016103/526f51b2-9cae-4b96-9f9e-c5ac84bb8e9b">

### Platform

Irrelevant

### Additional context

Could either be solved by making the routeApi constructor match the id transformation of the route constructor, or by changing the auto suggestions, but the latter option seems counter-intuitive

**Comment by schiller-manuel** [comment]
This seems to be a problem of file based routes, rather than `RouteApi`. Same issue with e.g. `useNavigate(from: '...')` hook.

**Comment by V1RE** [comment]
@schiller-manuel It seems to stem from the [logic in the `Route` constructor](https://github.com/TanStack/router/blob/912fae7e67f8a5b6a9b7445044393e3259a2a717/packages/react-router/src/route.ts#L558) and the way the route get's [matched based on the "from" property](https://github.com/TanStack/router/blob/912fae7e67f8a5b6a9b7445044393e3259a2a717/packages/react-router/src/Matches.tsx#L310) if I'm not mistaken

**Comment by schiller-manuel** [comment]
I think the issue lies in the generated code:

```typescript
import { Route as rootRoute } from "./routes/__root"
import { Route as IndexRoute } from "./routes/index"
import { Route as LayoutRoute } from "./routes/_layout"
import { Route as PostsRoute } from "./routes/posts"
import { Route as PostsIndexRoute } from "./routes/posts.index"
import { Route as LayoutLayoutARoute } from "./routes/_layout/layout-a"
import { Route as LayoutLayoutBRoute } from "./routes/_layout/layout-b"
import { Route as PostsPostIdRoute } from "./routes/posts.$postId"
import { Route as PostsPostIdDeepRoute } from "./routes/posts_.$postId.deep"

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      parentRoute: typeof rootRoute
    }
    "/_layout": {
      parentRoute: typeof rootRoute
    }
    "/posts": {
      parentRoute: typeof rootRoute
    }
    "/posts/": {
      parentRoute: typeof PostsRoute
    }
    "/_layout/layout-a": {
      parentRoute: typeof LayoutRoute
    }
    "/_layout/layout-b": {
      parentRoute: typeof LayoutRoute
    }
    "/posts/$postId": {
      parentRoute: typeof PostsRoute
    }
    "/posts_/$postId/deep": {
      parentRoute: typeof rootRoute
    }
  }
}

Object.assign(IndexRoute.options, {
  path: "/",
  getParentRoute: () => rootRoute,
})

Object.assign(LayoutRoute.options, {
  id: "/layout",
  getParentRoute: () => rootRoute,
})

Object.assign(PostsRoute.options, {
  path: "/posts",
  getParentRoute: () => rootRoute,
})

Object.assign(PostsIndexRoute.options, {
  path: "/",
  getParentRoute: () => PostsRoute,
})

Object.assign(LayoutLayoutARoute.options, {
  path: "/layout-a",
  getParentRoute: () => LayoutRoute,
})

Object.assign(LayoutLayoutBRoute.options, {
  path: "/layout-b",
  getParentRoute: () => LayoutRoute,
})

Object.assign(PostsPostIdRoute.options, {
  path: "/$postId",
  getParentRoute: () => PostsRoute,
})

Object.assign(PostsPostIdDeepRoute.options, {
  path: "/posts/$postId/deep",
  getParentRoute: () => rootRoute,
})

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  LayoutRoute.addChildren([LayoutLayoutARoute, LayoutLayoutBRoute]),
  PostsRoute.addChildren([PostsIndexRoute, PostsPostIdRoute]),
  PostsPostIdDeepRoute,
])
```

The path does not match the id, see `/layout` vs `/_layout`.

**Comment by V1RE** [comment]
Ah! Good one, I have some spare time, will try to create a PR

**Comment by V1RE** [comment]
@schiller-manuel Tried changing the logic of the codegen, but ran into TS issues when removing the underscores there, they seem to be important for inferring the route context types correctly. Changing the logic in matches.tsx seems to fix the issue, but might have overlooked something.
