### ISSUE TITLE
Wrong href when throwing redirect in React Strict Mode

### ISSUE THREAD

**Issue by universse** [TanStack/router#882]
### Describe the bug

For the [kitchen sink example](https://tanstack.com/router/v1/docs/examples/react/kitchen-sink-react-query-file-based), after turning on React Strict Mode and entering `/profile` route, `location.href` becomes `/login?redirect=%2Flogin%3Fredirect%3D%252Fprofile`. Should be `/login?redirect=%2Fprofile`. It's also reflected in the URL bar.

Side question, is it recommended to use `beforeLoad` to redirect from `/login` if user is already logged in instead of `useLayoutEffect`?

### Your Example Website or App

https://tanstack.com/router/v1/docs/examples/react/kitchen-sink-react-query-file-based

### Steps to Reproduce the Bug or Issue

See description

### Expected behavior

See description

### Platform

NA

**Comment by schiller-manuel** [comment]
cannot reproduce here (I only removed the `//` to enable react strict mode): https://codesandbox.io/p/devbox/vigorous-brown-f4vf7r?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqmn3o5x00072e69v1drmi1f%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqmn3o5x00022e6965dcf90f%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqmn3o5x00042e69nqmhriv3%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqmn3o5x00062e69wyr69wdj%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqmn3o5x00022e6965dcf90f%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqmn3o5x00012e69ebtdn1tq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqmn3o5x00022e6965dcf90f%2522%252C%2522activeTabId%2522%253A%2522clqmn3o5x00012e69ebtdn1tq%2522%257D%252C%2522clqmn3o5x00062e69wyr69wdj%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqmn3o5x00052e69qp2yyoe6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3001%252C%2522path%2522%253A%2522%252Flogin%253Fredirect%253D%25252Fprofile%2522%257D%255D%252C%2522id%2522%253A%2522clqmn3o5x00062e69wyr69wdj%2522%252C%2522activeTabId%2522%253A%2522clqmn3o5x00052e69qp2yyoe6%2522%257D%252C%2522clqmn3o5x00042e69nqmhriv3%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqmn3o5x00032e69eva0xucy%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clqmn3o5x00042e69nqmhriv3%2522%252C%2522activeTabId%2522%253A%2522clqmn3o5x00032e69eva0xucy%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

**Comment by universse** [comment]
![image](https://github.com/TanStack/router/assets/15166715/89085633-b38a-4abf-b57c-0d3a595372a4)

the wrong URL shows up when you enter `/profile` route first

**Comment by V1RE** [comment]
Could this be related to #861?

**Comment by schiller-manuel** [comment]
solved with 1.0.1
see [codesandbox](https://codesandbox.io/p/devbox/tanstack-router-react-example-kitchen-sink-react-query-file-based-2vw8dq?file=%2Fsrc%2Fmain.tsx%3A142%2C8&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqppma1k00073b6hvv17wbtw%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqppma1j00023b6h63aa06by%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqppma1j00043b6hpp3729do%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqppma1k00063b6h4ez8wllc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqppma1j00023b6h63aa06by%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqppma1j00013b6ha04hda8a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqppnnes005d3b6hwcdufu96%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A142%252C%2522startColumn%2522%253A8%252C%2522endLineNumber%2522%253A142%252C%2522endColumn%2522%253A8%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fmain.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522clqppma1j00023b6h63aa06by%2522%252C%2522activeTabId%2522%253A%2522clqppnnes005d3b6hwcdufu96%2522%257D%252C%2522clqppma1k00063b6h4ez8wllc%2522%253A%257B%2522id%2522%253A%2522clqppma1k00063b6h4ez8wllc%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqppma1j00053b6hwk50vf1w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3001%252C%2522path%2522%253A%2522%252Flogin%253Fredirect%253D%25252Fprofile%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqppma1j00053b6hwk50vf1w%2522%257D%252C%2522clqppma1j00043b6hpp3729do%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqppma1j00033b6hp7h4o8ca%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clqppma1j00043b6hpp3729do%2522%252C%2522activeTabId%2522%253A%2522clqppma1j00033b6hp7h4o8ca%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
