### ISSUE TITLE
Params flash undefined on specific route progression

### ISSUE THREAD

**Issue by geoff-harper** [TanStack/router#889]
### Describe the bug

If you cold start in a tab with some path params, navigate out to a different part of the tree, then back to the same path, it will double render with the first render having undefined params

1.  `/some-route/$id`
2.  `/home`
3.  `/some-route/$id` <- problem on first render here

### Your Example Website or App

https://codesandbox.io/p/devbox/small-rgb-8ghsp6

### Steps to Reproduce the Bug or Issue

1. start on `/test/okay`
2. go to `/about`
3. going to either `/test/okay` or `/test/womp` should show problem

### Expected behavior

I expected params to always there or for the ts type to reflect possibly falsyness

### Platform

- OS: any
- Browser: any
- Version: 1.0.0

**Comment by schiller-manuel** [comment]
I can't reproduce, not sure if I understood your steps correctly. Can you please provide a screen recording?


https://github.com/TanStack/router/assets/6340397/1b90a460-96dd-4c77-9f6f-3a3a6f4ef57d

**Comment by geoff-harper** [comment]
sorry I should have mentioned that its logged in the console
