### ISSUE TITLE
Cursor "pointer" flashes to default style after navigation

### ISSUE THREAD

**Issue by Doesntmeananything** [TanStack/router#893]
### Describe the bug

I have noticed that when you hover over an element with `cursor: pointer` style and perform any type of router navigation, the cursor momentarily switches to `cursor: default` and then back to `cursor: pointer`.

For instance, this occurs every time you click a `<Link />` component to perform a navigation. But this also happens on any element with `cursor: pointer`  when you use other mechanism to navigate somewhere. For example, you can hover over a regular button and use your keyboard to focus a link, and by pressing `Enter`  multiple times you can observe the same behavior.

This can be reproduced using official examples.

### Your Example Website or App

https://stackblitz.com/github/tanstack/router/tree/main/examples/react/basic?embed=1&theme=dark

### Steps to Reproduce the Bug or Issue

1. Hover over any link that will perform router navigation.
2. Observe that the mouse cursor has `cursor: pointer` style.
3. Click the link to perform navigation.
4. Observe that the mouse cursor flashes with `cursor: default` style.

### Expected behavior

As a user, I expect that the mouse cursor styles remains consistent with the element style when hovering over it and performing navigation.

### Screenshots or Videos

https://github.com/TanStack/router/assets/34657799/248a5c73-1d52-493a-aaa0-448d0bad33f3

### Platform

- OS: Linux
- Browser: Chrome
- Version: 120.0

**Comment by schiller-manuel** [comment]
Does not happen in Chrome on macOS:


https://github.com/TanStack/router/assets/6340397/ddaa41b5-6567-4864-aea6-74bb7270d7d9

**Comment by Doesntmeananything** [comment]
Yeah, I might've been to hasty with opening an issue for this. It seems like this is common when doing client-side routing in React. I've got the same behavior in other apps that aren't using TanStack router. And also on a Windows machine.

For some reason, the example in the docs was just particularly egregious for me. Will close this for now.
