### ISSUE TITLE
Typescript error, some route paths are reported as invalid

### ISSUE THREAD

**Issue by mmrath** [TanStack/router#896]
### Describe the bug

Some context in thread https://discord.com/channels/719702312431386674/1190162020440481844
[Stackblitz link](https://stackblitz.com/edit/github-mkmefb?file=src%2Fpages%2Flayout.tsx)

even though /account/setting is valid it is reported as in valid.
```
Type '"/" | "/account" | "/auth/login" | "/auth/register" | "/about" | "/account/setting" | "/account/change-password"' is not assignable to type '"/" | "/account" | "/auth" | "/auth/login" | "/auth/register" | "/about"'.
  Type '"/account/setting"' is not assignable to type '"/" | "/account" | "/auth" | "/auth/login" | "/auth/register" | "/about"'.(2322)
```

### Your Example Website or App

https://stackblitz.com/edit/github-mkmefb?file=src%2Fpages%2Flayout.tsx

### Steps to Reproduce the Bug or Issue

run `npm build` in console

### Expected behavior

no typescript error

### Platform

- OS: NA
- Browser: Chrome

**Comment by schiller-manuel** [comment]
instead of
```tsx
accountRoute = accountRoute.addChildren([accountIndexRoute, settingsRoute, changePasswordRoute]);

export const privateRoutes = privateRootRoute.addChildren([accountRoute]);
```

you must pass the result of `addChildren` into the parent's `addChildren` call:

```tsx
export const privateRoutes = privateRootRoute.addChildren([
  accountRoute.addChildren([
    accountIndexRoute,
    settingsRoute,
    changePasswordRoute,
  ]),
]);
```

see https://stackblitz.com/edit/github-mkmefb-dk5z93?file=src%2Frouter%2Fprivate_routes.tsx

otherwise, typescript is not aware of the assignment you made.

**Comment by 5ebastianMeier** [comment]
@schiller-manuel I stumbled upon this while digging through typing topics. Is this described somewhere in the docs (I couldn't find it thus far)? 
My previous attempt to split the route tree into modules where not all `addChildren` calls where in the same file caused this exact issue and it seems like something that can be easily overlooked. Since it really hurts the DX I think this should be prominently mentioned in the code based routing section of the docs.
Let me know if I can help to add a section.

**Comment by schiller-manuel** [comment]
@5ebastianMeier  it is described here but should be made more explicit: https://tanstack.com/router/v1/docs/framework/react/guide/code-based-routing#manually-building-the-route-tree

PRs welcome!

**Comment by 5ebastianMeier** [comment]
> [@5ebastianMeier](https://github.com/5ebastianMeier) it is described here but should be made more explicit: https://tanstack.com/router/v1/docs/framework/react/guide/code-based-routing#manually-building-the-route-tree
> 
> PRs welcome!

Oh I overlooked that, just saw the emphasis on declaring the parent route. I'll prepare something in the coming days.
