### ISSUE TITLE
Does not support React v16.8+

### ISSUE THREAD

**Issue by jdefting** [TanStack/router#900]
### Describe the bug

The docs say this library supports React v16.8+ (https://tanstack.com/router/v1/docs/installation).  However, when trying to run the basic example on React v17, the page crashes. This is because `useTransition` is a React v18 API.

### Your Example Website or App

https://stackblitz.com/edit/github-czdpyf?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

Run the quickstart example on React < v18

### Expected behavior

The example app should work on React v16.8+

### Screenshots or Videos

<img width="753" alt="Screenshot 2023-12-30 at 9 53 31 AM" src="https://github.com/TanStack/router/assets/87446002/0f9d99be-dee9-418f-8917-7f9139887f6e">

### Platform

- OS: macOS
- Browser: e.g. Chrome
- Version: 120.0.6099.129

**Comment by tannerlinsley** [comment]
Can you check this again on the latest version?

**Comment by tannerlinsley** [comment]
In my testing, everything seems to work great!

**Comment by trongbinh15** [comment]
I faced same issuse with `"react": "^17.0.2"` 
![image](https://github.com/TanStack/router/assets/43725147/99a4280d-8ca4-495e-93ab-13fab1d9cddc)

**Comment by jcoryalvernaz** [comment]
Facing the same issue with `"react": "^17.0.2"` and `"@tanstack/react-router": "^1.31.26"`
![Substrate 2024-05-22 09-50-43](https://github.com/TanStack/router/assets/38389357/ead3d3df-0528-465d-a4f3-4d5c1afbec8b)

**Comment by benherronscope** [comment]
@tannerlinsley  This is still an issue on the latest version, can this be reopened and looked at? I'm investigating switching routers but it's a pretty big blocker for me at the moment...

![image](https://github.com/TanStack/router/assets/70465353/25c623f9-66d2-4187-85e9-990c7f73d529)

"react": "17.0.2",
"@tanstack/react-router": "1.40.0"

**Comment by carnakovic** [comment]
It doesn't work for react v16 & v17 since version v1.27
