### ISSUE TITLE
useRouteContext typing does not include context from `beforeLoad`

### ISSUE THREAD

**Issue by nick-kang** [TanStack/router#901]
### Describe the bug

```typescript
// router.tsx
const dashboard = new Route({
  getParentRoute: () => root,
  path: 'dashboard',
  beforeLoad: () => {
    return { session: 'abc123' }
  },
  component: Dashboard,
})

// Dashboard.tsx
  const { session } = useRouteContext({  // session is not typed. session should be a string
    from: '/dashboard',
  })
```

Dashboard.tsx does not properly type the `session` from `beforeLoad` even though it is present in the route context.

### Your Example Website or App

https://stackblitz.com/edit/github-73nmhk?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

See bug description

### Expected behavior

`useRouteContext` should include the types from `beforeLoad`

### Platform

- OS: macOS
- Browser: Chrome
- Version: 1.0.5

**Comment by schiller-manuel** [comment]
You need to use `as const`:

```tsx
const { session } = useRouteContext({ from: '/' as const }); 
```

see https://stackblitz.com/edit/github-73nmhk-cs1a8c?file=src%2Fmain.tsx

**Comment by CHE1RON** [comment]
@schiller-manuel Using the breadcrumbs example [from the docs](https://tanstack.com/router/v1/docs/guide/router-context#processing-accumulated-route-context), how would you solve this issue there when retrieving `routeContext ` from some `match` 🤔

**Comment by schiller-manuel** [comment]
do you have a complete example on e.g. stackblitz?

**Comment by tadeumaia** [comment]
@schiller-manuel 
From our conversation on https://discord.com/channels/719702312431386674/1194007808010625136

context is not typed at the RootRoute beforeload, only their children.

**Comment by schiller-manuel** [comment]
I'll close this as the original issue is resolved. Please feel free to open new issues for further discussion.
