### ISSUE TITLE
Vite HMR breaks the router

### ISSUE THREAD

**Issue by bohdancho** [TanStack/router#902]
### Describe the bug

If a route is imported into the router file, and the router is first imported into another component (i.e. ```App.tsx```) and this other component is rendered with React ```root.render```, triggering Vite HMR by editing the router file (or any other file except for files that only export components) will cause the router to return no content, as in the page becomes empty.

### Your Example Website or App

https://stackblitz.com/edit/github-ju1bm9?file=src%2Frouter.tsx

### Steps to Reproduce the Bug or Issue

1. Go to the linked stackblitz project and wait for it to launch
2. Make any change to router.tsx (appending an empty line is sufficient)

### Expected behavior

I expected the router to be correctly updated with HMR or trigger a page reload, instead of returning nothing (probably null or an empty string).

### Platform

- OS: Windows
- Browser: Chrome
- Version: 120.0.6099.130 (Official Build) (64-bit)

### Additional context

Note: I had to update vite to 5.0.10 in the preconfigured Stackblitz project for HMR, and I also updated ```@tanstack/react-router``` to the latest version.

I found a workaround: if you put ```RouterProvider``` directly into ```root.render``` (in the provided stackblitz example just uncomment lines 16-21 and comment out lines 10-14 in main.tsx), everything works as expected.

**Comment by arminnaimi** [comment]
I have encountered the same issue and I have placed the `<RouterProvider />` in `App.tsx` in my Vite app. 

When I comment out the `<RouterProvider />`, HMR starts working again. With the `<RouterProvider />` in `App.tsx`, I don't see any console errors, but there WSOD.

**Comment by bohdancho** [comment]
@arminnaimi does the suggested workaround work for you?

**Comment by wk-ouisense** [comment]
Same for me after migrating my react-router-dom setup to @tanstack/router

**Comment by roastdev** [comment]
I'm seeing the same issue, would be nice to have it within App like usual to work

**Comment by tannerlinsley** [comment]
The example provided has many circular dependencies and a few places that would break fast-refresh rules. For HMR to work, you need to avoid circular imports and make sure you're following the fast-refresh rules. My suggestion:

- routeTree.ts (imports all routes and exports the route tree)
- router.ts (imports the route tree and builds the router)
- main.ts (imports the router and renders it using the router provider)
- routes/
  - route-a.tsx (exports a route)
  - route-b.tsx (exports a route)

For fast-refresh to work, you can only export components and/or an **uppercase named export of a route**:

```tsx
export const MyRoute = new Route(...)
```

You can always reference any of the examples to see a proper HMR setup.

**Comment by nklhtv** [comment]
@tannerlinsley I;ve tried to follow your guide but still have issues:
https://stackblitz.com/edit/tanstack-router-vvdsag
Steps to reproduce:
1. edit the text in the div element in App.tsx, Save
2. edit the text in the div element in router/Root.tsx, Save
3. edit the text in the div element in App.tsx, Save

Root element will be gone until i refresh the page.
![Screen Recording 2024-01-16 at 0 27 20](https://github.com/TanStack/router/assets/5950722/3d00c93e-8146-4d5f-b188-78ecd2d4fa57)

**Comment by mbeckem** [comment]
I have observed the same problem. Re-rendering the RouterProvider results in the RouterProvider not rendering anything under some circumstances (see comment above).

I have worked around the issue for now using the following hack. It forces recreation of the RouterProvider on HMR, which is less than ideal, but at least routes are being rendered.

```tsx
export function App() {
    const routerProvider = useRouterProvider();
    return <ChakraProvider theme={theme}>{routerProvider}</ChakraProvider>;
}

function useRouterProvider() {
    const forceReload = useRef(0);
    forceReload.current += 1;
    return <RouterProvider key={forceReload.current} router={router} />;
}

```
