### ISSUE TITLE
shouldReload behaving differently now?

### ISSUE THREAD

**Issue by blitzbohne** [TanStack/router#905]
### Describe the bug

Pre- 1.0.x we could simply return either true or false from shouldReload on route or an array of dependencies ie parts of the path parameters (as loaderDeps only support search params). However after updating to 1.0.6 I get no syntax error (so returning array seems to be still allowed?) but it now reloads every time eventhough the dynamic path parameter stays the same. If this is no longer supported (I couldn't find this in the docs anymore either only true/false) what's the proper way to only reload whenever a part of the dynamic path parameter changes? Here's my sample route:

```
const rootRoute = new Route({
    path: '/test/$id',
    loader: async ({ abortController, params }) => {
        console.log('LOADER called')
    },
    shouldReload: ({ params: { id } }) => [id],
})
```

This reloads every time when navigating to subpages eventhough the id stays the same. Returning false instead works as expected and calls loader only once but this is not exactly what we want.

Thanks

### Your Example Website or App

https://stackblitz.com/github/tanstack/router/tree/beta/examples/react/quickstart?file=src%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

See initial description

### Expected behavior

See initial description

### Platform

- Version: 1.0.6

**Comment by tannerlinsley** [comment]
`shouldReload` is either `true/false/() => true/false` now. If you're looking for a way to reload based on dependencies, use the `loaderDeps` function to return an object of deps. Params by default cause a route to reload as well, so no need to include them anywhere.
