### ISSUE TITLE
[DevTools] Obscure error "contextMap[utilName] is not a function" when passing certain context to the router 

### ISSUE THREAD

**Issue by AkshayPathak** [TanStack/router#909]
### Describe the bug

When passing a context to the `Router` with the `trpc.useUtils()` hook causes an obscure error.

```javascript
function MyApp() {
  const utils = trpc.useUtils();
  return <RouterProvider router={router} context={{ trpcClient: utils }} />;
}
```

The error is `Uncaught TypeError: contextMap[utilName] is not a function`. It occurs in the `<Explorer />` component in the DevTools.

I have found a temporary workaround by attempting to get the `context` panel to be in the collapsed state. As soon as I expand it, it throws this error. 

In the stackblitz, I am unable to collapse the `context` section by default. However, it throws the error regardless. 

From my testing, I am still unsure what types of items passed to the `context` field in the `RouterProvider` are causing the error. I have tried strings, numbers, variables from useState without it causing this error. 

### Your Example Website or App

https://stackblitz.com/edit/github-4ycrcx?file=client%2Fmain.tsx

### Steps to Reproduce the Bug or Issue

1. Go to Stackblitz above
2. See an error concurring
3. Change the trpcClient on line 42 to a string or number or any other variable and notice that it works

### Expected behavior

The DevTools should not throw an error when it sees the trpc utils. 

### Platform

- OS: Linux
- Browser: Chrome
- Version: Latest

**Comment by SeanCassiere** [comment]
Playing around with your reproduction, I noticed that there were some missing steps in the setup procedure.

I also noticed that if you don't use the `useUtils` helper and pass the client directly into the context it seems to render fine.

https://stackblitz.com/edit/github-4ycrcx-j8sala?file=client%2Fmain.tsx

**Comment by SeanCassiere** [comment]
The above example has been refactored to allow, for invalidating queries in the QueryClient using the [getQueryKey](https://trpc.io/docs/client/react/getQueryKey) helper from the trpc docs.

You can fetch the data you need in the loader using the *trpc helpers* and set the data in the QueryClient cache using the *getQueryKey*.

**Comment by AkshayPathak** [comment]
It wouldn't be only to invalidate, but rather to populate the react query cache, like so:

```javascript
loader: ({ context: { trpcClient, queryOptions } }) => {
  trpcClient?.document.getById.ensureData(queryOptions);
}
```

Just to be clear, the code above works just fine and I believe I got it from an old example from the Tanstack Router repo. 
The issue occurs within the DevTools which triggers this error when rendering the object in the `context` area (see below)

![image](https://github.com/TanStack/router/assets/7646037/e75d86d6-a9c6-4db1-aa04-c38d5a72f0ab)

**Comment by SeanCassiere** [comment]
Understood.

This still seems like something that should be possible with the getQueryKey helper and the trpc caller. I'll look into it further on my side.

**Comment by SeanCassiere** [comment]
@AkshayPathak
I cannot explain to you why this is... But if the *QueryClient* is injected into the context, then the `trpc.useUtils` work.

https://stackblitz.com/edit/github-4ycrcx-uctehc?file=client%2Fmain.tsx

**Comment by AkshayPathak** [comment]
@SeanCassiere It does indeed work! It's crazy that you found this. I don't understand why it works either!

**Comment by SeanCassiere** [comment]
@AkshayPathak 🤷🏽 probably because trpc relies on react-query's QueryClient and it being available via React context...

Close when you are sure everythings working fine.

**Comment by AkshayPathak** [comment]
Well, actually. I figured out why it works. If you provide more than 1 item to context, the DevTools only renders 1. 

See this code below:

```javascript
<RouterProvider
  router={router}
  context={{
    queryClient: queryClient,
    trpcClient: utils,
  }}
/>
```

The render of the DevTools is 
![image](https://github.com/TanStack/router/assets/7646037/b7acdd42-ce79-4c4f-9d12-f0b3b762bf7c)

**Comment by AkshayPathak** [comment]
@SeanCassiere  I still think this is a problem with DevTools.

**Comment by SeanCassiere** [comment]
That's not an issue with devtools, rather that's how trpc uses Javascript Proxy Objects to get its functionality.
The proxy object determines its functionality at runtime while it is being called.

https://stackblitz.com/edit/github-4ycrcx-zfkftx?file=client%2Fmain.tsx

You see above, how the devtools renders more than one item. Its the proxy object that cannot be rendered since it doesn't really have anything in it till its actually called.

**Comment by AkshayPathak** [comment]
Gotcha. And to confirm, the error goes away with any other discrete item is passed to the context object, e.g.

```javascript
<RouterProvider
  router={router}
  context={{
    discreteItem: "hello",
    trpcClient: utils,
  }}
/>
```

Would you, therefore, say that if the DevTools encounters a sole "proxy" object, that it does not attempt to render it and rather renders a `null` or `blank`.

**Comment by AkshayPathak** [comment]
Looking at the context object, from below: 
```javascript
const router = useRouter();
const routerState = useRouterState();

const explorerState = {
  ...router,
  state: router.state,
};

console.log("state: ", explorerState)
```

I see the following for the trpcContext 

```
options: 
-> context:
    -> trpcClient: Proxy(Function) {length: 0, name: 'noop'}
```

@tannerlinsley / @SeanCassiere Do you see any ideas of a fix for this?

**Comment by SeanCassiere** [comment]
As far as I'm aware you aren't able to detect a Proxy, and as such you cannot determine its signature.

Maybe it makes sense to add an option for "unknown" in [check conditions](https://github.com/TanStack/router/blob/a4e23a854376dc3cf20950ce81debf89a05866f6/packages/router-devtools/src/Explorer.tsx#L261C1-L269C4) in the dev-tools panel?
