### ISSUE TITLE
Nested File Based routing isn't working properly

### ISSUE THREAD

**Issue by KaisSalha** [TanStack/router#945]
### Describe the bug

File-based routing with nested routes alway sets the parent component to root instead of the actual parent.

### Your Example Website or App

https://github.com/KaisSalha/tanstack-router-file-based

### Steps to Reproduce the Bug or Issue

1) go to /dashboard/skills

It should print the Dashboard from the parent component. It doesn't.

### Expected behavior

As a user, I expected the Skills route to fit into the Dashboard route's Outlet

### Platform

- OS: macOs
- Browser: Chrome
- Version: 120.0.6099.199

**Comment by schiller-manuel** [comment]
You need to create a separate route for `/dashboard`, you only have one for the index route `/dashboard/`.

I fixed your example, see https://github.com/KaisSalha/tanstack-router-file-based/pull/1/files

**Comment by KaisSalha** [comment]
@schiller-manuel Thanks!
