### ISSUE TITLE
SSR Router does not work when there is basepath

### ISSUE THREAD

**Issue by universse** [TanStack/router#950]
### Describe the bug

SSR Router does not work when there is basepath

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-xzjwqs?file=src%2Frouter.tsx

### Steps to Reproduce the Bug or Issue

Modify the SSR example https://tanstack.com/router/v1/docs/examples/react/basic-ssr-file-based
- add `basepath`
- Refresh the StackBlitz browser
- Route content does not show up even though `Rendering: /app/` is logged to console.
- Inspect the script injected by DehydrateRouter. Only __root route is matched.
```
window.__TSR_DEHYDRATED__ = {"router":{"state":{"dehydratedMatches":[{"id":"__root__","status":"success","updatedAt":1704684196926}]}}}
```

### Expected behavior

SSR works with basepath.

### Platform

NA

**Comment by tannerlinsley** [comment]
Fixed with 4ebcf4ca160678e1763c5a834b0bab1623340f10
