### ISSUE TITLE
TSR CLI generates unused imports

### ISSUE THREAD

**Issue by bgoff1** [TanStack/router#953]
### Describe the bug

The generated route tree from `tsr generate` has unused imports so if the typescript option "noUnusedLocals" is turned on, then tsc will fail to build. Eslint will also fail with the following rule, regardless of tsconfig settings: `@typescript-eslint/no-unused-vars`.

Looks like the generated file always has three imports (`FileRoute, lazyFn, lazyRouteComponent`) and only uses those imports when the future.unstable_codeSplitting flag is on. I would expect the generated code to check for the usages and add the respective imports as necessary. 

### Your Example Website or App

https://stackblitz.com/edit/github-zdilpi?file=package.json

### Steps to Reproduce the Bug or Issue

1. Cancel the dev server or create a new terminal 
2. Run the "build" script in package.json
3. It will fail on tsc step

### Expected behavior

As a user, I would expect the generated route tree file to not have unused imports so that I am able to use the "noUnusedLocals" in the tsconfig file to help with type checking or the eslint rule "@typescript-eslint/no-unused-vars". 

### Platform

- OS: Windows
- Browser: N/A
- Version: N/A

The issue is regarding the build step, no browser issues

### Additional context

https://github.com/TanStack/router/blob/039b25e6aa6507ba0f4a04de89c42c393f96aedc/packages/router-cli/src/generator.ts#L274 here is where the import is being added.

**Comment by ZionLG** [comment]
Tanner said you should exlude the generated file from eslint.
qoute - "Yeah the gen file should be excluded from lintjng and ts. It’s still type safe output. But does some inner magic that isn’t normally allowed."

though, I guess it should still be fixed, if the unused imports effect the bundle size.
