### ISSUE TITLE
`router.history.push` results in 404 / empty page

### ISSUE THREAD

**Issue by bene** [TanStack/router#961]
### Describe the bug

The [docs](https://tanstack.com/router/v1/docs/guide/authenticated-routes) suggest using `router.history.push` after a user successfully signs in. However when using `push` I see the 404 component or no component at all if no 404 is configured.

After refreshing the page the correct component is rendered.

I also noticed, that the redirect in the [kitchen sink example](https://tanstack.com/router/v1/docs/examples/react/kitchen-sink) is not working, which uses the same approach.

### Your Example Website or App

https://stackblitz.com/~/github.com/bene/bug-report-tanstack-router

### Steps to Reproduce the Bug or Issue

For my example:
1. Click on `Login`
**Result:** 404 component

For the kitchen sink example:
1. Click on `Profile` -> redirected to `/login?redirect=%2Fprofile`
2. Enter a username and submit
**Result:** No redirect at all

### Expected behavior

As a user, I expected to see the correct route component after being redirected using `router.history.push` but i am seeing the 404 page (or an empty page if no 404 is configured).

### Screenshots or Videos

https://github.com/TanStack/router/assets/6875705/3050bda7-acbe-4c3e-8a69-fc8a312fc7c0

### Platform

- OS: macOS
- Browser: Chromium/Brave
- Version: 120.0.6099.199

**Comment by schiller-manuel** [comment]
Works for me if you only use a path instead of a full URL:

```tsx
const redirect = "/";
router.history.replace(redirect);
```

**Comment by bene** [comment]
But shouldn't it also work with the full URL? The [authentication guide of the docs](https://tanstack.com/router/v1/docs/guide/authenticated-routes#:~:text=redirect%3A-,location.href,-%2C) also uses `location.href`.

**Comment by noah-franklin** [comment]
Thank you guys, literally did the same thing didn't notice the location prop in the before load function, works beautifully now
