### ISSUE TITLE
SSR: throw redirect in beforeLoader does nothing

### ISSUE THREAD

**Issue by universse** [TanStack/router#966]
### Describe the bug

Throw redirect in beforeLoader does not work for SSR example.

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-u6w1y3?file=src%2Froutes%2F_auth.profile.tsx,src%2Froutes%2F_auth.tsx

### Steps to Reproduce the Bug or Issue

1. Add _auth.tsx with `beforeLoader` and _auth.profile.tsx.
2. Click on Profile link, redirect is thrown and index route is loaded.
3. Enter `/profile` route via address bar. User is not redirected to '/' route.

* Need to open StackBlitz browser URL in a new tab since the URL in iframe does not get updated.

### Expected behavior

User is redirected to '/' route.

### Platform

NA

**Comment by tannerlinsley** [comment]
We're tracking this internally with some key features around SSR. Thanks!
