### ISSUE TITLE
`future.unstable_codeSplitting` - unable to code-split the top-level index route

### ISSUE THREAD

**Issue by SeanCassiere** [TanStack/router#967]
### Describe the bug

Using the `future.unstable_codeSplitting` flag, you are unable to automatically code-split the `/` (top-level index) route.
For reference, this would be the very first route you see when navigating to the application at `localhost:3001`.

I've tried it using the following naming conventions.
1. `component.tsx, route.tsx, loader.tsx` at */routes/* does not produce a `/` route and throws an error due to id collision with _root_.
2. `index.component.tsx, index.tsx, index.loader.tsx` at */routes/* (note: index.tsx has **not** been provided a component) shows a blank/empty `/` page whilst also generating virtual route named as `/index` where the defined component and loaders are brought in. 

I normally wouldn't have made this issue, as this is only affecting the top route for me, which I could have done manual importing for. However, this would break the file structure being introduced and bring in an overall level of jank which could be *interesting* having to explain/justify to a team.

### Your Example Website or App

https://stackblitz.com/edit/github-zao5vf?file=src%2FrouteTree.gen.ts

### Steps to Reproduce the Bug or Issue

1. Go to the [basic-file-based-codesplitting](https://github.com/TanStack/router/tree/main/examples/react/basic-file-based-codesplitting) example.
2. Try breaking out the `/`/`index` route using the new naming automatic codesplitting naming convention.
3. 😓

### Expected behavior

As a user, I expect the `/` route to be able to perform the same code-splitting being introduced with the changes for `future.unable_codeSplitting`.
This would look like:
```
/routes
  component.tsx
  route.tsx
  loader.tsx
  /posts
    component.tsx
    ...
  logout.tsx
```

**Or**, to reserve the word `index` as a keyword to indicate that this route would service its closest parent path. This could *possibly* help with mixed-nested navigation allowing for something like:
```
/routes
  index.component.tsx
  index.route.tsx
  index.loader.tsx
  /posts
    $postId.component.tsx
    $postId.route.tsx
    $postId.loader.tsx
    index.component.tsx
    index.route.tsx
    index.loader.tsx
  ...
  logout.tsx
```

### Platform

- OS: macOS
- Browser: Arc/Chrome 
- Package version : 1.3.0

**Comment by tannerlinsley** [comment]
Should be fixed now
