### ISSUE TITLE
Typescript error when supplying a Zod schema with default values for `validateSearch`

### ISSUE THREAD

**Issue by TheHyphen** [TanStack/router#988]
### Describe the bug

I have the following Zod schema for validateSearch for a route:

```typescript
const schema = z.object({ page: z.number().default(1) });
const route = new Route({
  path: "/examples",
  component: Examples,
  getParentRoute: () => rootRoute,
  validateSearch: schema,
  // also tried with
  // validateSearch: (search: z.input<typeof schema>) => schema.parse(search)
});

function Examples() {
  const navigate = useNavigate();
  const onClick = () => {
    navigate({
      to: route.to,
      search: {}, // Typescript error here, expects `page` to be present
    });
  };
  return null;
}

const routeTree = rootRoute.addChildren([route]);
// RouterProvider with the Router and the route tree setup
```

Typescript error:

> Type '{}' is not assignable to type 'true | ParamsReducer<{ page: number; }, { page: number; }>'.ts(2322)
> link.d.ts(51, 5): The expected type comes from property 'search' which is declared here on type 'NavigateOptions<Route<any, "/", "/", string, "__root__", RootSearchSchema, RootSearchSchema, RootSearchSchema, RootSearchSchema, ... 10 more ..., any>, string, "/examples", string, "">'

### Your Example Website or App

https://stackblitz.com/edit/github-b2gzvt?file=src%2Fmain.tsx%3AL37

### Steps to Reproduce the Bug or Issue

See the line with the `navigate({ to: route.to, search: {} })` and the accompanied Typescript error. Or a similar error with `<Link to={route.to} search={{}} />`

### Expected behavior

Expected the `page` search param to be optional as it has a default value in the inferred zod schema with `z.input<typeof schema>`. Also, using `schema.parse({})` works as expected and doesn't complain about the missing properties.

### Platform

- OS: [e.g. macOS]
- Browser: [e.g. Chrome]
- Version: [e.g. 91.1]

**Comment by schiller-manuel** [comment]
router uses the return type of `validateSearch` to infer the type of the search parameters. zod's return type of `schema.parse()` is `z.output<typeof schema>` which in this case is:

```tsx
{
    page: number;
}
```

You need to tell router that you want to use a different type as the **input**  like this:

```tsx
validateSearch: (input: z.input<typeof schema> & SearchSchemaInput) =>
    schema.parse(input),
```

I updated your example: https://stackblitz.com/edit/github-b2gzvt-j7wrvr?file=src%2Fmain.tsx

**Comment by joseinaqa** [comment]
> router uses the return type of `validateSearch` to infer the type of the search parameters. zod's return type of `schema.parse()` is `z.output<typeof schema>` which in this case is:
> 
> ```tsx
> {
>     page: number;
> }
> ```
> 
> You need to tell router that you want to use a different type as the **input** like this:
> 
> ```tsx
> validateSearch: (input: z.input<typeof schema> & SearchSchemaInput) =>
>     schema.parse(input),
> ```
> 
> I updated your example: https://stackblitz.com/edit/github-b2gzvt-j7wrvr?file=src%2Fmain.tsx

This is not working as intended in the current version. I used this method and the Link component requires to pass a search that satisfies `z.output<typeof schema>`. Because the search is inferred from the output of `validateSearch` property. It should be like
```tsx
validateSearch: (input) =>
    schema.parse(input) as z.input<typeof schema>,
```
instead. Although this makes the `useSearch` output to be of type `z.input<typeof schema>`, whereas the output is actually `z.output<typeof schema>` because it's already parsed. I think it's a problem with type declarations, because search input is not inferred from the input of validateSearch, which could be due to z.parse using `unknown` as input that stops tanstack router from inferring the right types when using zod schema directly.
