### ISSUE TITLE
Pathless directories after dynamic directory is not properly excluded in URL

### ISSUE THREAD

**Issue by austinm911** [TanStack/router#992]
### Describe the bug

See [discord](https://discord.com/channels/719702312431386674/1195922287904428102/1195922287904428102) discussion

See [Reproduction](https://stackblitz.com/edit/tanstack-router-cqjfmc?file=package.json)

- Navigate to New Layout Directory,
- runtime pathname is /123/detail-layout/route2/123 but the route ID is /_auth/$teamId/_detail-layout, detail-layout is included in the URL
- original layout route which is nested in _auth but not $teamId works as expected, with runtime path  /layout-a

This also causes issues when referring to the ID of the path name, i.e. from RouteApi because of the pathless directory mismatch

### Your Example Website or App

https://stackblitz.com/edit/tanstack-router-cqjfmc?file=package.json

### Steps to Reproduce the Bug or Issue

See above

### Expected behavior

See above

### Platform

  System:
    OS: macOS 14.2.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 161.20 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 21.5.0 - ~/.nvm/versions/node/v21.5.0/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.5 - ~/.nvm/versions/node/v21.5.0/bin/npm
    pnpm: 8.14.1 - ~/Library/pnpm/pnpm
    bun: 1.0.22 - /opt/homebrew/bin/bun
  Browsers:
    Brave Browser: 120.1.61.109
    Chrome: 120.0.6099.129
    Edge: 120.0.2210.133
    Safari: 17.2.1

**Comment by tannerlinsley** [comment]
The short term solution required a few fixes:

- A type fix to properly infer file-based layout routes (just shipped)
- A placeholder `_auth.$teamId.tsx` route that exports an empty Route:

```tsx
import { FileRoute } from '@tanstack/react-router'

export const Route = new FileRoute('_auth/$teamId').createRoute({})
```

For now, this gives the `_detail-layout` route an actual route anchor, resulting in the detail route having a proper `id: 'detail-layout'` property, instead of a path.

Long-term, I'll work on a way to get the generator to auto generate this route for you.

**Comment by divmgl** [comment]
I'm not sure this should be closed though. This is still a valid use-case. For instance, this doesn't work:

<img width="255" alt="Screenshot 2024-03-03 at 10 24 50 AM" src="https://github.com/TanStack/router/assets/5452298/0be871c8-9556-4c2a-a15f-57ce28d86fd6">
